### ISSUE TITLE
How to use default packages of Vim 8 to install jedi-vim

### ISSUE THREAD

**Issue by lovekun** [davidhalter/jedi-vim#1006]
In windows, I use the default package mananger of Vim 8 to install jedi-vim. However, it does not work.

I put jedi-vim into `${Home}\vimfiles\pack\jedi\start\jedi`, However there are no tips, when I edit python files, and when I type `:help jedi-vim` in vim, it display 'there are no explanation for jedi-vim'

**Comment by davidhalter** [comment]
I have no idea how the default package manager works. However please provide `:version` so others can help debug this.

**Comment by lovekun** [comment]
I put the plugin into `${Home}\vimfiles\pack\jedi\start\jedi-vim`, and it works.
