### ISSUE TITLE
GoTo jumps to /jedi../stdlib

### ISSUE THREAD

**Issue by nusstter** [davidhalter/jedi-vim#1007]
### Issue

When i use goto on builtins it jumps to jedi-vim/pythonx/jedi/jedi/third_party/typeshed/stdlib/2and3/
Example when i jump to assertRaises from unittest 
i jump to `/pythonx/jedi/jedi/third_party/typeshed/stdlib/3/unittest/case.pyi` but instead i want to jump to `/usr/lib/python3/unittest/case.py`

:py3 print(sys.path) : 
```
['/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/lev/.local/l
ib/python3.7/site-packages', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-package
s', '_vim_path_']
```

### Output of “:verbose JediDebugInfo”

 JediDebugInfo
##### jedi-vim version

 - jedi-vim git version: 0.10.0-36-ge83112f
 - jedi git submodule status:  3ad3dc08b8bf9d749b2d0d9fca038657711c82f2 pythonx/jedi (v0.16.0-11-g3ad
3dc08)
 - parso git submodule status:  c864ca60d1a2f36524a4f79013a7de223e65e19d pythonx/parso (v0.6.0)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/usr/bin/python3`
 - global sys.version: `3.7.5 (default, Apr 19 2020, 20:18:17), [GCC 9.2.1 20191008]`
 - global site module: `/usr/lib/python3.7/site.py`

##### Jedi

 - path: `/home/lev/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.16.1

##### Jedi environment: <SameEnvironment: 3.7.5 in /usr>

 - executable: /usr/bin/python3
 - sys_path:
    - `/usr/lib/python37.zip`
    - `/usr/lib/python3.7`
    - `/usr/lib/python3.7/lib-dynload`
    - `/home/lev/.local/lib/python3.7/site-packages`
    - `/usr/local/lib/python3.7/dist-packages`
    - `/usr/lib/python3/dist-packages`

##### Known environments

 - <Environment: 3.8.0 in /usr> (/usr/bin/python3.8)
 - <Environment: 3.7.5 in /usr> (/usr/bin/python3.7)
 - <Environment: 2.7.17 in /usr> (/usr/bin/python2.7)

##### Settings

```
  omnifunc=jedi#completions
        Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim line 738
  completeopt=menuone,longest,preview
        Last set from ~/.vim/bundle/jedi-vim/plugin/jedi.vim line 36

**Comment by davidhalter** [comment]
What was the issue?
