### ISSUE TITLE
Error: jedi-vim failed to initialize Python when trying to use a python different than global system python

### ISSUE THREAD

**Issue by algorythmik** [davidhalter/jedi-vim#1008]
I installed jedi-vim with Pathogen. I want it to use my anaconda python which is python 3.6 and not my system python. I have edited my `$PATH` variable in my .bashrc file to:
```
export PATH="/opt/anaconda/3-5.0.0.1/bin:$PATH"
```
and I have pip installed jedi for anaconda python.

When I try to edit a python file, I get the following error:
```
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: No module named jedi (in function jedi#ini
t_python..<SNR>24_init_python..jedi#setup_python_imports, line 32). See :messages and/or :JediDebugInfo for more information.
```
Here is the output of :verbose JediDebugInfo:
```
##### Global Python

Using Python version 2 to access Jedi.
 - global sys.executable: `/opt/anaconda/3-5.0.0.1/bin/python`
 - global sys.version: `2.7.5 (default, Jun 11 2019, 14:33:56), [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]`
 - global site module: `/usr/lib64/python2.7/site.pyc`
```
content of my `.vimrc`

```
execute pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
syntax on
```
some more info if it can help:
```
which python
/opt/anaconda/3-5.0.0.1/bin/python
which python2
/usr/bin/python2
which python3
/opt/anaconda/3-5.0.0.1/bin/python3
```

**Comment by davidhalter** [comment]
Your Python version in VIM is Python 2. Therefore you need to install Jedi in Python 2. However please just install it in the sub-repository by using `git submodule update --init --recursive`.

BTW: We should remove the possibility to use jedi-vim with a pip installed Jedi, that only causes issues with virtualenvs.

**Comment by algorythmik** [comment]
thanks, Sorry to ask my question here, can I then make jedi to be aware of my anaconda packages or is it only aware of my python2 packages?

**Comment by davidhalter** [comment]
IIRC you can do :let jedi#force_py_version="..."
