### ISSUE TITLE
Don't use <Leader> for default mappings

### ISSUE THREAD

**Issue by WhyNotHugo** [davidhalter/jedi-vim#1010]
### Issue

Currently `jedi-vim` uses some key mapping thats start with <kbd>Leader</kbd>. The whole point of this customize-able aliased key, is for it to **only** be used by user-defined mappings, with no mappings using it out of the box.

Both nvim and plugins avoid using <kbd>Leader</kbd> for default bindings specifically because of this.

I tried binding <kbd>Leader</kbd>+<kbd>n</kbd> to something today, and had a super hard time figuring out why it was failing -- and it turns out jedi-vim had highjacked it.

### Steps to reproduce

Try to bind a combination reserved specifically for user-configured bindings, like <kbd>Leader</kbd>+<kbd>n</kbd>.

### Notes

I realise that it's possible to un-bind this, however, users shouldn't be expected to have to configure a plugin for it to not use a keybinding that's not meant for plugins to use. It's also non-trivial to debug the issue and figure out that `jedi-vim` hijacks the keybinding even though it's set to something else.

**Comment by davidhalter** [comment]
So what's the alternative?

**Comment by WhyNotHugo** [comment]
Any key combination not used by [neo]vim by default should be fine.
Pretty much any combination is valid except those starting with <kbd>Leader</kbd>, since those are explicitly reserved for user-defined keybindings.

**Comment by WhyNotHugo** [comment]
I think most plugins don't set keybindings for all their operations -- but it's also perfectly acceptable to do so though. :)

**Comment by davidhalter** [comment]
Sorry, I'm simply too lazy to research which keybindings are available, so please provide suggestions how to do it better. Otherwise it will probably just stay the way it always was, because why would anyone start working on it.

**Comment by davidhalter** [comment]
Decided to leave it like is. There are a ton of other Jedi based VIM plugins like deoplete, YCM or all the language servers. Feel free to use them instead.

**Comment by WhyNotHugo** [comment]
> There are a ton of other Jedi based VIM plugins like deoplete, YCM or all the language servers. Feel free to use them instead.

I don't quite follow -- this plugin works fine for me, I don't really need a replacement.

This issue is merely about not overriding <kbd>Leader</kbd> out of the box -- since that specific key is usually reserved and used for user-defined combinations. Even vim/nvim itself avoids defining any mapping that include <kbd>Leader</kbd> due to this.

**Comment by davidhalter** [comment]
It has always been the default in jedi-vim and I don't want to change it at the moment. I feel like the downside of all the Jedi users having their defaults changed over-weighs the upside of having better defaults. If I would do a rewrite of jedi-vim, I would probably use `gd` and the other shortcuts.

However I'm happy to reconsider if you look at what other popular completion providers use as defaults and what would make most sense in VIM. But `Any key combination not used by [neo]vim by default should be fine.` is not a good proposal IMO.
