### ISSUE TITLE
Feature request : external commands

### ISSUE THREAD

**Issue by MikyStar** [davidhalter/jedi-vim#1012]
Hi !

Vim has tons of possible keybindings depending on the plugins installed and it can get really quickly messy
I'm not really confortable using keybindings to do really specific actions like refactoring
So, I've been wondering if it could be possible to enable the use of commands instead, like being able to type something like :JediRefactor or :JediGotoDef

Thanks for your work !

**Comment by davidhalter** [comment]
I definitely agree that this would be nice, but I doubt anybody is going to implement it for you. So if you do the work yourself, I think it's very likely to be merged.

**Comment by davidhalter** [comment]
Closing, because nobody did the work.
