### ISSUE TITLE
Dot autocomplete on classes suggests Jedi internal function (mro)

### ISSUE THREAD

**Issue by julenpardo** [davidhalter/jedi-vim#1013]
### Issue

Dot autocomplete on classes suggests `mro`, which is a Jedi internal function. Jumping into it, one ends in `~/.vim/bundle/jedi-vim/pythonx/jedi/jedi/third_party/typeshed/stdlib/2and3/builtins.pyi`.

### Steps to reproduce

Just create a class and use the dot autocompletion.

![Screenshot_20200521_143845](https://user-images.githubusercontent.com/12843626/82560990-d0360680-9b72-11ea-9a81-465525dba95b.png)

I haven't defined any additional option for Jedi.

### Output of “:verbose JediDebugInfo”

```

#### Jedi-vim debug information


##### jedi-vim version


 - jedi-vim git version: 0.10.0-36-ge83112f
 - jedi git submodule status:  3ad3dc08b8bf9d749b2d0d9fca038657711c82f2 pythonx/jedi (v0.16.0-11-g3ad3dc08)
 - parso git submodule status:  c864ca60d1a2f36524a4f79013a7de223e65e19d pythonx/parso (v0.6.0)


##### Global Python


Using Python version 3 to access Jedi.
 - global sys.executable: `/usr/bin/python3`
 - global sys.version: `3.8.2 (default, Apr  8 2020, 14:31:25), [GCC 9.3.0]`
 - global site module: `/usr/lib/python3.8/site.py`

##### Jedi

 - path: `/home/julen/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.16.1

##### Jedi environment: <SameEnvironment: 3.8.2 in /usr>


 - executable: /usr/bin/python3
 - sys_path:
    - `/usr/lib/python38.zip`
    - `/usr/lib/python3.8`
    - `/usr/lib/python3.8/lib-dynload`
    - `/home/julen/.local/lib/python3.8/site-packages`
    - `/usr/lib/python3.8/site-packages`

##### Known environments


 - <Environment: 3.8.2 in /usr> (/usr/bin/python3.8)

 - <Environment: 3.6.10 in /usr> (/usr/bin/python3.6)



##### Settings


    ```
  omnifunc=jedi#completions
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim line 738
  completeopt=menuone,longest,preview
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim line 716
    ```


#### :version
    ```

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  8 2020 23:37:13)
Included patches: 1-717
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +cmdline_info      -farsi             +langmap           +mouse_sgr         +profile           +tag_binary        +virtualedit
+arabic            +comments          +file_in_path      +libcall           -mouse_sysmouse    +python/dyn        -tag_old_static    +visual
+autocmd           +conceal           +find_in_path      +linebreak         +mouse_urxvt       +python3/dyn       -tag_any_white     +visualextra
+autochdir         +cryptv            +float             +lispindent        +mouse_xterm       +quickfix          +tcl/dyn           +viminfo
-autoservername    +cscope            +folding           +listcmds          +multi_byte        +reltime           +termguicolors     +vreplace
+balloon_eval      +cursorbind        -footer            +localmap          +multi_lang        +rightleft         +terminal          +wildignore
+balloon_eval_term +cursorshape       +fork()            +lua/dyn           -mzscheme          +ruby/dyn          +terminfo          +wildmenu
+browse            +dialog_con_gui    +gettext           +menu              +netbeans_intg     +scrollbind        +termresponse      +windows
++builtin_terms    +diff              -hangul_input      +mksession         +num64             +signs             +textobjects       +writebackup
+byte_offset       +digraphs          +iconv             +modify_fname      +packages          +smartindent       +textprop          +X11
+channel           +dnd               +insert_expand     +mouse             +path_extra        +sound             +timers            -xfontset
+cindent           -ebcdic            +ipv6              +mouseshape        +perl/dyn          +spell             +title             +xim
+clientserver      +emacs_tags        +job               +mouse_dec         +persistent_undo   +startuptime       +toolbar           -xpm
+clipboard         +eval              +jumplist          +mouse_gpm         +popupwin          +statusline        +user_commands     +xsmp_interact
+cmdline_compl     +ex_extra          +keymap            -mouse_jsbterm     +postscript        -sun_workshop      +vartabs           +xterm_clipboard
+cmdline_hist      +extra_search      +lambda            +mouse_netterm     +printer           +syntax            +vertsplit         -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
    ```


#### :messages
    ```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"foo.py" 2L, 20C

NERDTree: 3 file(s) could not be loaded into the NERD tree
too-few-public-methods: Too few public methods (0/2)

F821: undefined name 'Foo'
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  8 2020 23:37:13)
  1: /etc/vimrc
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: ~/.vimrc
  4: /usr/share/vim/vim82/ftoff.vim
  5: /usr/share/vim/vim82/syntax/syntax.vim
  6: /usr/share/vim/vim82/syntax/synload.vim
  7: /usr/share/vim/vim82/syntax/syncolor.vim
  8: /usr/share/vim/vim82/filetype.vim
  9: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
 10: /usr/share/vim/vim82/colors/desert.vim
 11: /usr/share/vim/vim82/syntax/nosyntax.vim
 12: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 13: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 14: /usr/share/vim/vim82/ftplugin.vim
 15: /usr/share/vim/vim82/indent.vim
 16: ~/.vim/bundle/gruvbox/colors/gruvbox.vim
 17: ~/.vim/bundle/fzf/plugin/fzf.vim
 18: ~/.vim/bundle/fzf.vim/plugin/fzf.vim
 19: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 20: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 21: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 22: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 23: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 24: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 25: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 26: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 30: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 31: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 32: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 33: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 34: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 35: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 36: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 37: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 38: ~/.vim/bundle/nerdtree/nerdtree_plugin/vcs.vim
 39: ~/.vim/bundle/nerdtree-git-plugin/nerdtree_plugin/git_status.vim
 40: ~/.vim/bundle/powerline/powerline/bindings/vim/plugin/powerline.vim
 41: ~/.vim/bundle/vim-buftabline/plugin/buftabline.vim
 42: ~/.vim/bundle/tabular/plugin/Tabular.vim
 43: ~/.vim/bundle/markdown-preview.vim/plugin/mkdp.vim
 44: ~/.vim/bundle/rename.vim/plugin/rename.vim
 45: ~/.vim/bundle/vim-ripgrep/plugin/vim-ripgrep.vim
 46: ~/.vim/bundle/vim-gitgutter/plugin/gitgutter.vim
 47: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/utility.vim
 48: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/highlight.vim
 49: ~/.vim/bundle/vim-obsession/plugin/obsession.vim
 50: ~/.vim/bundle/ale/plugin/ale.vim
 51: ~/.vim/bundle/ale/autoload/ale/completion.vim
 52: ~/.vim/bundle/ale/autoload/ale/events.vim
 53: ~/.vim/bundle/vim-surround/plugin/surround.vim
 54: ~/.vim/bundle/nerdcommenter/plugin/NERD_commenter.vim
 55: ~/.vim/bundle/auto-pairs/plugin/auto-pairs.vim
 56: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 57: ~/.vim/bundle/vim-syntax-extra/plugin/vim-syntax-extra.vim
 58: ~/.vim/bundle/vim-closetag/plugin/closetag.vim
 59: ~/.vim/bundle/MatchTagAlways/plugin/MatchTagAlways.vim
 60: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 61: /usr/share/vim/vim82/plugin/gzip.vim
 62: /usr/share/vim/vim82/plugin/logiPat.vim
 63: /usr/share/vim/vim82/plugin/manpager.vim
 64: /usr/share/vim/vim82/plugin/matchparen.vim
 65: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 66: /usr/share/vim/vim82/plugin/rrhelper.vim
 67: /usr/share/vim/vim82/plugin/spellfile.vim
 68: /usr/share/vim/vim82/plugin/tarPlugin.vim
 69: /usr/share/vim/vim82/plugin/tohtml.vim
 70: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 71: /usr/share/vim/vim82/plugin/zipPlugin.vim
 72: ~/.vim/bundle/tabular/after/plugin/TabularMaps.vim
 73: ~/.vim/bundle/tabular/autoload/tabular.vim
 74: /usr/share/vim/vim82/syntax/python.vim
 75: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 76: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 77: ~/.vim/bundle/vim-pydocstring/ftplugin/python/pydocstring.vim
 78: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 79: /usr/share/vim/vim82/ftplugin/python.vim
 80: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 81: ~/.vim/bundle/indentpython.vim/indent/python.vim
 82: /usr/share/vim/vim82/indent/python.vim
 83: ~/.vim/bundle/MatchTagAlways/autoload/MatchTagAlways.vim
 84: ~/.vim/bundle/ale/autoload/ale.vim
 85: ~/.vim/bundle/ale/autoload/ale/util.vim
 86: ~/.vim/bundle/ale/autoload/ale/linter.vim
 87: ~/.vim/bundle/ale/ale_linters/python/bandit.vim
 88: ~/.vim/bundle/ale/ale_linters/python/flake8.vim
 89: ~/.vim/bundle/ale/ale_linters/python/mypy.vim
 90: ~/.vim/bundle/ale/ale_linters/python/prospector.vim
 91: ~/.vim/bundle/ale/ale_linters/python/pycodestyle.vim
 92: ~/.vim/bundle/ale/ale_linters/python/pydocstyle.vim
 93: ~/.vim/bundle/ale/ale_linters/python/pyflakes.vim
 94: ~/.vim/bundle/ale/ale_linters/python/pylama.vim
 95: ~/.vim/bundle/ale/ale_linters/python/pylint.vim
 96: ~/.vim/bundle/ale/ale_linters/python/pyls.vim
 97: ~/.vim/bundle/ale/ale_linters/python/pyre.vim
 98: ~/.vim/bundle/ale/ale_linters/python/vulture.vim
 99: ~/.vim/bundle/ale/autoload/ale/engine.vim
100: ~/.vim/bundle/ale/autoload/ale/command.vim
101: ~/.vim/bundle/ale/autoload/ale/python.vim
102: ~/.vim/bundle/ale/autoload/ale/path.vim
103: ~/.vim/bundle/ale/autoload/ale/history.vim
104: ~/.vim/bundle/ale/autoload/ale/semver.vim
105: ~/.vim/bundle/ale/autoload/ale/job.vim
106: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter.vim
107: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/async.vim
108: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/debug.vim
109: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/diff.vim
110: ~/.vim/bundle/nerdtree/syntax/nerdtree.vim
111: ~/.vim/bundle/ale/autoload/ale/cursor.vim
112: ~/.vim/bundle/ale/autoload/ale/sign.vim
113: ~/.vim/bundle/ale/autoload/ale/list.vim
114: ~/.vim/bundle/ale/autoload/ale/highlight.vim

F821: undefined name 'Foo'
F821: undefined name 'Foo'
E999: SyntaxError: invalid syntax

E999: SyntaxError: invalid syntax
E999: SyntaxError: invalid syntax
F821: undefined name 'Foo'
    ```


<details><summary>:scriptnames</summary>


    ```
  1: /etc/vimrc
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: ~/.vimrc
  4: /usr/share/vim/vim82/ftoff.vim
  5: /usr/share/vim/vim82/syntax/syntax.vim
  6: /usr/share/vim/vim82/syntax/synload.vim
  7: /usr/share/vim/vim82/syntax/syncolor.vim
  8: /usr/share/vim/vim82/filetype.vim
  9: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
 10: /usr/share/vim/vim82/colors/desert.vim
 11: /usr/share/vim/vim82/syntax/nosyntax.vim
 12: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 13: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 14: /usr/share/vim/vim82/ftplugin.vim
 15: /usr/share/vim/vim82/indent.vim
 16: ~/.vim/bundle/gruvbox/colors/gruvbox.vim
 17: ~/.vim/bundle/fzf/plugin/fzf.vim
 18: ~/.vim/bundle/fzf.vim/plugin/fzf.vim
 19: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 20: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 21: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 22: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 23: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 24: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 25: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 26: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 30: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 31: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 32: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 33: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 34: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 35: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 36: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 37: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 38: ~/.vim/bundle/nerdtree/nerdtree_plugin/vcs.vim
 39: ~/.vim/bundle/nerdtree-git-plugin/nerdtree_plugin/git_status.vim
 40: ~/.vim/bundle/powerline/powerline/bindings/vim/plugin/powerline.vim
 41: ~/.vim/bundle/vim-buftabline/plugin/buftabline.vim
 42: ~/.vim/bundle/tabular/plugin/Tabular.vim
 43: ~/.vim/bundle/markdown-preview.vim/plugin/mkdp.vim
 44: ~/.vim/bundle/rename.vim/plugin/rename.vim
 45: ~/.vim/bundle/vim-ripgrep/plugin/vim-ripgrep.vim
 46: ~/.vim/bundle/vim-gitgutter/plugin/gitgutter.vim
 47: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/utility.vim
 48: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/highlight.vim
 49: ~/.vim/bundle/vim-obsession/plugin/obsession.vim
 50: ~/.vim/bundle/ale/plugin/ale.vim
 51: ~/.vim/bundle/ale/autoload/ale/completion.vim
 52: ~/.vim/bundle/ale/autoload/ale/events.vim
 53: ~/.vim/bundle/vim-surround/plugin/surround.vim
 54: ~/.vim/bundle/nerdcommenter/plugin/NERD_commenter.vim
 55: ~/.vim/bundle/auto-pairs/plugin/auto-pairs.vim
 56: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 57: ~/.vim/bundle/vim-syntax-extra/plugin/vim-syntax-extra.vim
 58: ~/.vim/bundle/vim-closetag/plugin/closetag.vim
 59: ~/.vim/bundle/MatchTagAlways/plugin/MatchTagAlways.vim
 60: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 61: /usr/share/vim/vim82/plugin/gzip.vim
 62: /usr/share/vim/vim82/plugin/logiPat.vim
 63: /usr/share/vim/vim82/plugin/manpager.vim
 64: /usr/share/vim/vim82/plugin/matchparen.vim
 65: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 66: /usr/share/vim/vim82/plugin/rrhelper.vim
 67: /usr/share/vim/vim82/plugin/spellfile.vim
 68: /usr/share/vim/vim82/plugin/tarPlugin.vim
 69: /usr/share/vim/vim82/plugin/tohtml.vim
 70: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 71: /usr/share/vim/vim82/plugin/zipPlugin.vim
 72: ~/.vim/bundle/tabular/after/plugin/TabularMaps.vim
 73: ~/.vim/bundle/tabular/autoload/tabular.vim
 74: /usr/share/vim/vim82/syntax/python.vim
 75: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 76: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 77: ~/.vim/bundle/vim-pydocstring/ftplugin/python/pydocstring.vim
 78: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 79: /usr/share/vim/vim82/ftplugin/python.vim
 80: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 81: ~/.vim/bundle/indentpython.vim/indent/python.vim
 82: /usr/share/vim/vim82/indent/python.vim
 83: ~/.vim/bundle/MatchTagAlways/autoload/MatchTagAlways.vim
 84: ~/.vim/bundle/ale/autoload/ale.vim
 85: ~/.vim/bundle/ale/autoload/ale/util.vim
 86: ~/.vim/bundle/ale/autoload/ale/linter.vim
 87: ~/.vim/bundle/ale/ale_linters/python/bandit.vim
 88: ~/.vim/bundle/ale/ale_linters/python/flake8.vim
 89: ~/.vim/bundle/ale/ale_linters/python/mypy.vim
 90: ~/.vim/bundle/ale/ale_linters/python/prospector.vim
 91: ~/.vim/bundle/ale/ale_linters/python/pycodestyle.vim
 92: ~/.vim/bundle/ale/ale_linters/python/pydocstyle.vim
 93: ~/.vim/bundle/ale/ale_linters/python/pyflakes.vim
 94: ~/.vim/bundle/ale/ale_linters/python/pylama.vim
 95: ~/.vim/bundle/ale/ale_linters/python/pylint.vim
 96: ~/.vim/bundle/ale/ale_linters/python/pyls.vim
 97: ~/.vim/bundle/ale/ale_linters/python/pyre.vim
 98: ~/.vim/bundle/ale/ale_linters/python/vulture.vim
 99: ~/.vim/bundle/ale/autoload/ale/engine.vim
100: ~/.vim/bundle/ale/autoload/ale/command.vim
101: ~/.vim/bundle/ale/autoload/ale/python.vim
102: ~/.vim/bundle/ale/autoload/ale/path.vim
103: ~/.vim/bundle/ale/autoload/ale/history.vim
104: ~/.vim/bundle/ale/autoload/ale/semver.vim
105: ~/.vim/bundle/ale/autoload/ale/job.vim
106: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter.vim
107: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/async.vim
108: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/debug.vim
109: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/diff.vim
110: ~/.vim/bundle/nerdtree/syntax/nerdtree.vim
111: ~/.vim/bundle/ale/autoload/ale/cursor.vim
112: ~/.vim/bundle/ale/autoload/ale/sign.vim
113: ~/.vim/bundle/ale/autoload/ale/list.vim
114: ~/.vim/bundle/ale/autoload/ale/highlight.vim
    ```
</details>
```

**Comment by davidhalter** [comment]
That's not true, `mro` is an actual function.

```
>>> class Foo: pass
... 
>>> Foo.mro()
[<class '__main__.Foo'>, <class 'object'>]
```

**Comment by julenpardo** [comment]
I wouldn't expect to return anything that is not returned by `dir`.

**Comment by davidhalter** [comment]
Well, dir is basically just wrong.
