### ISSUE TITLE
Code completion for `matplotlib` objects.

### ISSUE THREAD

**Issue by whereistejas** [davidhalter/jedi-vim#1014]
Hey! First of all I want to thank all the contributors for an awesome vim plugin.

Most of my work revolves around the `matplotlib` library.

However, I am having trouble getting code-completion to work for objects of that library. For example,
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot([some-random-numpy-array])
```

I'm not getting code-completion suggestions for the methods of the `ax` and `fig` objects.
Is this a known issue?

**Comment by davidhalter** [comment]
We have had this issue before. The basic problem is that they don't use stubs/annotations to make clear what the return type of `subplots()` (in https://matplotlib.org/3.2.1/_modules/matplotlib/pyplot.html#subplots) is. Therefore I don't see this changing as long as there are no stubs or annotations.

PS: You did delete the form and basically omitted all the necessary information. Normally I just close these issues. The form is there for a reason, please use it in the future.
