### ISSUE TITLE
can't complete on tensorflow normally

### ISSUE THREAD

**Issue by caixxiong** [davidhalter/jedi-vim#1015]
When I type the following python codes
```python
import tensorflow as tf
a = tf.keras.layers.Dense(10)
```
jedi can not complete names at tf.keras, and more generally, it only complete less than 3 level of package structures. Meanwhile, when I type `a = tf.constant()`, there is no parameter list popup here. However,  the completion for `numpy, sciphy, panda etc.` works normally. My environment infos are as follows:
- mac osx 10.14.6
- python3.7.7
- vim 8.2 compiled with options: python3, -python2, conceal
- jedi 0.17 
- tensorflow 1.15

Finally, I find out the problem. Firstly, it is not a bug in jedi-vim plugin, but a bad thing in tensorflow1.15. Then I install the other version of tensorflow tf1.14 or tf2.2, and all things works well.

The main reason for this is that the package structure of tf1.15 is terrible. When you install tf1.15, there are `tensorflow` `tensorflow_ core` folders in site-packages path, and the actual codes of tf are in `tensorflow_core` folder. This will lead to the jedi can not find all definitions of tf apis. On the other hand, there is no `tennsorflow_core` folder in tf1.14 and tf2.2, and it becomes a subdirectory of site-packages/tensorflow named `core`.

There is an another interesting thing. When I run code at ipython, the names at tf.1.15 can be also completed well, and as far as I know, ipython also uses jedi for completion. So is it still possible that there is a problem in jedi-vim?

**Comment by davidhalter** [comment]
> So is it still possible that there is a problem in jedi-vim?

No it's not, one uses static analysis and the other has all the runtime information (i.e. can call dir on objects) additionally.

In general it's something that has to be discussed with tensorflow devs. They occasionally improve their code base to make it more suitable for static analysis. Another option is to use stubs, but unfortunately I cannot provide more than that.

**Comment by caixxiong** [comment]
> > So is it still possible that there is a problem in jedi-vim?
> 
> No it's not, one uses static analysis and the other has all the runtime information (i.e. can call dir on objects) additionally.
> 
> In general it's something that has to be discussed with tensorflow devs. They occasionally improve their code base to make it more suitable for static analysis. Another option is to use stubs, but unfortunately I cannot provide more than that.

Thanks very much! Does it mean that  ipython may use `dir()` function to obtain completion informations ?

**Comment by davidhalter** [comment]
Jedi uses `dir` and a lot of other `inspect` commands to learn about the runtime in `Interpreter` mode (which is used in IPython).
