### ISSUE TITLE
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 2 or 3

### ISSUE THREAD

**Issue by sepremento** [davidhalter/jedi-vim#1018]
### Issue

Windows 8.1, Python 3.6-32

Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 2 or 3. (in function jedi#init_python[4]..48_init_python, line 10)

`:ver` says I have `+python/dyn`, `+python3/dyn`, so I'm a little bit confused what to think.

**Comment by davidhalter** [comment]
Does `:python print(1)` work? And `:python3 print(1)`?

**Comment by sepremento** [comment]
No, I get `E370: Could not load library python27.dll` and then `E263: Sorry this command is disabled, the Python library could not be loaded.` Which is very strange as I have Python 3.6-32.

**Comment by davidhalter** [comment]
This is not a jedi-vim problem. Usually the best way forward is to uninstall Vim and reinstall it so you get a proper installation. VIM might have been compiled with another version. I generally have no idea how this works on Windows.

You could also contact the vim mailing list, asking why `:python3` does not work for you.

**Comment by joeytai** [comment]
this issue bks ur vim don;t have python3,
in my side
```brew install macvim```
it works for me.

**Comment by fenwk0** [comment]
Hi Jedi looks amazing and I'd love to get it running, the base instal of vim does not support Python.

What is a proper vim install for a raspberry pi?

$ uname -a
Linux minecraft-01 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

The error I get consistently is : 

Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 3. (in function jedi#
init_python[4]..<SNR>69_init_python, line 4) 

I even tried to rebuild vim with Python support 

sudo apt-get install libncurses5-dev libncursesw5-dev
cd /tmp && sudo rm -Rf vim && git clone https://github.com/vim/vim.git && cd vim 
make distclean 
rm auto/config.cache
./configure --enable-pythoninterp --prefix=/usr --with-python-config-dir=/usr/lib/python2.7/config-arm-linux-gnueabihf//--enable-python3interp=yes --with-python3-config-dir=/usr/lib/python3.7/config-3.7m-arm-linux-gnueabihf/ 
make && sudo make install

but still no luck, when I check via :ver

**Comment by masumndc1** [comment]
I had jedi-vim python 3 support issue with neovim in mac. 
I have solved it by running 
```
 sudo port install py-neovim
```
