### ISSUE TITLE
probably should not 'au winleave q'

### ISSUE THREAD

**Issue by Shane-XB-Qian** [davidhalter/jedi-vim#1019]
otherwise the result is a little flaky ...
looks we discussed a bit at #956, but i almost forgot that detail, code had been refined also, but that's for 'for_usages' ..
but actually, now i found if qf had multiple-result, general windows (other than qf) maybe messed & closed accidentally too ..
```vimscript
    augroup jedi_goto_window
        if a:for_usages
            autocmd BufWinLeave <buffer> call jedi#clear_usages()
        else
            autocmd WinLeave <buffer> q  " automatically leave, if an option is chosen
        endif
    augroup END
```
// so far, i can not figure out why this buffer level au was applied on general windows, but simply i suggested it perhaps better be no such au setting .. or as a workaround as well .. just fyi. anyway.

**Comment by davidhalter** [comment]
I don't really understand what we should change.

**Comment by Shane-XB-Qian** [comment]
i mean just remove 'au winleave <buffer> q', or what that mentioned 'option' was ?
your purpose i guess just wish qf would/can be auto closed after a 'cr' or ':cn' etc,
but somehow so far not sure why but it may applied such 'event' on others general windows - maybe closed accidently too - perhaps related to my env (?) or somehow ...

besides, many others plugins looks used to remain qf open - unless user chose to ..

just i found such wired case, and this is a fyi and suggestion, and it should be helpful if someone searched into here/this ticket, but it's ok - as long as augroup name and au even kind (winleave) not changed (please), user can 'au!' remove it in her/his side as well.
