### ISSUE TITLE
E117 Unknown function: jedi#remove_usages on insert

### ISSUE THREAD

**Issue by vegarab** [davidhalter/jedi-vim#1021]
### Issue

Using Vundle to install jedi-vim
`Plugin 'davidhalter/jedi-vim'`.

Opening a `.py` file gives the following error whenever I enter insert-mode:
```
Error detected while processing InsertEnter Autocommands for "<buffer=1>":
E117: Unknown function: jedi#remove_usages
```

##### jedi-vim version

 - jedi-vim git version: 0.10.0-37-ga0207fa
 - jedi git submodule status:  3ad3dc08b8bf9d749b2d0d9fca038657711c82f2 pythonx/jedi (v0.16.0-11-g3ad3dc08)
 - parso git submodule status:  c864ca60d1a2f36524a4f79013a7de223e65e19d pythonx/parso (v0.6.0)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/usr/local/bin/python3`
 - global sys.version: `3.8.3 (default, May 17 2020, 18:15:42), [GCC 10.1.0]`
 - global site module: `/usr/lib/python3.8/site.py`

##### Jedi

 - path: `/home/vegarab/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.16.1

##### Jedi environment: <SameEnvironment: 3.7.3 in /usr/local>

 - executable: /usr/local/bin/python3
 - sys_path:
    - `/usr/local/lib/python37.zip`
    - `/usr/local/lib/python3.7`
    - `/usr/local/lib/python3.7/lib-dynload`
    - `/home/vegarab/.local/lib/python3.7/site-packages`
    - `/usr/local/lib/python3.7/site-packages`

##### Known environments

 - <Environment: 3.8.3 in /usr> (/usr/bin/python3.8)

 - <Environment: 3.7.3 in /usr/local> (/usr/local/bin/python3.7)

 - <Environment: 3.6.10 in /usr> (/usr/bin/python3.6)

 - <Environment: 2.7.18 in /usr> (/usr/bin/python2.7)

##### Settings

```
  omnifunc=jedi#completions
	Last set from ~/dotfiles/.vim/bundle/jedi-vim/autoload/jedi.vim line 738
  completeopt=menuone,longest,preview
	Last set from /usr/share/vim/vimfiles/plugin/jedi.vim line 36
```

**Comment by davidhalter** [comment]
Can you upgrade to master? Not sure if it was fixed along the lines or if this is some weird issue. At least I don't find `jedi#remove_usages` anywhere in our codebase on master.

**Comment by vegarab** [comment]
I installed jedi directly using Vundle. I'd assume that pulled master? 

Manually installing by cloning master still produces the same results. 
I know I've had jedi installed long ago on this system. Could there be some cached files that are being loaded instead?

**Comment by davidhalter** [comment]
No idea. I'm pretty sure that there is something wrong with your system if you are using master.

remove_usages() was removed in 5880f2de93221bb6b8ade33bcd888047c86e8f05.

This name does not exist in current jedi-vim:

```
:~/.vim/bundle/jedi-vim$ git grep -i remove_usages
<nothing>
```

So I suppose you really have to dig deeper and remove potential other installations of jedi-vim that might be conflicting. I'm closing for now.

**Comment by blueyed** [comment]
@vegarab 
Check `:verb au InsertEnter` to see where it gets defined - maybe some custom/local script/config.
