### ISSUE TITLE
Jedi Vim crashing in conda env

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [davidhalter/jedi-vim#1022]
### Issue

Opening a python file causes vim to crash.
Opening an empty file and then running :JediDebugInfo causes vim to crash

Stderr is
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002b41c8d26240 (most recent call first):
```

Not sure how to debug this. 

I'm in a conda environment
```
$ python --version
Python 3.6.9 :: Anaconda, Inc.
```
and I've installed jedi-vim with `VimPlug`

This error encourages me to set PYTHONHOME, but doing so breaks anaconda

In the jedi-vim git clone that VimPlug creates, I see
```
$ git submodule status
3ad3dc08b8bf9d749b2d0d9fca038657711c82f2 pythonx/jedi (v0.16.0-11-g3ad3dc0)
c864ca60d1a2f36524a4f79013a7de223e65e19d pythonx/parso (v0.6.0)
```
The jedi-vim repo is up to date

But apparently I have a different version of jedi installed in the conda environment as a whole?
```
$ pip list | grep jedi
jedi                          0.15.1
```
VimPlug should be managing the jedi-vim installation, so I don't know why there's a different jedi installation in the conda environment. But I also don't know how to fix that without breaking anything, or if that's at all relevant to this issue.

**Comment by davidhalter** [comment]
> Not sure how to debug this.

Yeah me neither. I would probably try to reinstall everything from scratch. It just looks like a broken Python installation. Not sure why this would happen. But it has been happening before. It would maybe be interesting to see something like `:python3 import sys; print(sys.prefix, sys.path)` (without using jedi-vim).

If you want to debug this, you probably have to find out why this happens: `Fatal Python error: Py_Initialize: Unable to get the locale encoding`. I'm pretty sure you could trigger that without using jedi-vim somehow.

**Comment by LiterallyUniqueLogin** [comment]
Thank you for the fast reply! `:python3 import sys; print(sys.prefix, sys.path)` causes the same error - so maybe this is an issue with my vim setup, and not with jedi-vim specifically? Any pointers on how vim interoperates with python?

python works in all use-cases in this environment, so even if reinstalling everything is the fix, I wouldn't say that the environment is broken per se.

**Comment by davidhalter** [comment]
> python works in all use-cases in this environment, so even if reinstalling everything is the fix, I wouldn't say that the environment is broken per se.

Your Python installation is probably not broken. The problem is that VIM somehow embeds Python and the combination of VIM/Python is broken. Usually people that come here with similar issues just reinstall VIM (or install a newer version) and everything works fine.

I'm going to close, because this is definitely not a jedi-vim issue. However feel free to keep the discussion going here. I'm still reading :).

**Comment by LiterallyUniqueLogin** [comment]
Thanks! I'm recreating the entire conda env which'll take a bit, I'll let you know how that goes.

**Comment by LiterallyUniqueLogin** [comment]
I get a new error in my new environment, probably because I decided to install python 3.7 instead of 3.6. It seems that the python setup isn't a complete bust like last time though. The new error is below.

If my interpretation is correct, it seems that jedi is trying to parse `sys.version`, can't and fails. According to [the python docs](https://docs.python.org/3/library/sys.html#sys.version) Jedi should be looking in either [`sys.version_info`](https://docs.python.org/3/library/sys.html#sys.version_info) or [`platform`](https://docs.python.org/3/library/platform.html#module-platform), not `sys.version`. So maybe a fix is in order? Or perhaps that's a recommendation that's not widely adopted in the community, and this type of version string is uncommon (this [SO post](https://stackoverflow.com/a/34155037/2966505) suggests so). Thoughts?

```
jedi-vim error: jedi#setup_python_imports: Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/home/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 114, in <module>
    import jedi
  File "/home/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py", line 38, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
    import parso
  File "/home/.vim/plugged/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/.vim/plugged/jedi-vim/pythonx/parso/parso/parser.py", line 26, in <module>
    from parso import tree
  File "/home/.vim/plugged/jedi-vim/pythonx/parso/parso/tree.py", line 4, in <module>
    from parso._compatibility import utf8_repr, encoding
  File "/home/.vim/plugged/jedi-vim/pythonx/parso/parso/_compatibility.py", line 14, in <module>
    is_pypy = platform.python_implementation() == 'PyPy'
  File "/projects/resources/source/python-3.7.4/lib/python3.7/platform.py", line 1264, in python_implementation
    return _sys_version()[0]
  File "/projects/resources/source/python-3.7.4/lib/python3.7/platform.py", line 1225, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 19:02:36) \n[GCC 7.5.0]'
Error detected while processing function jedi#init_python[11]..<SNR>54_display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: Traceback (most recent call last): (in function jedi#init_python[4]..<SNR>54_init_python[27]..jedi#setup_python_imports, line 32). See :messages and/or :JediDebugInfo for more information.
```

Details:
```
$ which python
~/anaconda3/envs/ukb/bin/python
$ python -c "import sys; print(sys.version)"
3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50)
[GCC 7.5.0]
$ python -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by blueyed** [comment]
@LiterallyUniqueLogin 
Can you provide the full statement (multiple lines) from /projects/resources/source/python-3.7.4/lib/python3.7/platform.py, please?
(Jedi/parso is calling `platform.python_implementation() == 'PyPy'`, which should be fine I assume)

**Comment by LiterallyUniqueLogin** [comment]
You're right, that makes sense, this isn't an issue with how jedi-vim is interacting with the API.

But that pointed me to the fact that there's a pathing issue.

My python is installed in `~/anaconda3/envs/ukb/bin/python` and is version 3.7.6, not in `/projects/resources/source/python-3.7.4`. Any idea why code is being called from there?

For instance, from the shell
```
$ python --version
3.7.6
$ python -c "import platform; print(platform.__file__)"
/home/anaconda3/envs/ukb/lib/python3.7/platform.py
```
And from within vim
```
:python3 import sys; print(sys.version)
3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 19:02:36)
[GCC 7.5.0]
:python3 import platform; print(platform.__file__)
/projects/resources/source/python-3.7.4/lib/python3.7/platform.py
```

From `vim --version` I see no reference to python-3.7.4 but I do see a reference to my python3.7(.6) install
```
Linking: /home/conda/feedstock_root/build_artifacts/vim_1594072751144/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc   -Wl,-O2 -Wl,--sort-common -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/anaconda3/envs/ukb/lib -Wl,-rpath-link,/home/anaconda3/envs/ukb/lib **-L/home/anaconda3/envs/ukb/lib -Wl,--as-needed -o vim        -lm -ltinfo   -ldl     -L/home/anaconda3/envs/ukb/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lcrypt -lpthread -ldl -lutil -lrt -lm
```

I can still upload the platform.py file that's being called if you still think that's relevant.

**Comment by davidhalter** [comment]
Can you give us `:version`?

As I said I'm going to close.

**Comment by LiterallyUniqueLogin** [comment]
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul  6 2020 22:02:25)
Included patches: 1-1149
Compiled by conda@00cc5b93fbb1
Huge version without GUI.  Features included (+) or not (-):
+acl               -clientserver      +diff              +folding           +langmap           +mouse_dec         +num64             +reltime           +tag_binary        -toolbar           +writebackup       +arabic            -clipboard         +digraphs          -footer            +libcall           -mouse_gpm         +packages          +rightleft         -tag_old_static    +user_commands     -X11+autocmd           +cmdline_compl     -dnd               +fork()            +linebreak         -mouse_jsbterm     +path_extra        -ruby              -tag_any_white     +vartabs           -xfontset+autochdir         +cmdline_hist      -ebcdic            +gettext           +lispindent        +mouse_netterm     -perl              +scrollbind        -tcl               +vertsplit         -xim-autoservername    +cmdline_info      +emacs_tags        -hangul_input      +listcmds          +mouse_sgr         +persistent_undo   +signs             +termguicolors     +virtualedit       -xpm-balloon_eval      +comments          +eval              +iconv             +localmap          -mouse_sysmouse    +popupwin          +smartindent       +terminal          +visual            -xsmp+balloon_eval_term +conceal           +ex_extra          +insert_expand     -lua               +mouse_urxvt       +postscript        -sound             +terminfo          +visualextra       -xterm_clipboard   -browse            +cryptv            +extra_search      +ipv6              +menu              +mouse_xterm       +printer           +spell             +termresponse      +viminfo           -xterm_save        ++builtin_terms    +cscope            -farsi             +job               +mksession         +multi_byte        +profile           +startuptime       +textobjects       +vreplace+byte_offset       +cursorbind        +file_in_path      +jumplist          +modify_fname      +multi_lang        -python            +statusline        +textprop          +wildignore+channel           +cursorshape       +find_in_path      +keymap            +mouse             -mzscheme          +python3           -sun_workshop      +timers            +wildmenu+cindent           +dialog_con        +float             +lambda            -mouseshape        +netbeans_intg     +quickfix          +syntax            +title             +windows
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/anaconda3/envs/ukb/share/vim"
Compilation: /home/conda/feedstock_root/build_artifacts/vim_1594072751144/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -c -I. -Iproto -DHAVE_CONFIG_H   -DNDEBUG -O2 -isystem /home/anaconda3/envs/ukb/include -I/home/anaconda3/envs/ukb/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/anaconda3/envs/ukb/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/vim_1594072751144/work=/usr/local/src/conda/vim-8.2.1149 -fdebug-prefix-map=/home/anaconda3/envs/ukb=/usr/local/src/conda-prefix -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /home/conda/feedstock_root/build_artifacts/vim_1594072751144/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc   -Wl,-O2 -Wl,--sort-common -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/anaconda3/envs/ukb/lib -Wl,-rpath-link,/home/anaconda3/envs/ukb/lib -L/home/anaconda3/envs/ukb/lib -Wl,--as-needed -o vim        -lm -ltinfo   -ldl     -L/home/anaconda3/envs/ukb/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lcrypt -lpthread -ldl -lutil -lrt -lm
```

**Comment by LiterallyUniqueLogin** [comment]
I removed the other version of python from the PATH and the issue went away. I don't know why vim was pulling it in when running python from the command line wasn't an issue. But this fixes the problem. Thank you all for the help.

**Comment by davidhalter** [comment]
Running something with embedded Python is not the same as running it on the command line. It will probably just load some libraries that are somewhere in `/usr/lib` instead of an executable. So it could very well be that there was a mixup with the libraries in there.
