### ISSUE TITLE
Line numbers in Preview window

### ISSUE THREAD

**Issue by mlongval** [davidhalter/jedi-vim#1027]
This is not an "issue" but rather a question. 

I use line numbering when coding. 

I want to turn  OFF  the line numbers but ONLY in the PREVIEW window.

How/where would I instruct the jedi-vim plugin to NOT display line numbers in the PREVIEW window? 

Thanks

**Comment by davidhalter** [comment]
Sorry I don't know that. It's probably somehow possible.

You can probably do something like `autocommand BufReadPost quickfix set nonumber`. Good luck. The VIM documentation is usually pretty good about this stuff, but VIM itself is very complicated, so it's hard to find out where to look.
