### ISSUE TITLE
Vim freezes on python file opening

### ISSUE THREAD

**Issue by zakutin** [davidhalter/jedi-vim#1028]
### Issue
After the installation of jedi-vim, vim freezes in Windows Terminal or powershell on python file opening, so that I need to terminate the process, because vim does not accept commands. However, jedi-vim works well in gVim.

Windows 10 Pro x64 2004
PowerShell 7.0.3
Windows Terminal 1.3.2651.0

### Steps to reproduce
1. Install jedi-vim with help of vim-plug or vundle.
2. Open py file in Windows Terminal or powershell.
3. Vim freezes instantly.

### Output of “:verbose JediDebugInfo”

It is not possible to execute ":verbose JediDebugInfo" in Windows Terminal or powershell as it freezes on execution and doesn't let to display more. So the debug info is from gVim below:
[JediDebugInfo.txt](https://github.com/davidhalter/jedi-vim/files/5326742/JediDebugInfo.txt)

**Comment by davidhalter** [comment]
This is probably a VIM bug. I'll keep this one open for now, but without further investigation on your side, I doubt that we will ever solve this one. I personally use Ubuntu, so I cannot help.

**Comment by zakutin** [comment]
Thank you @davidhalter , I researched a little bit, there is something to do with `python3 import subprocess`. I tried to disable all modules and execute `python3 import subprocess` – the terminal got frozen. I also now think the problem is not with jedi-vim.

I reinstalled python and vim again, checked environment variables, everything looks fine, but the issue with python import still persists.

**Comment by davidhalter** [comment]
In that case, I will close here. If `:python3 import subprocess`, Jedi will not work by definition.

It's strange that reinstalling python does not help. I'm pretty sure quite a few other people use jedi-vim on Windows.
