### ISSUE TITLE
Please tag a new release with 3.9 support

### ISSUE THREAD

**Issue by QuLogic** [davidhalter/jedi-vim#1036]
### Issue

The current version (0.10.0) only includes parso with grammar up to 3.8. Thus parsing is broken with Python 3.9. In `master`, this submodule is updated and could work with 3.9 (though I have not tested it.)

### Steps to reproduce

Install neovim, vim-plug, and add jedi-vim; set default Python to 3.9. Then attempt to use, e.g., goto-assignment.

### Output of “:verbose JediDebugInfo”

Note, the command `:redir @+> | silent verb JediDebugInfo | redir END` did not work; I don't know why. I copied what I could from `:verbose JediDebugInfo` instead, but it got a bit weird:

##### jedi-vim version

 - jedi-vim git version: 0.10.0
 - jedi git submodule status:  60415033b40bcef939d2a5378e2eff7b563265c5 pythonx/jedi (v0.14.1)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.9.0 (default, Oct  6 2020, 00:00:00), [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]`
 - global site module: `/usr/lib64/python3.9/site.py`

##### Jedi

 - path: `~/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.14.1

##### Settings

```
g:jedi#force_py_version = 3 (default: 'auto')
g:jedi#use_splits_not_buffers = 'winwidth' (default: 1)
g:jedi#completions_enabled = 0 (default: 1)

  omnifunc=python3complete#Complete
        Last set from /usr/share/nvim/runtime/ftplugin/python.vim line 41
  completeopt=menuone,preview,noselect
        Last set from ~/.local/share/nvim/plugged/deoplete.nvim/autoload/deoplete/mapping.vim line 98
```

#### :version
```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_
FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redha
t/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1
 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissin
g-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_
GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.4.4/x86_64-redhat-linux-gnu/config -I/build
dir/build/BUILD/neovim-0.4.4/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.4.4/x86_64-redhat-linux-gnu/src/nvim
/auto -I/builddir/build/BUILD/neovim-0.4.4/x86_64-redhat-linux-gnu/include
Compiled by mockbuild

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by davidhalter** [comment]
Created 0.11.0

**Comment by QuLogic** [comment]
Thank you; this appears to be working once again.
