### ISSUE TITLE
jedi-vim fails to start

### ISSUE THREAD

**Issue by inyeollee** [davidhalter/jedi-vim#1038]
### Issue

Installed jedi-vim from GitHub. When launching vim as 'vim foo.py' it generates error message:

### Steps to reproduce

My env is:
macOS 11.1
Python 3.9.1 (compiled manually)
vim 8.2.2117 with python3 support (compiled manually)
jedi 0.17.2 (installed using pip)
jedi-vim (git cloned to ~/.vim/pack/jedi-vim/start/jedi-vim

No jedi-specific settings in vimrc

### Output of “:verbose JediDebugInfo”

Error detected while processing BufNewFile Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>3_LoadFTPlugin[17]..script /Users/inyeol/.vim/pack/jedi-vim/star
t/jedi-vim/ftplugin/python/jedi.vim[1]../Users/inyeol/.vim/pack/jedi-vim/start/jedi-vim/autoload/jedi.vim[292]..function jedi#init_python[13]..BufNewFile Autocommands for "*.py"
..FileType Autocommands for "*"..function <SNR>3_LoadFTPlugin[17]..script /Users/inyeol/.vim/pack/jedi-vim/start/jedi-vim/ftplugin/python/jedi.vim[1]../Users/inyeol/.vim/pack/je
di-vim/start/jedi-vim/autoload/jedi.vim[292]..function jedi#init_python[11]..<SNR>23_display_exception:                                                                          
line   19:                                                                                                                                                                       
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: dlopen(/Users/inyeol/util/lib/python3.9/lib-dynload/_posixsubprocess.cpython-39-darwin.so, 2
): Symbol not found: _PyExc_MemoryError (in BufNewFile Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>3_LoadFTPlugin[17]..script /Users/inyeol/.vim/pack/j
edi-vim/start/jedi-vim/ftplugin/python/jedi.vim[1]../Users/inyeol/.vim/pack/jedi-vim/start/jedi-vim/autoload/jedi.vim[292]..function jedi#init_python[4]..<SNR>23_init_python[27]
..jedi#setup_python_imports, line 32). See :messages and/or :JediDebugInfo for more information.                                                                                 
Error detected while processing BufNewFile Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>3_LoadFTPlugin[17]..script /Users/inyeol/.vim/pack/jedi-vim/star
t/jedi-vim/ftplugin/python/jedi.vim:                                                                                                                                             
line   36:                                                                                                                                                                       
E117: Unknown function: jedi#configure_call_signatures

**Comment by inyeollee** [comment]
Resolved. This was due to vim compilation issue. Closing.

**Comment by VladMikheenko** [comment]
I have the same problem. How can I solve it?

**Comment by inyeollee** [comment]
It was from vim compilation problem described here: https://github.com/vim/vim/issues/7551
I summarized the symptom and the workaround there.
