### ISSUE TITLE
Error detected while processing function jedi#goto_window_on_enter

### ISSUE THREAD

**Issue by lakenn** [davidhalter/jedi-vim#1041]
### Issue

"shows all the usages of a name" works. It shows me the list of usage in a split pane properly but when I try to go to the result containing the usage, i got the below error:

Error detected while processing function jedi#goto_window_on_enter:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'jedi_vim' has no attribute 'new_buffer'

### Steps to reproduce

`<leader>n` on new_hello and search pane show correctly and then try go to the location of the usage
<img width="1056" alt="Screenshot 2021-01-30 at 11 35 07 AM" src="https://user-images.githubusercontent.com/17800986/106346075-65d38980-62ef-11eb-8833-acc0499bd02f.png">

### .vimrc
let g:jedi#use_tabs_not_buffers = 1

if i set let g:jedi#use_tabs_not_buffers = 0, then it works

Thanks

**Comment by davidhalter** [comment]
Thanks for the report.

Next time please include the form that you were prompted to fill. It helps us understand things.
