### ISSUE TITLE
E117: Unknown function: jedi#configure_call_signatures

### ISSUE THREAD

**Issue by VladMikheenko** [davidhalter/jedi-vim#1051]
### Issue
Error detected while processing function <SNR>29_NetrwBrowseChgDir[195]..BufRead Autocommands for "*.py"..FileType Autocommands
for "*"..function <SNR>7_LoadFTPlugin[17]..script /c/Users/User/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim[1]../c/Users/User/
.vim/bundle/jedi-vim/autoload/jedi.vim[259]..function jedi#init_python[13]..function <SNR>29_NetrwBrowseChgDir[195]..BufRead Aut
ocommands for "*.py"..FileType Autocommands for "*"..function <SNR>7_LoadFTPlugin[17]..script /c/Users/User/.vim/bundle/jedi-vim
/ftplugin/python/jedi.vim[1]../c/Users/User/.vim/bundle/jedi-vim/autoload/jedi.vim[259]..function jedi#init_python[11]..<SNR>34_
display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 3. (in function <SNR>29_NetrwBrowseCh
gDir[195]..BufRead Autocommands for "*.py"..FileType Autocommands for "*"..function <SNR>7_LoadFTPlugin[17]..script /c/Users/Use
r/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim[1]../c/Users/User/.vim/bundle/jedi-vim/autoload/jedi.vim[259]..function jedi#ini
t_python[4]..<SNR>34_init_python, line 4)
Error detected while processing function <SNR>29_NetrwBrowseChgDir[195]..BufRead Autocommands for "*.py"..FileType Autocommands
for "*"..function <SNR>7_LoadFTPlugin[17]..script /c/Users/User/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim:
line   36:
E117: Unknown function: jedi#configure_call_signatures
Press ENTER or type command to continue

### Steps to reproduce

###1. Install Vundle:
**git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim**
###2. Paste minimal Vundle's config in your .vimrc:
_set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line_
###3. Install Jedi:
**Plugin 'davidhalter/jedi-vim'**
###4. Update Jedi:
**git submodule update --init --recursive** (in Jedi-Vim folder)
###6. Update Plugins:
**:PluginUpdate** (in Vim)
###6. Enter Vim

### Output of “:verbose JediDebugInfo”

I use python 3 and it works.
##### Global Python

Using Python version 3 to access Jedi.
Error when trying to import vim: Vim(python3):E370: Could not load library msys-python3.8.dll
python3 failed to run, likely a Python config issue.

**Comment by davidhalter** [comment]
As the message said, you are not able to load Python3 in VIM. This is not a jedi-vim issue. You likely have to reinstall VIM and Python or something like this.
