### ISSUE TITLE
Feature Request: Show documentation at cursor

### ISSUE THREAD

**Issue by RJaikanth** [davidhalter/jedi-vim#1052]
### Issue

Feature Request:
Show the documentation of the word at the current cursor like kite does currently.

Sorry if this has been already implemented, I could not see it as an option here

**Comment by davidhalter** [comment]
You can just use `K`. This should be implemented :)

**Comment by RJaikanth** [comment]
Hi @davidhalter sorry if i have not been clear enough. But what I am asking is the preview window updates itself to match the documentation of the function/class at cursor's position without having to press `K`. We only have to press it once and then the plugin can follow the cursor.

**Comment by davidhalter** [comment]
Yeah, sorry that won't happen, because I don't think it's worth the hassle (just the maintenance alone).

To be honest I also don't really understand when that would be really useful. Isn't it more practical to open with K and quickly close again to save screen space?
