### ISSUE TITLE
nothing happen after installing 

### ISSUE THREAD

**Issue by ben-sin** [davidhalter/jedi-vim#1061]
I am a newbie to coding. Using ubuntu 20.04. I install jedi thru the official reop by `sudo apt install vim-python-jedi` but after I installed nothing was changed in vim. Do I need to initialise it or I missing something? please help

**Comment by davidhalter** [comment]
Hi @ben-sin 

Sorry I'm afraid I probably cannot help you here. You should probably run `:JediDebugInfo` and show us the output.

**Comment by ben-sin** [comment]
Hi @davidhalter 

I tried runing `JediDebugInfo`, it return `E492: Not an editor command: JediDebugInfo`

**Comment by davidhalter** [comment]
Yeah, in that case jedi-vim is not installed. You should probably contact the `vim-python-jedi` maintainers or just use a VIM plugin manager like this one: https://github.com/junegunn/vim-plug.
