### ISSUE TITLE
Autocomplete from imports using SourceFileLoader

### ISSUE THREAD

**Issue by mdforti** [davidhalter/jedi-vim#1065]
### Steps to reproduce

editing python script
import module and possibly classes using importlib.machinery.SourceFileLoader instead of normal import
start new object
try to autocomplete property or method from new instance
ompni completion wont find pattern.

I don't know if this is a bug or a missing feature, but it would be great to have it working at some point. 

Thank you all for the help and the great tool.

**Comment by davidhalter** [comment]
This is not enough to reproduce your issue. You probably need to send your source file.

**Comment by mdforti** [comment]
exaple.py:
``` python
class greeter:
    def __init__(self):
        self.greet_phrase = "Hello World"
        pass

    def greet(self):
        print(self.greet_phrase)
```

noautocomplete.py
``` python
from importlib.machinery import SourceFileLoader

greeter = SourceFileLoader('greeter', 'example.py').load_module().greeter

G=greeter()

G.greet()
```

yesautocomplete.py:
```
from example import greeter

G = greeter()

G.greet()
```

**Comment by davidhalter** [comment]
`SourceFileLoader` and other dynamic things like changing a module's dict or using `setattr` are not supported. Just set the sys path properly.

**Comment by mdforti** [comment]
ok, thats clear now. Thank you !
