### ISSUE TITLE
jedi-vim errors on startup

### ISSUE THREAD

**Issue by whmsft** [davidhalter/jedi-vim#1071]
I just installed jedi-vim and then i when i started vim,
this was shown:

![image](https://user-images.githubusercontent.com/72214351/147451293-5955a918-d815-4b6d-aad0-398f0e63becf.png)

**Comment by davidhalter** [comment]
As the error said: Python 3 is required. Your VIM does not support that. Try installing a "newer" version with Python 3 support.

**Comment by whmsft** [comment]
what newer version? New vim?

**Comment by whmsft** [comment]
I do have vim 8.2 and python 3.8
What do you mean by "newer"

**Comment by davidhalter** [comment]
Your Vim is not able to access Python for some reason. This is not a jedi-vim issue. Please use the vim user mailing list and ask there for help.

**Comment by whmsft** [comment]
Ok, i will try and tell you the results
