### ISSUE TITLE
Find usages does not get path from vim path

### ISSUE THREAD

**Issue by kabeersvohra** [davidhalter/jedi-vim#1077]
### Issue

I am using a vim rooter plugin which sets `:pwd` to being the git (project root) whenever a file is opened. When I try to get usages using `<leader> n` on a function, it populates the quickfix list with a list of files relative to the file open. Therefore when I try and open the file, it does not open the correct path.

For example I have a file in `{project_root}/folder1/file1.py` and then I have a usage in `{project_root}/folder1/file2.py` and I try and go to `file2.py` from `file1.py` using jedi, it will open `{project_root}/file2.py` which will be blank.

### Steps to reproduce

`cd project_root`
`nvim folder1/file2.py`
navigate to function definition
`<leader> n`
select `file2.py` from quickfix list
blank `nvim` opens for `project_root/file2.py`

**Comment by davidhalter** [comment]
You have to provide the debug info...

**Comment by kabeervohra** [comment]
What debug info would be useful and how can I provide it?

**Comment by davidhalter** [comment]
Open a new issue and you see it. you just deleted it.
