### ISSUE TITLE
My silly question about the jedi-vim

### ISSUE THREAD

**Issue by tommylawy** [davidhalter/jedi-vim#1084]
Hi,
I am newbie in vim and it's my first time to install jedi-vim with VundleVim, and my vim version is 8.1
But when I write python code, after I click "dot" there's no popping-up window or message, is there anything errors?

My .vimrc
`
if has("syntax")
  syntax on
endif

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set nocompatible 
filetype plugin indent on
set number 
set showmatch
set tabstop=4  "设置Tab长度为4空格
set shiftwidth=4  " 设定 << 和 >> 命令移动时的宽度为 4
set autoindent  "继承前一行的缩进方式，适用于多行注释
set paste   "粘贴时防止出现缩进错误
set cursorline   " 突出显示当前行
set ignorecase smartcase    " 搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set hlsearch                " 搜索时高亮显示被找到的文本
filetype off                   "必须"
let g:jedi#environment_path = "/usr/bin/python3"
let g:jedi#auto_vim_configuration = 0
let g:SuperTabRetainCompletionType=2

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'preservim/nerdcommenter'
Plugin 'preservim/nerdtree'
Plugin 'davidhalter/jedi-vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'tell-k/vim-autopep8'
Plugin 'packloadall'
Plugin 'SuperTab'

autocmd FileType python3 noremap <buffer> <F9> :call Autopep8()<CR> # Use F9

" All of your Plugins must be added before the following line
call vundle#end()            " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
autocmd VimEnter * NERDTree
`

**Comment by davidhalter** [comment]
You forgot to fill out the form when creating the issue. Now we don't have enough information to debug your issue. Since You have ignored it, I'm closing this issue, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary debug information.
