### ISSUE TITLE
How to disable the docstring viewer on completion ?

### ISSUE THREAD

**Issue by hl037** [davidhalter/jedi-vim#1091]
During the completion (with the popup menu) a split is created conteining the docstring of the function. I think it's a recent addition, but I really disturb (piss) me. I have not see any configuration to disable it in the documentation.

Is there one ?

Could you add one if there is not yet ?

Thanks again for this wonderful plugin anyway !

**Comment by davidhalter** [comment]
I think you can just remove `preview` from `completeopt`.

**Comment by hl037** [comment]
Thank you very much !

Maybe add documentation on this point ?

**Comment by davidhalter** [comment]
It's already part of the README: https://github.com/davidhalter/jedi-vim#i-dont-want-the-docstring-window-to-popup-during-completion

**Comment by davidhalter** [comment]
No.
