### ISSUE TITLE
Hashlib issue on startup

### ISSUE THREAD

**Issue by roda37** [davidhalter/jedi-vim#1096]
Followed instructions as prescribed, used Vundle and vim-plug (just to be sure Vundle wasn't doing harm). But all I get is a hashlib error. I cannot paste the code since Vim wont allow me but I got a screenshot here. I am using the latest Arch Linux.

Update: I have compiled Vim from source, with python3 support in it. The parameters that I have used are as follows:

./configure --with-features=huge --enable-python3interp=yes \
    --enable-rubyinterp=yes --enable-cscope --enable-gui=auto \
    --enable-gtk2-check \
    --enable-fail-if-missing --enable-multibyte --enable-fontset \
    --with-x --with-compiledby="devidence" \
	--with-python3-config-dir=$(python3-config --configdir) \
    --with-ruby-command=/usr/bin/ruby
make
sudo make install

![image](https://user-images.githubusercontent.com/55464245/207812594-8b912f34-c9a3-4e59-b6ea-d32eb7737eee.png)

**Comment by davidhalter** [comment]
This looks like a build gone wrong. hashlib needs to be importable.
