### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mhjacks** [davidhalter/jedi-vim#1111]
### Issue

Could we get a new formal release?

### Steps to reproduce

I'm the packager of jedi-vim for Fedora, and it looks like git master fixes some issues in the package. I could package a snapshot, but it would be cleaner, and might help other distro packagers as well.

Thanks for the consideration!

**Comment by davidhalter** [comment]
I'm happy to tag a release, but someone needs to upgrade Jedi first.

**Comment by mhjacks** [comment]
I would be happy to work with the python3-jedi maintainers in Fedora on co-ordinating updates. What would the minimum version of Jedi be for such a new release, do you think? And what about parso?

**Comment by davidhalter** [comment]
0.19.0, latest parso.

**Comment by mhjacks** [comment]
Hm. Seems like it's been a while since parso has gotten a release, too, and it sounds like there have been some significant changes since 0.8.3. Do you think it would be appropriate to tag/release parso too? Meanwhile, I can work on coordinating with the other fedora maintainers; and I suspect other packages may well follow suit as well.

**Comment by jgb** [comment]
I've launched a PR to upgrade jedi to 0.19.0. Parso is still up to date according to the latest release tag (0.8.3) but indeed it might be useful to tag a release 0.8.4 over there as well so jedi-vim could be released with a fresh set of clothes.

**Comment by davidhalter** [comment]
Just tagged `v0.11.2`. I hope that will work for you.

About parso, yes we should probably do a new release soon, but I think that can also wait until Python 3.12 is out. The changes there are not that significant.
