### ISSUE TITLE
error: 5538 bytes of body are still expected

### ISSUE THREAD

**Issue by gaoxuezhao** [davidhalter/jedi-vim#1128]
install with plug vim-plug

error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 5538 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/davidhalter/jedi.git' into submodule path '/root/.vim/plugged/jedi-vim/pythonx/jedi' failed

**Comment by davidhalter** [comment]
This is not a Jedi error. Your clone of Jedi failed, which is an issue with git, GnuTLS, your operating system, your internet connection or GitHub.
