### ISSUE TITLE
Autocompletion over all tabs/within project

### ISSUE THREAD

**Issue by phui** [davidhalter/jedi-vim#116]
Thank you for the great plugin.

Is it possible to broaden the scope of auto-completion database to all open buffer, or even to all modules in certain root directory?

A similar feature can be found in eclipse/pydev, where one can add unique and different root directory and extra modules for each project. This recently becomes the only reason I open eclipse instead of vim for python development.

Many many thanks.

P. Hui

**Comment by tony** [comment]
> let g:neocomplcache_omni_functions.python = 'jedi#complete'

Note as of 2015-05-30, it would be ``jedi#completions``.

With neocomplete, this is working for me: 

``let g:neocomplete#sources#omni#functions.python = 'jedi#completions'``

Source: https://github.com/tony/vim-config/commit/10cd17ecc591f11d4017060cbfd3f81a5db6db03
