### ISSUE TITLE
Jedi and AutocomplPop

### ISSUE THREAD

**Issue by jojojames** [davidhalter/jedi-vim#123]
It seems Jedi-vim and AutocomplPop don't play nicely together.

list = []

list. <-- will randomly not complete with both together

let g:jedi#popup_select_first = 0

Will not work with AutocomplPop installed either. AutocomplPop does not automatically select the first word.

Tested this by removing Autocomp, witch allows Jedi-vim to work correctly.

Anyway to get them to play nicely?

**Comment by davidhalter** [comment]
@blueyed has changed something in the implementation of `popup_select_first`, could you retry?

**Comment by davidhalter** [comment]
We don't support AutocomplPop compatibilty, therefore I will close.
