### ISSUE TITLE
Not respecting configuration variables

### ISSUE THREAD

**Issue by veegee** [davidhalter/jedi-vim#130]
jedi-vim isn't respecting the following configuration variables:

let g:jedi#popup_select_first = 0
let g:jedi#show_function_definition = 0

Setting them seems to have no effect. Also, is there a way to make the function definition window pop up on the bottom instead of the top so the buffer that's being edited doesn't get shifted down?

**Comment by davidhalter** [comment]
@blueyed has changed something in the implementation of `popup_select_first`, could you retry?

**Comment by blueyed** [comment]
Is this still an issue for you?
There have been changes in this regard.

**Comment by dguaraglia** [comment]
This seems to be working fine for me.
