### ISSUE TITLE
using jedi-vim when coding with pygame

### ISSUE THREAD

**Issue by renl** [davidhalter/jedi-vim#146]
Hi,

I was wondering if anyone used jedi-vim with coding with pygame  before? Any idea why the code completion does not seems to work on the submodules?

for example, pygame.   <- code completion works here

but pygame.draw.   <- code completion does not work here.

Thanks.

**Comment by jubalh** [comment]
any news on this one?

**Comment by davidhalter** [comment]
No. Definitely not a priority. Sorry. It's so rare that it doesn't make sense to really prioritize it, when we can at the same time implement refactoring or something else with a rather huge impact.

**Comment by eeg710** [comment]
I'm also affected by this, just in case you were considering it. I know only three of us have commented, but it would be really nice to get a fix after 2.5 years.

**Comment by davidhalter** [comment]
@eeg710 This likely won't happen unless you do it yourself. It's just very hard for a type inference to infer state changes in a module. This is something that you can do, but is not of a recursive nature (and therefore simple type inference).

**Comment by davidhalter** [comment]
This won't happen. The py.test devs should just make their code less complicated ;)

**Comment by dbrgn** [comment]
> The py.test devs should just make their code less complicated

You probably mean pygame :)

**Comment by davidhalter** [comment]
What? I never said that :P ;)
