### ISSUE TITLE
jedi-vim is too too slow

### ISSUE THREAD

**Issue by fasterpython** [davidhalter/jedi-vim#163]
```
$vim test.py

import os, sys
os.
```

-- and then vim is fronzened for a few seconds.  
I found it's really very slow while trying auto-comple by  jedi-vim.

So, what can I do ?

---

OS: 64bit Debian/testing Dist
CPU: AMD IIx4  2.8GHz

Installed  jedi-vim by vundle

Configured  jedi-vim with: 
"For jedi-vim:
"pip install jedi -- done
let g:jedi#autocompletion_command = "< tab>"

**Comment by xlorepdarkhelm** [comment]
I do not have python-mode installed in vim, however jedi-vim is causing a noticeable slowdown when it is loaded. VIM 7.4, Python 3.4, latest jedi & jedi-vim. Whenever I am in editing mode in VIM with jedi-vim installed, there is a delay in my typing, which makes development frustrating to say the least. It is less than a second per-key-typed, I'd guess around 100 - 200ms delay. It exists even when I have absolutely no other plugins set up for VIM besides jedi-vim (and Pathogen). If I do not install jedi-vim, I do not experience this delay at all.

I can provide other details as needed.

**Comment by davidhalter** [comment]
@xlorepdarkhelm Just disable `show_call_signatures` and you're done. It's a known issue. That's the solution, if you don't want that minor delay.

**Comment by tony** [comment]
> @xlorepdarkhelm Just disable show_call_signatures and you're done. It's a known issue. That's the solution, if you don't want that minor delay.

I can confirm I got a little bit added pep by omitting call signatures.  Going to a/b test it a bit to see if it's worth keeping on. Signatures may not add enough value if there's a road bump at every parenthesis.

**Comment by diabloneo** [comment]
@davidhalter  That's the solution, thanks.

**Comment by flor385** [comment]
Guys, the problem on my system seems to be related to Pymode's folding. 

let g:pymode_folding=0

seems to make the difference (unlike setting rope to 0/1).

I got to try this after reading this:
https://github.com/klen/python-mode/issues/523

It seems pymode's folding has issues of it's own. Alternative folding plugins are recommended, I've yet to try them.

**Comment by balta2ar** [comment]
> Just disable show_call_signatures and you're done. It's a known issue. That's the solution, if you don't want that minor delay.

@davidhalter Is there a way to fix that issue? I really like call signatures, they are very useful to me.

**Comment by davidhalter** [comment]
https://github.com/davidhalter/jedi/issues/385 would probably solve it.

**Comment by samaklis** [comment]
I am having the same slowness issue as reported here under sygwin. I am using a laptop with an I7 cpu and performance or memory does not seem to be the cause. It takes about 20 seconds or so for jedi vim to respond. Even after the autocomplete loads, if i leave vim without entering anything for a bit say a min or so, the autocomplete takes again for ever to load.

For example:

os. <<< about 20 seconds
os.close << fast
[wait a min or so]
os. <<< about 20 seconds


The only modules I have installed are:
Vundle
jedi-vim

Vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct  8 2015 00:46:23)
Included patches: 1-801, 803-808, 810-891
Compiled by <cygwin@cygwin.com>

Any insight would be appreciated.

Thanks,

Constantine.

**Comment by gerryqd** [comment]
I have similar issue under Cygwin, native windows and Linux has no such issue.

I tried latest code.

**Comment by xuyuheng** [comment]
I think problem is pymode's virtualenv. Disable rope and virtualenv plugin solve the problem.

**Comment by kroq-gar78** [comment]
For me, the problem was pymode's folding, as suggested by @flor385. `let g:pymode_folding = 0` solved the issue for me.

**Comment by vatrat** [comment]
On Arch Linux with the current git download of Neovim built as "Release", can confirm that this is still a problem. Deocomplete-jedi and pythonmode installed, deocomplete set up and python-mode only installed with no prior usage. The "let g:pymode_rope = 0" trick worked for me. Not sure why this is still a problem after 3 years or so.

**Comment by blueyed** [comment]
@vatrat 
> Not sure why this is still a problem after 3 years or so.

Apparently nobody cares enough to debug and fix it?!

**Comment by skywind3000** [comment]
Can we use a timer polling method to avoid http timeout waiting ?

https://github.com/davidhalter/jedi-vim/issues/654

**Comment by davidhalter** [comment]
jedi-vim is not using http at all.

**Comment by sergeant-wizard** [comment]
I was also getting an unacceptable delay with `numpy` so I dug into the code and found out that `jedi.parser.cache.save_module` was consuming a significant amount of time with `use_filesystem_cache=True` (default, perhaps to save memory usage?).

The table below is what I measured on my Ubuntu 14.04 with Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz & SSD, in milliseconds.

| use_filesystem_cache | True | False |
|--------|------|-----|
| os | 380 | 220 |
| numpy | 7000 | 2100 |
| scipy | 7000 | 2150 |
| pandas | 450 | 250 |

```py
import jedi

s = 'import numpy ; numpy.'
script = jedi.Script(s, 1, len(s), '')
script.completions()
```

That said, I guess I should also look for async approaches like https://github.com/davidhalter/jedi/issues/385 or YCM.

**Comment by blueyed** [comment]
@sergeant-wizard 
deoplete / deoplete-jedi is also a good option, but requires you to use Neovim.

**Comment by vatrat** [comment]
And, really, if you're going to be using vim, you should use Neovim.

**Comment by skywind3000** [comment]
@blueyed neovim made good progress recently. As a windows user, I really like to switch from gvim.
nvim-qt is far more better than gvim (no flicker when scrolling).

If https://github.com/neovim/neovim/issues/6695 can be solved, I think most windows users will like to choose nvim-qt rather than gvim.

**Comment by skywind3000** [comment]
After the recent refactor of YouCompleteMe, jedi seems no delay and works fine now with the latest ycm.

**Comment by vatrat** [comment]
I don't know if this is important, but my problem was with deoplete, not youcompleteme.

**Comment by skywind3000** [comment]
deoplete needs a refactor too.

**Comment by vatrat** [comment]
So, are you saying this bug is still an issue with deoplete but not ycm?

**Comment by skywind3000** [comment]
Sure, I can confirm that.
because I have suggested ycm how to refactor before:

https://github.com/Valloric/YouCompleteMe/issues/2500

**Comment by blueyed** [comment]
@skywind3000 
deoplete is async, and uses timers?!

**Comment by vatrat** [comment]
At least when I last tried it, this problem only occurs with deoplete when python-mode is installed. It is some problem with rope, whatever that is, and can be fixed by disabling rope.

**Comment by LeErnst** [comment]
> @vatrat
> 
> > Not sure why this is still a problem after 3 years or so.
> 
> Apparently nobody cares enough to debug and fix it?!

3 years later i still have problems regarding speed. python-mode not installed
importing the pytorch library and with that i am waiting like 10 seconds....

**Comment by WuTheFWasThat** [comment]
same issue, pytorch takes forever

**Comment by gaoxuezhao** [comment]
same issue, pytorch takes forever
