### ISSUE TITLE
Would a ctags fall-back be something you would pull into the project?

### ISSUE THREAD

**Issue by toranb** [davidhalter/jedi-vim#170]
I'm a heavy ctags user and found that a nice feature is a "fall-back" to basic ctag definition when jedi cannot find a definition for some class / method.

Below is what I have hacked into my jedi_vim.py that works great for me personally. I'm sure a "ctags support" like flag would need to be added globally to jedi so that the plugin could conditionally fall back / or not (as some users might not want to opt in by default).

If this is something you would support / pull in => let me know and I can work on a legit pull request to add it w/ configuration.

![screen shot 2013-08-27 at 6 24 34 pm](https://f.cloud.github.com/assets/147411/1038909/82c1868a-0f70-11e3-9709-d7cb361b5d99.png)

**Comment by davidhalter** [comment]
There is some support for namespace packages now.
