### ISSUE TITLE
g:jedi#popup_select_first = 0 did not affect

### ISSUE THREAD

**Issue by heavenshell** [davidhalter/jedi-vim#179]
Hi.

When I set vimrc like following, popup always selected first item.

```
set completeopt=menu
let g:jedi#popup_on_dot = 1
let g:jedi#popup_select_first = 0
```
I do not want to select first item.

Is there any settings for not select first item?

### env
MacOS 10.8.4
Python 2.7.5
Vim 7.4.000(MacVim)

Regards,

**Comment by polyrabbit** [comment]
If you have both jedi-vim and neocomplcache enabled, the solution from @Shougo may help.
see https://github.com/davidhalter/jedi-vim/issues/258

**Comment by davidhalter** [comment]
So what's the remaining issue in jedi-vim here? I don't really understand.

@copitux 

> let g:jedi#popup_select_first = 0
> let g:jedi#auto_vim_configuration = 0

It doesn't surprise me that this doesn't work, because you're disabling the automatic configuration.

**Comment by heavenshell** [comment]
I still have problem even though `let g:jedi#auto_vim_configuration = 1`.

```viml
let g:jedi#auto_initialization = 1
let g:jedi#popup_on_dot = 1
let g:jedi#show_call_signatures = 0
let g:jedi#auto_vim_configuration = 1
let g:jedi#popup_select_first = 0
```

**Comment by davidhalter** [comment]
@blueyed has changed something in the implementation of `popup_select_first`, could you retry?

**Comment by heavenshell** [comment]
@davidhalter Sorry for late reply.
Greate, works fine!

**Comment by blueyed** [comment]
Thanks for repporting back.
Closing.
