### ISSUE TITLE
There is no easy (or at least documented) way to disable jedi while opening files

### ISSUE THREAD

**Issue by Kwpolska** [davidhalter/jedi-vim#201]
There are some files that Jedi can break on — for example python3 files while you have only python2.  Unfortunately, there is no easy way to disable Jedi while opening files, making it impossible to read those files in these cases.

```pytb
(python2-virtualenv)$ vim /usr/lib/python3.3/getpass.py
  File "./site.py", line 173
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
```

**Comment by davidhalter** [comment]
All right, as you said above this is not about jedi-vim (Also your reproduction case has nothing to do with neither Jedi nor jedi-vim), so I'm closing.
