### ISSUE TITLE
Vim crashes and gets ImportError: cannot import name MAXREPEAT

### ISSUE THREAD

**Issue by lv10** [davidhalter/jedi-vim#203]
After installing jedi using Vundle(also happens) installing without bundle, vim crashes looking the terminal and displaying an ImportError: cannot name import name MAXREPEAT.

Here is a screenshot of the whole thing (I couldn't copy/paste since the terminal is stuck):
http://s2.postimg.org/goz76vac9/Screen_Shot_2013_10_18_at_12_59_55_AM.png

**Comment by davidhalter** [comment]
Thanks @gotgenes 

Since I didn't receive an answer anymore, I'm closing.
