### ISSUE TITLE
"mtest.py" [New File]ImportError: No module named site

### ISSUE THREAD

**Issue by llvll0hsen** [davidhalter/jedi-vim#207]
Hi, 
First of all thanks for your great job. I recently started using jedi. So far I installed it on 2 linux system without any problem but I got stuck to using it on os x. I followed this instructions http://redkrieg.com/2012/12/11/writing-python-like-a-jedi/. when I try to use vim I am getting:
"mtest.py" [New File]ImportError: No module named site

and after that I can not quit the vim and I have to close the terminal. I dont know what exactly could be the problem. I recently upgrade to maverick and also I use Enthought Canopy for managing my python package which it changes the default python path. Any idea?
Thanks

**Comment by the5fire** [comment]
thx @cpdean ,you save my day.

In macOS:
```
brew uninstall macvim
brew install macvim
```
