### ISSUE TITLE
vim 7.3 junk text inserted to buffer when using completion (and Vundle)

### ISSUE THREAD

**Issue by danthedeckie** [davidhalter/jedi-vim#21]
Similar to issue #13, but I'm using the latest jedi-vim, and vim 7.3.584, and Vundle rather than Pathogen.

typing:

``` python
x = "text"

x.find(
```

and pressing '<c-x><c-o>' to bring up the omnicompletion results in 

``` python
x = "text"
       (sub, start=None, end=None)
x.find(
```

which then gets written on save.  When I put the cursor on the line, I get:

``` python
x = "text"
≡jedi=0, ≡      (*sub*, start=None, end=None) ≡jedi≡
x.find()
```

**Comment by subsetpark** [comment]
I am getting this issue with 
```
=`=jedi=0, =`=               (*_*arg*_*) =`=jedi=`=
```
While my encoding is utf-8.

**Comment by blueyed** [comment]
@subsetpark 
Seems like the syntax file gets not (correctly) for you, which should setup concealing rules for this.  It is meant to look like this (or at least similar), but then gets beautified using Vim's concealing feature.
You might want to search the jedi-vim issues, there was something in this regard already, where some other plugin conflicts with how jedi-vim sets things up.
