### ISSUE TITLE
Completion List is pink

### ISSUE THREAD

**Issue by NoahTheDuke** [davidhalter/jedi-vim#215]
As seen [here](http://i.imgur.com/GlJH60v.png), the colors are a little messed up for me. I've disabled all of my other plugins, but the color persisted, so I don't think it's an error from another script.

Any ideas on how I can fix this?

**Comment by ramidas** [comment]
hilight Pmenu ctermbg=<color> ctermfg=<color>

Acording to this answer: https://bbs.archlinux.org/viewtopic.php?id=139163

**Comment by achen0115** [comment]
@ramidas Thank you. It works.

**Comment by micuncang** [comment]
@mkadlof Thank you
