### ISSUE TITLE
jedi-vim causes lag in insert mode

### ISSUE THREAD

**Issue by alicee** [davidhalter/jedi-vim#217]
I'm experiencing an irritating lag in insert mode, i.e. it takes a long (up to 0.5 seconds) time for a character to appear after I type it. One of the files I'm having this issue with is ~800 lines of code, so I wouldn't expect mere size to be the root cause? Removing jedi-vim also removes the lag, so I assume it must have something to do with this plugin. Completely removing my .vimrc doesn't seem to have any effect. This happens with supertab, autocomplpop, and also when both of them are disabled.

I profiled some of the insert-mode madness like this:
```
:profile start profile.log
:profile func *
:profile file *
" At this point do slow actions
:profile pause
:noautocmd qall!
```

and it seems like `_vim_exception` is being called rather often (given that I only inserted ~80 chars):

```
FUNCTION  jedi#_vim_exceptions()
Called 313 times
Total time:   0.014491
 Self time:   0.014491

count  total (s)   self (s)
  313              0.002117     let l:result = {}
  313              0.000798     try
  313              0.000745         if a:is_eval
  261              0.002488             let l:result.result = eval(a:str)
  261              0.000370         else
   52              0.002304             execute a:str
   52              0.000199             let l:result.result = ''
   52              0.000060         endif
  313              0.000390     catch
                                    let l:result.exception = v:exception
                                    let l:result.throwpoint = v:throwpoint
                                endtry
  313              0.000692     return l:result
```
Perhaps this is an issue with vim-jedi interacting with one of my other plugins, so here's the global summary:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.238969   0.000101  <SNR>20_UpdateErrors()
    1   0.231162   0.000322  <SNR>20_CacheErrors()
    2   0.229969   0.000126  SyntaxCheckers_python_GetLocList()
    2   0.229843   0.000092  SyntasticMake()
    2   0.229751   0.011751  SyntasticLocalMake()
    3   0.053375   0.052994  <SNR>39_RunPyflakes()
    1   0.019087             GetPythonIndent()
  313   0.014491             jedi#_vim_exceptions()
    4   0.012549   0.000207  <SNR>20_OSSupportsShellpipeHack()
    2   0.012342   0.000284  <SNR>20_uname()
   56   0.008552             <SNR>25_Highlight_Matching_Pair()
    1   0.007604   0.000098  <SNR>20_RedrawErrors()
    1   0.005281   0.000056  <SNR>20_RefreshSigns()
    1   0.005174   0.005001  <SNR>20_SignErrors()
    1   0.001678   0.000034  <SNR>20_AutoToggleLocList()
    1   0.001599   0.000316  <SNR>20_ShowLocList()
    1   0.000686   0.000206  SyntasticCheckable()
    1   0.000568   0.000492  <SNR>11_LoadFTPlugin()
    1   0.000495   0.000329  <SNR>5_SynSet()
    5   0.000444   0.000387  <SNR>20_FilterLocList()
```

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    3   0.053375   0.052994  <SNR>39_RunPyflakes()
    1              0.019087  GetPythonIndent()
  313              0.014491  jedi#_vim_exceptions()
    2   0.229751   0.011751  SyntasticLocalMake()
   56              0.008552  <SNR>25_Highlight_Matching_Pair()
    1   0.005174   0.005001  <SNR>20_SignErrors()
    1   0.000568   0.000492  <SNR>11_LoadFTPlugin()
    5   0.000444   0.000387  <SNR>20_FilterLocList()
    1   0.000495   0.000329  <SNR>5_SynSet()
    1   0.231162   0.000322  <SNR>20_CacheErrors()
    1   0.001599   0.000316  <SNR>20_ShowLocList()
    2   0.012342   0.000284  <SNR>20_uname()
    3              0.000239  <SNR>39_ActivatePyflakesQuickFixWindow()
    1   0.000279   0.000236  <SNR>20_HightlightErrors()
    1              0.000231  <SNR>15_addtomrufs()
    3              0.000216  SyntasticAddToErrors()
    4   0.012549   0.000207  <SNR>20_OSSupportsShellpipeHack()
    1   0.000686   0.000206  SyntasticCheckable()
   13              0.000159  <SNR>20_LocList()
    1   0.000233   0.000147  <SNR>20_LoadChecker()
```

Any idea where to look or how to debug this?

**Comment by tkossak** [comment]
I have this problem too - on a file with 10 lines of code.
Have to remove to plugin because writing script is too annoying with the lag.

**Comment by davidhalter** [comment]
All right. Could all of you re-test with the current dev branch version of Jedi? I have the feeling that it's so much faster.

@pasky I feel `cma` is working way faster, now. Before the delay was really a nightmare. Now it's still a bit too slow, but quite OK. Especially when writing code without opening brackets, everything is pretty fast, otherwise you have a "minor" lag. That should eventually be removed by doing the whole thing asynchronous. What do you think?

**Comment by aaren** [comment]
@davidhalter seems promising so far!

**Comment by blueyed** [comment]
I think this issue can be closed for now?

Any other opinion?
Is it still slow for anyone?

**Comment by pasky** [comment]
Sorry for not following up.  It's not perfect I guess, but it really is much better than it used to be. Thank you very much! I guess "making the whole thing asynchronous" is really something that needs to wait for neovim now?

I think this is good enough now to warrant closing this.

**Comment by blueyed** [comment]
Thanks!

**Comment by roblevy** [comment]
It seems that `0.9.0` (the version currently being got by my `pip install --update`) still has this problem.

Where should I clone this repository to, to get the latest development version?

**Comment by davidhalter** [comment]
I think this should actually much better with `0.9.0`. If there are still problems, please post (or at least describe your codebase).

**Comment by roblevy** [comment]
This seems to be enough to trigger the behaviour:

```
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.random([3, 6]))
df.head(5).to_latex(header=False, index=True)
``` 

When the cursor is inside the parentheses associated with `to_latex`, the whole thing gets very laggy on my system.

**Comment by davidhalter** [comment]
yeah. That's kind of related, but it's also  a very complex call. Pandas and numpy are huge, so I think this can only be solved by making the whole thing async. If you want to add another issue you can, but it's a different one for me than the other ones here.

**Comment by balta2ar** [comment]
@davidhalter I already wrote in another issue but it looks like this one is more appropriate.

I wanted to added an important detail: I notice delays when I switch to Insert mode, however that happens not in `filetype=python` files but in `filetype=conf` file or when `filetype` is empty. File size is about 250KB, ~3600 lines.

Is there a way to enable that `InsertEnter` trigger for python files only? Here is how you can make a file similar to mine:

``` bash
yes '2013-01-21,14:00,14:39,queue,RT:123456,"comment"' | head -n 5000 > test
```

I tried to set some delay but there are still lags. Here my configuration:

``` vim
set noshowmode
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
let g:jedi#use_tabs_not_buffers = 0
let g:jedi#completions_command = ""

let g:jedi#auto_vim_configuration = 0
let g:jedi#auto_initialization = 0
let g:jedi#completions_enabled = 0
let g:jedi#show_call_signatures = "2"

let g:jedi#show_call_signatures_delay = 0

call jedi#configure_call_signatures()

let g:jedi#goto_assignments_command = "<leader>pa"
let g:jedi#goto_definitions_command = "<leader>pd"
let g:jedi#documentation_command = "<leader>pk"
let g:jedi#usages_command = "<leader>pu"
let g:jedi#rename_command = "<leader>pr"
```

**Comment by balta2ar** [comment]
Answering my own question, looks like this worked for me:
``` vim
autocmd FileType python call jedi#configure_call_signatures()
```

**Comment by naggie** [comment]
This also worked for me. I am using supertab -- when generating the completion menu it used to pause for seconds at at time.
