### ISSUE TITLE
Cannot see any call signatures (UnicodeDecodeError)

### ISSUE THREAD

**Issue by talha81** [davidhalter/jedi-vim#233]
When calling a function in a python file, I can not see any call signatures and the following error gets spit out to ":messages":

    Traceback (most recent call last):
      File "C:\Users\talha.ahmed\.vim\bundle\jedi-vim\jedi_vim.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "C:\Users\talha.ahmed\.vim\bundle\jedi-vim\jedi_vim.py", line 288, in show_call_signatures
        e = e.decode('UTF-8')
      File "C:\Python27\Lib\encodings\utf_8.py", line 16, in decode
        return codecs.utf_8_decode(input, errors, True)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in position 0: invalid start byte

__Other Info__

* I use vundle to update jedi-vim like this:

                Bundle "davidhalter/jedi-vim"
* The Latest Commit is:

        C:\Users\talha.ahmed\.vim\bundle\jedi-vim>git log -1
        commit 44b8165ba3b6665625dd88c45143135e66464a11
        Merge: 485e02d e324a34
        Author: Dave Halter <davidhalter88@gmail.com>
        Date:   Wed Dec 11 09:00:17 2013 -0800

            Merge pull request #230 from np1/master

            Small error in help text
* I am using the [standard compiled version of vim 7.4](ftp://ftp.vim.org/pub/vim/pc/gvim74.exe)  on windows 7. 
* :ver outputs the following 

        VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2013 14:38:33)
        MS-Windows 32-bit GUI version with OLE support
        Compiled by mool@tororo
        Big version with GUI.  Features included (+) or not (-):
        +arabic             +clientserver       +cryptv             -dnd                +file_in_path       +iconv/dyn          +lispindent         +mouse              +path_extra         +python3/dyn        +smartindent        +tag_old_static     +toolbar            +vreplace           -xterm_save         
        +autocmd            +clipboard          +cscope             -ebcdic             +find_in_path       +insert_expand      +listcmds           +mouseshape         +perl/dyn           +quickfix           -sniff              -tag_any_white      +user_commands      +wildignore         +xpm_w32            
        +balloon_eval       +cmdline_compl      +cursorbind         +emacs_tags         +float              +jumplist           +localmap           +multi_byte_ime/dyn +persistent_undo    +reltime            +startuptime        +tcl/dyn            +vertsplit          +wildmenu           
        +browse             +cmdline_hist       +cursorshape        +eval               +folding            +keymap             -lua                +multi_lang         -postscript         +rightleft          +statusline         -tgetent            +virtualedit        +windows            
        ++builtin_terms     +cmdline_info       +dialog_con_gui     +ex_extra           -footer             +langmap            +menu               -mzscheme           +printer            +ruby/dyn           -sun_workshop       -termresponse       +visual             +writebackup        
        +byte_offset        +comments           +diff               +extra_search       +gettext/dyn        +libcall            +mksession          +netbeans_intg      -profile            +scrollbind         +syntax             +textobjects        +visualextra        -xfontset           
        +cindent            +conceal            +digraphs           +farsi              -hangul_input       +linebreak          +modify_fname       +ole                +python/dyn         +signs              +tag_binary         +title              +viminfo            -xim                
           system vimrc file: "$VIM\vimrc"
             user vimrc file: "$HOME\_vimrc"
         2nd user vimrc file: "$HOME\vimfiles\vimrc"        
         3rd user vimrc file: "$VIM\_vimrc"
              user exrc file: "$HOME\_exrc"
          2nd user exrc file: "$VIM\_exrc"
          system gvimrc file: "$VIM\gvimrc"
            user gvimrc file: "$HOME\_gvimrc"
        2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
        3rd user gvimrc file: "$VIM\_gvimrc"
            system menu file: "$VIMRUNTIME\menu.vim"
        Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG   -DFEAT_XPM_W32   -DWINVER=0x0400 -D_WIN32_WINNT=0x0400  /Fo.\ObjGOLYHTRi386/ /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_W32 -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl85.dll\" -DDYNAMIC_TCL_VER=\"8.5\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python32.dll\" -DFEAT_PERL -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl514.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=19 -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby192.dll\" -DFEAT_BIG /Fd.\ObjGOLYHTRi386/ /Zi
        Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386 /nodefaultlib gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:i386 /nodefaultlib libcmt.lib oleaut32.lib  user32.lib      /nodefaultlib:python27.lib /nodefaultlib:python32.lib   "E:\tcl\lib\tclstub85.lib" WSock32.lib xpm\x86\lib\libXpm.lib /PDB:gvim.pdb -debug

* The following are all jedi-settings in _vimrc

        " Jedi vim settings {{{
        let g:jedi#use_tabs_not_buffers = 0

        " for custom mappings on jedi vim {{{
        function! g:splitandgoto()
                :rightbelow vsp
                :call jedi#goto()
        endfunction
        function! g:splitandgetdefinition()
                :rightbelow vsp
                :call jedi#get_definition()
        endfunction
        function! g:map_jedi_settings()
            nnoremap <buffer> <leader>D :call g:splitandgetdefinition()<cr>
            nnoremap <buffer> <leader>G :call g:splitandgoto()<cr>
        endfunction
        augroup custom_jedi_mappings
            autocmd!
            autocmd BufNewFile,BufEnter *.{py,pyw} :call g:map_jedi_settings()
        augroup END
        "}}}
        "}}}

**Comment by davidhalter** [comment]
Solved. See @talha81's encoding settings.
