### ISSUE TITLE
Auto-completion of OpenCV python bindings crashes vim

### ISSUE THREAD

**Issue by VaibhavBedia** [davidhalter/jedi-vim#235]
Hi,

I just installed opencv via Homebrew on Mac OSX 10.8.5 and tried a simple program which uses the python bindings. Autocompletion for other modules like numpy, pyqt4 etc works fine but as soon as i try out autocompletion for opencv module, vim crashes with the following message:

Vim: Caught deadly signal SEGV
Vim: preserving files...
Vim: Finished.
Segmentation fault: 11

Other info:
Python 2.7.5  
Vim - 7.4 installed via Homebrew
Jedi-vim installed via pathogen. Latest commit:

commit 44b8165ba3b6665625dd88c45143135e66464a11
Merge: 485e02d e324a34
Author: Dave Halter davidhalter88@gmail.com
Date:   Wed Dec 11 09:00:17 2013 -0800

```
Merge pull request #230 from np1/master

Small error in help text
```

**Comment by kasperschnack** [comment]
I can't get jedi-vim to do any autocompletion on the cv2(OpenCV) lib. Is it possible somehow? Should i use ctags for that?

**Comment by davidhalter** [comment]
I have no idea. You would have to research why it happens. Jedi certainly doesn't deal with ctags, but if you have your own solution that might work.

**Comment by blueyed** [comment]
@kasperschnack 
It would help to have some instructions for reproducing this, of course, e.g the steps required for a virtualenv and/or Docker container.  And then what you're trying to achieve.
(sorry if I missed something, only skimmed the issue/comments)

**Comment by kasperschnack** [comment]
@blueyed is it supposed to work out of the box with the OpenCV lib?

**Comment by blueyed** [comment]
@kasperschnack 
I don't know.
