### ISSUE TITLE
Wrong encoding of jedi-vim again

### ISSUE THREAD

**Issue by ShengYun** [davidhalter/jedi-vim#238]
Hi,

I created a pull request https://github.com/davidhalter/jedi-vim/pull/186 to force  `jedi.vim`'s encoding to utf-8, but when I update `jedi-vim` to the latest status today, the problem came again.

I believe it is caused in 3ad63c9, is there a way to fix this permanently? like changing `call_signature_escape` to some other characters? or set a modeline in jedi.vim?

**Comment by davidhalter** [comment]
Thanks for the report. I think the current solution with `==` should work pretty well!
