### ISSUE TITLE
Textmate bundle for Jedi

### ISSUE THREAD

**Issue by lawrenceakka** [davidhalter/jedi-vim#246]
Hi Dave,

I have released a bundle to enable Jedi based completion in Textmate, the editor for OSX.  The repo is at https://github.com/lawrenceakka/python-jedi.tmbundle

Do you think you could advertise it on the relevant part of your site?

Lawrence

**Comment by johnlamb** [comment]
Hi David.
Just to confirm that Lawrences TM bundle works without a hitch with Jedi 0.9.0. 
//John
