### ISSUE TITLE
jedi-vim thinks I don't have jedi installed

### ISSUE THREAD

**Issue by gfixler** [davidhalter/jedi-vim#249]
I checked out latest on master (d9a43db), and now when I open a Python file I get:

```
Error detected while processing /home/gfixler/.vim/bundle/jedi-vim/autoload/jedi.vim:
line  283:
Please install Jedi if you want to use jedi_vim.
```

I've done `git submodule update --init` in the .vim/bundle/vim-jedi directory, and `git status` shows nothing at all (so the submodule must be synced up), but it doesn't help. If I go into that directory, enter python, and try to `import jedi` I get:

```
>>> import jedi_vim
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "./jedi_vim.py", line 11, in <module>
    import vim
ImportError: No module named vim
```

If, while in Vim I type `:py import jedi_vim` I get:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gfixler/.vim/bundle/jedi-vim/jedi_vim.py", line 12, in <module>
    import jedi
ImportError: No module named jedi
```

**Comment by suvarna-khanal** [comment]
What do you mena by "All that was required in the end was a git submodule update --recursive from out in my main git repo." What exactly is 'main git repo'?. I too am having the same problem

**Comment by davidhalter** [comment]
@suvarna-khanal you need to run the update command in the jedi-vim repository, because Jedi needs to be up to date.

**Comment by robbyki** [comment]
Having the same issue. what exactly was the solution here? Already tried `git submodule update --recursive` but still getting `Please install Jedi if you want to use jedi-vim.` message for py files.

**Comment by davidhalter** [comment]
I don't understand submodules very well. But you might need to install it first? Is there something in the jedi subdirectory (in jedi-vim)?

**Comment by robbyki** [comment]
Started a new issue for this here: https://github.com/davidhalter/jedi-vim/issues/460#issuecomment-138539605

**Comment by acganesh** [comment]
I had the same issue.  In my case (which may be different), the problem was that I had multiple installations of Python, and vim was detecting the wrong version.  

I was able to fix this on OS X 10.10 by recompiling macvim and explicitly declaring the `vi_cv_path_python` variable, which specifies the path to the correct Python binary to the build script.

```
vi_cv_path_python=/usr/local/bin/python \
./configure --with-features=huge  --enable-rubyinterp \
                  --enable-pythoninterp \
                  --enable-perlinterp \
                  --enable-cscope
```

Hope this helps someone.

**Comment by acganesh** [comment]
I had this same issue.  Here's [the solution](https://github.com/davidhalter/jedi-vim/issues/460#issuecomment-139830360) that worked in my case (which might be different).

**Comment by joenmarz** [comment]
install jedi module through pip. If using python 3 then use:

> pip3 install jedi

**Comment by davidhalter** [comment]
**Do not install Jedi through pip. Install it with `git submodule update --init --recursive`.**
