### ISSUE TITLE
SAGE math with Jedi-Vim

### ISSUE THREAD

**Issue by soulcmdc-zz** [davidhalter/jedi-vim#262]
Is there a way to use a different-than-default interpreter with Jedi-Vim? Currently, none of the sage libraries auto-complete and are not able to be loaded into the normal python interpreter (intended to use the sage -python interpreter.)

**Comment by petRUShka** [comment]
@soulcmdc, could you please make some instruction on how to use jedi-vim to autocomplete build-in sage functions?
