### ISSUE TITLE
New line after bracket has 8 spaces indentation instead of 4?

### ISSUE THREAD

**Issue by quantonganh** [davidhalter/jedi-vim#266]
After typing the bracket and enter, the next line will has 8 spaces indentation:

```
            print conn.generate_url(
                    seconds,
                    'GET',
```

instead of 4:

```
            print conn.generate_url(
                seconds,
                'GET',
```

My `~/.vimrc`: https://github.com/quantonganh/salt-states/blob/master/vim/vimrc.jinja2

Did I miss something?

Here's the list of my plugins:

```
├── ctrlp.vim
├── gundo.vim
├── jedi-vim
├── nerdtree
├── powerline
├── salt-vim
├── supertab
├── syntastic
├── ultisnips
├── vim-fugitive
├── vim-indent-guides
├── vim-surround
├── vim-yankstack
└── vundle
```

**Comment by timothy-elson** [comment]
@quantonganh : I use a similar cocktail of plugins but removing jedi doesn't reduce the autoindent to 4 spaces.  Did you find a way to ensure 4 spaces on the newline after the bracket?

**Comment by blueyed** [comment]
btw: I recommend https://github.com/hynek/vim-python-pep8-indent.
