### ISSUE TITLE
Jedi not found

### ISSUE THREAD

**Issue by dbrgn** [davidhalter/jedi-vim#275]
@davidhalter see the newest comment (2014-05-23 16:58): https://aur.archlinux.org/packages/vim-jedi/

**Comment by blueyed** [comment]
0.9 has been released now.
Does it help?

**Comment by davidhalter** [comment]
0.9.0 is Jedi, not the jedi-vim version. We should release a 0.8.0 jedi-vim version very soon. I was going to a few days ago. But then something didn't work properly. I will try again very soon.

**Comment by davidhalter** [comment]
Closed. I have created a tag 0.8.0. Sorry for the 2 year delay :) At times forgotten and at times jedi-vim wasn't working.

**Comment by blueyed** [comment]
Arch users appear to really like their package manager.. :)

Everybody else uses a Vim plugin manager (mostly).
