### ISSUE TITLE
No completion with gi.repository (PyGobject)

### ISSUE THREAD

**Issue by Yinameah** [davidhalter/jedi-vim#279]
Hi,

I have some issues using jedi-vim with PyGobject Libraries. While the plugin (which is nice by the way, thx) is working perfectly with standard library (like ``math`` or ``sys``), after a 
``from gi.repository import Gtk``, ``Gtk.`` gives me a sad :
``Omni completion (^O^N^P) Pattern not found``

In the python console, (Python 2.7.5+), I did :
``jedi.Script('from gi.repository import Gtk;Gtk.').completions()`` and it returns 
``[ ]``
But ``dir(Gtk)`` returns all the good stuff.

So, in my opinion, the problem is on jedi-vim's side, but I'm not such an expert and maybe I'm doing somthing wrong.

I use Vim 7.4 on Linux Mint.
Just tell if you need other specs to see it trought.

Maybe I should add that the issue is the same with other libraries in ``gi.repository``, for example ``from gi.repository import Gio``

Thanks you

**Comment by codefolder** [comment]
I am using jedi as part of youcompleteme on vim, and it would be great if there is movement with regard to this issue.

Can one cross-reference the issue to memory allocation to generate stubs for Gtk?

For instance, in PyCharm the autocomplete issue is solved if I comment out the line

idea.max.intellisense.filesize=2500

in

/bin/idea.properties

Hope it is useful.

**Comment by davidhalter** [comment]
I'm closing this issue in favour of https://github.com/davidhalter/jedi/issues/531. Please continue commenting there.
