### ISSUE TITLE
Virtual Environment

### ISSUE THREAD

**Issue by ANtlord** [davidhalter/jedi-vim#280]
Hello. I know about https://github.com/davidhalter/jedi-vim/issues/31, but my vim-jedi doesn't work with virtual environment. I have looked inside by grep. I have found method which checks item 'VIRTUAL_ENV' in os (I mean get_sys_path() method). I set command print("super test") in start of this method for checking this method. And I don't had this message in vim. Does it mean that method was not called? Or don't I understand something?

Sorry for my English.

**Comment by davidhalter** [comment]
Will be part of https://github.com/davidhalter/jedi/issues/385
