### ISSUE TITLE
jedi-vim fails even when auto_initialization = 0

### ISSUE THREAD

**Issue by FrostyX** [davidhalter/jedi-vim#284]
Hi,
on the top of `.vimrc` I have

    let g:jedi#auto_initialization = 0

so I expect that `jedi-vim` will not try to start. It works, when `jedi` is installed, but when its not, then I got this error:

        "version.py" 8L, 59C
        Chyba při zpracování /home/frostyx/dotfiles/.vim/bundle/jedi-vim/autoload/jedi.vim:
	řádek  283:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/home/frostyx/dotfiles/.vim/bundle/jedi-vim/initialize.py", lin$
        <module>
            vim.command('echoerr "Please install Jedi if you want to use jedi_vim.")
        vim.error: Vim(echoerr):Please install Jedi if you want to use jedi_vim.
        E171: Chybí :endif
        Chyba při zpracování /home/frostyx/dotfiles/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim:
        řádek    8:
        E121: Nedefinovaná proměnná: g:jedi#auto_initialization
        E171: Chybí :endif

I am sorry for czech language in it, but I dont have english system here.

**Comment by phracek** [comment]
I have got the same issue on Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1190187

**Comment by phracek** [comment]
And all works fine. the steps mentioned as 4) shows file like /usr/lib/python2.7/site-packages/jedi/__init__.pyc

but still I can see message:
"preupgrade-assistant-0.11.7/preup/scanning.py" 153L, 5289C
Error detected while processing /usr/share/vim/vimfiles/autoload/jedi.vim:
line  283:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/vim/vimfiles/initialize.py", line 24, in <module>
    vim.command('echoerr "Please install Jedi if you want to use jedi_vim."')
vim.error: Vim(echoerr):Please install Jedi if you want to use jedi_vim.
E171: Missing :endif
Error detected while processing /usr/share/vim/vimfiles/ftplugin/python/jedi.vim:
line    8:
E121: Undefined variable: g:jedi#auto_initialization
E171: Missing :endif
Press ENTER or type command to continue

I have to mention that my ~/.vimrc file does not containg g:jedi#auto_initialization variable.

**Comment by phracek** [comment]
Please apply those commits to your code. On Fedora it is solved.
https://github.com/davidhalter/jedi-vim/commit/4724e18b633e54dbaac39759770601cc1979893a
https://github.com/davidhalter/jedi-vim/commit/bb5c473633921bdff522ff25e1839c4f90ea4ebe
https://github.com/davidhalter/jedi-vim/commit/d9a43db019da0390406e34cb161a61fba43bf250

https://bugzilla.redhat.com/show_bug.cgi?id=1190187#c7

**Comment by davidhalter** [comment]
So do I understand that correctly, it's just a versioning issue? Basically `0.7.0` is bugged and you would need a new release?

**Comment by davidhalter** [comment]
I think the solution for #263 fixed this issue. I'm closing, let me know if there's still an issue.

@phracek If you need still want to comment on the release issue I'm also glad to answer!

**Comment by rvu95** [comment]
got this error when i'm trying to use it to create `test.py`:

```
Error detected while processing /usr/share/vim/vimfiles/autoload/jedi.vim:
line  283:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/vim/vimfiles/initialize.py", line 24, in <module>
    vim.command('echoerr "Please install Jedi if you want to use jedi_vim."')
vim.error: Vim(echoerr):Please install Jedi if you want to use jedi_vim.
E171: Missing :endif
Error detected while processing /usr/share/vim/vimfiles/after/syntax/python.vim:
line    1:
E121: Undefined variable: g:jedi#show_call_signatures
E171: Missing :endif
Error detected while processing function <SNR>5_SynSet:
line   24:
E170: Missing :endfor

```

**Comment by davidhalter** [comment]
@rvu95 Hmm I'm pretty sure that we've fixed one of those bugs. Are you sure that you are using the latest jedi-vim?

**Comment by blueyed** [comment]
Yeah, it should be a warning only: https://github.com/davidhalter/jedi-vim/blob/dc23f0b859d3b5c087921b68cf7cd66803ecca83/jedi_vim.py#L80-L86

Also, the path (`"/usr/share/vim/vimfiles/initialize.py"`) looks like it was installed by some (system) package manager?!  It looks like it's coming from Arch: https://www.archlinux.org/packages/community/any/vim-jedi/

@davidhalter 
This contains the latest release (0.7.0), which is rather old already.
I guess there should be a new release?

@rvu95 
You are better off installing it through a Vim package manager (at least currently), instead of pacman - using the Git source/repo.

**Comment by davidhalter** [comment]
I forgot about that. Yes we should definitely do a new release (it's just a tag...). However, I still don't like that `jedi#show_call_signatures = 1` is now buggier than before. I have to disable it quite often. I think this would be something to fix before a release.

**Comment by rvu95** [comment]
@davidhalter yea, i'm using the latest version of jedi-vim

**Comment by sergiomb2** [comment]
Hello, maybe you should do another new release , 0.7.0 is the last release and is from 2013 .

Thanks.

**Comment by blueyed** [comment]
@sergiomb2 
It's not very common to use releases / tags with Vim plugins, is it?

@rvu95 
You are using the latest release, not the latest version, right?
Try it with "master" from Git - which is the normal way when using a plugin manager with Vim.

**Comment by sergiomb2** [comment]
@blueyed yes it is , at least in Linux Fedora .

    dnf repoquery vim-jedi

vim-jedi-0:0.7.0-8.fc23.noarch

**Comment by blueyed** [comment]
@sergiomb2 
I'd argue that it's more common to use Vundle, Neobundle, Pathogen etc to manage your plugins - or does Fedora really package all Vim plugins?!
(I guess jedi-vim is a bit special in this regard, given its Python dependency)

**Comment by sergiomb2** [comment]
No, Fedora just package a few plugins, but I can't quantify, less than 50 for sure [1], I don't know if syntax highlighting counts 

[1] https://apps.fedoraproject.org/packages/s/vim

**Comment by rvu95** [comment]
ah okay, manage to solved it, thanks :)
