### ISSUE TITLE
Signatures unusably slow on large codebase

### ISSUE THREAD

**Issue by eevee** [davidhalter/jedi-vim#295]
I tried jedi at $work today and the cursor movement was so ridiculously laggy that I could barely write any code.  Some hamfisted profiling revealed that `show_call_signatures` was blocking vim for almost half a second _for every keypress in Insert mode_.

Obviously I'm turning this feature off  :)  This was a decently-sized file (1000 lines?) with lots of imports (dozens) in a very large codebase (millions of lines?), but there looks to be clear room for improvement here:

- I get the delay even when the cursor isn't inside a function call, where it ought to be pretty easy to notice that nothing needs doing.
- From a quick glance, I think jedi is reparsing the entire file every time I add a character?  Surely if it already has an AST for a pristine file and the only change I've made is to type a `w` on a new line, it can make some use of the information it already had?

**Comment by davidhalter** [comment]
show_call_signatures is now way faster. For a multitude of reasons. Jedi has been rewritten.
