### ISSUE TITLE
Doesn't seem to be able to use spaces, not tabs

### ISSUE THREAD

**Issue by JBorrow** [davidhalter/jedi-vim#303]
Even when I remove auto_vim_configuration, there still seems to be an overwrite forcing me to use 4-long tabs instead of spaces.

**Comment by davidhalter** [comment]
Seriously. I don't think there's a Jedi issue here. 

I included the `filetype plugin on` in auto_vim_configuration, now (https://github.com/davidhalter/jedi-vim/commit/c9c019846782518b4b53754be606bebf17a3468b). So if you set it to 0 there's absolutely nothing anymore that changes the state of VIM.

Can you recheck?

**Comment by JBorrow** [comment]
Nope, still an issue - even carries over to neovim (which I am now using) and a completely fresh install.

Sorry I took so long to reply - I have been super busy. Thanks for looking into this - it's no longer an issue as I don't work with the stupid 2 space codebase any more but it could still come up with other people...

Here's a video of the behaviour

https://drive.google.com/file/d/0B2aPoUF0hBJYeEdrZGFfWTRXYk0/view?usp=sharing

**Comment by blueyed** [comment]
You can use `:verbose set shiftwidth?` to see where it's being set.

**Comment by JBorrow** [comment]
shiftwidth=4
        Last set from /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/ftplugin/
python.vim

- where python.vim is loaded before jedi - odd that it would only occur once jedi is included...

**Comment by blueyed** [comment]
`filetype plugin on` is being called by jedi-vim with `g:jedi#auto_vim_configuration = 1`, but it should skip setup then.  You can see this via `:debug filetype plugin on` (use `s` to step-into and then Enter to repeat).
Are you calling it manually before?
Please also try with `g:jedi#auto_vim_configuration = 0`.

**Comment by davidhalter** [comment]
No anwer.
