### ISSUE TITLE
Auto complete not working for certain imports

### ISSUE THREAD

**Issue by lanefeltis** [davidhalter/jedi-vim#307]
I am running RHEL5 with Python 2.4 under /usr/bin, however, I have compiled Python 2.7 and built vim using that version. Almost everything works for me, for example, in one file I have...

<b> This works with auto complete </b>
<code>import unittest</code>

<b> This does not work with auto complete and subsequently, neither does Mock methods </b>
<code>from mock import Mock</code>

<b> This does not work with auto complete, however, methods under each class work </b>
<code>from nose.tools import raises, assert_equal</code>

<b> This works with auto complete </b>
<code>from lib.company.common.foo import BaseFoo, Sub1Foo, Sub2Foo</code>

...my .vimrc is quite minimal...

" Pathogen Configuration
call pathogen#infect()
call pathogen#helptags()

" Syntastic Configuration
let g:syntastic_java_checkers = ['javac', 'checkstyle']
let g:syntastic_python_checkers = ['python, pep8']
let g:syntastic_python_python_exec = '/usr/local/bin/python2.7'

...any thoughts? Thanks!

**Comment by davidhalter** [comment]
Hmm, I have no idea what this might be about. I just checked nose now, `assert_equal` doesn't work, but `raises` does. But I also cannot find `assert_equal` in my version of nose.

I don't have `mock` on my computer, but judging from the source it should easily work.

You should just try the latest jedi dev version (not jedi-vim -> jedi!).

**Comment by davidhalter** [comment]
Pretty sure Jedi's import logic works well now.
