### ISSUE TITLE
Add virtualenv support

### ISSUE THREAD

**Issue by estin** [davidhalter/jedi-vim#31]
On switching virtualenv/interpreter do reinitialize python stuff.

When I start vim, jedi use system python interpreter

But I used VirutalEnv vim plugin for switching per project.
I have many projects in tabs for one vim instance.

To solve this issue I wrote simple function for reimporting jedi lib and jedi_vim files in new virtualenv

Sorry for my poor English (

**Comment by cmcginty** [comment]
See #685
