### ISSUE TITLE
Call signatures break undo history

### ISSUE THREAD

**Issue by wilywampa** [davidhalter/jedi-vim#313]
In this example, I write a line of code the display call signatures for `open` then write a `pass` line underneath. When I press undo afterwards, the `pass` line stays there even after hitting undo multiple times. It's actually somehow overwriting the `def` line. If I turn off call signatures and type the same code this doesn't happen.

![call_signatures](https://cloud.githubusercontent.com/assets/4472522/4683518/58857db4-5627-11e4-921e-2f6c2cc40cc6.gif)

**Comment by davidhalter** [comment]
Since #315 has been merged and it's not possible to solve the issue above I'm closing this issue.
