### ISSUE TITLE
:help jedi-vim doesn't work

### ISSUE THREAD

**Issue by ayeganovgb** [davidhalter/jedi-vim#317]
I am running on Ubuntu 12.04 with Vi IMproved 7.3 (2010 Aug 15, compiled May  4 2012 04:25:35). Jedi version 0.8.1-final0. Jedi-vim was installed using pathogen. Whenever I run ":help jedi-vim" I get "E149: Sorry, no help for jedi-vim". Running help on all other plugins I have works like a charm.

**Comment by Waxolunist** [comment]
You seem to use pathogen. Are you calling pathogen#helptags() in your vimrc?

**Comment by davidhalter** [comment]
True! :)

**Comment by blueyed** [comment]
@ayeganov 
Can you please report back?

**Comment by ayeganov** [comment]
I don't run pathogen#helptags in vimrc. Actually I recently did a full disk wipe, and installed xubuntu.  This problem is no longer present.
