### ISSUE TITLE
Nothing shown when show_call_signatures is set to 2

### ISSUE THREAD

**Issue by jadedarko** [davidhalter/jedi-vim#341]
I'm unsure if it's just not documented, but call signatures appear fine with '1', and do not appear at all with '2'.

Is there a special window that needs to be open for them to appear in?
Vim's documentation refers to the command-line as the window that opens when one types 'q:', but that can not be navigated out of, and does not contain call signatures either.

I should note that this is in vim with -python and +python3

**Comment by allenlz** [comment]
I missed 'noshowmode' too. I suggest to mention this in the README for jedi#show_call_signatures.
