### ISSUE TITLE
goto_definition does not handle decorators

### ISSUE THREAD

**Issue by sloria** [davidhalter/jedi-vim#348]
`goto_definition` does not handle decorated functions correctly. When executed on a wrapped function, you are taken to the wrapper function instead of the original function.

Here's a simple example that will reproduce the bug:

```python
from functools import wraps

def logged(f):
    # goto_definition directs here instead of the wrapped function
    @wraps(f)
    def wrapper(*args, **kwargs):
        print('Calling function {}'.format(f.__name__))
        f(*args, **kwargs)
    return wrapper


@logged
def add(x, y):
    return x + y

# When executing goto_definition with the cursor over "add" 
# I am taken to "wrapper"
print(add(2, 2))
```

It doesn't make a difference whether or not `functools.wraps` is used.

**Comment by davidhalter** [comment]
That's intended. Just use `goto_assignment`. The wrapper function is considered to be the actual definition of that function.

There's an issue to get better docstring support if you use `wraps`: https://github.com/davidhalter/jedi/issues/503. However don't expect the implementation of goto_definition to change. In Python you also get the wrapper (yes it's more complicated if you use wraps, but still).

**Comment by sloria** [comment]
Thanks @davidhalter for the clarification. 

I think the common case is that the user wants to go the wrapped function if it is decorated, and the definition if it is not decorated. If I wanted to go to the wrapper, I would just put my cursor on the decorator and run `goto_definition`. Is there a way to define a single keymapping to do this (i.e. always go to the definition of a function, sans wrappers)?

**Comment by davidhalter** [comment]
As I said: Use goto_assignments.

**Comment by sloria** [comment]
@davidhalter But `goto_assignment` will not recurse to imported symbols. 

For example, let's say import a decorated function and want to go to its definition.

```python
from my_mod import decorated_function

# I want to go to the definition of decorated_function
print(decorated_function(42))
```

If I use `goto_assignments` when my cursor is over the usage of `decorated_function(42)`, I am taken to the import statement. I then have to run `goto_assignments` again to get to `def decorated_function`. If I use `goto_definition`, I am taken to the wrapper function.

What I'd want is to be able to go directly to `def decorated_function` (without having to know whether the function is decorated or not).

**Comment by davidhalter** [comment]
> But goto_assignment will not recurse to imported symbols. 

I know and I'm kind of sorry for that. We might introduce a parameter for that in Jedi and another goto call in VIM.

**Comment by sloria** [comment]
> We might introduce a parameter for that in Jedi and another goto call in VIM.

@davidhalter  That would be excellent. IMO, a goto function that goes to `def`'s (handling decorators as described above) would obviate the need for the other two goto functions.

**Comment by blueyed** [comment]
@sloria 
There is some discussion in https://github.com/davidhalter/jedi/issues/570 also.
What do you think about a "auto" goto function / mode?

**Comment by sloria** [comment]
@blueyed That would be excellent. When I use `goto` I always want to go to the `def`, never the import (regardless of whether the function is decorated or not).

**Comment by davidhalter** [comment]
I'm closing this one in favor of https://github.com/davidhalter/jedi/issues/570. Hope that's ok :)

**Comment by blueyed** [comment]
@sloria 
There is a PR for this now: https://github.com/davidhalter/jedi-vim/pull/407
Please try it and provide feedback, thanks!

**Comment by sloria** [comment]
This seems to have regressed. Using `goto` on a decorated function goes to the decorator instead of the function definition. I can reproduce this on the same code snippet from the original post.

@davidhalter Can we re-open this?

**Comment by sloria** [comment]
To be more specific: `goto` does not behave correctly with decorated functions. `goto_assignment` does the right thing, but it doesn't follow imports. #607 should fix this issue; if that is implemented, then `goto_assignment` should behave as expected in all cases.

**Comment by sloria** [comment]
Ah, I just came across #808. I think that is the right way to go. That way, `goto` will follow imports but `goto_assignment` will not, which is what I would expect.

**Comment by davidhalter** [comment]
@sloria #808 is definitely the future. Please read that thread when it's merged and try again at that point. I think we're on a good way to fix this. The current usage in jedi-vim is a bit stupid, I agree.

**Comment by nickhuangxinyu** [comment]
> Ah, I just came across #808. I think that is the right way to go. That way, `goto` will follow imports but `goto_assignment` will not, which is what I would expect.

Hi, @sloria

could you let me know how you slove this? (push one button to go to real function instead of wrapper function)

Thanks very much

**Comment by davidhalter** [comment]
By default it's `<leader>d`. You can also read the docs/README. Please make sure you have an up-to-date jedi-vim (and submodules).
