### ISSUE TITLE
*IDEA* for call signature autocomplete

### ISSUE THREAD

**Issue by aliev** [davidhalter/jedi-vim#350]
I found autocomplete call signature for python screen: http://4.bp.blogspot.com/-LrjVL4Tg53E/UZfgVldTmsI/AAAAAAAAAHM/DYN6oKhIBsA/s1600/python-rope-show-function-default-args.png (i think there is from rope plugin). What do you think about this? how difficult it will be to do?

**Comment by davidhalter** [comment]
Quite possible. But it is a Jedi issue.

I'm going to leave this open anyhow. I think we already do this in Jedi. But I'm pretty sure that we don't add `=` (plus sorting is different).

**Comment by aliev** [comment]
@davidhalter thanks for response

**Comment by davidhalter** [comment]
This is working in jedi. It's just that the equals somehow doesn't show. We probably would need to change some very small things.
