### ISSUE TITLE
Unable to complete symbols from eggs at OSX

### ISSUE THREAD

**Issue by svagner** [davidhalter/jedi-vim#351]
Hi! Is it possible to detect definitions at eggs files?  I mean like MySQL_python-1.2.5-py2.7-macosx-10.9-intel.egg. It contain module definition MySQLdb, but jedi-vim can't complete this simbols

**Comment by davidhalter** [comment]
To answer your question: No I don't think that we support eggs. But we might in the future.

I don't really understand eggs anyway. Is there a good documentation of them anyway?

**Comment by svagner** [comment]
Yes, it is - http://peak.telecommunity.com/DevCenter/PythonEggs and https://pythonhosted.org/setuptools/formats.html. Generally, Eggs it is zip archive with python's package and metadata. I think it will be good quality for OsX users:)

**Comment by davidhalter** [comment]
Would be fixd by https://github.com/davidhalter/jedi/pull/745
