### ISSUE TITLE
Using with Neovim and Python3

### ISSUE THREAD

**Issue by leebrooks0** [davidhalter/jedi-vim#352]
I couldn't get your plugin to work with Neovim and Python3, I reported the issue here https://github.com/neovim/neovim/issues/1829 and so far it seems like it is not possible?

Your plugin is awesome by the way.

**Comment by davidhalter** [comment]
While I'm excited that neovim exists (and hope the best for its future), jedi-vim is still a pure Vim plugin. I'm not supporting Neovim, at least not until it's more mature. Therefore I'm closing this. It's up to them to be "kind of" backwards compatible. :)

However, I would be glad to eventually switch to Neovims new plugin architecture with a `jedi-neovim` or something like that.

**Comment by leebrooks0** [comment]
They have updated their python client to support py3, so everything is now working beautifully
Thanks!
