### ISSUE TITLE
Missing support for 3rd party modules

### ISSUE THREAD

**Issue by Rboin** [davidhalter/jedi-vim#353]
Having an issue with autocompletion for 3rd party modules like BeautifulSoup (and requests among others) under python3 (Windows 8.1 x64, 32-bit python3)

importing modules is fine and it returns the path like:
```python
import bs4
print(bs4)
<module 'bs4' from path\\to\\python\\lib\\site-packages\\bs4\\__init__.py'>
```

Completion does seem to be there, just not showing
``` python
import jedi
jedi.Script('import bs4; bs4.').completions()
[<Completion: BeautifulSoup>, <Completion: BeautifulStoneSoup>, <Completion: builder>, <Completion: builder_registry>, <Completion: CData>, <Completion: Comment>, <Completion: dammit>, <Completion: Declaration>, <Completion: DEFAULT_OUTPUT_ENCODING>, <Completion: diagnose>, <Completion: Doctype>, <Completion: element>, <Completion: FeatureNotFound>, <Completion: NavigableString>, <Completion: os>, <Completion: PageElement>, <Completion: ParserRejectedMarkup>, <Completion: ProcessingInstruction>, <Completion: re>, <Completion: ResultSet>, <Completion: soup>, <Completion: SoupStrainer>, <Completion: StopParsing>, <Completion: syntax_error>, <Completion: sys>, <Completion: Tag>, <Completion: testing>, <Completion: tests>, <Completion: UnicodeDammit>, <Completion: warnings>, <Completion: _s>, <Completion: _soup>, <Completion: __all__>, <Completion: __author__>, <Completion: __copyright__>, <Completion: __doc__>, <Completion: __file__>, <Completion: __license__>, <Completion: __name__>, <Completion: __package__>, <Completion: __version__>]
```

Trying to complete returns "Omni-completion Pattern not found"

**Comment by davidhalter** [comment]
Hmm this might be an issue with vim's internal Python version (check `:python import sys; print(sys.version_info)`).

**Comment by Rboin** [comment]
The ouput is:
sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)

Output for :python3 import sys; print(sys.version_info() is:
sys.version_info(major=3, minor=4, micro=2, releaselevel='final', serial=0)

**Comment by davidhalter** [comment]
Do you see? The Python versions are different. I think you probably didn't install bs4 under the Python version that you're using in VIM.

**Comment by Rboin** [comment]
ah yes, will compile vim for python 3 :)
thank you for the fast response!
