### ISSUE TITLE
*IDEA* search imports with suggestions

### ISSUE THREAD

**Issue by aliev** [davidhalter/jedi-vim#355]
it's just an idea. I do not know how hard it will be to implement (and whether there is a ready-made solution)

for example we write "reverse" (without importing django.core.urlresolvers.reverse). jedi automatically search for packages. and if the package is not imported it offers options:

"Please select one of the package where this object is defined":

1. django.core.urlresolvers.reverse
2. ...reverse
etc.

What do you think about this?

**Comment by davidhalter** [comment]
This has previously been suggested. This is possible, but you need a good index (which can get quite big). It wouldn't even be a huge amount of work, but I'm not sure if it's that easy to create such an index that also performs and doesn't sit in memory (don't want to load it every time). Maybe we could do something with `sqlite2`?

**Comment by aliev** [comment]
> Maybe we could do something with sqlite2?

good idea!

**Comment by davidhalter** [comment]
This is definitely on my list of the future wishlist and it has been discussed on the Jedi issue tracker again and again. Therefore I'm closing it here.
