### ISSUE TITLE
matplotlib.pyplot.figure(). autocompletion fails

### ISSUE THREAD

**Issue by hukangha** [davidhalter/jedi-vim#358]
Hi I'm using jedi 0.8.1

In my code:
import matplotlib.pyplot as plt
fig=plt.figure()    //succeed
fig.  ////not succeed patern not found

I guess I should report here..
Thanks

**Comment by davidhalter** [comment]
Yes., this is because figure is a complicated function that Jedi doesn't understand. At the moment there's not too much we could do about it. We could somehow "hack" Jedi to understand this, but that's a bad plan IMHO.

Sorry. :(
