### ISSUE TITLE
Renames dont work in __all__

### ISSUE THREAD

**Issue by raghuramos1987** [davidhalter/jedi-vim#361]
```python
__all__ = ['ABC']

class ABC:
    def __init__(self):
        pass
```

After renaming ABC to DAC

```python
__all__ = ['ABC']

class DAC:
    def __init__(self):
        pass
```

**Comment by davidhalter** [comment]
Hmm yes. Not sure if that is going to be included, but still it would be nice.

**Comment by raghuramos1987** [comment]
Not very important I guess. As long as theres a comment about it (maybe you've one and I missed it).

**Comment by davidhalter** [comment]
It's a Jedi issue and for the next 2 years I won't even think about this. Refactoring in Jedi is still in its beginnings and we might have this working one day or we might not. It's pretty hard to do right!

**Comment by mihaic** [comment]
Considering 3 years have passed, any chance of fixing this issue?

**Comment by davidhalter** [comment]
Give me two more, hopefully then we will be at point where refactoring is implemented and this is just an additional feature request.

Definitely not possible, now.
