### ISSUE TITLE
Rename variable with splits problem

### ISSUE THREAD

**Issue by petobens** [davidhalter/jedi-vim#362]
Consider the following minimal vimrc:

    set nocompatible

    let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
    let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

    let g:mapleader = ","

    set runtimepath+=$DOTVIM/bundle/jedi/

    if has('python3')
        let g:jedi#force_py_version = 3
    endif
    let g:jedi#use_tabs_not_buffers = 0
    let g:jedi#use_splits_not_buffers = 'right'

and, as in the GIF, open a `foo.py` file that contains

    x = 2
    print(x)

Now place the cursor on the `x` in the first line, type `,r` and once in insert mode type `y` and exit insert mode. You will se that jedi-vim correctly renames the variable but it also opens a split window. I expect the plugin not to open the split window.

![jedisplit](https://cloud.githubusercontent.com/assets/2583971/6196449/f3a41a84-b3b6-11e4-855b-735111262e70.gif)

**Comment by petobens** [comment]
If I comment these [three lines](https://github.com/davidhalter/jedi-vim/blob/master/jedi_vim.py#L420-422) the problem disappears and the replacement seems to work fine. However I'm not sure if it has any side effects. Can you please check it?
Thank you.

**Comment by davidhalter** [comment]
Hmm set shellslash seems to cause a lot of problems in many ways.

**Comment by petobens** [comment]
@davidhalter indeed. Fortunately my issue was solved by 054285e2b7485d4adabfd4956806e6567eedebfe.
