### ISSUE TITLE
Auto-completion does not support "aliases" created in package's __init__.py

### ISSUE THREAD

**Issue by samuell** [davidhalter/jedi-vim#368]
Some packages create aliases to their package components inside the packages' __init__.py file. E.g. the idea is that instead of writing:
```python
from testjedivim import testjedivim
testjedivim.test()
```
... one can just write
```python
import testjedivim
testjedivim.test()
```
This does not seem to be supported by jedi-vim's autocompletion.

Steps to reproduce:

```bash
# 0. Set $SOMEPYPATH to one of your PYTHONPATH components, e.g the first one:
export SOMEPYPATH=${PYTHONPATH%:*}
# 1. Create a folder for a package 'testjedivim'
mkdir $SOMEPYPATH/testjedivim
# 2. Create a test function in a file in the package:
echo "def test():" > $SOMEPYPATH/testjedivim/testjedivim.py
echo "    print 'test'" >> $SOMEPYPATH/testjedivim/testjedivim.py
# 3. Create an "empty" __init__.py:
echo "# Empty file" > $SOMEPYPATH/testjedivim/__init__.py
```
Now, create a file test.py and try:
```python
from testjedivim import testjedivim
testjedivim.  # Autocompletion will work here!
testjedivim.test()  # Yeah, that worked.
```
Now, make auto-completion stop working:
```bash
# 4. Alias the test function in __init__.py:
echo "import testjedivim" >> $SOMEPYPATH/testjedivim/__init__.py
echo "test = testjedivim.test" >> $SOMEPYPATH/testjedivim/__init__.py
```
Now, create a file test.py and try this, which *should now be working*:
```python
import testjedivim
testjedivim.  # Autocompletion WILL NOT work here!
```
This, although the following script will work fine in python:
```python
import testjedivim
testjedivim.test()
```

**Comment by davidhalter** [comment]
Which Jedi version are you using?

**Comment by samuell** [comment]
@davidhalter: I'm using the one that gets checked out automatically as a submodule with jedi-vim (checked out today), currently at commit: 8775d90

**Comment by davidhalter** [comment]
Wow. Is that one comming automatically with jedi-vim? Thought it was an older revision. I will try to update the current Jedi master branch asap.

**Comment by samuell** [comment]
Yeah, well "automatically" depends I guess ... I used the ansible git module, which does check out submodules automatically :) ... but yes, it is that commit that was checked out, as of today.

**Comment by davidhalter** [comment]
Yeah. That commit is broken as hell :-)

**Comment by samuell** [comment]
Okay :)

**Comment by samuell** [comment]
Is there some other commit I should manually rewind to? :)

**Comment by davidhalter** [comment]
Just wait an hour. :)

**Comment by samuell** [comment]
:+1: :)

**Comment by davidhalter** [comment]
It took me 1:15, but now it should work. ;-) You just have to update the Jedi submodule.

However, note that it's not a "release". It's still shaky.

**Comment by samuell** [comment]
@davidhalter Awesome, that was incredibly quick, let me try it out!

**Comment by samuell** [comment]
YEEAAH, it WORKS! :) Big thanks, @davidhalter ! So quick too!
