### ISSUE TITLE
Autocompletions kicks in only after typing three dots and also apparently incomplete jedi initialization

### ISSUE THREAD

**Issue by PhilResch** [davidhalter/jedi-vim#370]
Hi,

I have 32 bit Python 3.2 installed, my Vim is also a 32 bit version. I'm on 64 bit Windows 7. Jedi-Vim installed with Pathogen. Assume complete noobness on my part, I'm no real programmer and I've only started using Vim. Below are the relevant outputs. I apologize for them being images, but I have no clue how to copy an output of a vim command.

**:ver**
https://i.imgur.com/W08x6nu.png

**:scriptnames**
https://i.imgur.com/OkG4hLi.png

**:mes**
Nothing here after starting gVim. This shows :mes output after typing three dots in the insert mode: https://i.imgur.com/Wrq1rB8.jpg

**:set omnifunc**
```
omnfiunc=pythonComplete#complete
```

**:map**
https://i.imgur.com/Ltq8iQg.png

**My barebones .vimrc**
```
" Setup Pathogen
call pathogen#infect()

set omnifunc=jedi#completions
```

I manually change omnifunc to _jedi#completions_ when editing a python file. For some reason, it's never set automatically by jedi-vim or my vimrc.

Ctrl+Space doesn't do anything in the insert mode, other than add a single space. Other commands listed in :map seem to work.

Typing a dot gives an _Omni completion (^O^N^P) Pattern not found_ error. A dot is also typed in (I don't know if it should?). Same after the second dot (https://i.imgur.com/BWrQHW3.png), but after the third the full autocompletion pop up appears: http://i.imgur.com/WTTUzeI.png

I tried remaping the dot to ctrl-space, but to no avail. Disabling the dot leaves me with nothing.

Default <C-P> binding that brings up Vim autocompletion includes only whatever I had typed in before, no python goodies in sight (unless typed by myself): https://i.imgur.com/amTBU49.png

I'd really appreciate help, because jedi-vim is really appealing, and I wish to stick with Vim. Thanks in advance for your time.

**Comment by davidhalter** [comment]
Sorry I was on holidays, couldn't respond because of that.

> Assume complete noobness on my part, I'm no real programmer and I've only started using Vim.

Well oddly enough this is probably the best bug report I've ever gotten. All the information I need :-)

However, that doesn't change the fact that some very strange things seem to happen. I don't really understand it.

I strongly believe that the errors (in `:messages`) are the problem. But I don't really know why they are appearing and no one else is having that problem.

**Comment by davidhalter** [comment]
Can you recheck please? I changed the regex a few days ago. Latest master branch.

**Comment by PhilResch** [comment]
This issue totally slipped my mind, sorry for not responding. I ended up
removing VIM and all the plugins I had. I reinstalled it afterwards and
reconfigured it from the ground up. I can't pinpoint what I screwed up
previously, but Jedi Vim works great now.
