### ISSUE TITLE
Problem with signature: is not concealed / handled properly (test case)

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi-vim#376]
With the following code, using `ciw` on `BaseInlineAdmin` in `super()`:

    def formfield_for_dbfield(self, db_field, **kwargs):
        kwargs['widget'] = HiddenInput()
        return super(BaseInlineAdmin, self).formfield_for_dbfield(db_field, **kwargs)

The second line becomes:

    kwargs['wid=`=jedi=0, ut()=`= (*_*type*_*, obj) =`=jedi=`=

And leaving insert mode changes it to:

    kwargs['widut()

I've noticed that you've made changes to it today, but also after updating it's the same.

This happens in Vim (7.4.683), but not (fairly) current Neovim..

**Comment by davidhalter** [comment]
Please recheck, it seems to work better now.
