### ISSUE TITLE
first popup_on_dot indexing never finishes for matplotlib.pyplot

### ISSUE THREAD

**Issue by nkelhos** [davidhalter/jedi-vim#377]
I have a python script with:

<pre>
import matplotlib.pyplot as plt
plt
</pre>

If I open it in vim, and add in '.' after the 'plt', vim freezes up, and does not complete.  I'm aware that the first time you do this with a module, it does some kind of indexing, but it wasn't able to finish, even after I left it open for 10 minutes.  I then tried closing the terminal, which seemed to work fine.

After 3 hours, it was pointed out to me that I still had a vim process running, and it was taking up large amounts of memory and cpu %.  The vim process from the closed terminal was still running, and required kill -9 to stop.

It may be specific to that matplotlib.pyplot, as the '.'-complete worked fine with other modules (sys, math, os, my own small module, etc).  This was with no specific settings in .vimrc (jedi-vim was installed via pathogen), and no other vim modules installed.

I've gotten around this by adding
<pre>
let g:jedi#popup_on_dot = 0
</pre>
to my .vimrc file, but I really like the method-completion that this option removes, when it works.

**Comment by davidhalter** [comment]
How fast is your computer?

Jedi version?

**Comment by nkelhos** [comment]
It has 4 X5550 2.6 GHz cpus, with 4 cores each. (cat /proc/cpuinfo has 16 processors), and 47GB of ram.

I had cloned jedi-vim a month ago.  I just did git pull to test it again, but it still freezes up at the dot indexing.  Watching it's process in 'top' shows its slowly accumulating memory, ~Mb/sec .

**Comment by davidhalter** [comment]
Lol. That's pretty much 10 times more than i have :-)

Well, I'm not interested in the jedi-vim version. Try to update Jedi (which is a submodule).

**Comment by ikalnitsky** [comment]
Same bug with projects on my work.

**Comment by davidhalter** [comment]
Jedi commit?

**Comment by ikalnitsky** [comment]
Both (jedi, jedi-vim) masters. I have to note that I'm using Python 2.6 on the office. Perhaps it's related somehow. I will recheck on python 2.7.

**Comment by ikalnitsky** [comment]
Ok, the issue occurs on both py2.6 and py2.7. I can reproduce it even if I create a new file with content:

```python
import yaml
yaml.
```

when I type `.` it hangs.

**Comment by ikalnitsky** [comment]
I've reproduced it on both OS X and Debian Linux.

Moreover, I checked `jedi-vim` with `jedi` commit `7b402d7bbe0e07554f1f97ee3558167961a99b5a` and all works fine.

**Comment by ikalnitsky** [comment]
Ok, looks like we're in infinity loop - `jedi.parser.tokenize.py:generate_tokens`

**Comment by jimmyshen** [comment]
:+1: having this issue too but on OSX and concidentally also with autocompleting yaml on dot -- when I ran dtruss on OSX I also saw the runaway memory usage:

```
close_nocancel(0x5)    = 0 0
fstat64(0x3, 0x7FFF5011F240, 0x1000)     = 0 0
open_nocancel("/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/latin_1.pyc\0", 0x0, 0x1B6)     = 5 0
fstat64(0x5, 0x7FFF5011F018, 0x1B6)    = 0 0
read_nocancel(0x5, "\003\363\r\n3{\331Tc\0", 0x1000)     = 2591 0
fstat64(0x5, 0x7FFF5011F128, 0x1000)     = 0 0
read_nocancel(0x5, "virtualenvs/pymongo3/lib/python2.7/encodings/latin_1.pyR\016\0", 0x1000)     = 0 0
close_nocancel(0x5)    = 0 0
close_nocancel(0x3)    = 0 0
madvise(0x111958000, 0x40000, 0x9)     = 0 0
madvise(0x111958000, 0x40000, 0x9)     = 0 0
madvise(0x111958000, 0x40000, 0x9)     = 0 0
madvise(0x111958000, 0x40000, 0x9)     = 0 0
madvise(0x111958000, 0x40000, 0x9)     = 0 0
...
```

**Comment by davidhalter** [comment]
@ikalnitsky Hmm can you send me a debug trace (enable debugging in Jedi)? I wasn't able to reproduce it. Also if you're able, please post the matplotlib version (and if you know which file/line causes this, that as well).

**Comment by ikalnitsky** [comment]
@davidhalter here's debug log - http://xsnippet.org/360637/raw/

I don't have much time to dive deep into the code, but here's what I've found:

* Jedi fails evaluate this code snippet - https://github.com/yaml/pyyaml/blob/3.10/lib/yaml/constructor.py#L304-L332

* Because after evaluating this one -
https://github.com/yaml/pyyaml/blob/3.10/lib/yaml/constructor.py#L292-L302

* We missed this condition - https://github.com/davidhalter/jedi/blob/48392a7dacd847418aaca1c0bf7197e946b95769/jedi/parser/fast.py#L381 because `line_offset = 303` while `last_end_line = 302`. AFAIK, the `last_end_line` should be `304`.

**Comment by davidhalter** [comment]
Fixed upstream. Thanks so much @ikalnitsky for tracking this one down. Was quite easy to fix after your initial work!
