### ISSUE TITLE
Argument helper is overwriting the line above.

### ISSUE THREAD

**Issue by moorepants** [davidhalter/jedi-vim#378]
I just updated to the latest jedi-vim (head of master) and the function argument helper is now overwriting the line above in many cases. It doesn't do it all of the time. I haven't yet been able to isolate what causes it. Here is an example via screenshot. First I have this code:
![selection_064](https://cloud.githubusercontent.com/assets/276007/6873672/30cbcb2c-d46f-11e4-94b0-eb58aa660c02.png)
Then I edit an argument (vel>pos) and the line above is deleted:
![selection_065](https://cloud.githubusercontent.com/assets/276007/6873681/42fce06a-d46f-11e4-8a4f-94f3f5beef1a.png)

**Comment by davidhalter** [comment]
Yeah. Sorry, I know the issue, trying to fix it.

**Comment by moorepants** [comment]
Yes, that is the same issue.

**Comment by n8henrie** [comment]
Just getting set up with jedi-vim for the first time today and noticed this. Is there a known workaround? I tried disabling docstring popups [as shows in the FAQ](https://github.com/davidhalter/jedi-vim#faq) but not having any luck.

**Comment by davidhalter** [comment]
Yeah sorry. Hope to fix it tomorrow :)

**Comment by davidhalter** [comment]
All right. Faster than I actually hoped to be. Please recheck. I haven't tested it a lot, but it seems to be better than what we've just had.

**Comment by n8henrie** [comment]
I'm still having the issue intermittently on 43dcc4809f7c5280a55daa98ddd5c8415502d750. In my case it's with a functools partial, and the docstring is popping up twice for some reason but deletes the text underneath when the docstring closes.

**Comment by davidhalter** [comment]
Hmm can you give the exact example?

But it's really just one case? Right? Not in general.

**Comment by n8henrie** [comment]
Ha! Thanks for the followup. Also my bad as I checked the commit date but not the time. Great work, after a few brief checks cc9837dc236872cd94303f140a3d9fcfdd9432bf seems to be working fine.

**Comment by davidhalter** [comment]
I'm closing this one, since I'm pretty sure that it's actually solved. Let me know if something is still broken.
