### ISSUE TITLE
Required vim compiled with +python?

### ISSUE THREAD

**Issue by MikeDacre** [davidhalter/jedi-vim#386]
I am using gvim complied with python3, but not with python, when I try and use dot completion e.g. ``from matplotlib.`` I get the following error:

    Error: Required vim compiled with +python
    E117: Unknown function: pythoncomplete#Complete
    Press ENTER or type command to continue

Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/77714/7127900/bc6c1d56-e1ff-11e4-8f1d-e57c5126fc32.png)

**Comment by MikeDacre** [comment]
Argh. My bad, this was my mistake and it has already been answered in another issue report.

omnifunc=pythoncomplete#Complete has to be disabled

Closing. Sorry about that.

**Comment by davidhalter** [comment]
No problem. Glad you're finding out everything yourself :-)

**Comment by ProZoom** [comment]
how to solve it?
