### ISSUE TITLE
'Completion' object has no attribute 'docstring' - trying to use neocomplete

### ISSUE THREAD

**Issue by benbarbour** [davidhalter/jedi-vim#390]
The relevant part of my vimrc, I think, is:

```
autocmd FileType python setlocal omnifunc=jedi#completions
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
```
Which is from the neocomplete help file. And I get this in the message log when I type, for example, 'os.' in a python file that has os imported:
```
Traceback (most recent call last):
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi_vim.py", line 172, in completions
    info=PythonToVimStr(c.docstring()),  # docstr
AttributeError: 'Completion' object has no attribute 'docstring'
```

Apologies if this is a jedi bug or a neocomplete bug, but since the stacktrace was from jedi_vim I thought I'd file it here first.

**Comment by davidhalter** [comment]
You are using an old version of Jedi. https://github.com/davidhalter/jedi/issues/566 solves this by making a new release. Just update Jedi to the latest branch to fix it for now.
