### ISSUE TITLE
Installation through pip -  syntax error

### ISSUE THREAD

**Issue by dhavale** [davidhalter/jedi-vim#41]
When tried "pip install jedi" on ubuntu 12.04 x86_64, throws syntax error and other warning.

sandeep@sandeep-OptiPlex-755:~/python_play$ sudo pip install jedi --upgrade
Downloading/unpacking jedi
  Running setup.py egg_info for package jedi

```
package init file 'jedi/mixin/__init__.py' not found (or not a regular file)
warning: no previously-included files matching '*.pyc' found under directory '*'
```

Installing collected packages: jedi
  Found existing installation: jedi 0.5b3
    Uninstalling jedi:
      Successfully uninstalled jedi
  Running setup.py install for jedi
    package init file 'jedi/mixin/**init**.py' not found (or not a regular file)
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/jedi/mixin/_functools.py', 9, 42, '        return self.__func(_self.__args, *args, *_self.keywords, **kwargs)\n'))

```
warning: no previously-included files matching '*.pyc' found under directory '*'
```

Successfully installed jedi
Cleaning up...

**Comment by blueyed** [comment]
Sorry, I've meant #414 in the last commits being referenced here.
