### ISSUE TITLE
jedi-vim not completing

### ISSUE THREAD

**Issue by dstromberg** [davidhalter/jedi-vim#411]
I'm attempting to install/configure jedi-vim on OSX 10.10.2 with CPython 2.7.6 (sigh, old version).

I built vim with -with-features=big --enable-pythoninterp to get +conceal and +python .

I installed pathogen with:
mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

I added:
execute pathogen#infect()
...to the bottom of my ~/.vimrc .

I did a:
sudo pip install jedi

And I installed jedi-vim with:
git clone http://github.com/davidhalter/jedi-vim ~/.vim/bundle/jedi-vim

And I installed supertab with:
cd ~/.vim/bundle/
mkdir -p supertab/
cd supertab/
curl http://www.vim.org/scripts/download_script.php?src_id=21752 > supertab.vmb

And I started a fresh vi for testing (carefully getting /usr/local/bin/vim instead of /usr/bin/vim) .

However, when I go into vim and hit tab, I don't get a list of possibilities:

def main():
    print('hi')
    print('   abc'.strip())
    print(sys.ver

main()

~                                                                                
~                                                                                
~                                                                                
~                                                                                
~                                                                                
-- Keyword completion (^N^P) Pattern not found

What do I need to do to get jedi-vim to list/expand completions?

Thanks!

PS: I'm quite excited about Jedi's potential as a static analysis tool.  I've been using pylint a lot, but that's made me highly aware of pylint's tendency to miss (some!) problems.

**Comment by dstromberg** [comment]
BTW, I'm using a pyflakes plugin.  Is it possible that's conflicting with jedi-vim?

**Comment by dstromberg** [comment]
I'm in Terminal.app (terminal emulator), which I've heard has problems with control-space.

I've tried completing with control-space, tab, and control-n.  None of them give the rich sort of completions I was hoping for with jedi, though control-n does give some simple completions.

**Comment by dstromberg** [comment]
I'm using vim 7.4, not 7.3.

**Comment by dstromberg** [comment]
My list of enabled plugins:

  1: ~/.vimrc
  2: /usr/local/share/vim/vim74/syntax/syntax.vim
  3: /usr/local/share/vim/vim74/syntax/synload.vim
  4: /usr/local/share/vim/vim74/syntax/syncolor.vim
  5: /usr/local/share/vim/vim74/filetype.vim
  6: /usr/local/share/vim/vim74/ftplugin.vim
  7: ~/.vim/autoload/pathogen.vim
  8: /usr/local/share/vim/vim74/ftoff.vim
  9: ~/.vim/plugin/supertab.vim
 10: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 11: /usr/local/share/vim/vim74/plugin/getscriptPlugin.vim
 12: /usr/local/share/vim/vim74/plugin/gzip.vim
 13: /usr/local/share/vim/vim74/plugin/matchparen.vim
 14: /usr/local/share/vim/vim74/plugin/netrwPlugin.vim
 15: /usr/local/share/vim/vim74/plugin/rrhelper.vim
 16: /usr/local/share/vim/vim74/plugin/spellfile.vim
 17: /usr/local/share/vim/vim74/plugin/tarPlugin.vim
 18: /usr/local/share/vim/vim74/plugin/tohtml.vim
 19: /usr/local/share/vim/vim74/plugin/vimballPlugin.vim
 20: /usr/local/share/vim/vim74/plugin/zipPlugin.vim
 21: /usr/local/share/vim/vim74/scripts.vim
 22: /usr/local/share/vim/vim74/syntax/python.vim
 23: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 24: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 25: ~/.vim/ftplugin/python/pyflakes.vim
 26: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 27: /usr/local/share/vim/vim74/ftplugin/python.vim
 28: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim

**Comment by dstromberg** [comment]
I just tried:
sudo pip install -e git://github.com/davidhalter/jedi.git#egg=jedi
It gave the same result as sudo pip install jedi - no completions.

**Comment by dstromberg** [comment]
Perhaps it was the OS/X terminal.app control-space problem; I added let g:jedi#completions_command = "<C-N>" to my .vimrc, and then control-n started working.  I don't know why tab wasn't (and still isn't) working.

**Comment by davidhalter** [comment]
Well, looks like you solved it yourself :-) I have no idea either. Maybe use supertab.
