### ISSUE TITLE
jedi-vim issue in debian 

### ISSUE THREAD

**Issue by adrian-gluu** [davidhalter/jedi-vim#413]
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 2 or 3. (in fu
nction jedi#init_python..<SNR>31_init_python, line 40)

**Comment by blueyed** [comment]
So both `has("python")` and `has("python3")` are false.

Which Vim package have you installed?
You should probably install `vim-nox` or a similar package, which has Python support.

btw: there's also vim-python-jedi.. :)

**Comment by adrian-gluu** [comment]
Yes just got this fixed using the pkg vim-python-jedi

**Comment by blueyed** [comment]
Did this pull in another Vim package (with python support) then?

**Comment by adrian-gluu** [comment]
no, just the same version that comes with debian unstable (SID)
