### ISSUE TITLE
Conflict with simple operator highlighting plugin (Valloric/vim-operator-highlight)

### ISSUE THREAD

**Issue by oblitum** [davidhalter/jedi-vim#415]
I'm getting this in two machines (OS X and Ubuntu):

![screen shot 2015-05-09 at 22 34 33](https://cloud.githubusercontent.com/assets/1269815/7552712/a3675d06-f69b-11e4-914b-fc7265acd0e6.png)

[My jedi setup](https://github.com/oblitum/dotfiles/blob/osx/.vimrc#L335-L336) is just:

```vim
let g:jedi#auto_vim_configuration = 0
let g:jedi#completions_enabled = 0
```

I'm running a recent build of vim 7.4 (in OS X now, 7.4.699). A recent python 2 instance.

**Comment by davidhalter** [comment]
Does it work with `auto_vim_configuration = 1`?

**Comment by oblitum** [comment]
no, it doesn't.

**Comment by blueyed** [comment]
How did you install it? Maybe jedi-vim's after/syntax/python.vim isn't parsed at all?
Does `:hi jediFunction` give you some output, or an error?
Does your Vim have the `conceal` feature? (maybe post the output of `:version`).

**Comment by oblitum** [comment]
It should be some conflict with another plugin, I've just started it alone and found no issues, I'm looking it up the conflicting plugin.

**Comment by oblitum** [comment]
I just found it, the issue shows up when [Valloric/vim-operator-highlight](https://github.com/Valloric/vim-operator-highlight) is loaded. I'm not sure where the issue lies, here or there, in any case I will open another one there and rename this one.

**Comment by oblitum** [comment]
By the way, that operator highlight plugins is a quite simple plugin, but as it creates highlighting groups for special characters it may be conflicting with the ones used by jedi that are used with conceal.

**Comment by oblitum** [comment]
By the way, I've opened long ago another issue there that relates to this:

https://github.com/Valloric/vim-operator-highlight/issues/10

**Comment by blueyed** [comment]
I've left a comment at https://github.com/Valloric/vim-operator-highlight/issues/10#issuecomment-100664086, with a possible fix (for vim-operator-highlight).

For jedi-vim, you can use `let g:jedi#show_call_signatures = 2` to display them in the command line.
I've suggested this to be the default in https://github.com/davidhalter/jedi-vim/pull/412 btw - feedback would be appreciated.

**Comment by oblitum** [comment]
I do think that call signatures as popup is the ideal, the problem is the implementation which is unstable and hacky. So if command-line is less error-prone it could be the default indeed.

By the way, at https://github.com/Valloric/YouCompleteMe/pull/1300 I've documented an stable way of having popup for parameters which is stable for vim, since it uses vim's own mechanisms for that. It's working quite nice for C and C++.

**Comment by davidhalter** [comment]
@oblitum So how do you do it, if not by syntax modifications?

**Comment by oblitum** [comment]
@davidhalter by using the popup from completion support, poping up signature information solely at specific points (after parenthesis and comma, for example).

**Comment by oblitum** [comment]
I leave completion text empty for all completions, but the text at the menu I use to display the parameter information. There's a GIF at that pull request. You may check it here: https://github.com/oblitum/YouCompleteMe

**Comment by davidhalter** [comment]
@oblitum Yeah I guess that's ok. I personally prefer the current solution, because the text stays even if you type.

**Comment by oblitum** [comment]
@davidhalter I find it quite nice too, the question is _when it works_...

**Comment by davidhalter** [comment]
I actually think it works reasonably well. There are a few issues with it. But I don't experience it often (and I use undo a lot!).

**Comment by blueyed** [comment]
Another problem in this context might be when indenting plugins look at a line's content, e.g. vim-pep8-indent - where I came up with fixes to handle jedi-vim's inline call signatures better.

**Comment by davidhalter** [comment]
True. I think the biggest problem is actually automatic line wrappings (`textwidth` does that). Apart from that it will cause issues with a few other plugins (like this one), but I doubt that it will be a majority.

**Comment by oblitum** [comment]
@davidhalter it's not my experience, for example, I got this kind of issue with this some random plugin, I don't program much in python so it showed up to me when I tried to show it to a friend of mine, the problem is that it didn't work as it had work the last time I tried, so I had to debug it and finally showed it to my friend.
Ok, he got to his machine to try and then, it also didn't work similarly, I then recommended him to debug it since he was not using this particular conflicting plugin, or, just use the option to show signatures at the command line which should be more rock solid. I simply don't know where it won't work someway or another.

**Comment by davidhalter** [comment]
@oblitum Just use `let g:jedi#show_call_signatures = 2`. I know that it doesn't work for some people. But for most people it does. There are people complaining, but not a lot. So it cannot be a very big deal. Some people (including me) also really like it. But for a discussion about this you an comment in #412. I'd be willing to change it if a lot of people vote for it.
