### ISSUE TITLE
Slow autocompletion when using Python Selenium webdriver in Django tests

### ISSUE THREAD

**Issue by xmjandrews** [davidhalter/jedi-vim#419]
When coding Django tests that involve Python's Selenium webdriver, things can get very slow when using jedi-vim. 

As an example, if I want to type

       start_button\
            = self.driver.find_element_by_class_name('ButtonBox')\
            .find_element_by_id('StartButton')

after I type to the `find_element_by_id`, when I type `(`, it takes about 5 to 10 seconds for this character to appear and then the same amount of time for each character in `'StartButton'`.

I've only every noticed this very slow responsiveness when using Python Selenium. I use many other Python packages and libraries and the latencies are usually either unnoticeable or just a few hundred milliseconds.

I'm using jedi-vim from commit 9eaede84b235fcbbe1b9164dda29bccd8a406fb2 (Jan 6, 2015).

**Comment by davidhalter** [comment]
Please update jedi-vim and Jedi!

**Comment by xmjandrews** [comment]
Sorry! I really should have done that first.  

I am now on 66557903ae4c1174eb437a8feeeb718e69d5fa3a for jedi and bce599fc9cb29fe45171d22eb6fae525580fe42f for jedi-vim.

And indeed that does fix it. There's no delay any more.

Thank you!

**Comment by blueyed** [comment]
I'm glad it worked out.
