### ISSUE TITLE
Fix column detection with cmdline call signatures

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi-vim#421]
Ref: https://github.com/davidhalter/jedi-vim/commit/cfd71a6b548ac26af8468071908f18f341467dc2

Is it necessary to display the signatures in the "correct" column?

I think the `:undojoin` in there is doing some unwanted things, and found the whole procedure really overkill.

If the correct column is useful then this should get fixed/simplified probably.

**Comment by davidhalter** [comment]
cc @wilywampa

**Comment by wilywampa** [comment]
I agree that `undojoin` causes some subtle but serious issues. In my fork of jedi-vim, I implemented a better `save_first_col` function which has the advantages of never switching windows, changing settings, or using `undojoin`. The disadvantage is that it only works with 3 or fewer windows. If 4 or more windows are open it just returns column 0. I think it's a good tradeoff for the number of side effects it eliminates.

It works just by looking and the window widths of the three (or fewer) windows doing some basic arithmetic to figure out what the layout is and where in the layout the current window is.

Here: https://github.com/davidhalter/jedi-vim/pull/422

**Comment by wilywampa** [comment]
This can be closed since #422 was merged.

**Comment by blueyed** [comment]
Thanks!
