### ISSUE TITLE
Open vim folds if jumped to by go-to-{definition,assignment}

### ISSUE THREAD

**Issue by syntonym** [davidhalter/jedi-vim#424]
If a class/function definition is folded and I navigate to it via the search motion (e.g. `/class`) the fold is automatically opened so that I can see the term I just jumped to. `goto_definition` and `goto_assignment` seem not to do this. `usages()` on the other hand does open the fold (maybe because it uses a different motion internally?). It would be nice if `goto_definition` and `goto_assignment` would have the same behavior.

Feature Request

**Comment by blueyed** [comment]
Might be related to using `vim.current.window.cursor = d.line, d.column` (`jedi_vim.py:goto`) vs. `call cursor(l:data.lnum, l:data.col)` (`jedi#goto_window_on_enter`) - but calling `cursor()` manually on a fold did not open it for me..

Are you using `g:jedi#use_tabs_not_buffers`?

**Comment by syntonym** [comment]
I'm using `let g:jedi#use_tabs_not_buffers = 0`. Does it work as expected with `let g:jedi#use_tabs_not_buffers = 1` for you? For me it is indepenent of that setting.

**Comment by davidhalter** [comment]
Decided not to do this.
