### ISSUE TITLE
jedi-vim cannot find jedi because of import error

### ISSUE THREAD

**Issue by nye17** [davidhalter/jedi-vim#427]
Thanks for the great work in developing jedi-vim!

Jedi-vim worked perfectly well before yesterday when I did an anaconda update of the Jedi package.

Vim reports that "please install jedi if you wanna use jedi-vim" error during start-up, although jedi is installed from within anconda and can be imported in both conda python and Mac native python without problem. The python path within vim is also correctly set up; however, when I do,

:py import jedi

witihin MacVim, it reports 

from jedi import debug
ImportError, can not import debug,
 
in gui-mode, and 

File "/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/anaconda/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_ReplaceException
  Referenced from: /anaconda/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

in terminal-mode.

Any ideas?

**Comment by davidhalter** [comment]
I have no idea. Pretty sure that it's not Jedi or jedi-vim, but your setup.

**Comment by nye17** [comment]
thanks for the response! any suggestions on where to begin if I wanna debug this on my system?

**Comment by blueyed** [comment]
It looks like your Python/Vim setup is broken.
Try to figure out what the Python version/installation is in both cases and what the sys.path looks like in the first case.

**Comment by nye17** [comment]
thanks; how to verify if macvim is correctly linked to the anaconda python?

**Comment by nicholsn** [comment]
also just ran into this, have you figured it out?

Are you using homebrew to install macvim/vim?

Came across [this stackoverflow post](http://superuser.com/questions/440981/how-can-i-use-the-homebrew-python-version-with-homebrew-macvim-on-snow-leopard) that looks promising... Still working on it

**Comment by nye17** [comment]
Hey. That link seems to be the right place to begin with, and it does seem that that's where the problem comes from. I hadn't tried anything further but guess I'll the answer in that link later. Please keep me posted if you had any progress!

**Comment by nye17** [comment]
interestingly though, vim-jedi worked perfectly and my macvim setup/installation hasn't changed since, but it broken down after I upgraded vim-jedi and jedi one day --- which is why I came to open an issue here, despite that it doesn't seem to be a vim-jedi issue after all.

**Comment by scottdaniel** [comment]
I have about the same problem... perhaps something to do with the way conda sets up environments?

**Comment by davidhalter** [comment]
Please try again guys with the latest jedi-vim master branch and the latest jedi master branch and please report what Python version your VIM is using.

**Comment by scottdaniel** [comment]
The issue was fixed for me when I upgraded to vim 7.4 in /usr/bin/vim
