### ISSUE TITLE
Need key mapping cleanup functionality

### ISSUE THREAD

**Issue by cyniphile** [davidhalter/jedi-vim#428]
If one defines a key mapping in .vimrc as recommended in the README:

`let g:jedi#documentation_command = "K"`

This creates buffer specific mappings which are added to any buffer opened subsequently and persist even after a file is closed. If I update the mapping in .vimrc, all the old mappings still exist in all these previously opened files. 

Something should be added to  `ftplugin/python` to check for old mappings in the buffer and clear them.

**Comment by blueyed** [comment]
> If I update the mapping in .vimrc, all the old mappings still exist in all these previously opened files

You mean without restarting Vim, right?

**Comment by cyniphile** [comment]
No, actually. Even if I restart vim those buffer level mappings remain.

**Comment by blueyed** [comment]
That's odd.

Do normal buffer-local mappings get restored across Vim restarts for you, too?

    1. `:map <buffer> foo bar`
    2. Restart Vim
    3. `:map foo`

That shouldn't be the case (by default) AFAIK.

(I rather think the `g:jedi#documentation_command` setting is being set to late or something like that.)

**Comment by cyniphile** [comment]
Yes they do. Duplicating the commands above gives me a `foo     @bar`, even after restart. 

I do use SPF-13 plus a variety of additional plugins. I take it the problem must be coming from one of these sources and is not normal vim behavior?

**Comment by blueyed** [comment]
Yes, it's unusual.
I recommend bisecting your settings / the included plugins.

I'm curious, so please report back.

**Comment by davidhalter** [comment]
I certainly don't think this is a jedi-vim bug. Otherwise please prove.
