### ISSUE TITLE
Disabling "underscore autocompletion"?

### ISSUE THREAD

**Issue by wzyboy** [davidhalter/jedi-vim#429]
class Class1(object):
        def __init__(self, n):
            self.n = n

When trying to write a class like this, after `self.`, Jedi will pop up with a list of `__double_underscore_methods___` and automatically fill `self.__` for me since all the options start with double-underscores. Howerer, I just would like to type `self.n` so I have to manually backspace twice to delete `__` and type `n` instead. This also happens when all the options are `_single_underscore_methods`: I also have to delete that `_` to type in my own method name.

I have already configured `let g:jedi#popup_select_first = 0` and it worked in most cases. For example, if I `import os` then type `os.`, Jedi will not select the first option for me. But if all the options start with `_` or `__`, it will.

I am using vim-jedi in Arch Linux repository, which is fairly old (0.7.0). I've tried the latest git version but this issue persists.

Would there be a way to disable this behaviour? Thanks for your great work!

**Comment by davidhalter** [comment]
You could remove `longest` from `completeopt`?

**Comment by wzyboy** [comment]
Removing `longest` from `completeopt` makes it worse: the first double-underscore option (e.g. `__class__`) is auto completed for me. And there are still these configuration in my vimrc:

    let g:jedi#auto_vim_configuration = 0
    let g:jedi#popup_select_first = 0
    set completeopt=menuone

I think I may have mixed two issues here:

1. When there is `longest` in `completeopt`, it takes priority, and `os.` only triggers a list, not auto completion (what I expect), but `self.` triggers a list with common prefixes and the prefix (`__`) is auto completed (not what I expect, as stated in the first post).

2. When there is no `longest` in `completeopt`. `popup_select_first` takes priority, so no matter `os.` or `self.`, Jedi will complete the first option for me (I have to press more backspaces).

And why Jedi still select the first option for me even when I set `popup_select_first = 0`? IMHO this may be similar to a previous issue I've reported (https://github.com/davidhalter/jedi-vim/issues/374). I installed vim-jedi as a system package (in `/usr/share/...`, not `$HOME/.vim/...`). My configuration in `~/.vimrc` may be overwritten by system configuration. I'll try to figure out more about this and post any updates here later.

**Comment by wzyboy** [comment]
Okay, I've figured out. Installing vim-jedi as a Vundle package instead of a system package and set the options above solves this issue. No strange behaviours any more. Everything works like expected.

I'll never try to mess with "system-level" vim plugins and struggle with overwritten variables anymore. Vundle makes my life easier...

I am closing this issue. Sorry for bothering.

**Comment by davidhalter** [comment]
I don't really understand what went wrong, but thanks for looking into this yourself!
