### ISSUE TITLE
auto_initialization = 0 not respected

### ISSUE THREAD

**Issue by OliverUv** [davidhalter/jedi-vim#432]
Hi, `<leader>d` becomes bound to goto_definition even though I have

    let g:jedi#auto_vim_configuration = 0
    let g:jedi#auto_initialization = 0

**Comment by davidhalter** [comment]
That is strange, since auto_initialization is wrapped around that. Could you please try to update jedi-vim to the latest commit and then tell me where this is coming from (source?) It is not reproducible for me.

**Comment by davidhalter** [comment]
No answer.
