### ISSUE TITLE
PyGoto command to go to a custom identifier

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi-vim#433]
I would like to do `:PyGoto tornado.web.Application` to go to this identifier.

This would be similar to `:PyImport`.

Maybe `:PyImport` could be enhanced and renamed?
I find its name not very fitting: sounds like it would auto-add missing imports or something in this direction.

**Comment by davidhalter** [comment]
I agree. I would prefer your solution.

**Comment by davidhalter** [comment]
`:Pyimport` is basically what you want (on master). We can have a discussion about the name for this, but IMO it doesn't really matter. `Pyimport` and `Pygoto` would both be fine.
