### ISSUE TITLE
Type deduction doesn't seem to work for custom user types.

### ISSUE THREAD

**Issue by dpnova** [davidhalter/jedi-vim#434]
Here's an example from our project that would be awesome to get type deduction working for. For some reason it works fine if I import the class and use autocomplete directly... just not when the type is defined in the docstring.

    def create(self, data):
        """
        Create a hbase record.
        
        :type data: `inboxpersist.hbase.base.HBase`
        """
        data.|  # autocomplete doesnt do anything here

Thanks!

==================
Old Question Below:

The dosc here seem to suggest it's possible, but I can't seem to get it to work: http://jedi.jedidjah.ch/en/latest/docs/development.html#module-jedi.evaluate.dynamic

What sphinx syntax would be required to refer to a class as a type passed to a method and have jedi pick up stuff for autocompletion?

Cheers

**Comment by davidhalter** [comment]
This seems to work perfectly well for me:


```
def myfunction(node, foo):
    """Do something with a ``node``.

    :type node: str
    :param str foo: foo parameter description

    """
    node.| # complete here
```

What's your `:set omnifunc`? I would think that your jedi-vim is not correctly initialized.

**Comment by dpnova** [comment]
Hi David...

`omnifunc=jedi#completions`

Do you know what the syntax would be for referring to a class elsewhere in the project? Built in types are indeed working fine for me given the example you provided...

Cheers!

**Comment by davidhalter** [comment]
Well using the path or the name used in the module should both work IMO. If it doesn't add an issue (or rename this one).

**Comment by dpnova** [comment]
Thanks.. I've updated and included an example.

**Comment by davidhalter** [comment]
This issue seems to be a little strange to me. It's not a jedi-vim issue. Please add it to Jedi and then we talk again. This works in a lot of cases, but it might be an edge case. Please try to provide an example with open source code that is easily reproducible (if you post it to Jedi).
