### ISSUE TITLE
Auto completion on command line does not work

### ISSUE THREAD

**Issue by justhalf** [davidhalter/jedi-vim#435]
As described in the newly merged pull request (https://github.com/davidhalter/jedi-vim/pull/315), I have:

```vim
let g:jedi#show_call_signatures = 2
```

to let the signature call shows up in the command line.

But what I saw was nothing, only the usual `-- INSERT --` text at the beginning of the command line.

However, I also noticed that when I move the cursor speedily in a function (the place where it is supposed to trigger show call signature), sometimes I saw flashes of the function signature in the command line. So I believe it must have been overridden by some other text. Perhaps the `-- INSERT --` is displayed after Jedi prints the call signature to command line, hence overwriting the call signature printed by Jedi? Or is it conflicting with my vim config?

I'm on Fedora 19, with the following .vimrc:

```vim
filetype plugin indent on
set nocompatible
set modelines=0
set colorcolumn=80

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

syntax enable

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell

set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set number

set backup
if v:version >= 730
    set undofile
    set undoreload=10000    
endif
set undolevels=1000
"Save and load view state
au BufWinLeave * silent! mkview
au BufWinEnter * silent! loadview

"Remap Leader key
let mapleader=","

"Search behavior
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
"replace global in a line
set gdefault
set incsearch
set showmatch
set hlsearch
"Clear search
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %
"Handle long line
set wrap
if &diff
    set wrap
endif
set textwidth=119
set cc=120
set formatoptions=qrn1


nnoremap j gj
nnoremap k gk
nnoremap ; :
au FocusLost * :wa
"Split vertical window
nnoremap <leader>w <C-w>v<C-w>l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"Yank to the end of line
nnoremap Y y$
function! InitializeDirectories()
    let separator = "."
    let parent = $HOME
    let prefix = ".vim"
    let dir_list = {'backup': 'backupdir', 'views': 'viewdir', 'swap': 'directory'}
    for [dirname, settingname] in items(dir_list)
        let directory = parent . '/' . prefix . dirname . '/'
        if exists("*mkdir")
            if !isdirectory(directory)
                call mkdir(directory)
            endif
        endif
        if !isdirectory(directory)
            echo "Unable to create backup directory" . directory
        else
            exec "set " . settingname . "=" . directory
        endif
    endfor
endfunction
call InitializeDirectories()

"Delimitmate 
au FileType * let b:delimitMate_autoclose = 1

"Enable mouse usage
set mouse=a
"Command-T
let g:CommandTSearchPath = $HOME 
set pastetoggle = "Toggle"
set guifont=Monaco:h11
filetype on
filetype plugin on

" Folding
augroup vimrc
    au BufReadPre * setlocal foldmethod=indent
    au BufWinEnter * if &fdm == 'indent' | setlocal foldmethod=manual | endif
augroup END
nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space>")<CR>
vnoremap <Space> zf

" Autocomplete
autocmd FileType python set omnifunc=pythoncomplete#Complete

execute pathogen#infect()
autocmd CursorMovedI * if pumvisible() == 0|silent! pclose|endif
autocmd InsertLeave * if pumvisible() == 0|silent! pclose|endif
colorscheme peachpuff
autocmd VimEnter * set foldlevel=20
let g:jedi#show_call_signatures = 2
```

**Comment by blueyed** [comment]
Do you get any errors in `:mess`?

**Comment by blueyed** [comment]
Apart from that your `vimrc` is small, which should make it easy to bisect.

For starters, you do not really want/need `autocmd FileType python set omnifunc=pythoncomplete#Complete`, do you?

**Comment by justhalf** [comment]
No errors in `:mess`. Yes, I can remove it. I just realized I haven't been using jedi popup so far =O

But even after removing that, the same behaviour persists.

**Comment by blueyed** [comment]
> But even after removing that, the same behaviour persists.

Yes, it's not really related to your issue - I just noticed it.  You need to experiment yourself now.
`let g:jedi#show_call_signatures = 1` works?

**Comment by justhalf** [comment]
That works, although the popup disappears every other character, and then reappear on the next character.

**Comment by blueyed** [comment]
Try removing `autocmd CursorMovedI * if pumvisible() == 0|silent! pclose|endif` - I cannot see why that would be needed.
If that does not help, please experiment yourself a bit - by disabling some uncommon options/settings!

**Comment by justhalf** [comment]
Even when I used only `filetype on`, followed by the `execute
pathogen#infect()` and finally `let g:jedi#show_call_signatures = 2`, it
doesn't work. I already removed the `.vimviews` to confirm that the new
.vimrc is used. =/

**Comment by justhalf** [comment]
Even when I used only this:

```
filetype on
execute pathogen#infect()
let g:jedi#show_call_signatures = 2
```

it doesn't work.

I already removed the `.vimviews` to confirm that the new .vimrc is used. =/

**Comment by ches** [comment]
@justhalf Not sure about the problem of jitter using the popup call signatures, but for the command line option `showmode` interferes with it (hence the `-- INSERT --` you observed)—try `set noshowmode`.

**Comment by justhalf** [comment]
@ches That solves it! Thanks.

**Comment by davidhalter** [comment]
Can we close then?

**Comment by justhalf** [comment]
Yes.
