### ISSUE TITLE
unable to complete on "slightly complex" object

### ISSUE THREAD

**Issue by kraxli** [davidhalter/jedi-vim#438]
First of all many thanks for the great plugin that works great in general! 

However, it is not completing slightly complex object as "x" in the following example:

```python
import pandas as pd
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']), 'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
x = df.head(2)
x.        # no completion on this data-frame
```

the command line shows: "=jedi#complete_opened(0) Omni completion (^O^N^P) Pattern not found"

Could anybody please help out on this or does anybody have suggestions what could go wrong? 

Many thanks, David

**Comment by kraxli** [comment]
I just figured out that I do not have this issue on Ubuntu but still on Windows7 where I use WinPython-64bit-2.7.9.5 along with Neocomplete (however switching off Neocomplete does not solve the problem). 
Is this an issue with WinPython? Does anybody has successful experiences with the Anaconda installation on Windows? 

Thanks and sorry for the too early posting of the issue.
David

**Comment by kraxli** [comment]
Ok, Anaconda solves the problems. Sorry for posting here since this was not a jedi(-vim) problem but a Python distribution one.

**Comment by kraxli** [comment]
Sorry guys I am back. The issue is back as soon as I update jedi 0.8.1 which is packed in Anaconda to 0.9. So it is a jedi issue.

**Comment by davidhalter** [comment]
It's definitely a Jedi issue. Jedi seems to struggle hard with understanding pandas. 

I can not move it to the Jedi tracker, unfortunately. You have to open a new issue there, if you want.

**Comment by davidhalter** [comment]
There's already pandas issues in Jedi, so I'm closing this one (e.g. https://github.com/davidhalter/jedi/issues/520 or https://github.com/davidhalter/jedi/issues/372)
