### ISSUE TITLE
Rename fails with multiple same-named variables in different classes

### ISSUE THREAD

**Issue by ipsod** [davidhalter/jedi-vim#439]
```
class Vanilla(models.Model):
    title = 1
class Vanillin(models.Model):
    title = 1
```
Trying to rename "title" in one class totally and non-undo-ably deletes the whole line containing "title" in the other class.  Clearly, since they don't share scope, the other class shouldn't even be touched.

**Comment by davidhalter** [comment]
Is working now (Jedi dev branch).
