### ISSUE TITLE
Rename fails for longer names

### ISSUE THREAD

**Issue by jean** [davidhalter/jedi-vim#444]
Using the `\r` mapping, I rename `xrandr_out` to `xrandr_output` or `xrandr_outpu`. Jedi does 0 renames. 
But if I rename `xrandr_out` to `xrandr_outp`, Jedi does 4 renames.

**Comment by davidhalter** [comment]
Rename is pretty buggy still IMO. This is probably just a side-effect of its bad implementation.

**Comment by davidhalter** [comment]
Rename is buggy and there's like 10 other issues for it that describe the bug better. I'm closing :)
