### ISSUE TITLE
jedi.keywords module missing

### ISSUE THREAD

**Issue by madhavan020985** [davidhalter/jedi-vim#445]
````python
Error detected while processing /home/user/.vim/autoload/jedi.vim:
line  189:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/sk/.vim/plugin/jedi_vim.py", line 12, in <module>
    import jedi.keywords
ImportError: No module named keywords
````
I am not seeing the jedi.keywords module exposed in the jedi's repository - https://github.com/davidhalter/jedi/blob/master/jedi/__init__.py#L41. How does jedi.vim use this module?

in my local system, `pip list | grep jedi` shows `jedi (0.8.1-final0)`.

**Comment by blueyed** [comment]
You need to update Jedi-vim probably.
See https://github.com/davidhalter/jedi-vim/blob/master/jedi_vim.py#L12.

**Comment by madhavan020985** [comment]
yup, with new git cloned code it works...
