### ISSUE TITLE
shortcut to jump back after goto-definition

### ISSUE THREAD

**Issue by madhavan020985** [davidhalter/jedi-vim#446]
There is a shortcut - \g given for go to assignments/definitions. But the matching shortcut for jumping back to the original place is not there. i am sure, all people who use \g would like to jump back as well. i am seeing emacs's - (alt + dot) feature here, but the one for (alt + comma) is not here
````vim
let g:jedi#goto_command = "<leader>d"
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = ""
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#rename_command = "<leader>r"
````

**Comment by blueyed** [comment]
It is the standard `<c-o>` to go back in the jumplist, isn't it?

**Comment by madhavan020985** [comment]
Ctrl - o works.. it will be good and helpful, if it can be mentioned immediately after  --- let g:jedi#goto_assignments_command = "<leader>g"  in the readme page

**Comment by blueyed** [comment]
@madhavan020985 
Do you like to provide a PR for it?
Keep in mind that it is a generic feature of Vim though and jedi-vim has options to behave in a different way.
