### ISSUE TITLE
jedi-vim failed to initialize Python

### ISSUE THREAD

**Issue by jmanoel7** [davidhalter/jedi-vim#447]
I get error:

![jedi-vim-error](https://cloud.githubusercontent.com/assets/7516658/9019073/daa6fe22-37bc-11e5-9f62-f22f3971ac9d.png)

Help-me!

**Comment by jmanoel7** [comment]
I get error:
![jedi-vim-error](https://cloud.githubusercontent.com/assets/7516658/9019071/c5aeae3e-37bc-11e5-8280-3ec64b62aead.png)

**Comment by davidhalter** [comment]
It seems strange to me that it would try to open the file from `/AppData/Local/Temp`, did you download Jedi and not install it properly?

**Comment by jmanoel7** [comment]
the jedi is installed correctly:
pip2 install -U --force-reinstall jedi

**Comment by davidhalter** [comment]
Something is really strange. Either in your Jedi/jedi-vim installation or in your VIM installation. It doesn't make a lot of sense to me that it looks something up in `/AppData/Local/Temp`. So unless you have more information and can debug this yourself, I cannot help you.

**Comment by jmanoel7** [comment]
Sorry, I use:
-> http://win-builds.org/doku.php/download_and_installation_from_windows (I choose 64 bits)
-> https://bintray.com/veegee/generic/vim_x64
-> https://www.python.org/ftp/python/2.7.10/python-2.7.10.amd64.msi
-> https://github.com/tpope/vim-pathogen
-> https://github.com/davidhalter/jedi-vim/
-> https://pypi.python.org/packages/source/j/jedi/jedi-0.9.0.tar.gz#md5=2fee93d273622527ef8c97ac736e92bd
-> https://raw.githubusercontent.com/jmanoel7/my_dot_files/master/.vimrc_windows

**Comment by aliev** [comment]
@jmanoel7 what says ```vim --version | grep python``` command?

**Comment by BimbaLaszlo** [comment]
I bet You have `set shellslash` in Your _.vimrc_. That setting causes a lot of problem - turn off in it and the plugin will work.

I met with a similar issue with lambdalisue/vim-gita#40

**Comment by rakete** [comment]
Same Problem here after installing vim+jedi on windows. I do not have set shellslash in my .vimrc. Setting noshellslash explicitly does not help.

    > vim --version | grep python
    +cmdline_info    +insert_expand   +python/dyn      +virtualedit
    +comments        +jumplist        +python3/dyn     +visual
    Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSCOPE \
      -DWINVER=0x0400 -D_WIN32_WINNT=0x0400  /Fo.\ObjCOUYHRAMD64/ /Ox /GL -DNDEBUG \
      /Zl /MT -DFEAT_OLE -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA \
     -DDYNAMIC_LUA  -DDYNAMIC_LUA_DLL=\"lua52.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON \
     -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 \
     -DDYNAMIC_PYTHON3_DLL=\"python34.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY \
     -DDYNAMIC_RUBY_VER=220 -DDYNAMIC_RUBY_DLL=\"x64-msvcr120-ruby220.dll\" \
     -DFEAT_HUGE /Fd.\ObjCOUYHRAMD64/ /Zi
     Linking: link /RELEASE /nologo /subsystem:console /LTCG:STATUS oldnames.lib kernel32.lib \
     advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64  /nodefaultlib \
     libcmt.lib oleaut32.lib user32.lib   /nodefaultlib:lua52.lib   /nodefaultlib:python27.lib \
     /nodefaultlib:python34.lib      /PDB:vim.pdb -debug

I installed vim from the same source as jmanoel7, from here:
https://bintray.com/veegee/generic/vim_x64/7.4.827/view

I used vim-plug to install vim-jedi and installed jedi with pip2 install --user jedi:

    > pip install -U --user jedi
    You are using pip version 6.0.8, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Requirement already up-to-date: jedi in c:\users\rakete\appdata\roaming\python\python34\site-packages
    
The installed python version is:

    > python --version
    Python 3.4.3

**Comment by rakete** [comment]
I just figured out that the problem seems to be vim python-mode: https://github.com/klen/python-mode

I installed that one together with jedi, when I disable it the error message disappears.

**Comment by davidhalter** [comment]
@jmanoel7 Can you please try all the feedback?

**Comment by blueyed** [comment]
Closing because of missing feedback.
See #526 for a possible duplicate / similar issue.

**Comment by kzymtn** [comment]
I am in  similar (or almost the same) situation.
After googling and reading this issue, I notice that this problem not so frequently happen (and seems quite strange).
Thus I have checked my environment again.
I note my process of searching the reason because it may help someone, while I have NOT solve this yet.
-------
0. My Environments
OS: Windows10 (64bit)
VIM: 8.0 (2016 Sep 12, compiled Jan 1 2017 13:47:58) For MSWin64bit
    Kaoriya-Ver (ja_JP-localized-Ver)
Python: Only 3.6 (but put python35.zip and python35.dll at the install directory for gVim)
has('python') == has('python3') == 1
`:python print(1)` raise E887
`python3 print(1)` works.
-------
What I tried and checked.

1. Environmental Variables
TRY: As pointed above when/where `%USERPROFILE%/AppData/Local/Temp` are injected seems the point. I set Windows environmental variables %TEMP% and %TMP% to `%USERPROFILE%/AppData/Local/Temp` . I tried delete them.

RESULT: the problem did not disappear.

2. tempname() 
CHECK: without jedi-vim, execute `:echo tempname()` with above environmental variables unset.
RESULT: `%USERPROFILE%/AppData/Local/Temp/~~~.tmp` is displayed.
---------

I don't know very the answer but I guess that via tempname() `%USERPROFILE%/AppData/Local/Temp`  is injected the process.

**Comment by kzymtn** [comment]
I tried echo debug and found what it the problem.

I add echo statements around the line 76 of `autoload/jedi.vim`as bellow.
```vim
              echo "before error"
              echo 'python -c '.shellescape('import sys; sys.stdout.write(str(sys.version_info[0]    ))')
 76         let s:def_py = system('python -c '.shellescape('import sys; sys.stdout.write(str(sy    s.version_info[0]))'))
              echo "after error"
```

then , get message
```
before error
python -c 'import sys; sys.stdout.write(str(sys.version_info[0]))'
Error found in the processing the function jedi#init_python: line 7:
Error: jedi-vim failed to initialize Python: Vim(let):E484: Could not open a file "C:/Users/k
azuya/AppData/Local/Temp/VIo415F.tmp"  (in function jedi#init_python
[3]..<SNR>57_init_python, 行 18)  
```

the process stop before echo "after error". Thus line 66 the reason at a grance.
But why temporary file comes in? It is perhaps gvim on windows specific matter (so Not jedi-vim matter).
I have not found very the answer, one which met similar trouble should search in this line (gvim on windows).

**Comment by davidhalter** [comment]
@blueyed  This seems to be a separate issue. Should @kzymtn post this as a new issue?

**Comment by blueyed** [comment]
@kzymtn 
Yes, please create a new issue.

Also add information there if `:echo system('python -c '.shellescape('import sys; sys.stdout.write(str(sys.version_info[0]))'))` works by itself.
