### ISSUE TITLE
wrong import autocomplete for second element

### ISSUE THREAD

**Issue by aliev** [davidhalter/jedi-vim#449]
it is a bug?

![](https://dl.dropboxusercontent.com/u/5837324/jedi.png)

earlier imports worked correctly

short video https://dl.dropboxusercontent.com/u/5837324/jedi.mov

P.S. when I made:

cd ~/.vim/bundle/jedi-vim/jedi/
git checkout 7b402d7 (jedi 0.8.0 release)

It works correctly. it seems something wrong in jedi library?

correct behavior: https://dl.dropboxusercontent.com/u/5837324/jedi-vim-correctly.mov

**Comment by davidhalter** [comment]
Yes it's a bug. Something has been changed there. It works if you type `Second, f` and then autocomplete. It's something that is a bit annoying to fix.

**Comment by aliev** [comment]
@davidhalter I think need to go through all the commits and see at what stage was broken this thing. I'll do this for this week

**Comment by aliev** [comment]
@davidhalter another thing. is it possible to exclude words which have already been added during the import?

**Comment by davidhalter** [comment]
@aliev You don't need to go through all the commits. It was a complete rework of Jedi's parser - a new one. We have to find ways to fix it with the current parser.

Excluding words would actually be really nice. I guess it shouldn't be too hard. :)

**Comment by aliev** [comment]
@davidhalter wow! wow! thanks!

**Comment by davidhalter** [comment]
@aliev The content above (in dropbox) disappeared. Please make it available again and I'll reopen.

**Comment by aliev** [comment]
Hi, @davidhalter ! glad to see you! :)

I've uploaded video on youtube (sorry for missed file): https://www.youtube.com/watch?v=HJ38lkJQjus&feature=youtu.be

The first minute of video - how should not be.

**Comment by davidhalter** [comment]
This is fixed in Jedi's dev branch. So no need to reopen :)
