### ISSUE TITLE
"Project not exists" error on all autocomplete

### ISSUE THREAD

**Issue by subsetpark** [davidhalter/jedi-vim#450]
With no custom jedi settings in my vimrc, I get this error whenever autocomplete is triggered (for instance, typing `self.` in any method:

`Project not exists in =jedi#complete_opened(1), create one? `

**Comment by blueyed** [comment]
Grep your Vim plugins/config for this string ("Project not exists in ") - it is not from jedi-vim.

Something else gets triggered here that shouldn't.

**Comment by subsetpark** [comment]
You're right. I was manually selecting the Rope completion function and had forgotten to pull it out in moving to Jedi. Sorry to bother.
