### ISSUE TITLE
Paramter "suggestions" only shows =`=jedi=0, =`=    (*_*object*_*)  =`=jedi=`=

### ISSUE THREAD

**Issue by rthrmt** [davidhalter/jedi-vim#459]
Hi, as the title says, when I type a function normaly vim should show me the parameters that the function gets, but I only get the String in the title. Here is a screenshot: 

![jedi](https://cloud.githubusercontent.com/assets/1927120/9453996/e0d0b706-4abe-11e5-8247-aadbd3613377.png)

I get the same result on both my PC and my Laptop, both run Linux Mint 17.2 (Laptop is a fresh install), but it does function normally on a Ubuntu 15.04 installation. 

I have installed the plugin as a git submodule in a .dotfiles folder with symlinks pointing inside. 
My steps when I setup everything are 
* cloning the repo to ~/.dotfiles
* create symlinks
* run git submodule update --init inside 
* go into jedi-vim and run git submodule update --init again

[Here](https://github.com/rthrmt/dotfiles/blob/master/vimrc) is a link to my vimrc

Did I miss something during the setup?

**Comment by montefra** [comment]
I just upgraded to the latest jedi-vim and I've noticed this issue too. Yesterday it was working fine.

If I type e.g. ``isinstance(`` in an empty line I get a the popup showing:

    =`=jedi=0, =`=              (*_*object*_*, class_or_type_or_tuple) =`=jedi=`=

The signature is correct, except for the extra ``*_*``

For the record I use [Plug](https://github.com/junegunn/vim-plug) as plugin manager

**Comment by montefra** [comment]
Also if the previous line contains a string:
![jedi_nopopup](https://cloud.githubusercontent.com/assets/1394820/9466640/9a9bbce0-4b36-11e5-8285-a6d9c08e6a85.jpg)
the popup makes think vim that the closing ``"`` are missing and all becomes of the same colour of the string:
![jedi_with_popup](https://cloud.githubusercontent.com/assets/1394820/9466659/c3ec13a6-4b36-11e5-8c16-94b0de911d60.jpg)

**Comment by davidhalter** [comment]
Does it never work? `:ver`?

**Comment by montefra** [comment]
My vim version is:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  9 2014 17:36:40)
Included patches: 1-488

If I do:
1. open vim
2. run ``PlugUpdate`` to update the plugins
3. open a python file (either as ``:e file.py`` or loading a saved ``ctrlspace`` session)
4. Jedi-vim shows that strange behaviour shown before

If I do:
1. open vim
2. open a python file (either as ``:e file.py`` or loading a saved ``ctrlspace`` session)
3. Jedi works as expected.

``Plug`` after finishing the update, reload all the plugins, and this for some reason confuses jedi.

But my setting is different from @rthrmt, so I don't know.

I try to do some bisection and see if I can figure out when the issue appeared. I'll report back soon.

**Comment by rthrmt** [comment]
[Here](http://pastebin.com/z3ET1NDx) is the vim --version.

What do you mean with does it never work? I tried it with a few functions, everyone does show that string.

**Comment by rthrmt** [comment]
I changed
>execute pathogen#infect('bundle/{}')
to
> execute pathogen#infect('~/.dotfiles/bundle/{}')
and now it works again. It is weird, that the same configuration works on Ubuntu but not in Mint 0o.

**Comment by rthrmt** [comment]
I changed
`execute pathogen#infect('bundle/{}')`
to
`execute pathogen#infect('~/.dotfiles/bundle/{}')`
and now it works again. It is weird, that the same configuration works on Ubuntu but not in Mint 0o.

**Comment by montefra** [comment]
I just tried to revert to a commit of about one year ago, and found the same issue: if I run ``PlugUpdate`` and then open a python file, the jedi pop up look weird.

But: in ``Plug`` you can delay the loading of a plugin based on the file type. If I have this option on, the problem appears. If I remove the delayed loading, then jedi works as expected in bot the cases I outlined before.

ps: I have to admit that this is the first time that I remember updating the plugins and then open a python file to the in the same session.
pss: I'll ping @junegunn on the issue.
ppss: thanks for the great plugin

**Comment by montefra** [comment]
Update: there is a [fix for my problem](https://github.com/junegunn/vim-plug/issues/272)

From the comments there, it seems that when the plugin is not loaded correctly, the setup of  the conceal doesn't work as expected.

I guess that with pathogen something remained around...

**Comment by blueyed** [comment]
The fix was to handle `syntax` and especially `after/syntax` correctly (https://github.com/starcraftman/vim-plug/commit/5cabe33eafda6b39019ee13240c30853024aa72f).

Closing since it was never an issue in jedi-vim itself, but it only triggered it.

@montefra 
Thanks for reporting and investigating!
