### ISSUE TITLE
Completion inherited method in class

### ISSUE THREAD

**Issue by ANtlord** [davidhalter/jedi-vim#463]
Good day!

I've took a look, that name of inherited method is not complete in child class. I mean, that I redefine method from parent class in child class and name of this method not completed. I think, that it is issue of jedi-vim, because when I've type `self.` after dot I got list of methods of the current class with inherited. And it seems, that getting names on redefining the method of parent classes it same task.

For clarification I'm attaching the project https://github.com/ANtlord/vim-jedi-test. It contains two files. The file main.py contains child class and in this class pointed issue places by comments. Here https://github.com/ANtlord/vim-jedi-test/blob/master/main.py#L11 and here https://github.com/ANtlord/vim-jedi-test/blob/master/main.py#L14. And base.py contains parent class `BaseProgram`.

On line 11 plugin suggest method from `BaseProgram`, but not on line 14.

It seems, that I can implement this feature, but can you help me find places in project for research.

Sorry if my english is not clear.

**Comment by blueyed** [comment]
Thanks for your report!

Without looking to closely into it, it might be an issue with Jedi itself (https://github.com/davidhalter/jedi).
Have you tried updating `jedi` to the latest version?

For going forward, it would be great to have a test case and fix for `jedi` itself probably.

**Comment by ANtlord** [comment]
Why do you think, that it is jedi issue. Jedi returns to us list of methods, and jedi-vim show them in vim, right? I get this method but only when I type dot after object, but not on redefining method in child class. Does jedi have different cases for returning methods for object and for child class?

**Comment by ANtlord** [comment]
It because jedi can suggest completions by object, but not by class, right? And we can send to it `self`, because it returns methods, that have been defined already in class. But, Is it realy problem, I think a programmer doesn't forget about pointed methods in current class.

Sorry if my english is not clear.

**Comment by davidhalter** [comment]
> Why do you think, that it is jedi issue.

Because everything that has to do with the autocompletion logic is a Jedi issue. `jedi-vim` is not responsible for anything.

--------

With your examples I have found a duplicate in Jedi, so I'm going to close this one. Please continue commenting there. https://github.com/davidhalter/jedi/issues/585
