### ISSUE TITLE
Abort smart_auto_mappings when more typing is detected

### ISSUE THREAD

**Issue by untitaker** [davidhalter/jedi-vim#465]
Since upgrading, Jedi tries to be smart and automatically types "import " when it detects that I'm writing a from-import statement.
- Unfortunately I'm usually typing faster than Jedi, so now I have two "import"s and have to delete one.
- When writing inside a string, Jedi messes up sentences that contain a from.

**Comment by davidhalter** [comment]
You can disable that. It's mentioned somewhere in the README.

**Comment by untitaker** [comment]
I couldn't find an option specific to that. Do you mean disabling completions altogether?

On 28 September 2015 16:23:52 CEST, Dave Halter <notifications@github.com> wrote:
>You can disable that. It's mentioned somewhere in the README.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/davidhalter/jedi-vim/issues/465#issuecomment-143758080

-- 
Sent from my phone. Please excuse my brevity.

**Comment by blueyed** [comment]
> When writing inside a string, Jedi messes up sentences that contain a from.

Do you have a test case for that, so we can fix it?

**Comment by blueyed** [comment]
Use `let g:jedi#smart_auto_mappings = 0` to disable it.

**Comment by untitaker** [comment]
Ahh, didn't see the edit in my email client.

Demo at https://asciinema.org/a/9us1d3jem7uw58s3cu2zg8qwb, I assume you don't mean an actual patch against your testsuite?

**Comment by montefra** [comment]
I like the new feature.
I assume that ``let g:jedi#smart_auto_mappings = 0`` disable the feature altogether.

As shown in @untitaker video, the autocompletion happens also when writing a string (within quotes). 
I deem this a bug.

If vim-jedi knows when one is in insert mode in a python string, then it should automatically disable the smart auto mapping and reactivate it (if necessary) when going out of the string.

**Comment by davidhalter** [comment]
I agree with @montefra.

**Comment by blueyed** [comment]
JFI: #469 (matching "from " everywhere) has been fixed.

**Comment by blueyed** [comment]
..and just to rant a bit: it took me more time triaging the bugs around it than fixing it when it just hit me myself.. please consider digging into the code when you experience issues with OSS projects.

I'd still liked it better if there was some test covering this, but still.

**Comment by blueyed** [comment]
The remaining issue here remains:

> Unfortunately I'm usually typing faster than Jedi, so now I have two "import"s and have to delete one.

I've looked into this briefly before, and it does not seem to be possible easily: the mapping expands the whole thing, and there's no way to abort it if more keys are being detected easily.

**Comment by montefra** [comment]
@blueyed : thank you for fixing it.

About the rant: I tend to fix stuff myself and commit when I can.
I know vimscript enough to adjust my settings, and I have not idea on how jedi works, besides the fact that it works wonderfully. I was thinking along the lines of disabling the feature when in a string or a comment and. if possible, that sounds complicated. Your solution is brilliant, but I didn't get the hint when looking at the code that does the smart auto mapping.

**Comment by ngoonee** [comment]
I just saw this, and I like the behaviour, but it seems to cause some bugs in conjunction with neocomplete. Quick summary - it doesn't just auto-complete 'import', it also auto-selects the last selection. I did a (more) detailed report here - https://github.com/Shougo/neocomplete.vim/issues/485

 I could turn it off, but as I said, I like this behaviour and would want to get it working properly.

**Comment by davidhalter** [comment]
Since `smart_auto_mappings` is now disabled by default, most people won't run into this problem. IMO it's not easily solvable and I don't have any intention to waste my life on this (so has probably nobody else). VIM is really annoying when it comes to stuff like this, so we won't fix it.

It's unfortunate that VIM doesn't support stuff like this, because it would be really nice, but I guess that's just the old editor vs. IDE disadvantage.
