### ISSUE TITLE
is there a way to show call signatures window ONLY when I press some keys

### ISSUE THREAD

**Issue by liuzhanwei** [davidhalter/jedi-vim#466]
When I set :let g:jedi#show_call_signatures=1,  the signatures window frequently hided the texts I were reading, so it is a little annoying.

It would be more convinient if this kind of windows appear below the typing position rather than above.
Or I can only turned it off by setting it 0.

But sometimes I need it.
So is there a way to show this window when I press Ctrl+space even if g:jedi#show_call_signatures=0?
How to make it come true by setting ~/.vimrc?

Thanks!

**Comment by davidhalter** [comment]
There's currently no way to do that. But you could set `g:jedi#show_call_signatures=2` (see documentation).

**Comment by blueyed** [comment]
Related: [delayed call signatures](https://github.com/davidhalter/jedi-vim/pull/436).

**Comment by liuzhanwei** [comment]
Thanks for replying.
However, the effect by setting g:jedi#show_call_signatures=2 is exactly same as 1. There is no difference. The signature window is not moved to the status area.

**Comment by davidhalter** [comment]
It should make a difference. Do you have the latest jedi-vim version (from this repository).

**Comment by liuzhanwei** [comment]
The difference now comes out after I restart the computer just now. 
Yes, g:jedi#show_call_signatures=2 is all I want.
Thank you again.

**Comment by puraminy** [comment]
Any update?
