### ISSUE TITLE
No support for python 3 under virtualenv

### ISSUE THREAD

**Issue by nicorevin** [davidhalter/jedi-vim#467]
I have no omni completion (and jump-to-declarations) for installed packages except my current working project and standard library.
Throws `Omni completion (^O^N^P) Pattern not found.`
Python 3.4 and 3.5 tested.
Works ok with python2.7-based venvs.

Jedi itself works ok. See https://github.com/davidhalter/jedi/issues/629#issuecomment-145190484

Environment:
- archlinux, linux 4.2.2, vim 7.4.884.
- ubuntu 14.04, vim 7.4.52.

**Comment by davidhalter** [comment]
What I just realized is that you probably suffer from the fact that VIM is coming with one (or two) Python versions that it works with.

You can check that versions by using `:python import sys; print(sys.path);`. This is the version that it will infer package information from, every other Python version will be ignored. 

This is probably going to be solved by https://github.com/davidhalter/jedi/issues/385.

**Comment by nicorevin** [comment]
Yes, when I reinstall vim with python3 support I can finally use jedi. This 2vs3 hell seems to have spread its lousy tentacles everywhere...

**Comment by davidhalter** [comment]
It's not really about that, VIM just binds to one version. So you're still not going to be able to use it in both 3.4 and 3.5. What we need is a client/server structure to deal with this. 

I will close, because its something we cannot really change right now.

**Comment by blueyed** [comment]
JFI: with Neovim at least it's possible to use Python 2 and 3 at the same time.
