### ISSUE TITLE
Wrong Import Autocomplete In Comments

### ISSUE THREAD

**Issue by strin** [davidhalter/jedi-vim#469]
I was typing some text in comment that includes "from xxx". Once I press spacebar, the autocomplete fills in "import". 

<img width="592" alt="screen shot 2015-10-05 at 11 33 24 am" src="https://cloud.githubusercontent.com/assets/2183232/10289776/0fcb53d4-6b55-11e5-8af7-1806763bc5e7.png">

<img width="589" alt="screen shot 2015-10-05 at 11 33 33 am" src="https://cloud.githubusercontent.com/assets/2183232/10289778/12f014be-6b55-11e5-9e22-cbb94813a25a.png">

**Comment by blueyed** [comment]
See also #465.  I'll leave it open because it's specific about comments/strings.
