### ISSUE TITLE
E117: Unknown function

### ISSUE THREAD

**Issue by tobilocker** [davidhalter/jedi-vim#471]
Jedi-Vim, GVim, Windows. `:python import jedi` gives me no error and  `:echo has("python")` returns `1`

When loading a python file i get:

        Error detected while processing C:\Program Files\vim\vim74\bundle\after\ftplugin
        \python\jedi.vim:
        line    1:
        E117: Unknown function: jedi#init_python
        E15: Invalid expression: !jedi#init_python()
        line    5:
        E121: Undefined variable: g:jedi#auto_initialization
        E15: Invalid expression: g:jedi#auto_initialization
        Error detected while processing C:\Program Files\vim\vim74\bundle\after\syntax\p
        ython.vim:
        line    1:
        E117: Unknown function: jedi#init_python
        E15: Invalid expression: !jedi#init_python()
        line    5:
        E121: Undefined variable: g:jedi#show_call_signatures
        E15: Invalid expression: g:jedi#show_call_signatures > 0 && has('conceal')

**Comment by blueyed** [comment]
> When loading a python file i get:

Do you `:edit` it in Vim or open it as an argument?
What is the output of `:JediDebugInfo`?

**Comment by tobilocker** [comment]
Yes, edit `e: python_file.py`

`JediDebugInfo?` gives me: `E492: Not an editor command:...`

So probably something wrong with my installation. Could be because i have been facing lots of more OS related problems until this point.

Thank you for the quick responce anyway!

**Comment by blueyed** [comment]
> JediDebugInfo? gives me: E492: Not an editor command:...

Then update jedi-vim first, please.. :)

**Comment by tobilocker** [comment]
Yes. Struggling with this right now. Once because it is Windows and once because our company's proxy has blocked the github port.
I will try to do so and keep you updated.
Thanks

**Comment by blueyed** [comment]
> has blocked the github port

You can the `https` URL for the Git remote then.

**Comment by blueyed** [comment]
@tobilocker 
Any update on this?

**Comment by tobilocker** [comment]
Hello I will close this because i could not locate the error since this is a company notebook and i do not have the time to continue trying to set up a vim as python editor right now. Thanks for your help!
