### ISSUE TITLE
Autocompletion not working within nested functions

### ISSUE THREAD

**Issue by aliev** [davidhalter/jedi-vim#490]
completion is not working in nested functions. example:

```
class TestClass(object):
    def first_method(self):
        def second_method():
            pass
        
        seco<C-X><C-O> # vim says: Pattern not found
        import ipdb; ipdb.<C-X><C-O> # vim says: Pattern not found
```

what do you think guys?

**Comment by davidhalter** [comment]
I'm 99% sure that this is a Jedi issue. Might even be a parser issue.

**Comment by davidhalter** [comment]
Well. I know now where it's coming from. In Jedi there's an xfailing test with an open issue in the Jedi issue tracker. So I'm closing.
