### ISSUE TITLE
fallback on case insensitive when case sensitive does not match

### ISSUE THREAD

**Issue by nicolas33** [davidhalter/jedi-vim#494]
Example:

```python
import inspect
inspect.getMemb<C-p> # fails to complete on getmembers

```
If completion is "validated", case should be fixed.

**Comment by davidhalter** [comment]
Since this is most likely a Jedi issue, can you give me a test case with Jedi itself?

**Comment by nicolas33** [comment]
I don't see a bug. I'm more requesting a feature. Unless I'm mistaken, case insensitive fallbacks is not implemented, is it?

**Comment by nicolas33** [comment]
My bad. It's in Jedi, actually. I'll try to provide a test case.

**Comment by nicolas33** [comment]
Don't know what I did but it works...
Thanks.

**Comment by davidhalter** [comment]
No problem. Thanks for taking care of it :)
