### ISSUE TITLE
Jedi plugin breaks 'iabbrev' in python buffers

### ISSUE THREAD

**Issue by HoborgHUN** [davidhalter/jedi-vim#495]
I was trying to add a few 'iabbrev' mappings to fix my usual typos, and I noticed that they don't work when I'm editing a python file. Disabling the Jedi plugin fixes it.
Tested it with vanilla vim with only vim-plug and jedi-vim enabled, and the problem still exists.

**Comment by blueyed** [comment]
Hmm, they work for me.  Are you invoking them automatically, or manually through e.g. `<C-]>`?

**Comment by HoborgHUN** [comment]
Ok, here is some more info:
`iabbrev` creates an abbreviation, that gets triggered in insert mode whenever I type in a given word. In my case, I enter the following command:
```
:iabbrev wiht with
```
After this, the expected behavior is that whenever i type `wiht` and press space in insert mode, the word is replaced with the correct spelling. And it works as expected in all buffers (even while typing this comment in vim), except inside a python buffer. Also, after further testing, it seems like it works
in a python buffer when I press enter after typing the word, but not when I press space.

I don't understand what `<C-]>` has to do with any of this. I looked it up in the help, and it is used for jumping around in the help or tags files. I am not aware of a way to trigger the abbreviations manually.

Thank you for your help in advance.

**Comment by HoborgHUN** [comment]
I forgot to mention that I'm running terminal vim on Ubuntu 14.04.3 LTS
The vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
```

**Comment by njharman** [comment]
Have same issue with inorea similar to iabbrev. terminal vim on Ubu 15.10. Broken only with jedi-vim running, only in python buffers.  Loading jedi-vim with vundle complete .vimrc https://github.com/njharman/dotfiles/blob/master/.vimrc

**Comment by moribellamy** [comment]
Same on MacVim.

https://gist.github.com/moribellamy/d9dc628f927c1b4281bd // vim --version

**Comment by supervacuo** [comment]
Same, `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  8 2016 11:53:44)`, `jedi-vim` a0c3269

Using `<return>` to expand the abbreviation works as expected, it's only `<space>` that seems problematic.

`:verbose imap <space>` shows:

```i  <Space>     *@<C-R>=jedi#smart_auto_mappings()<CR>
        Last set from ~/.dotfiles/vim/bundle/jedi.vim/ftplugin/python/jedi.vim```

This is a regression; I recently updated `jedi-vim` and started experiencing this problem. If I have more time before this is fixed I will do a `git-bisect` to find out exactly where..

**Comment by davidhalter** [comment]
This is the auto_smart_mappings feature. You guys can turn it off, if you cant.
