### ISSUE TITLE
Problems with candidates

### ISSUE THREAD

**Issue by felipefariax** [davidhalter/jedi-vim#496]
Hello!

I have 2 libs installeds via setup.py install: keras and theano.

if I type:
    from theano.<C-n> I can select any candidate normally.

but if I type:
    from keras.<C-n> I can't select any candidate...

How jedi-vim would behave in this case?

do I have to write something inside \__init__.py on keras folder?

How jedi-vim will know where to look for functions inside files?

**Comment by davidhalter** [comment]
Can you please try to import these libraries from the command line? Which Python versions are you using? Also `:ver` of vim.

**Comment by felipefariax** [comment]
Hi, @davidhalter!

I think that my problem is due to PYTHONPATH, when I manually set the PYTHONPATH to the lib it works, do you know how can I do it permanently? maybe with setup.py, I would'nt like to put on .bashrc...

I'm using neovim V0.1 and Python2.7.

**Comment by davidhalter** [comment]
I'm pretty sure that it's either not correctly installed (and not even accessible via direct imports in Python) or a version issue.

If it's the latter, you have to install it properly for the right version (you can check your vim Python version with `:python import sys; print(sys.version_info)` and `:python3 ...`).
