### ISSUE TITLE
`...` should not auto-start completion

### ISSUE THREAD

**Issue by auscompgeek** [davidhalter/jedi-vim#506]
With `g:jedi#popup_on_dot = 1`, jedi-vim starts completion after typing three consecutive dots (i.e. `...`, the Ellipsis object). This is rather disorientating, and causes issues when trying to write a function stub (e.g. in a `.pyi` file for type hinting), as pressing enter will insert the first completion (which happens to be `abs`, as Jedi decides to complete globals).

Note that `...` is a valid Python **3** expression, but is not valid Python 2 syntax.

Running latest jedi-vim HEAD (which is, as at time of writing, commit dc23f0b859d3b5c087921b68cf7cd66803ecca83), using Python 3.

Of course, `let g:jedi#popup_on_dot = 0` is a workaround, but it's a sucky workaround :smile:

**Comment by blueyed** [comment]
The popup-on-dot feature should probably check if the previous char is not a dot and/or matches Vim's `iskeyword`.

    let pos = getcurpos()
    let c = getline(pos[1])[pos[2]-2]
    if c =~ '\k'
      " do completion
    endif

**Comment by blueyed** [comment]
Apart from that, you could also use the unicode elipsis as a workaround maybe ("…").

**Comment by davidhalter** [comment]
> The popup-on-dot feature should probably check if the previous char is not a dot and/or matches Vim's iskeyword.

I agree.

**Comment by auscompgeek** [comment]
> The popup-on-dot feature should probably check if the previous char is not a dot and/or matches Vim's `iskeyword`.

Sounds sensible. Although, the fact that `.` and `..` alone don't trigger the popup, but `...` does, intrigues me. What's causing that?

> Apart from that, you could also use the unicode elipsis as a workaround maybe ("…").

Probably not:

```pytb
  File "<stdin>", line 1
    …
    ^
SyntaxError: invalid character in identifier
```

**Comment by davidhalter** [comment]
> Sounds sensible. Although, the fact that . and .. alone don't trigger the popup, but ... does, intrigues me. What causes that?

Oh probably a Jedi issue. Actually `...` shouldn't trigger a completion, but `....` should! :)

**Comment by davidhalter** [comment]
This is actually not a Jedi issue anymore. After an elipsis there's certainly the possibility of something like `or` (even without spaces):
```
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.9.0
>>> ...or...
Ellipsis
>>> 
```

However the completion shouldn't be triggered by popup_on_dot.

**Comment by davidhalter** [comment]
Fixed in Jedi (master). Now no completions are possible anymore after ... .
