### ISSUE TITLE
How to make jedi and python-mode work together?

### ISSUE THREAD

**Issue by crazy-canux** [davidhalter/jedi-vim#508]
python-mode can use rope to complete and use pylint pep8 pep257 mccabe and pyflakes  to check the code.
How to make jedi to it the same way?

**Comment by blueyed** [comment]
I  would disable some of python-mode's options, e.g. the completion.

**Comment by davidhalter** [comment]
I agree. Or what I'm doing: I use flake8 with syntastic plus Jedi.

**Comment by blueyed** [comment]
FWIW, here are my python-mode settings: https://github.com/blueyed/dotfiles/blob/7fd3569816a39ea4871b86f930ac39ad03eb10f2/vimrc#L1555-L1565 - I am not sure if I am using anything from it still though.

**Comment by crazy-canux** [comment]
Looks enable everything in pymode and jedi works.

**Comment by crazy-canux** [comment]
I use python-mode to check the syntax.
And use jedi for complete.
