### ISSUE TITLE
Rename variables with let g:jedi#use_tabs_not_buffers = 1 causes the variable in current file to be left unchanged

### ISSUE THREAD

**Issue by srinathgs** [davidhalter/jedi-vim#513]
With `let g:jedi#use_tabs_not_buffers = 1`, I tried to do `<leader>r` on a variable name.

It replaces all the occurrences of the variable in all the files and then the file from which the original replace variable was invoked is reset to the last saved state. I mean the variable name is restored to the old variable name in the file from which the rename variable command was invoked.

This happens only with use_tabs_not_buffers set to 1

**Comment by blueyed** [comment]
Can you reproduce this using a single file only, or does it involve changing in multiple files?

A step by step test case would be nice to have, then it could be transformed into a real test also.

**Comment by srinathgs** [comment]
@blueyed It occurs with multiple files

**Comment by srinathgs** [comment]
- set `let g:jedi#use_tabs_not_buffers = 1` in your vimrc
- open a file in vim
- go to a `class` definition and keep the name of the `class` under cursor
- press `<leader>r`
- this makes vim go into insert mode after removing the name of the `class`
- type in the required name
- exit the insert mode by pressing `ESC`
- `jedi-vim` opens new tabs for the files where this `class` is `import`ed
- you can see that the class name under the cursor is restored to the original name but all the other files that `import` this `class` has the new name

**Comment by srinathgs** [comment]
@blueyed It works with a single file. but if the class is being imported into other file, then the original file is left untouched

**Comment by davidhalter** [comment]
This has been an issue for a long time in Jedi, the relevant issue is https://github.com/davidhalter/jedi/issues/1047.
