### ISSUE TITLE
async and lambda brakes autocompletion

### ISSUE THREAD

**Issue by akhilman** [davidhalter/jedi-vim#514]
```python
async def func(fu=None):
    return fu(True)
async def do():
    await func(fu=lambda x: x is False)
```
this code brakes auto-completion, seems to be jedi parser issue.
removing async/await or replacing lambda by real function bring auto-completion back.

**Comment by davidhalter** [comment]
Jedi has no 3.5 support, yet.

**Comment by davidhalter** [comment]
I don't think Jedi properly supports async, yet. However we got rid of the errors.
