### ISSUE TITLE
vim-jedi adding artifacts to previous line

### ISSUE THREAD

**Issue by last-partizan** [davidhalter/jedi-vim#515]
When i try to omni-complete `return unicode(self.attrname)` jedi adds artifacts to previous line.
This happens if complete found something and if not found anything to complete.
Seems like this happens only if completing python functions (like unicode/str/list/int), and does not with any other - like mark_safe from django.

![2016-01-05 14-54-08](https://cloud.githubusercontent.com/assets/301015/12115898/76c2f900-b3be-11e5-8a40-3a7e3a1919e4.png)

**Comment by davidhalter** [comment]
`:ver`? List of plugins? Are you using any way of syntax modifying or color schemes?

**Comment by Shtucer** [comment]
https://github.com/davidhalter/jedi-vim/issues/459

**Comment by last-partizan** [comment]
[scriptnames.txt](https://github.com/davidhalter/jedi-vim/files/78518/scriptnames.txt)
[ver.txt](https://github.com/davidhalter/jedi-vim/files/78519/ver.txt)

here is my scriptnames and version.

I'm using colorscheme wombat256mod. And what is "syntax modifying"?

**Comment by last-partizan** [comment]
This happens only if
```
let g:jedi#show_call_signatures = "2"
```

**Comment by blueyed** [comment]
@last-partizan 
Can you provide the file where this happens?
It's likely caused by some pattern mismatch with regard to the concealing magic that gets done.

**Comment by last-partizan** [comment]
```
class TestClass(object):

    def __unicode__(self):
        return unicode(self.<start autocomplete here>)
```

Here it is

**Comment by davidhalter** [comment]
@last-partizan Can you try to remove the colorscheme? Also try to remove everything other than jedi-vim and check again.

**Comment by last-partizan** [comment]
Okay, i just moved my ~/.vim ~/.vimrc ~/.gvimrc and removed any plugins
With clean vimrc it looks like this
![2016-01-07 13-40-59](https://cloud.githubusercontent.com/assets/301015/12169843/72fa0f16-b544-11e5-9a13-9d06e6c2e8ac.png)

After i close bracket - that strange lines are removed

![2016-01-07 13-47-40](https://cloud.githubusercontent.com/assets/301015/12169941/3c11216e-b545-11e5-8a6c-4d1f4ce2b6f5.png)

Now i will try to find what causes problem.

**Comment by last-partizan** [comment]
Ok, i found it. It's not a plugin, it's 

```
let g:jedi#show_call_signatures = "2"
```
(or 3 or everything that is not 0 and 1, result is the same)

**Comment by blueyed** [comment]
@last-partizan 
I could not reproduce it using both jedi-vim master and the 0.7.0 tag.

I have tried neovim master and Vim 7.4.944 (which seems to be the same as with you).

But I have not tried it using a minimal vimrc, so some of my/your options might be involved.

**Comment by last-partizan** [comment]
@blueyed can you post your vimrc?

**Comment by blueyed** [comment]
@last-partizan 
It's probably better to start from a minimal one..
But FWIW it's at https://github.com/blueyed/dotfiles/blob/master/vimrc - but not in sync with my local one.

**Comment by davidhalter** [comment]
No reaction and I'm pretty sure this simple case doesn't trigger that bug. Probably an outdated library.
