### ISSUE TITLE
Did jedi-vim support pip installed package?

### ISSUE THREAD

**Issue by hacpai** [davidhalter/jedi-vim#518]
I install python with brew and python site-package directory is /usr/local/lib/python2.7/site-packages.

I try go to method definitions using `<leader>d`.

But it prompt:

```
jedi Couldn't find any definitions for this
```

**Comment by davidhalter** [comment]
Well, basically it supports it, but if the Python version of vim doesn't match it, it won't work. It also might not work for certain packages, because they are too complicated.

**Comment by hacpai** [comment]
@davidhalter Thanks. I update vim and it works.
