### ISSUE TITLE
VisualStudio hack not working on jed-vim

### ISSUE THREAD

**Issue by xuboying** [davidhalter/jedi-vim#521]
There is a hack for intelligence in VS that you can write code in following way
```python
import wx
    def rtc_OnChar(self, e):
        if False:
            e = wx.KeyEvent
        e.  <---------Here the information will be popup
```
in jedi-vim
The same way does not work, nothing will popup 
If we can not use the VS hack, how could we easily get the variable e be recognized as wx.KeyEvent
(All hack can be removed by regex before published)

**Comment by davidhalter** [comment]
Well this does not work, because if False will never be evaluated (which makes sense usually).

Once https://github.com/davidhalter/jedi/pull/664 is merged, you can do it with simple PEP 484 type hint comments.
