### ISSUE TITLE
Let jedi-vim to be less complaisant

### ISSUE THREAD

**Issue by chkur** [davidhalter/jedi-vim#524]
I don't want jedi-vim to insert word "import" on import string. I want write it myself. Also it inserts on copypaste. And I get something like "from PIL import import Image".
I didn't find possibility to disable this option.

**Comment by davidhalter** [comment]
You didn't read the README well enough. `g:jedi#smart_auto_mappings` is your friend.
https://github.com/davidhalter/jedi-vim/blob/master/doc/jedi-vim.txt
