### ISSUE TITLE
Errors with Python 2.6: ValueError: zero length field name in format

### ISSUE THREAD

**Issue by prologic** [davidhalter/jedi-vim#525]
I often get this error when trying to "goto the definition" of some attribute/function/variable.
```#!python
Traceback (most recent call last):
  File "/home/prologic/.vim/bundle/jedi-vim/jedi_vim.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/home/prologic/.vim/bundle/jedi-vim/jedi_vim.py", line 247, in goto
    echo_highlight("Couldn't find any definitions for this.")
  File "/home/prologic/.vim/bundle/jedi-vim/jedi_vim.py", line 91, in echo_highlight
    msg.replace('"', '\\"')))
ValueError: zero length field name in format
```

Could this possibly be that jedi-vim is using my system's Python 2.6.6 here at all?

**Comment by blueyed** [comment]
> Could this possibly be that jedi-vim is using my system's Python 2.6.6 here at all?

Yes, this is not compatible with Python 2.6.

It would not be hard to use `{0}` instead, but apparently you do not want Python 2.6 to be used after all?!

According to https://github.com/davidhalter/jedi-vim#installation Python 2.6 should be supported - so there's a bug here, too (or the docs on the requirements need to be changed).

**Comment by prologic** [comment]
Since I've done nothing special to make jedi-vim use Python 2.6 or 2.7 and jedi-vim states it supports 2.6; yes; we should fix this bug :)
