### ISSUE TITLE
jedi-vim showing =`=jedi= ... =`=jedi`=`

### ISSUE THREAD

**Issue by strin** [davidhalter/jedi-vim#528]
Normally it should show hints like arglists for f(arglist), 
but sometimes it shows weird  =`=jedi= (arglist) =`=jedi`=`.

**Comment by blueyed** [comment]
See also #515.

Can you provide a test case to reproduce it?

**Comment by davidhalter** [comment]
Closing because it's a duplicate. However, please comment if you can reproduce it with a test case.

**Comment by strin** [comment]
issue solved. jedi-vim seems to have a conflict with my syntax file.
i am using the syntax from pymode.
