### ISSUE TITLE
vim python dynamic support?

### ISSUE THREAD

**Issue by benhoff** [davidhalter/jedi-vim#529]
Hey my vim package maintainer started compiling vim with dynamic support for python 2 and python 3. So a casual check of `:version` returns `+python/dyn +python3/dyn`. If I try to open up a python file, I get a "please install Jedi if you want to use jedi_vim" error. 

Using a python3 interperter shows I have verified that I can import jedi, so I think that vim is trying python 2 first.

Any way around this issue? Is there a way to specify the python version or something?

**Comment by davidhalter** [comment]
There is, read the documentation.

**Comment by benhoff** [comment]
I missed it even after scanning the docs multiple times. But I'm not a through reader.
Eventual found the answer [here](http://stackoverflow.com/questions/29835076/need-some-vim-advice-on-switching-to-python3).

`let g:jedi#force_py_version = 3`

Is the answer if anyone else has a similar problem and stumbles here.

**Comment by davidhalter** [comment]
Sorry for not giving it to you directly, but I sometimes struggle looking it up myself :)

**Comment by benhoff** [comment]
no worries, you helped me find the answer which I appreciate tremendously!
