### ISSUE TITLE
Jedi pydoc is appearing in nerstree_tabs's vertical split.

### ISSUE THREAD

**Issue by Narengowda** [davidhalter/jedi-vim#533]
I use split screen with the help of nerdtree, on autocompletion function doc is appearing in vertical spilt.
If I dont use split screen function doc will be appeared in horizontal split screen.

let g:jedi#show_call_signatures = "0"

Not helping

**Comment by davidhalter** [comment]
What would you want instead?

**Comment by davidhalter** [comment]
No answer.
