### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by isaiah** [davidhalter/jedi-vim#535]
Could you please make a new release? So we can update the package for Archlinux. As you see it's been locked to `0.7.0`.

https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/vim-jedi

**Comment by anatol** [comment]
The current 0.7.0 release does not work in vim compiled with `+python/dyn`. It would be great to get a new release with python3/dyn support.

Here is related Arch Linux bug report
https://bugs.archlinux.org/task/47500#comment143106

**Comment by davidhalter** [comment]
@blueyed I'm actually quite happy with it currently. I will just tag the commit I'm on.

**Comment by davidhalter** [comment]
Yep, I'm really sorry for ignoring this for so long. At times I have just forgotten it and at other times jedi-vim wasn't working properly.

@anatol I'm still not sure if +python/dyn is working properly. There's still a pretty big issue about it afaik.

**Comment by anatol** [comment]
@davidhalter Arch users reported that current head works much better than 0.7.0 release. So thanks for releasing 0.8.0 - it will make our users happier.

If there are any additional issues we'll report you back.

**Comment by blueyed** [comment]
Thanks!

You've missed "only" https://github.com/davidhalter/jedi-vim/commit/8215b220f965b79909cbd591dc427d22e9fd206c btw, but should be fine - at least for Arch.. :D

**Comment by davidhalter** [comment]
I missed the commit intentionally, since I haven't tested it locally. And I think we were fine without it for a long time :-)
