### ISSUE TITLE
Jedi-vim on raspberry pi

### ISSUE THREAD

**Issue by kapsharma** [davidhalter/jedi-vim#538]
Hi,

I tried to install jodi-vim on raspberry pi. I don't code that often but when I do, I like the features supported by jodi-vim and I have used it before on my other linux systems. I followed your guide to install using vundle but it just doesn't to work. I am wondering if some one has installed it on raspberry pi os. 

It will be great help if you have any pointers.

Cheers

**Comment by davidhalter** [comment]
Sorry. Apparently nobody seems to be able to help :( I hope you find a way to deal with this some time.
