### ISSUE TITLE
jedi-vim affects other settings in .vimrc

### ISSUE THREAD

**Issue by ramidas** [davidhalter/jedi-vim#539]
When I added `execute pathogen#infect()` to my .vimrc command `set tabstop=4` lost its power. I.e. the tabs are set to default 8 instead of 4 chars. I can still manually write it in vim command line but I don't want to do this every time. 

my `.vimrc`:

```
execute pathogen#infect()                                                       

set tabstop=4
set shiftwidth=4
set number
set cursorline
hi CursorLine cterm=NONE ctermbg=darkgrey guibg=darkgreyo
hi LineNr ctermfg=gray
hi CursorLineNr ctermfg=white

map <F1> :echo @%<CR>
map <F2> :r! date "+\%Y-\%m-\%d - \%H:\%M"<CR>
map <F7> :tabp<CR>
map <F8> :tabn<CR>
map <F9> i<!--<Esc>
map <F10> i--><Esc>
```

vim version
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 21 2015 12:30:04)
Included patches: 1-712
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
```

I'm using this plugin: https://github.com/davidhalter/jedi-vim

**Comment by davidhalter** [comment]
@ramidas You have to try to debug this yourself. Jedi-vim itself doesn't affect the tabstop. 

@blueyed What's the command again to find where a value comes from?

**Comment by blueyed** [comment]
Try `:verbose set tabstop?`.

**Comment by davidhalter** [comment]
No reaction.
