### ISSUE TITLE
argument suggestions  in window splits with long lines do unexpected word-wrapping

### ISSUE THREAD

**Issue by dwlocks** [davidhalter/jedi-vim#540]
When the code has these attributes:
- vertically split windows
- 3 or more indentation levels, or long-ish lines.
- format strings

Then jedi-vim does some unexpected word wrapping for the popups (pic 1), but only while parens are unmatched (pic 2).  When the bug is induced, lines that are not as long will also show the strange popup-wrapping (pic 3).  But if the long lines are not there, the unmatched parens on the shorter line will not show the funny wrapping.
![jedi-popup-1](https://cloud.githubusercontent.com/assets/68471/12935738/c6dbdfa0-cf5d-11e5-98fa-cdf1553a670f.png)
![jedi-popup-2](https://cloud.githubusercontent.com/assets/68471/12935740/cba53f7c-cf5d-11e5-919c-504633c717db.png)
![jedi-popup-3](https://cloud.githubusercontent.com/assets/68471/12935742/d09f1f70-cf5d-11e5-9b91-39f84bae24a3.png)

**Comment by dwlocks** [comment]
version info:

    :ver                                                                                       
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)                         
    Included patches: 1-52                                                                     
    Modified by pkg-vim-maintainers@lists.alioth.debian.org                                    
    Compiled by buildd@                                                                        
    Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):                       
    +acl             -ebcdic          +localmap        +printer         +title                 
    +arabic          +emacs_tags      +lua             +profile         +toolbar               
    +autocmd         +eval            +menu            +python          +user_commands         
    +balloon_eval    +ex_extra        +mksession       -python3         +vertsplit             
    +browse          +extra_search    +modify_fname    +quickfix        +virtualedit           
    ++builtin_terms  +farsi           +mouse           +reltime         +visual                
    +byte_offset     +file_in_path    +mouseshape      +rightleft       +visualextra           
    +cindent         +find_in_path    +mouse_dec       +ruby            +viminfo               
    +clientserver    +float           +mouse_gpm       +scrollbind      +vreplace              
    +clipboard       +folding         -mouse_jsbterm   +signs           +wildignore            
    +cmdline_compl   -footer          +mouse_netterm   +smartindent     +wildmenu              
    +cmdline_hist    +fork()          +mouse_sgr       -sniff           +windows               
    +cmdline_info    +gettext         -mouse_sysmouse  +startuptime     +writebackup           
    +comments        -hangul_input    +mouse_urxvt     +statusline      +X11                   
    +conceal         +iconv           +mouse_xterm     -sun_workshop    -xfontset              
    +cryptv          +insert_expand   +multi_byte      +syntax          +xim                   
    +cscope          +jumplist        +multi_lang      +tag_binary      +xsmp_interact         
    +cursorbind      +keymap          -mzscheme        +tag_old_static  +xterm_clipboard       
    +cursorshape     +langmap         +netbeans_intg   -tag_any_white   -xterm_save            
    +dialog_con_gui  +libcall         +path_extra      +tcl             +xpm                   
    +diff            +linebreak       +perl            +terminfo                               
    +digraphs        +lispindent      +persistent_undo +termresponse                           
    +dnd             +listcmds        +postscript      +textobjects                            
       system vimrc file: "$VIM/vimrc"                                                         
         user vimrc file: "$HOME/.vimrc"                                                       
     2nd user vimrc file: "~/.vim/vimrc"                                                       
          user exrc file: "$HOME/.exrc"                                                        
      system gvimrc file: "$VIM/gvimrc"                                                        
        user gvimrc file: "$HOME/.gvimrc"                                                      
    2nd user gvimrc file: "~/.vim/gvimrc"                                                      
        system menu file: "$VIMRUNTIME/menu.vim"                                               
      fall-back for $VIM: "/usr/share/vim"                                                     
    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk
    -2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cair
    o -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/us
    r/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I
    /usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz   -pthread -DORBIT2=1
     -D_REENTRANT -I/usr/include/libgnomeui-2.0 -I/usr/include/libart-2.0 -I/usr/include/gconf/
    2 -I/usr/include/gnome-keyring-1 -I/usr/include/libgnome-2.0 -I/usr/include/libbonoboui-2.0
     -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/
    usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/
    dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x8
    6_64-linux-gnu/glib-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/libbonobo-2.0 -I/us
    r/include/bonobo-activation-2.0 -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/incl
    ude/gail-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/atk-1.0 -I/usr
    /lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gio-unix-2.0/ -I/
    usr/include/pixman-1 -I/usr/include/libpng12     -g -O2 -fstack-protector --param=ssp-buffe
    r-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1 -D_LARGEFILE64_SOURCE=1                  
    Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,
    -E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-
    2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.
    0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype     -lgnomeui-2 -lSM -lICE -lbonoboui-2 
    -lgnomevfs-2 -lgnomecanvas-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lar
    t_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -l
    gdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lfreetype -lgconf-2 -lgthread-2.0 -lgmodul
    e-2.0 -lgobject-2.0 -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinf
    o -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector 
    -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/py
    thon2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dyna
    mic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthre
    ad -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib

**Comment by davidhalter** [comment]
Same issue as #493. We are trying to get rid of changing the buffer for this feature and are trying to use floating windows.
