### ISSUE TITLE
Please consider remove jedi folder so we can use git subtree function for jedi intergation

### ISSUE THREAD

**Issue by xuboying** [davidhalter/jedi-vim#541]
After trying git subtree I feel it's more convenint to get jedi updated

for example: 
git subtree add --prefix bundle/jedi-vim https://github.com/davidhalter/jedi-vim.git master --squash
git subtree add --prefix bundle/jedi-vim/jedi https://github.com/davidhalter/jedi.git master --squash
git subtree pull --prefix bundle/jedi-vim/jedi https://github.com/davidhalter/jedi.git linter --squash

**Comment by davidhalter** [comment]
Is there a good read on subtree vs submodules?

**Comment by xuboying** [comment]
Sorry, I'm new to subtree and submodules, I know them beasue I was seeking methods for handling 3pp repos and many documents recommaned to use subtree instead of submodules
However this issue is about letting users to update the jedi by themselves, as I feel users are prone to update jedi instesd of jedi-vim as jedi-vim is a more stable project(unless changes happen in vim).
This is just a recommandation, you may have your own consideration :)
A yield way maybe allow a user specified folder(as seeking path), for whom like to download the the latest module and still allow other users use the buildin jedi. (make sure give a debug function in jedi-vim to show which jedi is using)

**Comment by davidhalter** [comment]
> However this issue is about letting users to update the jedi by themselves, as I feel users are prone to update jedi instesd of jedi-vim as jedi-vim is a more stable project(unless changes happen in vim).

This is wrong. I'm pretty sure that jedi-vim is less stable.

> this issue is about letting users to update the jedi by themselves

You can do this. Just update the submodule.

----
From http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/:

> The sub-project’s code is available right after the clone of the super project is done.

This is the only actual advantage I see. While it's a big one I also see the issue that Jedi would get tied closer to jedi-vim. I don't like that. Therefore I won't do it, unless a git expert tells me why this would make sense. (or that subtrees are indeed much better than submodules).

~ Dave
