### ISSUE TITLE
Error on vim start with latest from master

### ISSUE THREAD

**Issue by WaltHP** [davidhalter/jedi-vim#542]
I get this every time I start vim now after pulling the latest jedi-vim

Error: jedi-vim failed to initialize Python: jedi#setup_py_version: Vim(pyfile):Traceback (most recent call last): (in function jedi#init_python..<SNR>44_init_python..jedi#setup_py_version, line 18)

**Comment by blueyed** [comment]
Might be #522 or #526 possibly, and needs more investigation from your side, because the error is missing the real info.  This is really unfortunate, but nobody took the time to fix/improve the error handling.

**Comment by melta** [comment]
I have similar issue on vim start:

Error: jedi-vim failed to initialize Python: jedi#setup_py_version: Vim(py3file):ERROR:root:code for hash md5 was not found. (in function jedi#init_python..<SNR>93_init_python..jedi#setup_py_version, line 18)

Tested with python-3.5.0 and system python -3.4

**Comment by melta** [comment]
Please let me know how can I provide you more information.

**Comment by blueyed** [comment]
It would be helpful to investigate (debug the vim plugin) and improve the error message, too.
There are 2 popular issues IIRC.

**Comment by melta** [comment]
I have no idea why, but after I recompiled vim with system python 3.4.3 above problem was gone. But I still have error if I use any python3 (3.3.6, 3.4.4, 3.5.0, 3.5.1 compiled by myself). If I import jedi directly from any python3 compiled by myself it works. It breaks only if I try to import jedi from vim command window (:py3 import jedi)

P.S I have no problems with python2 (2.7.10, 2.7.11) and it doesn't matter if I use compiled python2 version or system one. It is weird.

**Comment by melta** [comment]
Forgot to add trace-back:
`:py3 import jedi`  
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/melta/tmp/python/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/home/melta/tmp/python/lib/python3.5/site-packages/jedi/api/__init__.py", line 16, in <module>
    from jedi.parser import Parser, load_grammar
  File "/home/melta/tmp/python/lib/python3.5/site-packages/jedi/parser/__init__.py", line 21, in <module>
    from jedi.parser import tree as pt
  File "/home/melta/tmp/python/lib/python3.5/site-packages/jedi/parser/tree.py", line 39, in <module>
    from jedi import cache
  File "/home/melta/tmp/python/lib/python3.5/site-packages/jedi/cache.py", line 23, in <module>
    import shutil
  File "/home/melta/tmp/python/lib/python3.5/shutil.py", line 13, in <module>
    import tarfile
  File "/home/melta/tmp/python/lib/python3.5/tarfile.py", line 48, in <module>
    import struct
  File "/home/melta/tmp/python/lib/python3.5/struct.py", line 13, in <module>
    from _struct import *
ImportError: /home/melta/tmp/python/lib/python3.5/lib-dynload/_struct.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyByteArray_Type

**Comment by davidhalter** [comment]
@melta Hmm, but this looks like a Python issue to be honest. Probably something's wrong with your Python 3.5 installation. `import shutil` is something that should not fail, because it's a builtin.

Maybe you try  `python3.5 -c 'import shutil'` once?!

**Comment by melta** [comment]
@davidhalter thank you for your reply.

> Maybe you try python3.5 -c 'import shutil' once?! Or in vim :python3 import shutil
Both imports work fine.

It looks like it is something with python and vim setup. All my python2 + vim setups work fine. But python3+vim doesn't.  I can import jedi directly in python3 but I get error when I try to import jedi under vim. The same thing happens when I try to import ssl under vim. But when I import ssl directly in python3 it works. I'm using Fedora 23 and already tested all kinds of vim compilation parameters and can't get it to work with python3. 

Anyway, thank you for your help and your time!

**Comment by davidhalter** [comment]
Closing, because I'm pretty sure this as an issue with Python/VIM and not Jedi.
