### ISSUE TITLE
Autocompletion list incomplete

### ISSUE THREAD

**Issue by DanHam** [davidhalter/jedi-vim#543]
Firstly, thanks for a great plugin. However, I seem to be having a few issues with only a partial list of possible completions being displayed:

![vim_socket](https://cloud.githubusercontent.com/assets/4364798/13445329/6eecbf74-e003-11e5-9d34-db07998c18d8.png)

The full list of possible completions seems to be displayed when using bpython so I believe my python set up is working OK 
![bpython_socket](https://cloud.githubusercontent.com/assets/4364798/13445347/8a5d02d2-e003-11e5-91aa-ede24bbde2dd.png)

First my vim --version output:
`dan@smudge ~ $ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 27 2016 00:55:03)
MacOS X (unix) version
Included patches: 1-1129
Compiled by MacPorts
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
-cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/opt/local/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -I/opt/local/include -DMACOS_X_UNIX  -pipe -Os -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -o vim        -lm  -lncurses -liconv -lintl -framework Cocoa`

I have seen a similar post/issue and tried to duplicate the steps you suggested to help diagnose the issue. I've dumped the output in a text file as I was having some issues with formatting

[debug.txt](https://github.com/davidhalter/jedi-vim/files/153839/debug.txt)

**Comment by davidhalter** [comment]
There's a `setattr` call in `socket._socketobject.__init__`. We could probably support this in the far away future, but unless you do it yourself (within Jedi), this is just too hard (it's easy in bpython, because there you just need to use `dir()`. I'm closing, because it's something that is mentioned in the Jedi docs.

However, I don't have a problem if you try to implement this :) It just won't be easy :)
