### ISSUE TITLE
Autocompletion isn't working. How can we help jedi?

### ISSUE THREAD

**Issue by martin-damien** [davidhalter/jedi-vim#544]
I have this simple example:

```python
#! /usr/bin/env python3

import curses

# Start
stdscr = curses.initscr()
curses.noecho()
curses.cbreak()

try:
    stdscr.border(0)
    stdscr.addstr(12,25, "Test")
    stdscr.refresh()
    stdscr.getch()
except Error:
    pass

# End
curses.nocbreak()
curses.echo()
curses.endwin()
```

Autocompletion doesn't work for `stdscr` (but works well for curses and my own classes).

In PHP you can add a comment to help autocompletion:

```php
/** @var \DateTime $myDate */
```

This explain that `$myDate` is a `\DateTime` instance, and so, autocompletion can work correctly (PHPStorm, Vim with Padawan, ...).

Is there such a thing with Jedi? Or could it be implemented? I googled but found nothing.

**Comment by blueyed** [comment]
See http://jedi.jedidjah.ch/en/latest/docs/features.html#type-hinting.

For the "linter" branch (of jedi, not jedi-vim) it will also use function annotations (PEP 484), e.g.

```
def test_foo(User: foo):
    foo.
```

**Comment by davidhalter** [comment]
PEP384 support is pretty good already. Jedi even understands  comments (however in this issue this probably wouldn't help, because we're talking about builtin stuff that you normally cannot access).

`curses` is actually not that easy to understand. If you want you can create a fake `_curses` (note the underscore) module in `jedi/evaluate/compiled/fake/_curses.pym` to help Jedi.

**Comment by martin-damien** [comment]
I tested this code with PyCharm and curses has no completion too.
It is a good thing that Jedi can manage this kind of old C based libraries with fakers.

As I'm totally new to curses I can't promise you that I'll provide such a faker for Jedi. But when I'll be handy with it, I'll do.

**Comment by davidhalter** [comment]
It's almost impossible to get to the curses window objects without creating one. This basically means that there will just not be any completions for curses. Sorry.
