### ISSUE TITLE
Rename fails for specific names

### ISSUE THREAD

**Issue by spapanik** [davidhalter/jedi-vim#545]
Reformat does not  work with specific names

```python
def foo():
    bar = 1
    return bar
```

If I try to rename `bar` to `output` then I get `Jedi did 0 renames!`, although I can rename `bar` to almost any other word.

**Comment by blueyed** [comment]
Fixed in https://github.com/davidhalter/jedi-vim/commit/0d613b5cf976eb23b2be24880d228578039eed59.
Thanks, @mozbugbox!
