### ISSUE TITLE
completion fallback to local file words

### ISSUE THREAD

**Issue by nicolas33** [davidhalter/jedi-vim#546]
Is there a way to get jedi-vim fallback to local file completion?

**Comment by blueyed** [comment]
I think that's more the part of completion plugins like https://github.com/Shougo/deoplete.nvim, YCM etc.

After all, jedi-vim only sets up explicit mappings for completion (`<C-space>`, `.` and `from foo `) - and has no "auto-completion as you type".

You probably just want to use `<C-p>` etc (Vim's native completion) in those cases?!
Check out `:h ins-completion`.

**Comment by nicolas33** [comment]
Yes. In vim, I was stucked because when jedi-vim completion is invoked I could not use `<c-p>` anymore. `<c-x><c-i>` works as expected.

I would still expect `<c-p>` to complete with search backwards in file, though.

Do I misunderstand something about how `<c-p>` is supposed to work?

**Comment by nicolas33** [comment]
> I would still expect <c-p> to complete with search backwards in file, though.

...once jedi-vim completion was started.

**Comment by blueyed** [comment]
Once there's a popup-menu, `<c-p>` behaves differently than when invoking completion through it, and will typically select the previous entry of the current list (which is omni completion (`<c-x><c-o>`), triggered by jedi-vim).

I hope that answers your question(s)?!

**Comment by blueyed** [comment]
> I would still expect <c-p> to complete with search backwards in file, though.
> ...once jedi-vim completion was started.

That's what `<c-e><c-p>` might give you: `<c-e>` to stop completion, and then invoke the basic `<c-p>` (or `<c-x><c-i>`) completion.

**Comment by nicolas33** [comment]
Alright! Thank you much Daniel for this learning session! :smiley:
