### ISSUE TITLE
airline colorschema disappears after jedi finishing codes indication, how to fix it?

### ISSUE THREAD

**Issue by xros** [davidhalter/jedi-vim#550]
the original issue was here: https://github.com/vim-airline/vim-airline/issues/1100

After removing jedi-vim, the airline shows up back. So i guess it's about jedi-vim, which might change the colorschema of airline somehow.

don't know where it affects that.

F.Y.I. the jedi-vim works like a charm, it's just jedi-vim does not work well with airline  https://github.com/vim-airline/

**Comment by davidhalter** [comment]
I just grepped for color and couldn't find anything. I doubt that we're doing anything with the color scheme.

**Comment by xros** [comment]
@davidhalter Hi.  I found a clue yesterday: I found that the airline would come back if I jump between different windows in Vim using <kbd>Ctrl</kbd><kbd>w</kbd><kbd>n</kbd>   start a new window, jump out and jump back...

I think this is because the jedi does not release the window focus or vim-airline does not capture the latest window. 

after jedi giving grammar guides:

![snapshot209](https://cloud.githubusercontent.com/assets/2342412/13938814/3f7a4808-f00a-11e5-8959-36da2ed0b545.png)

after *re-sizing* my terminal or *jumping* windows between main window or NERDTree.

![snapshot210](https://cloud.githubusercontent.com/assets/2342412/13938832/6eb69342-f00a-11e5-8e2c-c98412a27e93.png)

They say airline support automatically re-sizing

**by the way**, how to debug this?

**Comment by xros** [comment]
this problem was solved. 
here's the reference.
https://github.com/vim-airline/vim-airline/issues/78#issuecomment-21161085

and here's my vim-airline settings in .vimrc

```
" airline settings                                                                                                
let g:airline#extensions#tabline#enabled = 1                                                                      
let g:airline#extensions#tabline#left_sep = ' '                                                                   
let g:airline#extensions#tabline#left_alt_sep = '|'                                                               
let g:airline_powerline_fonts = 1                                                                                 
let g:airline_exclude_preview=1    
```

thank you @davidhalter :smile:

**Comment by davidhalter** [comment]
Thanks for debugging :)
