### ISSUE TITLE
Broken go-to command / "g:jedi#use_splits_not_buffers value is not correct"

### ISSUE THREAD

**Issue by yevhen-m** [davidhalter/jedi-vim#553]
`g:jedi#use_splits_not_buffers value is not correct, valid options are: winwidth,bottom,top,left,right`

I have this error, everything worked fine yesterday.
I want jedi to open definitions in the current window, this is default behaviour according to docs.

Ubuntu 14.04
NVIM 0.1.3-dev

My jedi settings:
```
let g:jedi#completions_enabled = 0
let g:jedi#auto_initialization = 0
let g:jedi#smart_auto_mappings = 0
let g:jedi#auto_vim_configuration = 0
nnoremap <silent> <leader>g :call jedi#goto()<CR>
```

**Comment by blueyed** [comment]
What is your `g:jedi#use_splits_not_buffers` setting?
It should be `1` by default, and then the warning should not appear..

> I have this error, everything worked fine yesterday.

What has changed?
Have you updated jedi-vim?
Are you using the version from git, or a packaged version?

**Comment by yevhen-m** [comment]
The value is 1, it worked correctly yesterday, but today it is broken.
I've updated plugins today, yes.
Go-to behaviour is strange: it throws me somewhere, but not to the definition. I've seen neovim.api.nvim.NvimError: cursor position outside buffer.
I install packages with vim-plug, so I suppose it's a git version of jedi-vim.

**Comment by blueyed** [comment]
With `1` the following code should not be true?!
https://github.com/davidhalter/jedi-vim/blob/48ad42de86f1c177670967df046f56a20fdfe403/jedi_vim.py#L644

I wonder if it's a type issue..
Please put some `print(type(...))` in there, or figure out in general why the `elif` is true for you.

What Neovim version are you using?  Has this been updated since yesterday?

**Comment by blueyed** [comment]
> I've updated plugins today, yes.

What was the previous version of jedi-vim?  Maybe you can use git-bisect to find where it regressed.

**Comment by yevhen-m** [comment]
I have the value 1 for g:jedi#use_splits_not_buffers, but I get into this elif clause ))). How can it happen?

**Comment by yevhen-m** [comment]
neovim==0.1.7
jedi-vim -- 0d613b5 revision (master)

**Comment by yevhen-m** [comment]
I've commented out 644-658 and now go-to works, but tag stack is not used despite it's enabled by default.

**Comment by yevhen-m** [comment]
![image](https://cloud.githubusercontent.com/assets/10185058/14317417/d0dc41fe-fc10-11e5-8fa9-0baea0b323a5.png)

New error ))

**Comment by yevhen-m** [comment]
I've changed some code in jedi_vim.py and now tagstack works.
![image](https://cloud.githubusercontent.com/assets/10185058/14317550/70f2fc28-fc11-11e5-867f-1d5cb8623f9a.png)

**Comment by blueyed** [comment]
@yevhen-m 
> How can it happen?

Maybe related to the type (`1` would be `!= '1'`) - that's why I've asked to print it there.

btw: screenshots are not very useful for error reporting (traceback, code changes)..

**Comment by yevhen-m** [comment]
Screenshots have good quality, but if you say so, I'll put here tracebacks next time.

**Comment by blueyed** [comment]
Screenshots cannot be searched for duplicates etc, need to be opened etc.
And for code changes, a unified diff is more useful for sure.

That's not the real issue though, but why the `elif` is true for you.
Please debug it (just add some prints etc) and provide more information.
Thanks in advance!

**Comment by yevhen-m** [comment]
Thanks very much for your help! ))

**Comment by yevhen-m** [comment]
You were right, I've changed some '1' to 1 and now jedi works as before.

```
diff --git a/jedi_vim.py b/jedi_vim.py
index f6aeb18..85b5f8e 100644
--- a/jedi_vim.py
+++ b/jedi_vim.py
@@ -74,7 +74,7 @@ def vim_command(string):
 
 
 def vim_eval(string):
-    return _catch_exception(string, 1)
+    return _catch_exception(string, '1')
 
 
 def no_jedi_warning(error=None):
@@ -258,7 +258,7 @@ def goto(mode="goto", no_output=False):
                     echo_highlight("Builtin modules cannot be displayed (%s)."
                                    % d.desc_with_module)
             else:
-                using_tagstack = vim_eval('g:jedi#use_tag_stack') == '1'
+                using_tagstack = vim_eval('g:jedi#use_tag_stack') == 1
                 if d.module_path != vim.current.buffer.name:
                     result = new_buffer(d.module_path,
                                         using_tagstack=using_tagstack)
@@ -639,9 +639,9 @@ def py_import_completions():
 @catch_and_print_exceptions
 def new_buffer(path, options='', using_tagstack=False):
     # options are what you can to edit the edit options
-    if vim_eval('g:jedi#use_tabs_not_buffers') == '1':
+    if vim_eval('g:jedi#use_tabs_not_buffers') == 1:
         _tabnew(path, options)
-    elif not vim_eval('g:jedi#use_splits_not_buffers') == '1':
+    elif not vim_eval('g:jedi#use_splits_not_buffers') == 1:
         user_split_option = vim_eval('g:jedi#use_splits_not_buffers')
         split_options = {
             'top': 'topleft split',
@@ -657,7 +657,7 @@ def new_buffer(path, options='', using_tagstack=False):
         else:
             vim_command(split_options[user_split_option] + " %s" % escape_file_path(path))
     else:
-        if vim_eval("!&hidden && &modified") == '1':
+        if vim_eval("!&hidden && &modified") == 1:
             if vim_eval("bufname('%')") is None:
                 echo_highlight('Cannot open a new buffer, use `:set hidden` or save your buffer')
                 return False
@@ -667,9 +667,9 @@ def new_buffer(path, options='', using_tagstack=False):
             return True
         vim_command('edit %s %s' % (options, escape_file_path(path)))
     # sometimes syntax is being disabled and the filetype not set.
-    if vim_eval('!exists("g:syntax_on")') == '1':
+    if vim_eval('!exists("g:syntax_on")') == 1:
         vim_command('syntax enable')
-    if vim_eval("&filetype != 'python'") == '1':
+    if vim_eval("&filetype != 'python'") == 1:
         vim_command('set filetype=python')
     return True
```

**Comment by blueyed** [comment]
@yevhen-m 
Can you try #555, please?

**Comment by yevhen-m** [comment]
Yes, I've pulled your revision.

**Comment by blueyed** [comment]
And it works, too?

**Comment by yevhen-m** [comment]
Give me a few hours to test your revision please.

**Comment by yevhen-m** [comment]
You're revision works and fixes all the issues. Thanks for your help!

**Comment by blueyed** [comment]
@yevhen-m 
Thanks for testing and reporting back!

It's still unclear to me why that issue did not pop up earlier and/or what is triggering it.

Regarding your Neovim version:

> neovim==0.1.7

That does not really exist, does it?

**Comment by yevhen-m** [comment]
It's unclear to me too )). 

https://pypi.python.org/pypi/neovim

**Comment by yevhen-m** [comment]
Thanks for your suggestion. I've just tested neovim versions 0.1.5 and 0.1.7 and the latter breaks jedi-vim     revision 0d613b5.

**Comment by blueyed** [comment]
Oh, that's the python-neovim package actually.
I am using 0.1.5-1 (on Arch).

What Neovim package/version are you using?  The release notes mention that you need a recent version of Neovim (https://github.com/neovim/python-client/releases).

I've tried it in a virtualenv with python-neovim at 0.1.7, but it still seems sane to me (using a recent Neovim).

What does the following give you with a failing combo?

> :py import vim; print(type(vim.eval("g:jedi#use_tag_stack")))

**Comment by yevhen-m** [comment]
What's the difference between neovim and python-neovim? I install it with pip, you?

**Comment by yevhen-m** [comment]
Oh, sorry, I didn't see you writin "Neovim", not "neovim".

**Comment by blueyed** [comment]
Neovim is the actual editor.. :)

With pip it's `neovim`, yes..
Please paste the output of `nvim --version`.

**Comment by yevhen-m** [comment]
`
NVIM 0.1.3-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/build/config -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/src -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-J9QpWm/neovim-0.1.2ubuntu1+git201604070123+2385+17~ubuntu14.04.1/build/include
Compiled by buildd@lcy01-16

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
`

**Comment by blueyed** [comment]
Is that the nightly build then?

**Comment by yevhen-m** [comment]
What's that? ))

**Comment by blueyed** [comment]
https://github.com/neovim/neovim/releases/tag/nightly

**Comment by blueyed** [comment]
How do you install it?  Some PPA?

**Comment by yevhen-m** [comment]
https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu

**Comment by blueyed** [comment]
Yep, that looks like it's the nightly.
Which is good, but leaves me more stumbled.
We have not figured out the root cause yet, and my PR breaks other usages of `vim_eval` as the Travis build shows (e.g. lists should not be casted to strings).

I think the fix would be to wrap things with `int()` on the Python side, but it would still be great to see why and where it regressed.

Can you `pip install -e` the python-neovim client, please (via a git checkout of https://github.com/neovim/python-client) and the git-bisect it to find out which commit breaks it?
(you can mark 0.1.5 as good and 0.1.7 as bad right away).
That would be awesome!

**Comment by yevhen-m** [comment]
As I can see, the last good revision was 2db41a5. 
cc24cd2 -- bad revision.

**Comment by blueyed** [comment]
@yevhen-m 
That is a [merge commit](https://github.com/neovim/python-client/commit/cc24cd2c4c9118b7c4ce18e504f996b3a5cb3340)..
Can you pin it down to a commit from this merge?

**Comment by blueyed** [comment]
git-bisect should do this normally.. maybe restart it with the merge as bad and 9498b38 as good (before the merge) - if you are certain.

**Comment by yevhen-m** [comment]
`6655ced` and `22537a2` give me these errors, next are broken as I described earlier.
```
"../server.py" 260L, 8122C                                                                                                                                           
function jedi#init_python[3]..<SNR>102_init_python[31]..jedi#force_py_version[2]..jedi#setup_py_version[14]..provider#python3#Call[9]..remote#host#Require[13]..provi
der#pythonx#Require, line 15                                                                                                                                         
Vim(if):Channel was closed by the client                                                                                                                             
Failed to load python3 host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the ge
nerated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.                                  
Press ENTER or type command to continue       
```

**Comment by blueyed** [comment]
Oh, but that's another error then..
The commit after them is https://github.com/neovim/python-client/commit/3ed0e93 - so that would be the regression.

**Comment by blueyed** [comment]
@yevhen-m 
Can you test https://github.com/davidhalter/jedi-vim/pull/557, please?
(using the latest Neovim/python-neovim).

**Comment by yevhen-m** [comment]
Tomorrow )).

**Comment by bfredl** [comment]
To be sure here, are you using master neovim as well? ( I went ahead and released the neovim python package 0.1.6 (+0.1.7  compatibility fix) because I thought neovim 0.1.3 was going to be tagged very soon, guess I should have waited until neovim 0.1.3...)

**Comment by blueyed** [comment]
@bfredl
Yes, he is using the nightly.

**Comment by bfredl** [comment]
I have a bit of hard time to follow the bug here, could someone reproduce a test case where neovim behaves differently that vim, or than python-client 0.1.5 ?
I suppose, the intended behavior is that `vim.eval("1+2")` => <type 'str'> but neovim is returning an int? (quick testing localy neovim does the same as vim, at least for python2)

**Comment by yevhen-m** [comment]
I use python3, I should have noted this earlier.

**Comment by yevhen-m** [comment]
Hey, guys )), master revision is broken for me.
neovim==0.1.5
NVIM 0.1.3-dev

**Comment by blueyed** [comment]
jedi-vim uses an autoload function: [vim_eval](https://github.com/davidhalter/jedi-vim/blob/4ddbabd30a10ab00a2265cc668ddba72cc223879/jedi_vim.py#L76-L77) => [_catch_exception](https://github.com/davidhalter/jedi-vim/blob/4ddbabd30a10ab00a2265cc668ddba72cc223879/jedi_vim.py#L60-L69) => [jedi#_vim_exceptions](https://github.com/davidhalter/jedi-vim/blob/4ddbabd30a10ab00a2265cc668ddba72cc223879/autoload/jedi.vim#L186-L202).

I could not reproduce it myself yesterday (got `str` with `:py import vim; print(type(vim.eval("g:jedi#use_tag_stack")))` and python-client 0.1.7 in a virtualenv, but have not checked if it was really used).

> neovim is returning an int?

Yes, for some reason @yevhen-m seems to get an int.

**Comment by bfredl** [comment]
Hmm, vim also converts ints when they part of a compound like (`vim.eval("[2,3]")`), kinda weird (and a missed opportunity of introducing sane behavior in a backwards compatible way...), but in some sense self-consistent, I suppose. Shouldn't be too hard to fix in the python-client.
