### ISSUE TITLE
when i type `from x ` jedi-vim makes 'import' appear even if i've `let g:jedi#completions_enabled = 0`

### ISSUE THREAD

**Issue by tinruufu** [davidhalter/jedi-vim#559]
this was not always the case, so i think it happened in a recent-ish update, and the readme doesn't mention any way to disable it shy of not initialising jedi at all

im here for jumping to definitions, i have other, more general-purpose plugins for completion

**Comment by davidhalter** [comment]
Just disable smart mappings.
