### ISSUE TITLE
Call Signatures wrap in text

### ISSUE THREAD

**Issue by Milor123** [davidhalter/jedi-vim#561]
Hi guys, I've having this problem in some occasions, when I stay within parenthesis of object, jedi shows me the args needed by the object, however sometimes when I press for save, and then run the code, happens that jedi inserts the signature in the code text.

for example: 
![image_example](https://lh3.googleusercontent.com/lMMgKriR5hc-RPrZPC5_psQ5ovYmXA-8PQ0z_ZHHzJH1EicFzJ6iOqdH3IKY18taJZE6aMZL0Mm8-Lbh2nN4-o9ZFJVskhuCeCCHxFk63Ef4FsM3MWCazXXaSnMDyv_dKZ14hQkmvMyS4pWa6s0GPADW9Yfdr4xDLe_Je3MCX1qIrTFEbifJ4Y_7XrLWDDgb6AlTiGUPws8rk0BtTIGtHkXyGK4v7otga3PO_ZxStHQS4dtbmurByYXcmoJKPr07RZ7eZ7WANEwK3XeNn8mkB1WzCokMwbTmNHALOnpwKMIjaEBU-lFFXvdHEjEofKKbrM5432O8SZJr8-beKMmShUfXSrm2tLnnMpgzDyI601BdskEDTv1R0997-1P3qnWgfdSMcbOyR4H184EAbgXx7GHO7Z0arOV8cpvBGH-uX-tdi7s2cBGe_Dxl1QboYHmGrtT5fIeSSOjlvtsWacUgfS4XJFLGPoCHtI9odTTFfaeJZ4ggDDj8grJM5Dbp80A0Jiuu4ViZ4r3PjOiN1ss4ECuBihhP_KE4zufQCnC-PraQXoiGZur6w4obdnPOolbcDWFu=w503-h168-no)

normally when I change to another place and I leave the parentheses or press `esc` key, this is removed, but as I mentioned above, **sometimes the jedi is bugged and save the signature with the text, which is annoying**

I could delete this function, but I like this.

Greetings!!

**Comment by davidhalter** [comment]
How do you save?

**Comment by Milor123** [comment]
I do use  `inoremap <C-Z> <C-O>:update<CR>`

**Comment by davidhalter** [comment]
We should probably have an autocommand that automatically removes those before saving. Is that even possible?

**Comment by davidhalter** [comment]
It seems like BufWritePre would do the job.

**Comment by Milor123** [comment]
I'm not sure but I must use `u` key  for undo to text and happens that sometimes I lose the line because the `u` cant undo.

I'm going to read about of `BufWritePre `, but I've never used this

Thank you very much :D

**Comment by valentjedi** [comment]
Hi, I have this issue too occasionally. I switch to insert mode inside parenthesis and then back to normal mode. Does anyone have some workaround? I basically can imagine about `BufWritePre` since I use it for removing trailing spaces, but what to put in it?

**Comment by blueyed** [comment]
@valentjedi 
Are you also saving from insert mode?

Regarding the mapping from @Milor123 (`inoremap <C-Z> <C-O>:update<CR>`):
 - Have you remapped ctrl-z then to something else, or don't you like backgrounding your Vim?
 - I would recommend to also leave insert mode when saving: it is a nice way to go back to normal mode, but also save the file.  I basically do this most of the time, and therefore espcially cannot see why you would save while in insert mode.

Also, your mapping goes back one character to the right for me?! (in Neovim)

Anyway, there are several issues regarding this already, and the code is a bit flaky I'd say.  It got improved over time, so make also sure to use Jedi-Vim from Git master, and not the last release.
And then you could try to debug it - a reproducible test case would really help, of course.

**Comment by valentjedi** [comment]
@blueyed Thanks for tips! I'm always save from normal mode and often background vim (to run tests, I use very short TDD cycle). Issue is quate rare so I don't have reproducible case unfortunately. So I'll try to catch it somehow.

**Comment by ibigbug** [comment]
I'm getting nearly the same problem but not when saving, each time I quit I mode, the sig text remains in the file.

![image](https://cloud.githubusercontent.com/assets/543405/20958117/ec0cea2a-bc8e-11e6-8ecd-601edc2625ca.png)

![image](https://cloud.githubusercontent.com/assets/543405/20958160/2da50b66-bc8f-11e6-9b20-e8cd0da034ef.png)

**Comment by davidhalter** [comment]
AFAIK we have just changed the default again. Please retry with the current master.

**Comment by ibigbug** [comment]
![image](https://cloud.githubusercontent.com/assets/543405/20971064/152dcad2-bccb-11e6-85f1-b846e3cccaa9.png)

I think it's the same as my local master ?

**Comment by blueyed** [comment]
@ibigbug 
That's a new experience for me - seeing a screenshot of GitHub to state what the current revision is.. - at least not wrapped in a `.doc` ;)
Apart from this: it's a regression for you then?

@davidhalter 
I can imagine that there is a problem where removal does not work correctly, e.g. because of escaping.

I am not using master and have not tested the PR in question myself.

**Comment by ibigbug** [comment]
@blueyed ya it's a little wired and tricky way, though it works!.

I just run :PluginUpdate and checkout the jedi-vim to the latest revision.

**Comment by valentjedi** [comment]
I switched to emacs some time ago and I didn't know if this issue exists yet. So I just installed latest version of jedi-vim and jedi from master branch and check couple of signatures. Now it displays not as pop up above the function call but in little split above. Is this an expected behaviour now be default?

**Comment by davidhalter** [comment]
@valentjedi This is not an emacs plugin.

@ibigbug Sorry, I was tired.

**Comment by blueyed** [comment]
@ibigbug 
Sorry, it's not clear to me if there is still an issue for you after using master.

If there is a regression, please create a new issue - referencing this one.

**Comment by valentjedi** [comment]
@davidhalter Sorry for posting comment on closed issue, but I wrote above about jedi-vim and vim in particular. Note about emacs was there only to mention that I'm not using vim now and don't know if issue still exists. But to check it anyway I just installed all this stuff on my vim and check it. It seems that issue is gone :)
