### ISSUE TITLE
Cannot get completion on tensorflow

### ISSUE THREAD

**Issue by zhou13** [davidhalter/jedi-vim#562]
I cannot get the completion on tensorflow (https://github.com/tensorflow/tensorflow).  If I input
````
import tensorflow as tf
tf.
````
, I got "Pattern not found" in omni completion.  Here is my jedi-vim comfiguration:
````
let g:jedi#completions_enabled = 1
let g:jedi#popup_select_first = 0
let g:jedi#show_call_signatures = 0
let g:jedi#goto_definitions_command = "<C-]>"
let g:jedi#force_py_version = 3
````

I am using python 3.5.  The strange thing is that I am able to get the completion if I execute the following script directly in python:
````
import jedi
source = '''
import tensorflow as tf
tf.'''
script = jedi.Script(source, 3, len('tf.'), 'example.py')
completions = script.completions()
print(completions)
````

Other python modules work correctly in my vim.  Any advice how to debug this problem?

**Comment by davidhalter** [comment]
How did you install it?

**Comment by zhou13** [comment]
You mean how did I install tensorflow?  I use my distro's package so it is in the same place as other system python package:  `/usr/lib/python3.5/site-packages/tensorflow`

**Comment by zhou13** [comment]
If you are trying to install tensorflow on python 3.5 using pip, you may want to rename tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl to tensorflow-0.8.0-cp35-cp35m-linux_x86_64.whl.

**Comment by davidhalter** [comment]
Try `:PythonJedi import tensorflow`, please.

**Comment by zhou13** [comment]
OK I think that is the problem.  I got
````
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 45, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyLong_FromLong
````

**Comment by zhou13** [comment]
This seems to be a a problem of vim since `:py3 import tensorflow` gives the same error

**Comment by davidhalter** [comment]
See, not our issue anymore :)
