### ISSUE TITLE
Autocomplete and call signature

### ISSUE THREAD

**Issue by Milor123** [davidhalter/jedi-vim#563]
Hi guys, I would like to show a possible bug with the `autocomplete` when a `call signature` is enable.

*Figure 1. (Bad):*
![bad_work](https://i.imgur.com/cLUcwww.png)

*Figure 2. (Nice):*
![nice_work](https://i.imgur.com/n4cBc9T.png)
<hr/>
In the **Figure 1** the `call signature` generate when I'm in the parenthesis `()` writes as text and then when the `autocomplete` need search the word, cant complete correctly

In the **Figure 2** works nice, because the `call signature` not puts the word above of code

Thank you very much. Greetings!

**Comment by davidhalter** [comment]
In Jedi's dev branch this doesn't seem to be a problem anymore
