### ISSUE TITLE
jedi-vim + supertab does not complete variables names? 

### ISSUE THREAD

**Issue by Rmano** [davidhalter/jedi-vim#564]
Please bear with me if this is a newbie question --- I am quite a newbie with jedi-vim. 
I have this on my `.vimrc`: 

```
Plug 'ervandew/supertab'
    let g:SuperTabDefaultCompletionType = "context"
    let g:SuperTabContextDefaultCompletionType = "<c-x><c-o>"
    "let g:SuperTabRetainCompletionDuration = "session"
    let g:SuperTabLongestEnhanced = 1
    let g:SuperTabCrMapping = 0
    augroup Supertab
        autocmd!
        autocmd FileType text call SuperTabSetDefaultCompletionType("<c-n>")
        autocmd FileType tex call SuperTabSetDefaultCompletionType("<c-n>")
    augroup END
"
Plug 'davidhalter/jedi-vim'
    let g:jedi#auto_vim_configuration = 0
    autocmd FileType python setlocal completeopt-=preview
    let g:jedi#show_call_signatures = "2"
```

and while `jedi-vim` works ok for my editing in Python, it never suggest autocompletion on variables. For example, if I have 

```
start_time = -1
if start_
```

and press `TAB` I have a `"Omni completion" pattern not found` error. What am I doing wrong? 
Commenting out or in ` let g:jedi#auto_vim_configuration = 0` did not change things. 

Thanks!

**Comment by blueyed** [comment]
I think it's more related to your supertab config than jedi-vim.
I've experimented with using supertab and it's chaining myself, but cannot help you right now regarding this.
Check `imap <tab>` to see what is bound to tab and then dig deeper from there.
Also check `set omnifunc?` (which can be triggered with <kbd>C-x</kbd><kdb>C-o</kbd>.

**Comment by Rmano** [comment]
Thanks for the help. 

Just to add a bit of data for if someone has some hint --- name completions works ok on the other modes. 

`set omnifunc?` says `omnifunc=pythoncomplete#Complete` and `:imap <tab>` says 

```
i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
```

which is supposed to try to expand a snippet and otherwise calling the omnifunc. Nevertheless, variable expansion does not function even if I call it directly with `<C-x><C-o>`. 

Curiosly, it works with plain `<C-n>`...

**Comment by blueyed** [comment]
`pythoncomplete#Complete` is not from jedi-vim.
Try `verb set omnifunc?` to see where it's set (probably in the default Python ftplugin).

I have `setlocal omnifunc=jedi#completions` myself in `~/.vim/after/ftplugin/python.vim`.

**Comment by blueyed** [comment]
> Curiosly, it works with plain <C-n>... 

That is Vim's builtin keyword completion, which is different from omni-completion.

**Comment by Rmano** [comment]
Ok --- found it. I had a remnant autocmd around I do not know from where. 
Thanks a lot ...
