### ISSUE TITLE
Completion does not work with psycopg2

### ISSUE THREAD

**Issue by OwenChia** [davidhalter/jedi-vim#565]
Completion does not work in these examples when I using vim with jedi-vim, but ptpython/ipython work:

```python
import psycopg2

conn = psycopg2.connect('user=postgres')
conn.<TAB>
```
```python
import psycopg2

conn = psycopg2.connect('user=postgres')
cur = conn.cursor()
cur.<TAB>
```

**Comment by davidhalter** [comment]
It will not work for a long time. It's just hard to understand compiled modules. Sorry f the depressing answer, but it's not Python code and not the standard library and therefore not the central business.
