### ISSUE TITLE
Unicode docstrings not displaying correctly in python 3

### ISSUE THREAD

**Issue by cryptomaniac512** [davidhalter/jedi-vim#566]
Hi,
I have a problem like this:

Some function with unicode in docstring (russian):
![2016-05-12-020730_511x126_scrot](https://cloud.githubusercontent.com/assets/10251687/15187896/4b26deb0-17e6-11e6-8943-97f16d97b6be.png)

import of this function in another module:
![2016-05-12-020913_408x57_scrot](https://cloud.githubusercontent.com/assets/10251687/15187923/87df8a78-17e6-11e6-845f-84f8e3f06f91.png)

if I run c-x c-o when type function name in import or if I call documentation via jedi by typing 'K' I can see something like this:
![2016-05-12-021018_942x126_scrot](https://cloud.githubusercontent.com/assets/10251687/15188013/ff02908c-17e6-11e6-918a-43ca7271b29d.png)

:ver
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 29 2016 11:28:12)
Included patches: 1-1797
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +clientserver    +cursorbind      +ex_extra        +gettext         +linebreak       +mouseshape      +multi_byte      +printer         +signs           +tcl/dyn         +vertsplit       +writebackup
+arabic          +clipboard       +cursorshape     +extra_search    -hangul_input    +lispindent      +mouse_dec       +multi_lang      +profile         +smartindent     +terminfo        +virtualedit     +X11
+autocmd         +cmdline_compl   +dialog_con_gui  +farsi           +iconv           +listcmds        +mouse_gpm       -mzscheme        +python/dyn      +startuptime     +termresponse    +visual          -xfontset
+balloon_eval    +cmdline_hist    +diff            +file_in_path    +insert_expand   +localmap        -mouse_jsbterm   +netbeans_intg   +python3/dyn     +statusline      +termtruecolor   +visualextra     +xim
+browse          +cmdline_info    +digraphs        +find_in_path    +job             +lua/dyn         +mouse_netterm   +packages        +quickfix        -sun_workshop    +textobjects     +viminfo         +xsmp_interact
++builtin_terms  +comments        +dnd             +float           +jumplist        +menu            +mouse_sgr       +path_extra      +reltime         +syntax          +timers          +vreplace        +xterm_clipboard
+byte_offset     +conceal         -ebcdic          +folding         +keymap          +mksession       -mouse_sysmouse  +perl/dyn        +rightleft       +tag_binary      +title           +wildignore      -xterm_save
+channel         +cryptv          +emacs_tags      -footer          +langmap         +modify_fname    +mouse_urxvt     +persistent_undo +ruby/dyn        +tag_old_static  +toolbar         +wildmenu        -xpm
+cindent         +cscope          +eval            +fork()          +libcall         +mouse           +mouse_xterm     +postscript      +scrollbind      -tag_any_white   +user_commands   +windows
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm
-I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/in
clude/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o
vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lns
l    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -
lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm

:JediDebugInfo:
> Using Pyton version: 3

**Comment by davidhalter** [comment]
Hmm, could you maybe play around a bit with Jedi?

**Comment by cryptomaniac512** [comment]
What do you mean?

**Comment by davidhalter** [comment]
Check if this is a problem with Jedi and not jedi-vim.

**Comment by cryptomaniac512** [comment]
I load module with my sources like this
`>>> _module = jedi.Script(path='path/to/module.py')`
and then get names
`>>> _names = jedi.api.names(_module.source)`
```
>>> _names[4]
<Definition class BaseContentModel>
>>> _names[4].doctring()
'Много букав'
```
So, It works wel from jedi...
```
Python 3.5.1
>>> jedi.__version__
'0.9.0'
```

**Comment by davidhalter** [comment]
This might probably be related with https://github.com/davidhalter/jedi/pull/728.

**Comment by davidhalter** [comment]
davidhalter/jedi#728 has ben merged. Should solve this issue.

It would be nice if you tested this with Jedi's dev branch. If it's still not working let me know and I will reopen.
