### ISSUE TITLE
option to disable autocompletion/auto-typing of "import" keyword

### ISSUE THREAD

**Issue by hjwp** [davidhalter/jedi-vim#567]
I just cant get used to it!

**Comment by blueyed** [comment]
There is a setting already.
You would find it even in the issues.
A PR to make this easier to find would be nice - in case you've searched for it and have not found it.

**Comment by hjwp** [comment]
@blue-eyed - I've looked through the official jedi docs, and I've searched issues for 'import completion", "import keyword autocomplete" and "disable import" but I can't find anything that looks like the ability to disable that specific thing. Can you help me find it?

**Comment by blueyed** [comment]
See #559 and #524.

`let g:jedi#smart_auto_mappings = 0`

**Comment by blueyed** [comment]
@hjwp 
Sorry for coming across rude.

I've created #568 to improve the situation.

Thanks for flying jedi-vim.. :)

**Comment by hjwp** [comment]
No rudeness perceived! Also, I now see that section in the official docs, sorry I missed it the first time round.
