### ISSUE TITLE
Jedi Vim async autocompletion

### ISSUE THREAD

**Issue by aliev** [davidhalter/jedi-vim#569]
sometimes it is very annoying when you need to wait until the auto complete to be done (in this case, the editor will be blocked until completion).

is it possible to use a new patch of vim (and neovim) to implement asynchronous autocompletion?

gitgutter async example https://github.com/airblade/vim-gitgutter/commit/882073f4b5a4621c880120141956f44c90e92868#diff-302765a6376ab8c93ca461ad1fdb5d7dL14

Thanks!

**Comment by blueyed** [comment]
You should use [deoplete](https://github.com/Shougo/deoplete.nvim) for this.
It will use Jedi as a backend for Pyhthon.

But we should use this method to fix #568, and also for the call signatures.

**Comment by aliev** [comment]
@blueyed but deoplete is only for neovim...

**Comment by aliev** [comment]
@blueyed I mean we're waiting for vim 8 (https://github.com/vim/vim/blob/master/runtime/doc/version8.txt) and we can use/realize some features now. There are jobs and times which can improve jedi autocompletion :)

**Comment by davidhalter** [comment]
I'm waiting for https://github.com/davidhalter/jedi/issues/385
