### ISSUE TITLE
vim-jedi hang at startup

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [davidhalter/jedi-vim#570]
Hello,

When I start reading any python file with vim. It starts using full CPU and hangs until I press Ctrl-C and then I get this error:
```
Error: jedi-vim failed to initialize Python: Vim(let):E484: Can't open file /tmp/vX6HzgX/0 (in function jedi#init_python[3]..<SNR>43_init_python, line 16)
```
Any Idea ? 

Thanks a lot

**Comment by davidhalter** [comment]
No idea. Sorry. This seems very strange.

**Comment by GuillaumeLeclerc** [comment]
I reinstalled everything and it's working :)

**Comment by davidhalter** [comment]
Nice! :)
