### ISSUE TITLE
trying to make it work together with YouCompleteMe

### ISSUE THREAD

**Issue by jabbalaci** [davidhalter/jedi-vim#571]
For autocompletion, I want to use YouCompleteMe. However, jedi-vim has some nice features that I also need, mainly variable / function renaming. If I add jedi-vim and disable its autocompletion, autocompletion doesn't work at all:

```
Plug 'davidhalter/jedi-vim'
let g:jedi#completions_enabled = 0
```

If I simply add jedi-vim (without the `let g:jedi#completions_enabled = 0` line), then jedi-vim takes completion over from YCM. However, I prefer YCM's completion, so I would like to keep that.

How to make jedi-vim work together with YCM?

**Comment by davidhalter** [comment]
Why doesn't work the thing above?

**Comment by jabbalaci** [comment]
I tried it on two different Linuxes and they behave differently, though they use the same shared config file.

1) Manjaro Linux, neovim is installed with pacman
```
    $ nvim --version
    NVIM 0.1.4
    Build type: RelWithDebInfo
    Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.4/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
    Compiled by builduser

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc
    For differences from Vim, see :help vim-differences

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/share/nvim"
```

If I add this line:

    Plug 'davidhalter/jedi-vim'

then it's still YCM that is used. Jedi-vim's renaming (`<leader>r`) works.
`let g:jedi#completions_enabled = 0` has no effect, YCM is used.

2) Ubuntu Linux, neovim is compiled from source
```
    $ nvim --version
    NVIM 0.1.4
    Build type: Debug
    Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/opt/neovim-0.1.4/build/config -I/opt/neovim-0.1.4/src -I/opt/neovim-0.1.4/.deps/usr/include -I/opt/neovim-0.1.4/.deps/usr/include -I/opt/neovim-0.1.4/.deps/usr/include/luajit-2.0 -I/opt/neovim-0.1.4/.deps/usr/include -I/opt/neovim-0.1.4/.deps/usr/include -I/opt/neovim-0.1.4/.deps/usr/include -I/opt/neovim-0.1.4/.deps/usr/include -I/usr/include -I/opt/neovim-0.1.4/build/src/nvim/auto -I/opt/neovim-0.1.4/build/include
    Compiled by ...

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc
    For differences from Vim, see :help vim-differences

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/local/share/nvim"
```

If I add this line:

    Plug 'davidhalter/jedi-vim'

then jedi-vim's completer is used (I get a different list). Jedi-vim's renaming works.
If I also add the line

    let g:jedi#completions_enabled = 0

then autocompletion stops working, nothing pops up. Renaming still works.

3) Ubuntu Linux, neovim is installed from PPA
I also tried to install neovim from PPA, as it is suggested on the Neovim home page. It installed version 0.1.5-dev, but it behaved like the previous one.

**Comment by davidhalter** [comment]
That is expected behavior from jedi-vim. Your problem is that the neovim/YCM combination doesn't seem to be working. Sorry, I cannot help you here.

**Comment by blueyed** [comment]
Yeah, YCM (and also deoplete) ship their own Jedi copy etc.
YCM should also work with Neovim.
But it is not an issue with jedi-vim apparently.
