### ISSUE TITLE
How to hide function hinting?

### ISSUE THREAD

**Issue by BeyondTheBoundary** [davidhalter/jedi-vim#578]
I try to search a option to hide the popup for function hinting, It bothers me a lot. Someone please help me.

![screenshot from 2016-06-02 11-16-05](https://cloud.githubusercontent.com/assets/8280375/15733810/ed24b6be-28b3-11e6-94b2-4c12270021ea.png)

![screenshot_function](https://cloud.githubusercontent.com/assets/8280375/15733809/ed233f96-28b3-11e6-82b6-51f016966234.png)

Not a doc, just a pop up show when go into a function.

**Comment by davidhalter** [comment]
`let jedi#show_call_signatures = 0`. Read the docs next time, please.

**Comment by Sermuns** [comment]
> `let jedi#show_call_signatures = 0`. Read the docs next time, please.

Stop being mean.

**Comment by davidhalter** [comment]
While I could have formulated that a bit "nicer", it's not mean. It is a problem that there's a lot of these questions where people are just too lazy to read the documentation.

The problem with this is that it takes quite a bit of maintainer time. It usually takes me a few minutes to answer these and I would rather invest my time into something useful or something that fulfills me.

I feel like people like you do not understand the burden of being a maintainer and the amount of stuff you have to do that you do not really want to do.
