### ISSUE TITLE
Get completions based on code outside the current buffer

### ISSUE THREAD

**Issue by infokiller** [davidhalter/jedi-vim#580]
I often use ipython to write python code interactively. Sometimes I want to write pieces of code that would be hard to write on the command line, so I use ipython's `%edit` magic function which opens vim for me.
The problem is that I don't get completions for many names that were already defined using the ipython prompt or previous editing sessions. 
Example: if I type on the ipython prompt `my_list = []` and then use the `%edit` magic to open vim, typing `my_list.` won't offer me any completions like `append`.

Is there any way around this?

Thanks!

**Comment by davidhalter** [comment]
No.

**Comment by infokiller** [comment]
Thanks for looking into this so quickly.
Do you have any suggestions how to work around that?
If I can get the content of the previous ipython code, can I "inject" it somehow to jedi so that it will be aware of it?

**Comment by davidhalter** [comment]
My solution for this is to not do everythin in IPython. It's better if you write scripts anyway. I tend to write cleaner code that way. It also gets you a better "history".

IPython is also working on integrating Jedi. So at least the REPL completions there will be better.

**Comment by blueyed** [comment]
> IPython is also working on integrating Jedi

Nice.  That might then actually take care of this issue?!

@infokiller 
Instead of using the IPython shell, you could do it in Vim altogether and use `:w !python` to execute it.
That also allows for a range, of course.

**Comment by infokiller** [comment]
@blueyed 
I like to have a stateful interactive environment. There's also an IPython plugin for vim, I might give that a try.
