### ISSUE TITLE
PyQt Autocomplete question

### ISSUE THREAD

**Issue by dillon4287** [davidhalter/jedi-vim#585]
Jedi-vim assumes that when object is instantiated that I necessarily will be calling one of the defined methods in the class. If I just have one `__init__` method then when I press period to declare a method that was not declared in the class jedi-vim autocompletes the `__init__ `method for me, when I wished to have something like:
```
form = MainWindow()
form.show()
```

And jedi-vim would autocomplete:
`form.__init__()`
incorrectly.

**Comment by davidhalter** [comment]
I think this is an issue with VIM. Remove the `longest` option from `completeopt` and you should be fine.
