### ISSUE TITLE
Syntax is enabled on first open python buffer

### ISSUE THREAD

**Issue by CLaverdiere** [davidhalter/jedi-vim#588]
I have 'syntax off' in my config, but jedi-vim enables syntax highlighting for the first python buffer opened in a fresh vim instance. Buffers opened afterwards do not have syntax highlighting.

version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  9 2016 09:35:51)
Included patches: 1-1910
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +clientserver    +cursorbind      +ex_extra        +gettext         +linebreak       +mouseshape      +multi_byte      +printer         +signs           +tcl/dyn         +vertsplit       +writebackup
+arabic          +clipboard       +cursorshape     +extra_search    -hangul_input    +lispindent      +mouse_dec       +multi_lang      +profile         +smartindent     +termguicolors   +virtualedit     +X11
+autocmd         +cmdline_compl   +dialog_con_gui  +farsi           +iconv           +listcmds        +mouse_gpm       -mzscheme        +python/dyn      +startuptime     +terminfo        +visual          -xfontset
+balloon_eval    +cmdline_hist    +diff            +file_in_path    +insert_expand   +localmap        -mouse_jsbterm   +netbeans_intg   +python3/dyn     +statusline      +termresponse    +visualextra     +xim
+browse          +cmdline_info    +digraphs        +find_in_path    +job             +lua/dyn         +mouse_netterm   +packages        +quickfix        -sun_workshop    +textobjects     +viminfo         +xsmp_interact
++builtin_terms  +comments        +dnd             +float           +jumplist        +menu            +mouse_sgr       +path_extra      +reltime         +syntax          +timers          +vreplace        +xterm_clipboard
+byte_offset     +conceal         -ebcdic          +folding         +keymap          +mksession       -mouse_sysmouse  +perl/dyn        +rightleft       +tag_binary      +title           +wildignore      -xterm_save
+channel         +cryptv          +emacs_tags      -footer          +langmap         +modify_fname    +mouse_urxvt     +persistent_undo +ruby/dyn        +tag_old_static  +toolbar         +wildmenu        -xpm
+cindent         +cscope          +eval            +fork()          +libcall         +mouse           +mouse_xterm     +postscript      +scrollbind      -tag_any_white   +user_commands   +windows
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -
I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/incl
ude/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o v
im   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl
   -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lut
il -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm

JediDebugInfo:
Using Python version: 3

**Comment by davidhalter** [comment]
Can you trace it down, do you know where it comes from? I cannot find it.

IMO syntax can also be a dependency. If people don't want to use syntax, don't use Jedi. But that's just me.

**Comment by CLaverdiere** [comment]
I'll take a look at it tonight. It seems unreasonable to have syntax as a dependency though. The fact that I don't want my code highlighted should have nothing to do with using a completion plugin.

**Comment by davidhalter** [comment]
ping.

**Comment by CLaverdiere** [comment]
I couldn't find it. I decided to instead just re enable syntax for python.
