### ISSUE TITLE
*IDEA* Sorting by frequency in completions list 

### ISSUE THREAD

**Issue by scenix007** [davidhalter/jedi-vim#589]
Hello, I think sorting items in completions list by frequency would be awesome, especially in large package, inspired by similar feature in Pycharm IDE.

**Comment by davidhalter** [comment]
How does it work in Pycharm? And which frequency? Per file? Per project? Globally?

**Comment by davidhalter** [comment]
No answer.

I think this is quite complicated without a database (like Pycharm has it).

**Comment by blueyed** [comment]
Does also more fit into a completion framework like https://github.com/Shougo/deoplete.nvim (and deoplete-jedi regarding Jedi).
