### ISSUE TITLE
Want to use the default auto-completion when Jedi-vim fail to auto-complete

### ISSUE THREAD

**Issue by walkerlala** [davidhalter/jedi-vim#591]
I'm using Jedi-vim for day to day Python programming. But due to the dynamic feature of Python, Jedi often fail to do auto-completion. However, when Jedi fail, the autocompletion comes with Vim, which autocomplete when there is any similar text in the same buffer, fail too.  It just lose its effect, sometimes leaving me some `<c-p>`sI think maybe that's because I use **SuperTab**).

So I am wondering whether I can do something to inform Vim that when Jedi fail, use the original Vim autocompletion. Anyone help ?

Thanks!

**Comment by davidhalter** [comment]
This is not part of jedi-vim.

You can get this to work pretty easily if you want. Just read the jedi-vim source code and look where completions are invoked. You could just start VIM's own completion if jedi doesn't return any completions. But this is where I'm going to let you sit, because I don't think it's a feature that I would want.

**Comment by blueyed** [comment]
Yes, this can become complex.
Supertab is useful in this context, since it provides chaining already.
The best might be to use droplete (with Neovim) which supports multiple sources.

**Comment by walkerlala** [comment]
@davidhalter Can you give me some hints about where jedi return completions so that if Jedi-vim return nothing, I can invoke Vim's original completion there. I'm not so familiar with the syntax of vimscript , and source code of Jedi-vim seems to be too much for me to read through. Thanks!

**Comment by davidhalter** [comment]
Just read the source code of the VIM files. It's really not a lot. You don't need to read the Python stuff.
