### ISSUE TITLE
Position of Function Parameter Recommendation

### ISSUE THREAD

**Issue by icp1994** [davidhalter/jedi-vim#595]
Hi!

This is not a issue more of a quality of life change. Currently jedi-vim shows function parameter recommendations in are above the current like blocking the code in the above and looks like [this](https://i.imgur.com/4yvDacA.png). I think it would be more intuitive to show it below the current line like [bpython does](https://i.imgur.com/Pi4kpIh.png). Is there a currently a way to show them in the split-window?

Thanks in advance

**Comment by davidhalter** [comment]
There's currently show_call_signatures=2, look at the documentation. I'd also be happy with a pull request for the parameters below the current line. It would just need to be an additional option, like `show_call_signatures=3`.

**Comment by davidhalter** [comment]
Closing for now, because I think there's good documentation on it and if somebody really want's to implement it below the cursor, feel free, but it's not really something to give priority to.
