### ISSUE TITLE
autocompletion of locally installed python package

### ISSUE THREAD

**Issue by danarte** [davidhalter/jedi-vim#600]
Hello, I'm pretty new to vim (and ssh connections) so 99.99% my question is already answered/ is common knowledge, but I couldn't find the answer so I will try and open an issue.

I have a python package installed locally on a server I'm connected to via ssh (when I was installing I called "python setup.py install --user" from the folder with the installation) now when I'm importing this package in my python code and trying to autocomplete jedi does won't autocomplete. I found that the package was installed in "~/.local/lib/python2.7/site-packages/HTSeq-0.6.1-py2.7-linux-x86_64.egg/HTSeq/init.pyc".

My guess is that I need to add that path to some place but I dont know where I need to put that.
Also, I'm working on a server without root/sudo so my hands are somewhat tied and I need to resolve this locally.

Any help will be appreciated. Thanks.

**Comment by davidhalter** [comment]
`egg` files are something that Jedi 0.9.0 was not able to import.

This has changed since: https://github.com/davidhalter/jedi/pull/745

However, it's not in a release, yet. Please wait a bit until Jedi is released or update Jedi yourself to the development version. This is a bit risky, but should be ok for now.

**Comment by danarte** [comment]
Cool, thanks for the answer.
You could close the issue if you wish or you could leave it and comment on it when the feature is out so people could get the answer when they search for this... its up to you.
Anyway thanks for the development, it's a great tool.
