### ISSUE TITLE
jedi git submodule not at master

### ISSUE THREAD

**Issue by thet** [davidhalter/jedi-vim#604]
that's maybe intentional, but the git submodule "jedi" in "jedi-vim" is not at master.
I did a fresh install with vundle and this is what ``git status`` in ~/.vim/bundles/jedi-vim/jedi shows me:

``HEAD detached at 995a653``

I do manually check out master to get the latest improvements on nested namespaces.

**Comment by davidhalter** [comment]
It's intentional. I'm only updating on releases to keep the pypi release upgrade the same with jedi-vim.
