### ISSUE TITLE
Jedi uses VIRTUAL_ENV always

### ISSUE THREAD

**Issue by GitFree** [davidhalter/jedi-vim#605]
Version: lastest
ENV: MacOSX 10.11.15 + vim 
Phenomenon:
1. My project need package libs(called libs just for example), I installed libs in my virtualenv, jedi-vim goto virtualenv libs package, which is correct. 
2. Then I want to debug and edit libs, so I copy libs to my project root dir,  the jedi-vim still goto virutalenv libs package, which is wrong, because python will run my root dir libs package.
3. Then I leave my virtualenv, jedi-vim goto my root dir libs package, which is correct.

Issue: jedi-vim goto wrong definition package directory if project root dir have same package name as virtualenv

**Comment by blueyed** [comment]
This sounds like an issue related to the `sys.path` handling in https://github.com/davidhalter/jedi/blob/171873761b8c6b86c62bb88095f950047ff8aef2/jedi/api/__init__.py#L127-L130.

Can you try the following patch, and see if it fixes the issue?

```diff
diff --git i/jedi_vim.py w/jedi_vim.py
index f44e381..bf74571 100644
--- i/jedi_vim.py
+++ w/jedi_vim.py
@@ -145,7 +145,9 @@ def get_script(source=None, column=None):
         column = vim.current.window.cursor[1]
     buf_path = vim.current.buffer.name
     encoding = vim_eval('&encoding') or 'latin1'
-    return jedi.Script(source, row, column, buf_path, encoding)
+    import sys
+    return jedi.Script(source, row, column, buf_path, encoding,
+                       sys_path=sys.path)
```

(It will ignore the `$VIRTUAL_ENV` then always)

If that works we could have e.g. a setting to ignore the `$VIRTUAL_ENV` variable?

**Comment by GitFree** [comment]
@blueyed  It seems your jedi version is 0.10? My jedi version is 0.9.0,which is the latest of pypi.   
In jedi version 0.9.0 there is no sys_path parameter.

**Comment by blueyed** [comment]
Then please try it with Jedi from master.
You can update the "jedi" submodule in the jedi-vim clone - assuming that you are using jedi-vim through Git / a plugin manager.

**Comment by GitFree** [comment]
@blueyed  I have upgraded jedi,wihtou your patch, it goto the wrong virtualenv too,but with your your patch, it works!!
Thanks!

**Comment by GitFree** [comment]
@blueyed  but with your patch, normal virtualenv can't import now. Phenomenon 1 of my pre-post failed.

**Comment by blueyed** [comment]
@GitFree 
That was expected.

> If that works we could have e.g. a setting to ignore the $VIRTUAL_ENV variable?

What do you think?  What is a good way to control this behavior?  A global setting?

**Comment by GitFree** [comment]
I think the perfect result is jedi-vim goto works like the python imports does,first looks for local packages,then virtualenv packages.   
Is it possible to combine sys.path according to the order of local sys.path "plus" virtualenv sys.path?

**Comment by blueyed** [comment]
It would probably be possible to improve this in Jedi, I assume.
We need @davidhalter's expertise here.. :)

**Comment by davidhalter** [comment]
Actually I'm not really sure that I care too much until we have a proper implementation of virtualenvs in Jedi. I'm also closing because of that (there exists a feature issue in Jedi that covers this)

But at the same time I don't think it's a virtualenv issue, really. You can probably produce the same behavior when you install globally. Jedi uses the `sys.path` without the current directory as first priority and then starts to analyze other stuff, because I think that's the best way to know if something is on the sys.path or not.

I think using `pip install -e .` is perfect for a lot of projects but unfortunately not many people know.
