### ISSUE TITLE
Use Jedi's option to follow imports when going to assignment

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi-vim#607]
Jedi got a new feature to follow import with `goto_assignments`: https://github.com/davidhalter/jedi/commit/ebd080a0fd018eb326f73473303fa10515e201bd.

How should this be used in jedi-vim?

`goto_assignments` is used in 3 places currently: as fallback in "goto" (when no definitions are found), for "goto assignment" and with `:PyImport`.

**Comment by davidhalter** [comment]
IMO this should definitely be used as the primary `goto` function. It's what I think the users have wanted for a long time (and I have therefore added it in Jedi).

**Comment by davidhalter** [comment]
There's now `\g` and `\d` and `\s`, so I think we're good here.
