### ISSUE TITLE
python import not working

### ISSUE THREAD

**Issue by karimsqualli96** [davidhalter/jedi-vim#611]
### Issue
hello everyone, i'm started using jedi with vim, the autocompletition work great, but there is a problem with imports, when i type `from module import somthing1-working, no-more-autcomplete`
the first thing imported from the module work with autocompletition, but when i put the comma and try to import another thing its don't work
### Versions

 - jedi-vim: last
 - Python: 3.5

**Comment by blueyed** [comment]
Sounds like a jedi-vim issue.. can you try it with the "dev" and/or "master" branch from there?  (update the "jedi" submodule in the jedi-vim repo).

And are you using jedi-vim master, or the last release?

**Comment by karimsqualli96** [comment]
i installed jedi-vim using vundle, so i guess its the master branch.

**Comment by davidhalter** [comment]
superseeded by: https://github.com/davidhalter/jedi/issues/766
