### ISSUE TITLE
Can't dynamically disable jedi-vim

### ISSUE THREAD

**Issue by ryanbahneman** [davidhalter/jedi-vim#614]
### Issue

I'm using a multiple cursor plugin (terryma/vim-multiple-cursors), and that conflicts with jedi-vim completion.

I'm trying to disable the completion calls dynamically with " let jedi#completions_enabled = 0" and "let jedi#popup_on_dot = 0", but the calls still get made anyway.

How can I temporarily disable jedi-vim
### Steps to reproduce

When I'm working with multiple cursors and type ".", autocompletion starts up and I get a buffer full of ":call <SNR>180_apply_user_input_next('i')."
### Versions

NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unuse
d-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neo
vim-20160824-20295-1v4lzzs/neovim-0.1.5/build/config -I/tmp/neovim-20160824-20295-1v4lzzs/neovim-0.1.5/src -I/tmp/neovim-20160824-20295-1v4lzzs/neovim-0.1.5/d
eps-build/usr/include -I/tmp/neovim-20160824-20295-1v4lzzs/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160824-20295-1v4lzzs/neovim-0.1.5/deps-build/us
r/include -I/tmp/neovim-20160824-20295-1v4lzzs/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160824-20295-1v4lzzs/neovim-0.1.5/deps-build/usr/include -I
/tmp/neovim-20160824-20295-1v4lzzs/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160824-2
0295-1v4lzzs/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160824-20295-1v4lzzs/neovim-0.1.5/build/include
Compiled by ryanbahneman@Ryans-Awesome-MacBook-Pro-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.5/share/nvim"
In case you are not using jedi-vim from Git master, please test it there, too.
### Output of the "JediDebugInfo" command (in a Python buffer)

Using Python version: 2
### Output of "scriptnames" Vim command

 1: ~/dotfiles/nvim/init.vim
  2: ~/.vim/dein/repos/github.com/Shougo/dein.vim/autoload/dein.vim
  3: ~/.vim/dein/repos/github.com/Shougo/dein.vim/autoload/dein/util.vim
  4: /usr/local/Cellar/neovim/0.1.5/share/nvim/runtime/ftoff.vim
  5: ~/.vim/dein/.dein/autoload/dein/autoload.vim
  6: ~/.vim/dein/.dein/autoload/dein/parse.vim
  7: ~/.vim/dein/.dein/autoload/dein/types/git.vim
  8: /usr/local/Cellar/neovim/0.1.5/share/nvim/runtime/filetype.vim
  9: ~/.vim/dein/.dein/ftdetect/ftdetect.vim
 10: ~/.vim/dein/.dein/ftplugin.vim
 11: /usr/local/Cellar/neovim/0.1.5/share/nvim/runtime/ftplugin.vim
 12: /usr/local/Cellar/neovim/0.1.5/share/nvim/runtime/indent.vim
 13: /usr/local/Cellar/neovim/0.1.5/share/nvim/runtime/syntax/syntax.vim
 14: /usr/local/Cellar/neovim/0.1.5/share/nvim/runtime/syntax/synload.vim
 15: /usr/local/Cellar/neovim/0.1.5/share/nvim/runtime/syntax/syncolor.vim
 16: ~/.vim/dein/.dein/colors/desert.vim
 17: ~/.vim/dein/.dein/plugin/EasyMotion.vim
 18: ~/.vim/dein/.dein/plugin/NERD_tree.vim
 19: ~/.vim/dein/.dein/autoload/nerdtree.vim
 20: ~/.vim/dein/.dein/lib/nerdtree/path.vim
 21: ~/.vim/dein/.dein/lib/nerdtree/menu_controller.vim
 22: ~/.vim/dein/.dein/lib/nerdtree/menu_item.vim
 23: ~/.vim/dein/.dein/lib/nerdtree/key_map.vim
 24: ~/.vim/dein/.dein/lib/nerdtree/bookmark.vim
 25: ~/.vim/dein/.dein/lib/nerdtree/tree_file_node.vim
 26: ~/.vim/dein/.dein/lib/nerdtree/tree_dir_node.vim
 27: ~/.vim/dein/.dein/lib/nerdtree/opener.vim
 28: ~/.vim/dein/.dein/lib/nerdtree/creator.vim
 29: ~/.vim/dein/.dein/lib/nerdtree/flag_set.vim
 30: ~/.vim/dein/.dein/lib/nerdtree/nerdtree.vim
 31: ~/.vim/dein/.dein/lib/nerdtree/ui.vim
 32: ~/.vim/dein/.dein/lib/nerdtree/event.vim
 33: ~/.vim/dein/.dein/lib/nerdtree/notifier.vim
 34: ~/.vim/dein/.dein/autoload/nerdtree/ui_glue.vim
 35: ~/.vim/dein/.dein/nerdtree_plugin/exec_menuitem.vim
 36: ~/.vim/dein/.dein/nerdtree_plugin/fs_menu.vim
 37: ~/.vim/dein/.dein/plugin/Tabular.vim
 38: ~/.vim/dein/.dein/plugin/airline.vim
 39: ~/.vim/dein/.dein/autoload/airline.vim

**Comment by davidhalter** [comment]
This hasn't been an issue for anyone else and since nobody has shown interest, it's definitely not something I will implement (also since I think almost nobody will ever use this), so I'm closing this as won't fix.
