### ISSUE TITLE
can't use jedi-vim on vim8.0.6?

### ISSUE THREAD

**Issue by yangbeom** [davidhalter/jedi-vim#615]
### Issue
can't use jedi-vim on vim 8.0.6?
i used jedi-vim on vim 7.4? maybe 7.4
### Steps to reproduce
![Imgur](http://i.imgur.com/Pj14xM1.png)
### Versions

 - jedi-vim: how can u know? installed on 21/9/2016 used git clone
   
    ```git clone --recursive https://github.com/davidhalter/jedi-vim.git```
 - Vim / Neovim: Vim 8.0.6
 - Python: python3.5

**Comment by davidhalter** [comment]
`:version`?

**Comment by blueyed** [comment]
Looks like your Vim is not built with Python.. `:version` output would be needed indeed.

**Comment by yangbeom** [comment]
OMG
![Imgur](http://i.imgur.com/98aYBHQ.png)
Thank u guys :)

**Comment by yangbeom** [comment]
![Imgur](http://i.imgur.com/Pm5xpmJ.png)
