### ISSUE TITLE
import jedi in vim throws Symbol not found: __PyCodecInfo_GetIncrementalDecoder

### ISSUE THREAD

**Issue by phoenixbai** [davidhalter/jedi-vim#616]
### Issue
I am using pathogen managing my plugins and installed the jedi-vim as instructed. But it is not working.
It seems like the linked python issue, but not sure how to solve it, so could you help please?

### Steps to reproduce
os: OS X EL caption
locally, I installed Anaconda and use it as default with version 2.7.12.
but vim is compiled with system default python, which version is 2.7.10.

under these two versions, I manually installed jedi using pip install:

1) Anaconda version:
` import sys`
`sys.version`

>'2.7.12 |Anaconda 2.1.0 (x86_64)| (default, Jul  2 2016, 17:43:17) \n[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]'

`jedi.__version__`

>'0.9.0'

` sys.path`

>['', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/virtualenv-12.0.5-py2.7.egg', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/mmh-1.1-py2.7-macosx-10.5-x86_64.egg', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/httplib2-0.9-py2.7.egg', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/oss-0.3.7-py2.7.egg', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/protobuf-3.0.0a3.dev0-py2.7.egg', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/sqlparse-0.2.0.dev0-py2.7.egg', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg', '/Users/phoenix/workspace/github/xgboost/python-package', '/Users/phoenix/programs/anaconda/lib/python27.zip', '/Users/phoenix/programs/anaconda/lib/python2.7', '/Users/phoenix/programs/anaconda/lib/python2.7/plat-darwin', '/Users/phoenix/programs/anaconda/lib/python2.7/plat-mac', '/Users/phoenix/programs/anaconda/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/phoenix/programs/anaconda/lib/python2.7/lib-tk', '/Users/phoenix/programs/anaconda/lib/python2.7/lib-old', '/Users/phoenix/programs/anaconda/lib/python2.7/lib-dynload', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/PIL', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/Sphinx-1.2.3-py2.7.egg', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/runipy-0.1.1-py2.7.egg', '/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/setuptools-26.1.1-py2.7.egg']

2) system default version:

` import sys`
`sys.version`

>2.7.10 (default, May 26 2015, 13:01:57) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]'

`jedi.__version__`

>'0.9.0'

`sys.path`

>['', '/usr/local/lib/python2.7/site-packages/pgmagick-0.5.8-py2.7-macosx-10.10-x86_64.egg', '/usr/local/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg', '/Users/phoenix/workspace/github/xgboost/python-package', '/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/Cellar/numpy/1.9.2_1/libexec/nose/lib/python2.7/site-packages', '/Library/Python/2.7/site-packages']

I did:

`brew link -overwrite python`

Now, when I vim and do below, it throws errors like this:

`vim`
`:py import jedi`

>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 16, in <module>
    from jedi.parser import Parser, load_grammar
  File "/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/jedi/parser/__init__.py", line 22, in <module>
    from jedi.parser import tokenize
  File "/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/jedi/parser/tokenize.py", line 16, in <module>
    from io import StringIO
  File "/Users/phoenix/programs/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/phoenix/programs/anaconda/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/phoenix/programs/anaconda/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/phoenix/programs/anaconda/lib/python2.7/lib-dynload/_io.so

### Versions

 - jedi-vim: '0.9.0'
 - Vim / Neovim: 2.7.3
 - Python: 2.7.10

What goes wrong here? How could I fix it? I am using vim, not macvim.

thanks

**Comment by blueyed** [comment]
Looks like your Vim needs to be built against the Python in `/Users/phoenix/programs/anaconda/lib/python2.7/lib-dynload/_io.so`?!
I recommend to try Neovim, which allows to use several/dynamic Python versions.

**Comment by phoenixbai** [comment]
Hi @blueyed 
I think I choose the hard way by recompiling the vim-8 with anaconda python.
and when I do the :py import jedi, it throws similar but new errors like below:

>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/Users/phoenix/programs/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 13, in <module>
    from itertools import chain
ImportError: dlopen(/Users/phoenix/programs/anaconda/lib/python2.7/lib-dynload/itertools.so, 2): Symbol not found: _PyBoo
l_Type
  Referenced from: /Users/phoenix/programs/anaconda/lib/python2.7/lib-dynload/itertools.so
  Expected in: flat namespace
 in /Users/phoenix/programs/anaconda/lib/python2.7/lib-dynload/itertools.so

I used below command to configure and compile/install the vim-8, what am I doing wrong? could u please help? Sorry for being a little stubborn for not using neovim.

`make distclean`
`./configure --enable-pythoninterp --enable-rubyinterp --enable-luainterp --enable-perlinterp --with-python-config-dir=/Users/phoenix/programs/anaconda/lib/python2.7/config`
`make`
`sudo make install`

vim version is: 8.0
`py print(sys.version)`

> 2.7.12 |Anaconda 2.1.0 (x86_64)| (default, Jul  2 2016, 17:43:17)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]

And I installed jedi manually through pip:
`pip install jedi`

> phoenix@Phoenix:bundle$ python
Python 2.7.12 |Anaconda 2.1.0 (x86_64)| (default, Jul  2 2016, 17:43:17)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
\>\>\> import jedi

this is successful.

Thanks

**Comment by blueyed** [comment]
Is the `python` where you `import jedi` the one from `/Users/phoenix/programs/anaconda/lib/python2.7`?!

Check `:py import site; print(site.__file__)`.

From the traceback it looks like it is not looking at odd locations though.

You could try to look at what Vim is doing when it loads python, i.e.:
 - start Vim (but do not load python, e.g. use `vim -Nu NONE` to be sure
 - `:echo getpid()` to get its PID
 - in a new terminal: `sudo strace -f -p $PID_OF_VIM 2>&1 | grep -i python`
 - then in Vim: `:py import sys`

You should then see what python related files are being accessed in Vim in the strace window.

btw: there is usually no need to install `jedi` with pip.
The vim plugin is meant to pick up the one from the Git submodule.
E.g. I am getting an ImportError when trying to `:py import jedi` myself.

FWIW: I've just added https://github.com/davidhalter/jedi-vim/commit/6a6595f5c5bf116f1f3b3434009bb2be77b494e2, so please try updating jedi-vim and try that command.  Paste the output here then, please.

Since you are using `brew link -overwrite python` I guess you are better of in the homebrew support channels probably?!

**Comment by blueyed** [comment]
I am closing the issue here, but will look at responses still.

**Comment by blueyed** [comment]
Regarding Neovim: there is a `:CheckHealth` command which helps with Python issues.

**Comment by phoenixbai** [comment]
@blueyed ,

I downloaded latest jedi including 6a6595f, and follow the steps you mentioned above. But it failed to print anything. I am guessing probably because jedi is not configured/working correctly yet.

I googled, and saw some conclusions that on OSX, only vim installed through brew works perfectly. So, I used brew installed the vim8 again. After working out the linking issue, it is working FINALLY.

jedi is awesome, with its help, I can totally get rid of IDE now.
thank you very much for all the support and help!

Wish you a good day!

**Comment by blueyed** [comment]
> But it failed to print anything

Also no errors?!  That would be strange.

> jedi is awesome, with its help, I can totally get rid of IDE now.

It is indeed!  Cheers to @davidhalter for all of this!

As for the integration in Vim/Neovim, I find it much better through deoplete and https://github.com/zchee/deoplete-jedi/ - you have a completion server there that's async.

I am glad it worked out for you! :)
