### ISSUE TITLE
Jedi failed to autocomplete pandas

### ISSUE THREAD

**Issue by Yefee** [davidhalter/jedi-vim#617]
### Steps to reproduce
```
import pandas as pd
aa = pd.date_range()
```
### Versions

 - jedi-vim: The latest version
 - Vim / Neovim: 7.2
 - Python: miniconda-2.7.12

I am a new user to Jedi-Vim. It works fine with numpy but why it cannot complete for other packages, like pandas, matplotlib....
Could anyone give me some suggestions? Sorry to bother.

**Comment by davidhalter** [comment]
Pandas completions have a few problems. It's a known issue and there are a lot of issues that describe this behavior. Sorry, this won't improve in the near future.
