### ISSUE TITLE
Exception for certain python files.

### ISSUE THREAD

**Issue by thekswenson** [davidhalter/jedi-vim#621]
### Issue

jedi-vim raises an exception for certain files (as for the one that is attached).
The exception is raised for any key combination like `<Shift>k` or `<Leader>g`.

### Steps to reproduce

0. renamed the attached file from "[AdjacencyGraph.txt](https://github.com/davidhalter/jedi-vim/files/492974/AdjacencyGraph.txt)" to "AdjacencyGraph.py".
1. Open "AdjacencyGraph.txt" with jedi-vim activated.
2. Go to line 221.
3. Move the cursor to "_addReality" and type `<Shift>k`.

### Versions

 - jedi-vim:  => 0.8.0-41-g6a6595f
 - Vim / Neovim: vim 7.4.1689
 - Python:   2.7.12

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of the "JediDebugInfo" command (in a Python buffer)

I am not sure how to do this.

### Output of the "messages" Vim command

```
> Exception, this shouldn't happen.
> Traceback (most recent call last):
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 141, in wrapper
> 
>     return getattr(self, name)
> AttributeError: 'UserContextParser' object has no attribute '_user_scope'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 141, in wrapper
> 
>     return getattr(self, name)
> AttributeError: 'UserContextParser' object has no attribute '_user_stmt'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 141, in wrapper
> 
>     return getattr(self, name)
> AttributeError: 'UserContextParser' object has no attribute '__parser'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 294,
> in clear_names
>     clear_names(c.children)
> AttributeError: 'Name' object has no attribute 'children'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/kms/.vim/bundle/jedi-vim/jedi_vim.py", line 305, in show_documenta
> tion
>     definitions = script.goto_definitions()
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 366, in
> goto_definitions
>     definitions = set(self._prepare_goto(goto_path))
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 270, in
> _prepare_goto
>     debug.dbg('start: %s in %s', goto_path, self._parser.user_scope())
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 143, in wrapper
> 
>     result = func(self)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 3
> 22, in user_scope
>     user_stmt = self.user_stmt()
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 143, in wrapper
> 
>     result = func(self)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 2
> 93, in user_stmt
>     module = self.module()
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 3
> 39, in module
>     return self._parser().module
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 143, in wrapper
> 
>     result = func(self)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 2
> 83, in _parser
>     parser = FastParser(self._grammar, self._source, self._path)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 106, in _
> _call__
>     p = super(CachedFastParser, self).__call__(grammar, source, module_path)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 243, in _
> _init__
>     self.update(source)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 257, in u
> pdate
>     self._parse(source)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 383, in _
> parse
>     line_offset, nodes)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 435, in _
> get_node
>     p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer
> )
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 155,
> in __init__
>     self.module = p.parse(self._tokenize(tokenizer))
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/pgen2/parse.py", line 10
> 6, in parse
>     if self.addtoken(type, value, prefix, start_pos):
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/pgen2/parse.py", line 17
> 0, in addtoken
>     value, start_pos, prefix, self.addtoken)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 269,
> in error_recovery
>     self._stack_removal(grammar, stack, index + 1, value, start_pos)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 304,
> in _stack_removal
>     clear_names(children=node[1])
>   File "/home/kms/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 298,
> in clear_names
>     self._scope_names_stack[-1][c.value].remove(c)
> KeyError: 'mi'
> Error detected while processing function jedi#show_documentation:
> line    1:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/kms/.vim/bundle/jedi-vim/jedi_vim.py", line 132, in wrapper
>     return func(*args, **kwargs)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi_vim.py", line 117, in wrapper
>     return func(*args, **kwargs)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi_vim.py", line 315, in show_documenta
> tion
>     echo_highlight('No documentation found for that.')
>   File "/home/kms/.vim/bundle/jedi-vim/jedi_vim.py", line 90, in echo_highlight
>     msg.replace('"', '\\"')))
>   File "/home/kms/.vim/bundle/jedi-vim/jedi_vim.py", line 73, in vim_command
>     _catch_exception(string, False)
>   File "/home/kms/.vim/bundle/jedi-vim/jedi_vim.py", line 66, in _catch_exceptio
> n
>     repr(PythonToVimStr(string, 'UTF-8')), int(is_eval)))
> KeyboardInterrupt
```

### Output of "scriptnames" Vim command

>   1: /usr/share/vim/vimrc
>   2: /usr/share/vim/vim74/debian.vim
>   3: /usr/share/vim/vim74/syntax/syntax.vim
>   4: /usr/share/vim/vim74/syntax/synload.vim
>   5: /usr/share/vim/vim74/syntax/syncolor.vim
>   6: /usr/share/vim/vim74/filetype.vim
>   7: ~/.vimrc
>   8: /usr/share/vim/vim74/ftoff.vim
>   9: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
>  10: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
>  11: /usr/share/vim/vim74/ftplugin.vim
>  12: /usr/share/vim/vim74/indent.vim
>  13: /usr/share/vim/vim74/indoff.vim
>  14: /usr/share/vim/vim74/syntax/nosyntax.vim
>  15: ~/.vim/colors/Dark2_kms.vim
>  16: ~/.vim/bundle/supertab/plugin/supertab.vim
>  17: ~/.vim/bundle/csapprox/plugin/CSApprox.vim
>  18: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
>  19: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
>  20: /usr/share/vim/vim74/plugin/gzip.vim
>  21: /usr/share/vim/vim74/plugin/logiPat.vim
>  22: /usr/share/vim/vim74/plugin/matchparen.vim
>  23: /usr/share/vim/vim74/plugin/netrwPlugin.vim
>  24: /usr/share/vim/vim74/plugin/rrhelper.vim
>  25: /usr/share/vim/vim74/plugin/spellfile.vim
>  26: /usr/share/vim/vim74/plugin/tarPlugin.vim
>  27: /usr/share/vim/vim74/plugin/tohtml.vim
>  28: /usr/share/vim/vim74/plugin/vimballPlugin.vim
>  29: /usr/share/vim/vim74/plugin/zipPlugin.vim
>  30: ~/.vim/bundle/csapprox/after/plugin/CSApprox.vim
>  31: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
>  32: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
>  33: /usr/share/vim/vim74/ftplugin/python.vim
>  34: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
>  35: /usr/share/vim/vim74/syntax/python.vim
>  36: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
>  37: /usr/share/vim/vim74/scripts.vim
>  38: /usr/share/vim/vim74/ftplugin/rst.vim
>  39: /usr/share/vim/vim74/syntax/rst.vim
>  40: /usr/share/vim/vim74/syntax/vim.vim
>  41: /usr/share/vim/vim74/syntax/lua.vim
>  42: /usr/share/vim/vim74/syntax/perl.vim
>  43: /usr/share/vim/vim74/syntax/pod.vim
>  44: /usr/share/vim/vim74/syntax/ruby.vim
>  45: /usr/share/vim/vim74/syntax/java.vim
>  46: /usr/share/vim/vim74/syntax/html.vim
>  47: /usr/share/vim/vim74/syntax/cpp.vim
>  48: /usr/share/vim/vim74/syntax/c.vim

**Comment by davidhalter** [comment]
Can you upgrade to the Jedi master branch? I think this line has been remove from master branch and should no longer be a problem. It's tontally different on the diff branch (which I would not recommend you using).

**Comment by thekswenson** [comment]
Yes...
  updating to Master in the "jedi" repo (didn't realize I had to do another pull there) did the trick.

**Comment by thekswenson** [comment]
Thank you!

**Comment by davidhalter** [comment]
Yeah that's a bit unfortunate. I'm still not content with the latest master branch (and therefore haven't done a release on it).
