### ISSUE TITLE
E925:Current quickfix was changed

### ISSUE THREAD

**Issue by luoyancn** [davidhalter/jedi-vim#622]
### Issue
When I use <leader>n to find the usage of method, Then select the quickfix and pressing Enter to jump to the selected line yields E925

### Steps to reproduce

    1.Open https://github.com/openstack/keystone/blob/master/keystone/federation/utils.py  with jedi-vim activated.
    3.Go to line 250.
    4.Move the cursor to "get_remote_id_parameter" and type <leader>n.
    5.Then select the quickfix and pressing Enter to jump to the selected line
    Then , the error E925 orccured.

### Versions

 - jedi-vim: with the commit id 9384d464eccfe8ff8a63393d622fafce0a4e7933
 - Vim / Neovim: vim 8.0.0016
 - Python:2.7.12

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of the "JediDebugInfo" command (in a Python buffer)
Using Python version: 2
 - sys.version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
 - site module: C:\Python27\Lib\site.pyc
Jedi path: C:\Vim\bundle\jedi-vim\jedi\jedi\__init__.pyc

Jedi version: 0.9.0

jedi-vim git version: 0.8.0-43-g9384d46

jedi git submodule status:  995a6531225ba0b65e1ff863d97e5404d989047b jedi (v0.9.0-19-g995a653)

### Output of the "messages" Vim command
E925:Current quickfix was changed

### Output of "scriptnames" Vim command
  1: C:\Vim\_vimrc
  2: C:\Vim\vim80\vimrc_example.vim
  3: C:\Vim\vim80\defaults.vim
  4: C:\Vim\vim80\syntax\syntax.vim
  5: C:\Vim\vim80\syntax\synload.vim
  6: C:\Vim\vim80\syntax\syncolor.vim
  7: C:\Vim\vim80\filetype.vim
  8: C:\Vim\vim80\ftplugin.vim
  9: C:\Vim\vim80\indent.vim
 10: C:\Vim\vim80\pack\dist\opt\matchit\plugin\matchit.vim
 11: C:\Vim\vim80\ftoff.vim
 12: C:\Vim\bundle\Vundle.vim\autoload\vundle.vim
 13: C:\Vim\bundle\Vundle.vim\autoload\vundle\config.vim
 14: C:\Vim\bundle\vim-go\ftdetect\gofiletype.vim
 15: C:\Vim\vim80\delmenu.vim
 16: C:\Vim\vim80\menu.vim
 17: C:\Vim\vim80\lang\menu_zh_cn.utf-8.vim
 18: C:\Vim\vim80\autoload\paste.vim
 19: C:\Vim\vim80\indoff.vim
 20: C:\Vim\vim80\colors\desert.vim
 21: C:\Vim\bundle\nerdtree\plugin\NERD_tree.vim
 22: C:\Vim\bundle\nerdtree\autoload\nerdtree.vim
 23: C:\Vim\bundle\nerdtree\lib\nerdtree\path.vim
 24: C:\Vim\bundle\nerdtree\lib\nerdtree\menu_controller.vim
 25: C:\Vim\bundle\nerdtree\lib\nerdtree\menu_item.vim
 26: C:\Vim\bundle\nerdtree\lib\nerdtree\key_map.vim
 27: C:\Vim\bundle\nerdtree\lib\nerdtree\bookmark.vim
 28: C:\Vim\bundle\nerdtree\lib\nerdtree\tree_file_node.vim
 29: C:\Vim\bundle\nerdtree\lib\nerdtree\tree_dir_node.vim
 30: C:\Vim\bundle\nerdtree\lib\nerdtree\opener.vim
 31: C:\Vim\bundle\nerdtree\lib\nerdtree\creator.vim
 32: C:\Vim\bundle\nerdtree\lib\nerdtree\flag_set.vim
 33: C:\Vim\bundle\nerdtree\lib\nerdtree\nerdtree.vim
 34: C:\Vim\bundle\nerdtree\lib\nerdtree\ui.vim
 35: C:\Vim\bundle\nerdtree\lib\nerdtree\event.vim
 36: C:\Vim\bundle\nerdtree\lib\nerdtree\notifier.vim
 37: C:\Vim\bundle\nerdtree\autoload\nerdtree\ui_glue.vim
 38: C:\Vim\bundle\nerdtree\nerdtree_plugin\exec_menuitem.vim
 39: C:\Vim\bundle\nerdtree\nerdtree_plugin\fs_menu.vim
 40: C:\Vim\bundle\buf_it\plugin\buf_it.vim
 41: C:\Vim\bundle\vim-startify\plugin\startify.vim
 42: C:\Vim\bundle\tagbar\plugin\tagbar.vim
 43: C:\Vim\bundle\vim-airline\plugin\airline.vim
 44: C:\Vim\bundle\vim-airline\autoload\airline.vim
 45: C:\Vim\bundle\vim-airline\autoload\airline\init.vim
 46: C:\Vim\bundle\vim-airline\autoload\airline\parts.vim
 47: C:\Vim\bundle\vim-airline-themes\plugin\airline-themes.vim
 48: C:\Vim\bundle\vim-trailing-whitespace\plugin\trailing-whitespace.vim
 49: C:\Vim\bundle\vim-multiple-cursors\plugin\multiple_cursors.vim
 50: C:\Vim\bundle\ack.vim\plugin\ack.vim
 51: C:\Vim\bundle\ctrlp.vim\plugin\ctrlp.vim
 52: C:\Vim\bundle\ctrlp.vim\autoload\ctrlp\mrufiles.vim
 53: C:\Vim\bundle\vim-fugitive\plugin\fugitive.vim
 54: C:\Vim\bundle\TabBar\plugin\tabbar.vim
 55: C:\Vim\bundle\syntastic\plugin\syntastic\autoloclist.vim
 56: C:\Vim\bundle\syntastic\plugin\syntastic\balloons.vim
 57: C:\Vim\bundle\syntastic\plugin\syntastic\checker.vim
 58: C:\Vim\bundle\syntastic\plugin\syntastic\cursor.vim
 59: C:\Vim\bundle\syntastic\plugin\syntastic\highlighting.vim
 60: C:\Vim\bundle\syntastic\plugin\syntastic\loclist.vim
 61: C:\Vim\bundle\syntastic\plugin\syntastic\modemap.vim
 62: C:\Vim\bundle\syntastic\plugin\syntastic\notifiers.vim
 63: C:\Vim\bundle\syntastic\plugin\syntastic\registry.vim
 64: C:\Vim\bundle\syntastic\plugin\syntastic\signs.vim
 65: C:\Vim\bundle\syntastic\plugin\syntastic.vim
 66: C:\Vim\bundle\syntastic\autoload\syntastic\util.vim
 67: C:\Vim\bundle\a.vim\plugin\a.vim
 68: C:\Vim\bundle\vim-go\plugin\go.vim
 69: C:\Vim\bundle\jedi-vim\plugin\jedi.vim
 70: C:\Vim\bundle\delimitMate\plugin\delimitMate.vim
 71: C:\Vim\bundle\delimitMate\autoload\delimitMate.vim
 72: C:\Vim\vim80\plugin\getscriptPlugin.vim
 73: C:\Vim\vim80\plugin\gzip.vim
 74: C:\Vim\vim80\plugin\logiPat.vim
 75: C:\Vim\vim80\plugin\manpager.vim
 76: C:\Vim\vim80\plugin\matchparen.vim
 77: C:\Vim\vim80\plugin\netrwPlugin.vim
 78: C:\Vim\vim80\plugin\rrhelper.vim
 79: C:\Vim\vim80\plugin\spellfile.vim
 80: C:\Vim\vim80\plugin\tarPlugin.vim
 81: C:\Vim\vim80\plugin\tohtml.vim
 82: C:\Vim\vim80\plugin\vimballPlugin.vim
 83: C:\Vim\vim80\plugin\zipPlugin.vim
 84: C:\Vim\bundle\indentLine\after\plugin\indentLine.vim
 85: C:\Vim\bundle\vim-airline\autoload\airline\extensions.vim
 86: C:\Vim\bundle\vim-airline\autoload\airline\extensions\quickfix.vim
 87: C:\Vim\bundle\vim-airline\autoload\airline\extensions\netrw.vim
 88: C:\Vim\bundle\vim-airline\autoload\airline\extensions\ctrlp.vim
 89: C:\Vim\bundle\vim-airline\autoload\airline\extensions\tagbar.vim
 90: C:\Vim\bundle\vim-airline\autoload\airline\extensions\branch.vim
 91: C:\Vim\bundle\vim-airline\autoload\airline\extensions\syntastic.vim
 92: C:\Vim\bundle\vim-airline\autoload\airline\extensions\whitespace.vim
 93: C:\Vim\bundle\vim-airline\autoload\airline\extensions\wordcount.vim
 94: C:\Vim\bundle\vim-airline\autoload\airline\section.vim
 95: C:\Vim\bundle\vim-airline\autoload\airline\highlighter.vim
 96: C:\Vim\bundle\vim-airline\autoload\airline\themes\dark.vim
 97: C:\Vim\bundle\vim-airline\autoload\airline\themes.vim
 98: C:\Vim\bundle\vim-airline\autoload\airline\msdos.vim
 99: C:\Vim\bundle\vim-airline\autoload\airline\util.vim
100: C:\Vim\bundle\vim-airline\autoload\airline\builder.vim
101: C:\Vim\bundle\vim-airline\autoload\airline\extensions\default.vim
102: C:\Vim\bundle\syntastic\autoload\syntastic\log.vim
103: C:\Vim\bundle\vim-startify\autoload\startify.vim
104: C:\Vim\bundle\vim-startify\autoload\startify\fortune.vim
105: C:\Vim\bundle\vim-startify\syntax\startify.vim

**Comment by blueyed** [comment]
For reference, the URL of the file is https://raw.githubusercontent.com/openstack/keystone/7ba53701989490667d220a3faecae2b484a007c5/keystone/federation/utils.py.

I cannot reproduce it (using my config).
It might be related to another plugin interfering.

`:h E925`:
> 							*E925* *E926*
If the current quickfix or location list was changed by an |autocommand| while
processing a quickfix or location list command, it will be aborted.

(seems to be specific to Vim)

Try removing some of your plugins until the error is gone.. maybe http://vimawesome.com/plugin/bisectly is helpful in that regard - came across it recently (no idea how well it works though).

**Comment by luoyancn** [comment]
@blueyed 
Thanks for your advice!
After removing the plugin named pyflakes-vim, the error disappeard.
Maybe, this problem is a bug of pyflakes-vim.

**Comment by blueyed** [comment]
Great!
If it is https://github.com/kevinw/pyflakes-vim then it seems you do not need it, since you are using Syntastic already.
Btw: you might want to try Neomake instead, which is async.

**Comment by Near-Tam** [comment]
@luoyancn 
I have a same problem.
Did you removing a pyflakes-vim file ? 
I could not understand your operation, would you like to tell me your detail operation.
