### ISSUE TITLE
client/server architecture

### ISSUE THREAD

**Issue by dholth** [davidhalter/jedi-vim#623]
pythonVScode's completions serializer https://github.com/DonJayamanne/pythonVSCode/blob/master/pythonFiles/completion.py

**Comment by blueyed** [comment]
Please elaborate.

**Comment by dholth** [comment]
It should read separate Jedi Vim into a client and server so the completions can run under a different python than that embedded in vim
On Sep 29, 2016 18:03, Daniel Hahler <notifications@github.com> wrote:Please elaborate.

**Comment by blueyed** [comment]
That is what https://github.com/zchee/deoplete-jedi does and (at least for me) out of the scope for this plugin.

**Comment by dholth** [comment]
Looking for python 2 and pypy completions from a Python 3 vim...
On Sep 29, 2016 18:29, Daniel Hahler <notifications@github.com> wrote:That is what https://github.com/zchee/deoplete-jedi does and (at least for me) out of the scope for this plugin.

**Comment by blueyed** [comment]
Well, you can use Neovim and deoplete/deoplete-jedi then.

But this is not really a support channel.
Closing.
