### ISSUE TITLE
Pythoncomplete does not work with python3

### ISSUE THREAD

**Issue by clobrano** [davidhalter/jedi-vim#627]
### Issue
Pythoncomplete does not work with python3

### Steps to reproduce
1. Install jedi-vim with vim-plug package manager
2. Import sys; sys.

at the "dot" after sys, VIM replies with error:

Error: Required vim compiled with +python
E117 Unknown function: pythoncomplete#Complete

### Versions

 - jedi-vim: commit 9384d464eccfe8ff8a63393d622fafce0a4e7933
 - Vim / Neovim: VIM 7.4 +python3
 - Python: 3.5.2

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of the "JediDebugInfo" command (in a Python buffer)
Using Python version: 3
 - sys.version: 3.5.2 (default, Sep 10 2016, 08:21:44), [GCC 5.4.0 20160609]
 - site module: /usr/lib/python3.5/site.py
Jedi path: /home/carlolo/.vim/plugged/jedi-vim/jedi/jedi/__init__.py
Jedi version: 0.9.0
jedi-vim git version: 9384d46
jedi git submodule status:  995a6531225ba0b65e1ff863d97e5404d989047b jedi (v0.9.0-19-g995a653)

### Output of the "messages" Vim command
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"rem.py" 4L, 57C
E117: Unknown function: pythoncomplete#Complete
E117: Unknown function: pythoncomplete#Complete
 - sys.version: 3.5.2 (default, Sep 10 2016, 08:21:44), [GCC 5.4.0 20160609]
 - site module: /usr/lib/python3.5/site.py
Jedi path: /home/carlolo/.vim/plugged/jedi-vim/jedi/jedi/__init__.py
Jedi version: 0.9.0
 - sys.version: 3.5.2 (default, Sep 10 2016, 08:21:44), [GCC 5.4.0 20160609]
 - site module: /usr/lib/python3.5/site.py
Jedi path: /home/carlolo/.vim/plugged/jedi-vim/jedi/jedi/__init__.py
Jedi version: 0.9.0

**Comment by blueyed** [comment]
`pythoncomplete#Complete` is not jedi-vim's completion function.
Something else is overwriting it probably.

Check `:verb set omnifunc?`.

Note to self: include this in `:JediDebugInfo` + settings.

**Comment by clobrano** [comment]
Oops, sorry about that, it was one of my configuration files not updated

For the records
omnifunc=pythoncomplete#Complete

**Comment by tastyminerals** [comment]
I have the same issue. What should I do? Could you please be more specific?

**Comment by davidhalter** [comment]
Please open a new ticket, you don't exactly have the same issue, some things have changed in jedi-vim.
