### ISSUE TITLE
goto looks in dir tree before pythonpath?

### ISSUE THREAD

**Issue by davidszotten** [davidhalter/jedi-vim#629]
Hi,

I might be misunderstanding something, but i think this might be a bug:

It looks like jedi-vim traverses the current path before the python path when looking for modules, finding the wrong module:

```
$  tree
.
├── src
│   └── package
│       ├── __init__.py
│       └── __init__.pyc
└── tests
    └── package
        ├── __init__.py
        └── sub
            └── test.py


$  pwd
/root/project/tests/package/sub

$  PYTHONPATH=/root/project/src python -c'import package; print package.__file__'
/root/project/src/package/__init__.pyc

$ cat test.py
import package

$  PYTHONPATH=/root/project/src vim test.py

[cursor on "package", goto assignment]

speed: init 0.0003857612609863281
dbg: Parsed /root/project/tests/package/sub/test.py, with 1 parsers in 1 splits.
speed: parsed 0.015059947967529297
speed: import (<Name: package@1,7>,) 0.015541553497314453
dbg: search_module 'package' in '/root/project/tests/package/sub/test.py'
dbg: pickle loaded: '/root/project/tests/package/__init__.py'
"~/project/tests/package/__init__.py" 0L, 0C

# finds `tests/package`, not `src/package`
```

**Comment by blueyed** [comment]
Sounds like a Jedi issue.  Can you reproduce it using `jedi.Script(…).assignments()` (might be wrong)?
Does it also happen without `PYTHONPATH`?

**Comment by davidszotten** [comment]
no, jedi from python gets it right:

```
$  pwd
/root/project/tests/package/sub
$  PYTHONPATH=/root/project/src python
>>> [a.module_path for a in jedi.Script('import package').goto_assignments()]
['/root/project/src/package/__init__.py']
```

without `PYTHONPATH` i wouldn't even expect a regular import to work, since the package wouldn't be on `sys.path`

**Comment by blueyed** [comment]
Then what is the difference between `sys.path` for both cases?
Also ensure that you are using the same `jedi` version.
Is `VIRTUAL_ENV` involved?

**Comment by davidszotten** [comment]
no virtualenv in my example above. same jedi

`sys.path` inside vim includes `_vim_path_`, which sounds like it might be the culprit. not familiar enough with vim+python to know what that means

**Comment by davidhalter** [comment]
I personally think that VIM/python/custom python paths don't really work well together. If anything you should modify the path within vim (`:python sys.path.append...`).

**Comment by davidszotten** [comment]
switching to `:python` doesn't help. neither `:python sys.path.append...` nor `insert(0, ..)` makes a difference

**Comment by davidhalter** [comment]
Use `pip install -e .`.

**Comment by davidszotten** [comment]
still doesn't help i'm afraid. `python import package; print package.__file__` prints the correct file, but goto assignment still goes to the wrong place

**Comment by davidhalter** [comment]
Can you retry? Now with 0.12.0 I'm pretty sure this was fixed. You need to upgrade both jedi and jedi-vim though.

**Comment by davidszotten** [comment]
can confirm that upgrading fixes it. thanks!
