### ISSUE TITLE
Argument pop-up causes erroneous reflow

### ISSUE THREAD

**Issue by Tinche** [davidhalter/jedi-vim#63]
Hi. Here's a code snippet to help reproduce the issue.

```
#!/usr/bin/env python
class Module(object):
    def __init__(self, name, url=None):
        self.name = name
        self.url = url 

mods = [ 
    Module('jedi-vim', url='https://github.com/davidhalter/jedi-vim'),
    Module('', url='https://github.com/davidhalter/jedi-vim'),
]

another_list = []
```

Position the cursor to 10,12 (the first quote in the argument list of the second Module constructor in `mods`. Press I to enter insert mode. Move cursor one column to the left. Instead of displaying the argument pop-up correctly, the text one line above (which should have been overlaid by the pop-up) is mangled and broken up, and all code after the cursor seems to be syntax colored as being inside quotes (i.e. as a string - note another_list being colored red). See attached screenshots for clarification. Also the current line gets pushed down one line. 

Also interestingly, moving the cursor around within the parens seems to alternate showing and hiding the pop-up. If I move the cursor one line up (to the first module definition parens), it works properly.
![before](https://f.cloud.github.com/assets/1909233/42144/c1e1ba22-55ff-11e2-9a1b-13220d409c1b.png)
![after](https://f.cloud.github.com/assets/1909233/42148/2a4e9012-5600-11e2-98b5-31d91fb5c87f.png)

**Comment by ilyuha21st** [comment]
Hello, folks. It's possible to customize top-popup function parameter list color scheme?

**Comment by davidhalter** [comment]
No. :)

**Comment by ilyuha21st** [comment]
Thank, you.

**Comment by davidhalter** [comment]
Yes. Search the Readme for `show_call_signatures`.

**Comment by ilyuha21st** [comment]
thanks
