### ISSUE TITLE
Can't change mapping

### ISSUE THREAD

**Issue by vhoyer** [davidhalter/jedi-vim#630]
### Issue
I have mapped <leader>n and K to other things, I just wanna change/disable the jedi mappings but 
```
let g:jedi#documentation_command = ""
let g:jedi#usages_command = ""
```
don't work

### Steps to reproduce
I don't know what to enter here... since its not such difficult thing. I just press the <leader>n and, instead of what I've mapped I get the jedi-vim output even thought I changed the `g:jedi#...` variable.

### Versions

 - jedi-vim: 0.9.0
 - Vim / Neovim: 7.4
 - Python: 2.7.12 (output from python --version)

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of the "JediDebugInfo" command (in a Python buffer)
Using Python version: 3
 - sys.version: 3.5.2 (default, Sep 10 2016, 08:21:44), [GCC 5.4.0 20160609]
 - site module: /usr/lib/python3.5/site.py
Jedi path: /home/vhoyer/.vim/bundle/jedi-vim/jedi/jedi/__init__.py
Jedi version: 0.9.0
jedi-vim git version: 0.8.0-43-g9384d46
jedi git submodule status:  995a6531225ba0b65e1ff863d97e5404d989047b jedi (v0.9.0-19-g995a653)

### Output of the "messages" Vim command
NERDTree: CWD is now: /home/vhoyer/Documents/python/
"test.py" 8L, 174C
 - sys.version: 3.5.2 (default, Sep 10 2016, 08:21:44), [GCC 5.4.0 20160609]
 - site module: /usr/lib/python3.5/site.py
Jedi path: /home/vhoyer/.vim/bundle/jedi-vim/jedi/jedi/__init__.py
Jedi version: 0.9.0
 - sys.version: 3.5.2 (default, Sep 10 2016, 08:21:44), [GCC 5.4.0 20160609]
 - site module: /usr/lib/python3.5/site.py
Jedi path: /home/vhoyer/.vim/bundle/jedi-vim/jedi/jedi/__init__.py
Jedi version: 0.9.0

### Output of "scriptnames" Vim command
  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim74/debian.vim
  3: /usr/share/vim/vim74/syntax/syntax.vim
  4: /usr/share/vim/vim74/syntax/synload.vim
  5: /usr/share/vim/vim74/syntax/syncolor.vim
  6: /usr/share/vim/vim74/filetype.vim
  7: ~/.vimrc
  8: ~/.plugins.vim
  9: /usr/share/vim/vim74/ftoff.vim
 10: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 11: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 12: /usr/share/vim/vim74/ftplugin.vim
 13: /usr/share/vim/vim74/indent.vim
 14: /usr/share/vim/vim74/syntax/nosyntax.vim
 15: ~/.vim/bundle/gruvbox/colors/gruvbox.vim
 16: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
 17: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 18: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 19: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 20: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 21: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 22: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 23: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 24: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 25: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 26: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 27: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 28: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 29: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 30: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 31: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 32: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 33: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 34: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 35: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 36: ~/.vim/bundle/supertab/plugin/supertab.vim
 37: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 38: ~/.vim/bundle/vim-airline/plugin/airline.vim
 39: ~/.vim/bundle/vim-airline/autoload/airline.vim
 40: ~/.vim/bundle/vim-airline/autoload/airline/init.vim
 41: ~/.vim/bundle/vim-airline/autoload/airline/parts.vim
 42: ~/.vim/bundle/syntastic/plugin/syntastic/autoloclist.vim
 43: ~/.vim/bundle/syntastic/plugin/syntastic/balloons.vim
 44: ~/.vim/bundle/syntastic/plugin/syntastic/checker.vim 
 45: ~/.vim/bundle/syntastic/plugin/syntastic/cursor.vim
 46: ~/.vim/bundle/syntastic/plugin/syntastic/highlighting.vim
 47: ~/.vim/bundle/syntastic/plugin/syntastic/loclist.vim
 48: ~/.vim/bundle/syntastic/plugin/syntastic/modemap.vim
 49: ~/.vim/bundle/syntastic/plugin/syntastic/notifiers.vim
 50: ~/.vim/bundle/syntastic/plugin/syntastic/registry.vim
 51: ~/.vim/bundle/syntastic/plugin/syntastic/signs.vim
 52: ~/.vim/bundle/syntastic/plugin/syntastic.vim
 53: ~/.vim/bundle/syntastic/autoload/syntastic/util.vim
 54: ~/.vim/bundle/vdebug/plugin/vdebug.vim
 55: ~/.vim/bundle/ctrlp.vim/plugin/ctrlp.vim
 56: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/mrufiles.vim
 57: ~/.vim/bundle/nerdcommenter/plugin/NERD_commenter.vim
 58: ~/.vim/bundle/taglist.vim/plugin/taglist.vim
 59: ~/.vim/bundle/vim-markdown-preview/plugin/vim-markdown-preview.vim
 60: ~/.vim/bundle/bclose.vim/plugin/bclose.vim
 61: ~/.vim/bundle/vim-snippets/plugin/vimsnippets.vim
 62: ~/.vim/bundle/vim-surround/plugin/surround.vim
 63: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 64: /usr/share/vim/vim74/plugin/gzip.vim
 65: /usr/share/vim/vim74/plugin/logiPat.vim
 66: /usr/share/vim/vim74/plugin/matchparen.vim
 67: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 68: /usr/share/vim/vim74/plugin/rrhelper.vim
 69: /usr/share/vim/vim74/plugin/spellfile.vim
 70: /usr/share/vim/vim74/plugin/tarPlugin.vim
 71: /usr/share/vim/vim74/plugin/tohtml.vim
 72: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 73: /usr/share/vim/vim74/plugin/zipPlugin.vim
 74: ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
 75: ~/.vim/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
 76: ~/.vim/bundle/vim-airline/autoload/airline/extensions/netrw.vim
 77: ~/.vim/bundle/vim-airline/autoload/airline/extensions/ctrlp.vim
 78: ~/.vim/bundle/vim-airline/autoload/airline/extensions/branch.vim
 79: ~/.vim/bundle/vim-airline/autoload/airline/extensions/syntastic.vim
 80: ~/.vim/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
 81: ~/.vim/bundle/vim-airline/autoload/airline/extensions/po.vim
 82: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
 83: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline.vim
 84: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/autoshow.vim
 85: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/tabs.vim
 86: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buffers.vim
 87: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
 88: ~/.vim/bundle/vim-airline/autoload/airline/section.vim
 89: ~/.vim/bundle/vim-airline/autoload/airline/highlighter.vim
 90: ~/.vim/bundle/gruvbox/autoload/airline/themes/gruvbox.vim
 91: ~/.vim/bundle/vim-airline/autoload/airline/themes.vim
 92: ~/.vim/bundle/vim-airline/autoload/airline/util.vim
 93: ~/.vim/bundle/vim-airline/autoload/airline/builder.vim
 94: ~/.vim/bundle/vim-airline/autoload/airline/extensions/default.vim
 95: ~/.vim/bundle/syntastic/autoload/syntastic/log.vim
 96: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/buflist.vim
 97: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim
 98: /usr/share/vim/vim74/scripts.vim
 99: ~/.vim/bundle/nerdtree/syntax/nerdtree.vim
100: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/utils.vim
101: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
102: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
103: /usr/share/vim/vim74/ftplugin/python.vim
104: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
105: /usr/share/vim/vim74/indent/python.vim
106: /usr/share/vim/vim74/syntax/python.vim
107: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
108: ~/.vim/view/~=+Documents=+dev-env=+hello_bottle=+hello.py=
109: /usr/share/vim/vim74/ftplugin/text.vim
110: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount/formatters/default.vim
111: /usr/share/vim/vim74/ftplugin/help.vim
112: /usr/share/vim/vim74/syntax/help.vim
113: /usr/share/vim/vim74/ftplugin/vim.vim
114: /usr/share/vim/vim74/indent/vim.vim
115: /usr/share/vim/vim74/syntax/vim.vim
116: /usr/share/vim/vim74/syntax/lua.vim
117: /usr/share/vim/vim74/syntax/perl.vim
118: /usr/share/vim/vim74/syntax/pod.vim
119: /usr/share/vim/vim74/syntax/ruby.vim
120: ~/.vim/view/~=+.plugins.vim=
121: ~/.vim/view/~=+.vimrc=
122: ~/.vim/bundle/syntastic/syntax_checkers/vim/vimlint.vim
123: ~/.vim/bundle/syntastic/syntax_checkers/vim/vint.vim

**Comment by davidhalter** [comment]
As a starter, `let g:jedi_vim#docunetation_command = ""` seems to have an issue in it. Might this be the issue?

**Comment by vhoyer** [comment]
about the misspelling, its correct in the vimrc. but how do I check for execution order?

**Comment by davidhalter** [comment]
Can you post your vimrc?

**Comment by vhoyer** [comment]
https://github.com/vhoyer/dotfiles/blob/master/.vimrc

**Comment by davidhalter** [comment]
You load the plugins in the beginning and in the end you change the Jedi settings. t  has to be he other way around.

**Comment by blueyed** [comment]
@davidhalter 
Not necessarily: he appears to use vim-plug..
@vhoyer 
I recommend adding some `echom` into jedi-vim and your vimrc to figure out what is happening

**Comment by blueyed** [comment]
@vhoyer 
Use `:verb map ,n` to see where the mapping comes from (assuming `,` is your leader key).

**Comment by vhoyer** [comment]
@blueyed this is the output from `verb map <space>n` (<space> is my leader)
```
n  <Space>n    *@:call jedi#usages()<CR>
        Last set from ~/.vim/view/~=+Documents=+anos.py=
   <Space>n      :NERDTreeToggle<CR>
        Last set from ~/.vimrc
```
but just on *.py files, I assume that, since jedi-vim loads only on python files, it overlaps my keymapping because it loads afterwards. But, haven't looked at the code, can't tell for sure

**Comment by blueyed** [comment]
Are you using https://github.com/kopischke/vim-stay?

The mapping comes from a view file, I.e. it was saved and restored like that.

**Comment by blueyed** [comment]
See http://vimdoc.sourceforge.net/htmldoc/options.html#'viewoptions'.
Recommended by vim-stay: set viewoptions=cursor,folds,slash,unix

You have probably "options" in there.  You could keep it, but should remove the old view files then probably.
