### ISSUE TITLE
force_py_version to python2 does not work on Ubuntu 16.10

### ISSUE THREAD

**Issue by thekswenson** [davidhalter/jedi-vim#631]
### Issue

I've added `let g:jedi#force_py_version = 2` to my .vimrc.
This yields the error message:

> Error detected while processing function jedi#init_python:
> line    7:
> Error: jedi-vim failed to initialize Python: Could not setup g:jedi#force_py_ver
> sion: jedi#setup_py_version: Vim(pyfile):E319: Sorry, the command is not availab
> le in this version: pyfile /home/kms/.vim/bundle/jedi-vim/initialize.py (in func
> tion jedi#init_python[3]..<SNR>33_init_python, line 6)
> Error detected while processing function jedi#init_python[3]..<SNR>33_init_pytho
> n[4]..jedi#force_py_version[2]..jedi#setup_py_version:
> line   14:
> E319: Sorry, the command is not available in this version: pyfile /home/kms/.vim
> /bundle/jedi-vim/initialize.py
### Steps to reproduce
1. Install Ubuntu 16.10
2. Install jedi-vim
3. add `let g:jedi#force_py_version = 2` to your .vimrc
4. open a python file and see error message
### Versions
- jedi-vim: [master] 0.8.0-47-ge66c2e1
- Vim / Neovim: 7.4.1829
- Python: 2.7.12+

In case you are not using jedi-vim from Git master, please test it there, too.
### Output of the "messages" Vim command

> Error detected while processing function jedi#init_python:
> line    7:
> Error: jedi-vim failed to initialize Python: Could not setup g:jedi#force_py_ver
> sion: jedi#setup_py_version: Vim(pyfile):E319: Sorry, the command is not availab
> le in this version: pyfile /home/kms/.vim/bundle/jedi-vim/initialize.py (in func
> tion jedi#init_python[3]..<SNR>33_init_python, line 6)
> Error detected while processing function jedi#init_python[3]..<SNR>33_init_pytho
> n[4]..jedi#force_py_version[2]..jedi#setup_py_version:
> line   14:
> E319: Sorry, the command is not available in this version: pyfile /home/kms/.vim
> /bundle/jedi-vim/initialize.py
### Output of "scriptnames" Vim command

  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim74/debian.vim
  3: /usr/share/vim/vim74/syntax/syntax.vim
  4: /usr/share/vim/vim74/syntax/synload.vim
  5: /usr/share/vim/vim74/syntax/syncolor.vim
  6: /usr/share/vim/vim74/filetype.vim
  7: ~/.vimrc
  8: /usr/share/vim/vim74/ftoff.vim
  9: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 10: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 11: /usr/share/vim/vim74/ftplugin.vim
 12: /usr/share/vim/vim74/indent.vim
 13: /usr/share/vim/vim74/indoff.vim
 14: /usr/share/vim/vim74/syntax/nosyntax.vim
 15: ~/.vim/colors/Dark2_kms.vim
 16: ~/.vim/bundle/supertab/plugin/supertab.vim
 17: ~/.vim/bundle/csapprox/plugin/CSApprox.vim
 18: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 19: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 20: /usr/share/vim/vim74/plugin/gzip.vim
 21: /usr/share/vim/vim74/plugin/logiPat.vim
 22: /usr/share/vim/vim74/plugin/manpager.vim
 23: /usr/share/vim/vim74/plugin/matchparen.vim
 24: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 25: /usr/share/vim/vim74/plugin/rrhelper.vim
 26: /usr/share/vim/vim74/plugin/spellfile.vim
 27: /usr/share/vim/vim74/plugin/tarPlugin.vim
 28: /usr/share/vim/vim74/plugin/tohtml.vim
 29: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 30: /usr/share/vim/vim74/plugin/zipPlugin.vim
 31: ~/.vim/bundle/csapprox/after/plugin/CSApprox.vim
 32: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 33: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 34: ~/.vim/bundle/SimpylFold/ftplugin/python/SimpylFold.vim
 35: /usr/share/vim/vim74/ftplugin/python.vim
 36: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 37: /usr/share/vim/vim74/syntax/python.vim
 38: ~/.vim/bundle/jedi-vim/after/syntax/python.vim

**Comment by davidhalter** [comment]
`:version`?

**Comment by blueyed** [comment]
> E319: Sorry, the command is not available in this version: pyfile 

Would we useful to know if "+python" is in `:version` indeed - probably just not built with Python..

**Comment by blueyed** [comment]
Maybe this Vim is only built against Python 3, if at all?!

**Comment by thekswenson** [comment]
> :version
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 17 2016 07:39:04)
> Included patches: 1-1829
> Modified by pkg-vim-maintainers@lists.alioth.debian.org
> Compiled by pkg-vim-maintainers@lists.alioth.debian.org
> Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
> +acl             +conceal         +file_in_path    +linebreak       -mouse_sysmouse  +python3         +tcl             +wildignore
> +arabic          +cryptv          +find_in_path    +lispindent      +mouse_urxvt     +quickfix        +termguicolors   +wildmenu
> +autocmd         +cscope          +float           +listcmds        +mouse_xterm     +reltime         +terminfo        +windows
> +balloon_eval    +cursorbind      +folding         +localmap        +multi_byte      +rightleft       +termresponse    +writebackup
> +browse          +cursorshape     -footer          +lua             +multi_lang      +ruby            +textobjects     +X11
> ++builtin_terms  +dialog_con_gui  +fork()          +menu            -mzscheme        +scrollbind      +timers          -xfontset
> +byte_offset     +diff            +gettext         +mksession       +netbeans_intg   +signs           +title           +xim
> +channel         +digraphs        -hangul_input    +modify_fname    +packages        +smartindent     +toolbar         +xsmp_interact
> +cindent         +dnd             +iconv           +mouse           +path_extra      +startuptime     +user_commands   +xterm_clipboard
> +clientserver    -ebcdic          +insert_expand   +mouseshape      +perl            +statusline      +vertsplit       -xterm_save
> +clipboard       +emacs_tags      +job             +mouse_dec       +persistent_undo -sun_workshop    +virtualedit     +xpm
> +cmdline_compl   +eval            +jumplist        +mouse_gpm       +postscript      +syntax          +visual
> +cmdline_hist    +ex_extra        +keymap          -mouse_jsbterm   +printer         +tag_binary      +visualextra
> +cmdline_info    +extra_search    +langmap         +mouse_netterm   +profile         +tag_old_static  +viminfo
> +comments        +farsi           +libcall         +mouse_sgr       -python          -tag_any_white   +vreplace
>    system vimrc file: "$VIM/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>   system gvimrc file: "$VIM/gvimrc"
>     user gvimrc file: "$HOME/.gvimrc"
> 2nd user gvimrc file: "~/.vim/gvimrc"
>     system menu file: "$VIMRUNTIME/menu.vim"
>   fall-back for $VIM: "/usr/share/vim"
> Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/u
> sr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/us
> r/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1
> .0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include
> /libgnomeui-2.0 -I/usr/include/gnome-keyring-1 -I/usr/include/libbonoboui-2.0 -I/usr/include/libxml2 -I/usr/include/libgnome-2.0 -I/usr/include/
> libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/orbit-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.0 -I/usr/inc
> lude/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/incl
> ude/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/includ
> e/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/gnome-vfs-2.0
> -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I
> /usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-se
> curity -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
> Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-funct
> ions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0
>  -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnome-2 -lpopt -lb
> onobo-2 -lbonobo-activation -lORBit-2 -lgnomecanvas-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpa
> ngoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgdk_pixbuf-2.0 -lgnomevfs-2 -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -lSM
>  -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector
> -strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-
> linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -
> ldl -lcrypt -lm
>

**Comment by thekswenson** [comment]
There is no "+python", only "+python3".
Does this mean I have to request the Ubuntu packagers to include "python" when compiling?

**Comment by davidhalter** [comment]
Hmm it probably depends which vim package you're using. I'm using ubuntu as well, but it works for me (14.04).

**Comment by thekswenson** [comment]
This was the issue.  One must install vim-gnome-py2 rather than the Ubuntu default vim-gnome.

**Comment by thekswenson** [comment]
For Ubuntu 17.04 I had to follow these instruction to get jedi-vim to work with python2:  https://askubuntu.com/a/775073/14747

**Comment by thekswenson** [comment]
For Ubuntu 17.10, I have yet to find a solution for this.  The ppa:pi-rho/dev has no vim for Artful :(.

**Comment by davidhalter** [comment]
I think I'm using vim-gtk. Ubuntu 16.04 though.

**Comment by thekswenson** [comment]
I found a way to use the 17.04 packages with 17.10 from pi-rho:  https://askubuntu.com/a/982986/14747.
