### ISSUE TITLE
function call signatures in insert mode wraps erroneously

### ISSUE THREAD

**Issue by thekswenson** [davidhalter/jedi-vim#632]
### Issue
When adding a function call the pop-up call signature often needlessly wraps to span 2 lines.
Here is an example:

![wrap](https://cloud.githubusercontent.com/assets/9959942/19902989/3dcbdc38-a06d-11e6-944e-db86a1cc7b70.png)

### Steps to reproduce

1. create a python file
2. type a funciton call

### Versions

 - jedi-vim:  [master] 0.8.0-47-ge66c2e1
 - Vim / Neovim:  7.4.1829
 - Python:  2.7.12+

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of "scriptnames" Vim command

>   1: /usr/share/vim/vimrc
>   2: /usr/share/vim/vim74/debian.vim
>   3: /usr/share/vim/vim74/syntax/syntax.vim
>   4: /usr/share/vim/vim74/syntax/synload.vim
>   5: /usr/share/vim/vim74/syntax/syncolor.vim
>   6: /usr/share/vim/vim74/filetype.vim
>   7: ~/.vimrc
>   8: /usr/share/vim/vim74/ftoff.vim
>   9: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
>  10: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
>  11: /usr/share/vim/vim74/ftplugin.vim
>  12: /usr/share/vim/vim74/indent.vim
>  13: /usr/share/vim/vim74/indoff.vim
>  14: /usr/share/vim/vim74/syntax/nosyntax.vim
>  15: ~/.vim/colors/Dark2_kms.vim
>  16: ~/.vim/bundle/supertab/plugin/supertab.vim
>  17: ~/.vim/bundle/csapprox/plugin/CSApprox.vim
>  18: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
>  19: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
>  20: /usr/share/vim/vim74/plugin/gzip.vim
>  21: /usr/share/vim/vim74/plugin/logiPat.vim
>  22: /usr/share/vim/vim74/plugin/manpager.vim
>  23: /usr/share/vim/vim74/plugin/matchparen.vim
>  24: /usr/share/vim/vim74/plugin/netrwPlugin.vim
>  25: /usr/share/vim/vim74/plugin/rrhelper.vim
>  26: /usr/share/vim/vim74/plugin/spellfile.vim
>  27: /usr/share/vim/vim74/plugin/tarPlugin.vim
>  28: /usr/share/vim/vim74/plugin/tohtml.vim
>  29: /usr/share/vim/vim74/plugin/vimballPlugin.vim
>  30: /usr/share/vim/vim74/plugin/zipPlugin.vim
>  31: ~/.vim/bundle/csapprox/after/plugin/CSApprox.vim
>

**Comment by davidhalter** [comment]
So you do have that problem if your terminal is big enough to show 

What's your `:set wrap?`

**Comment by thekswenson** [comment]
"wrap" is set.
In this case, the problem occurs even when the terminal is wide enough to show the call signature.

The problem does not occur when "nowrap" is set.

The problem has something to do with the number of characters in the line above the one I'm editing (the line that is written over with the call signature:   if I delete the right number of characters from the line above, then the error will not occur.
Also, if I resize the width of the terminal I can make wide enough so that the wrap doesn't occur.

**Comment by blueyed** [comment]
Have you tried using the ccmdline-window mode instead?

**Comment by blueyed** [comment]
There might be a bug here for sure, but it seems none of the maintainers is eager to investigate, so also please feel free to do so yourself.. :)

**Comment by blueyed** [comment]
Please try/test #652 and provide feedback there - it might help in your case.
See https://help.github.com/articles/checking-out-pull-requests-locally/ for help on checking it out locally.

**Comment by thekswenson** [comment]
I've checkout out your pull request locally.
It doesn't seem to alleviate the problem...
  I see identical behavior.

**Comment by blueyed** [comment]
The issue is weird in general.
Do you see it often?

Can you try it with a minimal vimrc, and/or bisect which other plugin might cause it?

**Comment by davidhalter** [comment]
Same issue as #493. We are trying to get rid of changing the buffer for this feature and are trying to use floating windows.
