### ISSUE TITLE
"No documentation found for that" with user-defined functions in a different directory 

### ISSUE THREAD

**Issue by thekswenson** [davidhalter/jedi-vim#637]
### Issue
Consider a user-defined module where a function is imported with a line like
`from mymodule import myfunction`
jedi-vim does not bring me to the function definition when typing `<leader>d`, if the modules is not in the same directory as the file I'm editing. It instead gives the message "jedi-vim: No documentation found for that" . Similarly, typing `<Shift>k` gives the same error message.

### Steps to reproduce
1. Unzip the attached archive.
[jedivimdoctest.tar.gz](https://github.com/davidhalter/jedi-vim/files/602341/jedivimdoctest.tar.gz)
2. open jedivimdoctest/main.py
3. move the cursor to "closefunc()" and type `<Shift>k`, see that the docstring is printed.
4. move the cursor to "farfunc()" and type `<Shift>k`, see that the docstring is not printed and the error message "jedi-vim: No documentation found for that." is printed.

### Versions

 - jedi-vim:  [master] 0.8.0-47-ge66c2e1
 - Vim / Neovim: 7.4.1829
 - Python: 2.7.12+

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of "scriptnames" Vim command

> 1: /usr/share/vim/vimrc
> 2: /usr/share/vim/vim74/debian.vim
> 3: /usr/share/vim/vim74/syntax/syntax.vim
> 4: /usr/share/vim/vim74/syntax/synload.vim
> 5: /usr/share/vim/vim74/syntax/syncolor.vim
> 6: /usr/share/vim/vim74/filetype.vim
> 7: ~/.vimrc
> 8: /usr/share/vim/vim74/ftoff.vim
> 9: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
> 10: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
> 11: /usr/share/vim/vim74/ftplugin.vim
> 12: /usr/share/vim/vim74/indent.vim
> 13: /usr/share/vim/vim74/indoff.vim
> 14: /usr/share/vim/vim74/syntax/nosyntax.vim
> 15: ~/.vim/colors/Dark2_kms.vim
> 16: ~/.vim/bundle/supertab/plugin/supertab.vim
> 17: ~/.vim/bundle/csapprox/plugin/CSApprox.vim
> 18: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
> 19: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
> 20: /usr/share/vim/vim74/plugin/gzip.vim
> 21: /usr/share/vim/vim74/plugin/logiPat.vim
> 22: /usr/share/vim/vim74/plugin/manpager.vim
> 23: /usr/share/vim/vim74/plugin/matchparen.vim
> 24: /usr/share/vim/vim74/plugin/netrwPlugin.vim
> 25: /usr/share/vim/vim74/plugin/rrhelper.vim
> 26: /usr/share/vim/vim74/plugin/spellfile.vim
> 27: /usr/share/vim/vim74/plugin/tarPlugin.vim
> 28: /usr/share/vim/vim74/plugin/tohtml.vim
> 29: /usr/share/vim/vim74/plugin/vimballPlugin.vim
> 30: /usr/share/vim/vim74/plugin/zipPlugin.vim
> 31: ~/.vim/bundle/csapprox/after/plugin/CSApprox.vim

**Comment by davidhalter** [comment]
Not sure if it's a bug, but I have trouble with my local branches at the moment. let me first fix them.

But now I think I see: There's a good chance that the issue is your sys_path modification. Jedi is still not very good in recognizing and calculating them. It's kind of hard as well.

Also sys.path modifications are generally wrong anyway. Design your code in a way where stuff is on Python path (in libraries or WITHIN your module).

**Comment by thekswenson** [comment]
Thanks for the feedback.

Is this really bad practice to modify sys_path...
   do you know a simple way to obtain the same functionality without the user having to do anything?
I was under the impression that this was a very nice solution.

**Comment by davidhalter** [comment]
No it's not ;-) It's considered a pretty bad practice in the Python world. Most people just use proper packages with `__init__.py` and stuff. Also there is `pip install -e .`.

I think this book could help you. It's pretty long, but I think know-how abut Python project setups is pretty big.

http://docs.python-guide.org/en/latest/writing/structure/

**Comment by thekswenson** [comment]
Thanks for the tip and the reference!
