### ISSUE TITLE
Confliction with Valloric/vim-operator-highlight

### ISSUE THREAD

**Issue by Aulddays** [davidhalter/jedi-vim#639]
### Issue
I happen to have Valloric/vim-operator-highlight plugin installed in my vim.
When I use jedi-vim together with it, the parameter suggestions (when I typed some function name and type a '(' ) are broken (Or to be precise, broken in most cases, except the line above current line happens to be comments or a string). Instead, it shows something like:

> =\`=jedi=0, =\`=(*_*file*_*, keys) =\`=jedi=\`=

The reason is that jedi-vim uses "=`=" as the syntax match pattern to show the parameter suggestion box (syn match jediXXX's defined in after/syntax/python.vim and autoload/jedi.vim).
Unfortunately, vim-operator-highlight highlights that '=', preventing jediFunction from being syntax matched.

The solution is simple: in .vimrc, let g:jedi#call_signature_escape to be something else that would not be affected by vim-operator-highlight.
This is apparently not an issue of jedi-vim. However, maybe the author may consider putting some comments on it in the documentation, in case that others may face a similar condition where the syntax matching are broken by some other stuff.

Thanks for the great plugin the author made.

**Comment by davidhalter** [comment]
It's pretty well known that call signatures in Jedi are hacky and that it might collide with other syntax modifications. I'm not sure how to document that very well. 

It's not something that belongs in the README, but we could document it better in `docs/jedi-vim.txt`. So if you have a good place to document that in feel free to PR.

In general I think the README should be rather short(er) and we should point to the docs.

**Comment by blueyed** [comment]
Maybe there could be a better default for g:jedi#call_signature_escape?!

**Comment by davidhalter** [comment]
I think it doesn't really matter what it is, it will always collide with something. It needs to be ascii, consist of multiple characters and not the same ones.

The only improvement that I can imagine is using non-python operators. It's unlikely that people will do syntax modifications on those. `?` and `!` are the only characters that are not used, AFAIK. The backtick is only used in Python 2.

I would be perfectly fine with a default of `?!?`. I think that is better for a large part of the Python community.

**Comment by blueyed** [comment]
`?!?` sounds good.
@Aulddays 
Do you feel like creating a PR to change this?

**Comment by Aulddays** [comment]
Thanks for the quick replies.
When I came across the problem, Google led me to a few discussions on after/syntax/python.vim failing on setting up Conceal, which was unfortunately not my case. It took me some time to figure things out since I'm not quite familiar with vim plugins. Since I did not find something on Google, I though it may be a rare condition. However, as @davidhalter mentioned, it is actually kind of well-known, so maybe we could give some clue in FAQ section in readme and linking to docs/jedi-vim.txt.
@blueyed and @davidhalter Actually I have never created a PR before, and It seems to be fun to give it a shot.

**Comment by davidhalter** [comment]
Thanks mate! You did well. :)

**Comment by igavrilov** [comment]
This commit (a69e6b8cc022d1f2ef65333c2e7b81f2f13cd7f9) broke signature popup for me. Any ideas?
<img width="587" alt="screen shot 2016-12-08 at 11 16 02" src="https://cloud.githubusercontent.com/assets/5064741/21002887/2ecd1402-bd39-11e6-8d39-96555c62b571.png">

**Comment by igavrilov** [comment]
I believe it also will cause a failure in test/signatures.vim.

**Comment by davidhalter** [comment]
Can you disable all your grammar modifications and color schemes and retry

**Comment by davidhalter** [comment]
https://github.com/davidhalter/jedi-vim/pull/646 should fix this.
