### ISSUE TITLE
Unknown function: jedi#init_python

### ISSUE THREAD

**Issue by ryanfakir** [davidhalter/jedi-vim#648]
### Issue
when running .py I got log like this:

`Error detected while processing C:\Users\pyan\.vim\bundle\jedi-vim\after\ftplugin
    \python\jedi.vim:
    line    1:
    E117: Unknown function: jedi#init_python
    E15: Invalid expression: !jedi#init_python()
    line    5:
    E121: Undefined variable: g:jedi#auto_initialization
    E15: Invalid expression: g:jedi#auto_initialization
    Error detected while processing C:\Users\pyan\.vim\bundle\jedi-vim\after\syntax\p
    ython.vim:
    line    1:
    E117: Unknown function: jedi#init_python
    E15: Invalid expression: !jedi#init_python()
    line    8:
    E121: Undefined variable: g:jedi#show_call_signature_escape
    E15: Invalid expression: g:jedi#show_call_signatures_escape `
### Versions

 - jedi-vim: most latest one i believe since I use vundle to update plugins
 - Vim / Neovim:VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  9 2016 08:08:03)
Included patches: 1-1721

 - Python: 2.7.2 and 3.5.2
I am on window 10, I am not sure this issue is from vundle or from jedi-vim
I echo globpath(&rtp, 'autoload/vundle.vim') the output is directory of bundle\Vundle.vm\autoload\vundle.vim. Which is good I think.

**Comment by davidhalter** [comment]
Since nobody ever looked at this, please provide `:JediDebugInfo` with the latest jedi-vim.

**Comment by abracwan** [comment]
Apologies for posing on a stale issue. I think it is an issue with Vundle. I use Pathogen as my plugin manager, and when I was messing around with its configuration, I was able to produce a similar issue to what you got. So you can just re-install Vundle and hopefully all will be fine.

**Comment by davidhalter** [comment]
I'm closing, since `:JediDebugInfo` was never provided.
