### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by fayimora** [davidhalter/jedi-vim#649]
### Issue
I installed this lovely plugin and thought autocomplete wasn't working until I realised that the library was only installed with `pip3`. I set the plugin to python 3 using `let g:jedi#force_py_version = 3` but got this error:
![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-30-18-11-01.png)

I did some research and thought perhaps compiling vim with`python3` will solve the issue but I got an error saying the plugin requires vim to be compiled with `python`. I couldn't get vim to compile with both versions as it seems only one can exist on a macbook so I'm not sure where to go from here.

Question: How do I get the plugin to work with python 3? I'm happy to change `force_py_version` on a per project basis if necessary.

### Versions

 - jedi-vim: master
 - Vim / Neovim: Vim 8.0.124
 - Python: 3

**Comment by blueyed** [comment]
> but I got an error saying the plugin requires vim to be compiled with `python`

Are you sure you had `+python3` then in `:ver`?

I recommend using Neovim, which allows for both Python 2 and 3.

**Comment by fayimora** [comment]
@blueyed yes I had `+python3` but `-python`

**Comment by fayimora** [comment]
The error I get. ![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-30-23-53-23.png)

**Comment by blueyed** [comment]
You should find out where that error comes from then..
E.g. by grepping your plugins.

**Comment by fayimora** [comment]
Yeah seems it might to be coming from `neocomplete` 

![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2017-01-01-01-39-55.png)

**Comment by blueyed** [comment]
You should grep for the Error message also.

**Comment by blueyed** [comment]
Closing since it is not a jedi-vim issue.

**Comment by fayimora** [comment]
@blueyed with virtualenv, shouldn't this work? I think the issue I'm having is actually with pip installed packages and virtualenv, not python2/3. For instance, I can't seem to jump into definitions for pip installed packages(django, flask e.t.c) but builtins work just fine. However, it actually finds the definition in the system python, not my virtual environment.

**Comment by blueyed** [comment]
Have you set `$VIRTUAL_ENV`?
Search the existing issues, IIRC it was discussed here a few times already.
