### ISSUE TITLE
Autocompletion cache across sessions?

### ISSUE THREAD

**Issue by imaluengo** [davidhalter/jedi-vim#653]
I've installed jedi-vim in a chrooted Chromebook (not too quick arm processor).

Upon opening a file and trying to autocomplete numpy as `np.<C-Space>` the first time it takes a long time (few seconds), then the cache seems to do its work and jedi autocompletion works instantly.

However, if I close vim and open it again, it will take another ~10 seconds to populate the cache for numpy again. 

Is it the expected behaviour or is there something wrong? Is it possible to save the autocompletion cache for some modules across vim sessions? (or just closing and openning vim). If so, how can I do it?

Thanks

**Comment by blueyed** [comment]
AFAIK Jedi itself caches here only - and probably in some way that the jedi-vim requests gets not considered for it.

I think this should work like you expect it to work.

**Comment by davidhalter** [comment]
I'm pretty sure the chromebook is loading the parser cache (which can also take quite a while). I'm not sure we can help you, because there's caching in place. It's just not that fast on your computer.

**Comment by blueyed** [comment]
@imaluengo 
Can you check if removing Jedi's disk cache (typically in `~/.cache/jedi/`) has the same effect, or is it even slower than after a Vim restart (which would be expected).

**Comment by avillani** [comment]
hi,
I have a similar problem.
If I write `import numpy as np` and then `np.`, it takes ages before options are displayed. Some files are written in the cache. i f i close the file, reopens and dot `np.`, takes ages again.
If I deletes ~/.cache/jedi, it doesn't change the behavior, and i see files poping up when i type `np.`

My $HOME has a dot in the name... : '/home/local/EMSE2000/firstname.name'

Hope it helps.

**Comment by napseis** [comment]
hi,
I have a similar problem.
If I write import numpy as np and then np., it takes ages before options are displayed. Some files are written in the cache. i f i close the file, reopens and dot np., takes ages again.
If I deletes ~/.cache/jedi, it doesn't change the behavior, and i see files poping up when i type np.

My $HOME has a dot in the name... : '/home/local/EMSE2000/firstname.name'

Hope it helps.

**Comment by ekiefl** [comment]
I have the same issue, except in some cases it is intolerably slow (minutes). I'm not sure where jedi is storing a cache, so I can't check if its even slower without it. I checked ~/.cache/jedi but its not there.

**Comment by blueyed** [comment]
It is in `~/.cache/jedi/` for me.

**Comment by davidhalter** [comment]
Dear all, sorry I cannot help you for now. There's no way we don't either parse a lot (really A LOT) of files or load them from cache. Maybe the next Jedi version will be 10% better, but it won't magically be awesome. I have ideas to improve it, but it will take some time and is not guaranteed. On a modern laptop it doesn't take ages, but I know that on chromebooks and the like it will take quite a loooong time. I'm sorry for that, but it will not change soon and even if, this is the wrong issue tracker for it. It's all about jedi, not jedi-vim.

For now you will just have to either remove jedi-vim or use something like YCM.
