### ISSUE TITLE
Jedi not working with venv module of Python3

### ISSUE THREAD

**Issue by notpratheek** [davidhalter/jedi-vim#655]
### Issue

Jedi doesn't seem to support the ```venv``` virtual environment module that is provided by default in python, since python 3.3

Is there a way to get this working ?

(Also, I'm using python3 mainly, but when I checked with ```JediDebugInfo```, it seems to load only python2 and not python3. Is there a way choose which version of python to load and use ?)

### Steps to reproduce

1. Create a new virtual env with the provided ```venv``` module of python3
```$ python3 -m venv testdir```
2. Activate the newly created virtual env
```
$ cd testdir
$ . bin/activate
(testdir)$ 
```
3. Start typing code
```
(testdir)$ gvim hello.py
```

---

(Additional steps, if necessary)
(2.1 Install a package of your choice, Eg: Django)
```
(testdir)$ python3 -m pip install django
```
(2.2 have auto complete support for the Django package, that is installed in this virtual env)
```
(testdir)$ gvim ./mysite/polls/views.py
```

---

### Versions

 - jedi-vim:
(Using the master branch of the plugin, with the following commit) : 9384d464eccfe8ff8a63393d622fafce0a4e7933

- jedi (the submodule):

cloned it as submodule itself, with in this plugin. It has the commit ID: 
[995a6531225ba0b65e1ff863d97e5404d989047b](https://github.com/davidhalter/jedi/tree/995a6531225ba0b65e1ff863d97e5404d989047b)

 - Vim / Neovim:
Mainly using vim (gvim), it's version is: 

```
$ gvim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2017 09:36:31)
Included patches: 1-142
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"

```

 - Python:

Mainly using Python3, instead of Python2. In any case, I'm providing both versions: 

```
$ python2
Python 2.7.12 (default, Sep 29 2016, 13:30:34) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux2
```
```
$ python3
Python 3.5.2 (default, Oct 14 2016, 12:54:53) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux
```
In case you are not using jedi-vim from Git master, please test it there, too. 
(this is not applicable to me, as I'm using the master branch of the jedi-vim repo)

### Output of the "JediDebugInfo" command (in a Python buffer)

```
Using Python version: 2
 - sys.version: 2.7.12 (default, Sep 29 2016, 13:30:34), [GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]
 - site module: /usr/lib64/python2.7/site.pyc
Jedi path: /home/pratheek/.vim/bundle/jedi-vim/jedi/jedi/__init__.pyc
Jedi version: 0.9.0
jedi-vim git version: 0.8.0-43-g9384d46
jedi git submodule status:  995a6531225ba0b65e1ff863d97e5404d989047b jedi (v0.9.0-19-g995a653)
```

### Output of the "messages" Vim command

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
 - sys.version: 2.7.12 (default, Sep 29 2016, 13:30:34), [GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]
 - site module: /usr/lib64/python2.7/site.pyc
Jedi path: /home/pratheek/.vim/bundle/jedi-vim/jedi/jedi/__init__.pyc
Jedi version: 0.9.0
```

### Output of "scriptnames" Vim command

```
  1: /etc/vimrc
  2: /usr/share/vim/vim80/syntax/syntax.vim
  3: /usr/share/vim/vim80/syntax/synload.vim
  4: /usr/share/vim/vim80/syntax/syncolor.vim
  5: /usr/share/vim/vim80/filetype.vim
  6: /usr/share/vim/vim80/ftplugin.vim
  7: ~/.vim/vimrc
  8: ~/.vim/autoload/pathogen.vim
  9: /usr/share/vim/vim80/ftoff.vim
 10: ~/.vim/bundle/markdown/ftdetect/markdown.vim
.
.
.
```

(... contains more output, trimmed to only the top ten scriptnames)

-----

**Edit:** 

Small update, when I set Jedi to force use Python3 (with ```let g:jedi#force_py_version = 3```), I get this error

![unknown_error](https://cloud.githubusercontent.com/assets/1803997/21955046/61063af4-da88-11e6-949c-a45d5195e08e.png)

The (g)vim that I use, has the ```+python``` feature compiled in (it has both python and python3 compiled in) and is supported ! (as mentioned above in the ```gvim --version```

**Comment by blueyed** [comment]
The last error happened for somebody else already (but screenshots are hard to find..).
The issue with Vim is that it only uses one/the first Path on, and in the last case py3 gets loaded and py2 is not available anymore.

**Comment by notpratheek** [comment]
@blueyed 

I managed to solve the issue ! 

I went through issue #486 and found mine was a similar problem. 

I used the following settings: 

```viml
let g:jedi#force_py_version = 3
set omnifunc=jedi#completions
```

I had set ```omnifunc=pythoncomplete#Complete``` for python, but later changed this to ```omnifunc=jedi#completeions```, and now it works, (having both n the vimrc, resulted in error, 😅 so I removed the vim-default one, and opt-ed for the jedi completions)
