### ISSUE TITLE
No modules completion  in project directory without __init__.py files in modules

### ISSUE THREAD

**Issue by yuriizinets** [davidhalter/jedi-vim#670]
### Issue
No modules completion in project directory without __init__.py files in modules

### Steps to reproduce
Just installed vim, Vundle and jedi-vim through Vundle.
In my .vimrc:
autocmd FileType python setlocal completeopt-=preview
let g:jedi#show_call_signatures = "2"

### Versions

 - jedi-vim: 0.10.0
 - Vim / Neovim: 8.0
 - Python: 2.7.13 / 3.6.0

### Output of the "JediDebugInfo" command (in a Python buffer)
Using Python version: 3
 - sys.version: 3.6.0 (default, Jan 16 2017, 12:12:55), [GCC 6.3.1 20170109]
 - site module: /usr/lib/python3.6/site.py
Jedi path: /home/yzinets/.vim/bundle/jedi-vim/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /home/yzinets/.vim/bundle/jedi-vim
    - /usr/lib/python36.zip
    - /usr/lib/python3.6
    - /usr/lib/python3.6/lib-dynload
    - /home/yzinets/.local/lib/python3.6/site-packages
    - /usr/lib/python3.6/site-packages
    - _vim_path_
jedi-vim git version: 0.8.0-69-g0dea756
jedi git submodule status:  70200861661a921016563717487c1ced9993acdb jedi (v0.10.0)

##### Settings
```
g:force_py_version = '3' (default: 'auto')
g:show_call_signatures = '2' (default: 1)

  omnifunc=jedi#completions
        Last set from ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
  completeopt=menu
        Last set from ~/.vimrc
```

### Output of the "messages" Vim command
"run.py" 6L, 85C
 - sys.version: 3.6.0 (default, Jan 16 2017, 12:12:55), [GCC 6.3.1 20170109]
 - site module: /usr/lib/python3.6/site.py
Jedi path: /home/yzinets/.vim/bundle/jedi-vim/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /home/yzinets/.vim/bundle/jedi-vim
    - /usr/lib/python36.zip
    - /usr/lib/python3.6
    - /usr/lib/python3.6/lib-dynload
    - /home/yzinets/.local/lib/python3.6/site-packages
    - /usr/lib/python3.6/site-packages
    - _vim_path_

### Output of "scriptnames" Vim command
  1: /etc/vimrc
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: ~/.vimrc
  4: /usr/share/vim/vim80/ftoff.vim
  5: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
  6: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
  7: /usr/share/vim/vim80/filetype.vim
  8: /usr/share/vim/vim80/ftplugin.vim
  9: /usr/share/vim/vim80/indent.vim
 10: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 11: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 12: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 13: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 14: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 15: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 16: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 17: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 18: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 19: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 20: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 21: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 22: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 23: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 24: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 25: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 26: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 27: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 28: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 29: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 30: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
 31: /usr/share/vim/vim80/plugin/gzip.vim
 32: /usr/share/vim/vim80/plugin/logiPat.vim
 33: /usr/share/vim/vim80/plugin/manpager.vim
 34: /usr/share/vim/vim80/plugin/matchparen.vim
 35: /usr/share/vim/vim80/plugin/netrwPlugin.vim
 36: /usr/share/vim/vim80/plugin/rrhelper.vim
 37: /usr/share/vim/vim80/plugin/spellfile.vim
 38: /usr/share/vim/vim80/plugin/tarPlugin.vim
 39: /usr/share/vim/vim80/plugin/tohtml.vim
 40: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 41: /usr/share/vim/vim80/plugin/zipPlugin.vim
 42: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 43: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 44: /usr/share/vim/vim80/ftplugin/python.vim
 45: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 46: /usr/share/vim/vim80/indent/python.vim

**Comment by davidhalter** [comment]
This is not enough information. Can you give us the file you're in? And say where you're trying to complete?

**Comment by smorad** [comment]
I'm seeing this as well. https://www.python.org/dev/peps/pep-0420/ says that from 3.3 onward, __init__.py should not be required for namespace packages, but this doesn't appear to be the case with `jedi-vim`.
<img width="445" alt="screen shot 2017-02-27 at 6 44 33 pm" src="https://cloud.githubusercontent.com/assets/1743889/23389475/ffec93f0-fd1c-11e6-9297-6a7aca7d9da4.png">
<img width="299" alt="screen shot 2017-02-27 at 6 44 11 pm" src="https://cloud.githubusercontent.com/assets/1743889/23389474/ffeaeb04-fd1c-11e6-866d-643057c686c7.png">
<img width="265" alt="screen shot 2017-02-27 at 6 44 26 pm" src="https://cloud.githubusercontent.com/assets/1743889/23389473/ffea2174-fd1c-11e6-8eb1-8e5927f1c38d.png">


.


#### Jedi-vim debug information
Using Python version: 3
 - sys.version: 3.4.5 (default, Nov  9 2016, 16:24:59), [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
 - site module: /usr/lib64/python3.4/site.py
Jedi path: /home/stevemo/.vim/bundle/jedi-vim/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /home/stevemo/.vim/bundle/jedi-vim
    - /home/stevemo/fbcode
    - /usr/lib64/python34.zip
    - /usr/lib64/python3.4
    - /usr/lib64/python3.4/plat-linux
    - /usr/lib64/python3.4/lib-dynload
    - /usr/lib64/python3.4/site-packages
    - /usr/lib/python3.4/site-packages
    - _vim_path_
jedi-vim git version: 0.8.0-73-g682f377-dirty
jedi git submodule status: +f05c0714c701ab784bd344aa063acd216fb45ec0 jedi (v0.9.0-550-gf05c071)

##### Settings
```
g:force_py_version = 3 (default: 'auto')
g:popup_on_dot = 0 (default: 1)

  omnifunc=jedi#completions
        Last set from ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
  completeopt=menuone,longest,preview
        Last set from ~/.vim/bundle/jedi-vim/plugin/jedi.vim
```
