### ISSUE TITLE
Make JediDebugInfo more robust (import jedi error)

### ISSUE THREAD

**Issue by gfplk** [davidhalter/jedi-vim#675]
### is a bug of jedi-vim or vim8.0? i used centos7 and i had compiled the vim for python3 supported.

 - jedi-vim:
 - Vim / Neovim:
 - Python:

In case you are not using jedi-vim from Git master, please test it there, too.

**Comment by gfplk** [comment]
i am used mobile phone to submit this issue, please help me.

**Comment by blueyed** [comment]
What should `:import jedi` do?
Line 97 is `import jedi`: https://github.com/davidhalter/jedi-vim/blob/0dea756fd92945a1093760b8fa0858ccfd5098d6/jedi_vim.py#L97.

It looks like you've installed it not correctly.
Make sure to include/checkout the submodule when installing from Git.
Also please provide the output from `:JediDebugInfo` if it's still an issue.

**Comment by gfplk** [comment]
./configure --enable-fail-if-missing --enable-python3interp --enable-multibyte --enable-fontset --with-features=huge --enable-gui=gnome --prefix=/usr/local/apps/vim
That is the command compiled the vim.

when i opened vim and type into : py3 print(1), it's ok.
but type into: py3 import platform, the same error output.

this is the error output.
Please install Jedi if you want to use jedi-vim.
The error was: /usr/local/apps/python3.5.3/lib/python3.5/lib-dynload/_posixsubprocess.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyExc_Runtime
Error

but i had used pip installed the jedi lib for python3
and my .vimrc had one line code for jedi-vim: "let g:jedi#force_py_version = 3". i think there is nothing wrong with it.

What's wrong?

**Comment by gfplk** [comment]
for why used :import jedi do?
answer, i debuged the jedi-vim plugin, i find when the vim run the jedi_vim.py , and line 97 , the code on the line is "import jedi", but error output.

so, i want to known why, and i open vim and type into : py3 import os, it's ok
type into :py3 import jedi , error output.

I find some lib for python3 is ok, another lib maybe wrong.

**Comment by gfplk** [comment]
I used the command :Jedidebuginfo

this is the output.

#### Jedi-vim debug information
Using Python version: 3
 - sys.version: 3.5.3 (default, Feb 11 2017, 20:51:47), [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
 - site module: /usr/local/apps/python3.5.3/lib/python3.5/site.py
处理 function jedi#debug_info 时发生错误:
第   19 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute '__file__'

**Comment by gfplk** [comment]
我绕过了这个问题，直接把系统换成ubuntu desktop 16了。

这个问题，必定是我python3编译没有安装好，或者是centos7有问题。

**Comment by blueyed** [comment]
Looks like a follow up error: `jedi_vim` was imported, but `jedi_vim.jedi` seems to be `None`.
In this case previous errors are relevant, too (see `:mess`).

I will look into making this more robust.

**Comment by blueyed** [comment]
@gfplk 
Please try https://github.com/davidhalter/jedi-vim/pull/678 (also if you do not have any problems anymore).
