### ISSUE TITLE
Renaming don't work

### ISSUE THREAD

**Issue by nasim80** [davidhalter/jedi-vim#676]
### Issue

When I press <ESC> after renaming a variable, the variable stays unchanged.
.
### Steps to reproduce

Open a python file and try to rename a variable.

### Versions

 - jedi-vim: Lastest
 - Vim / Neovim: vim 8.0
 - Python: 3.6.0
 - Jedi 0.10.0

#### Jedi-vim debug information
Using Python version: 3
 - sys.version: 3.6.0 (default, Jan 16 2017, 12:12:55), [GCC 6.3.1 20170109]
 - site module: /usr/lib/python3.6/site.py
Jedi path: /home/nathaniel/.vim/plugged/jedi-vim/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /home/nathaniel/.vim/plugged/jedi-vim
    - /usr/lib/python36.zip
    - /usr/lib/python3.6
    - /usr/lib/python3.6/lib-dynload
    - /usr/lib/python3.6/site-packages
    - _vim_path_
jedi-vim git version: 0dea756
jedi git submodule status:  70200861661a921016563717487c1ced9993acdb jedi (v0.10.0)

##### Settings
```
g:force_py_version = 3 (default: 'auto')
g:documentation_command = '<leader>d' (default: 'K')
g:goto_definitions_command = '<leader>g' (default: '')

  omnifunc=jedi#completions
        Last set from ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
  completeopt=menu,preview
```

**Comment by gfplk** [comment]
这个功能没必要啊。
自打我用这个插件，我用的最多的就是这两个功能：
1，代码跳转
2，自动补全

希望jedi-vim能去除其它功能。留这两个就好了。

**Comment by davidhalter** [comment]
@nasim80 This is a Jedi issue. There's like 5 issues for this. I'm closing as a duplicate.

**Comment by blueyed** [comment]
@gfplk 
JFI: the rename feature is supposed to be more powerful then that.
Please also only write in English here.
