### ISSUE TITLE
sys.path grows with projects in editable mode

### ISSUE THREAD

**Issue by bmihelac** [davidhalter/jedi-vim#686]
### Issue

sys.path grows with projects in editable mode

### Steps to reproduce

Installed virtualenv
installed project with editable mode, ie:

`pip install -e git+https://github.com/bmihelac/django-cruds.git@91de0b6e82c8fdea814ed0e672544ab12bd6d57b#egg=django_cruds
`
vim __init__.py

Use any jedi-vim command, ie. autocomplete.

`:python import sys; print sys.path`

sys.path includes multiple paths for editable project (and it grows with usage)

['/opt/boxen/data/virturalenvs/test-jedi/src/django-cruds', '/opt/boxen/data/virturalenvs/test-jedi/src/django-cruds', '/opt/boxen/data/virturalenvs/test-jedi/src/django-cruds', '/opt/boxen/data/virturalenvs/test-jedi/src/django-cruds'
....
]

I'd like to debug where are this paths added, but without success so far.

### Versions

 - jedi-vim:

latest

 - Vim / Neovim:

8.0 (124)

 - Python:

2.7.3

In case you are not using jedi-vim from Git master, please test it there, too.

**Comment by davidhalter** [comment]
There's an issue template for a reason. Please use it.

**Comment by blueyed** [comment]
Indeed.  This would include the whole sys.path.
Tried to reproduce it with an existing project quickly, but could not.

Does it happen with Python3, too?

**Comment by bmihelac** [comment]
Thanks for your reply and sorry for describing this thing superficially. I'll update ticket with proper information ASAP.

**Comment by bmihelac** [comment]
After reinstalling vim, upgraded to latest python 2.7.X, clearing vim plugins, I cannot reproduce this anymore. Sorry about the noise, I own you a beer or coffee :)

**Comment by davidhalter** [comment]
Absolutely no problem. This was probably an old issue with Jedi. I've seen this a while ago.
