### ISSUE TITLE
<leader>d goes to the decorator not the actual function

### ISSUE THREAD

**Issue by yifeikong** [davidhalter/jedi-vim#689]
### Issue

I have a func called `my_func`

    @my_decorator
    def my_func():
        pass
    
    from my_module import my_func

if I call `<leader>d` on my_func, jedi takes me to the decorator, not the function

**Comment by raulchen** [comment]
+1 for this feature

**Comment by martinpelikan** [comment]
@yifeikong How about `<leader>g` ?

**Comment by davidhalter** [comment]
What versions of jedi-vim / jedi are you using guys? I think this was an issue about half a year ago. But it shouldn't anymore. Update Jedi.

If you think this is still a problem, please post a full reproduction case with all code involved and your settings/vimrc, etc. I'll close for now.
