### ISSUE TITLE
Problem starting a new python script

### ISSUE THREAD

**Issue by cja000** [davidhalter/jedi-vim#690]
### Issue

Every time I start a new Python script with the line:
#!/usr/bin/env python

And press enter at the end, Vim hangs
I have to kill it from another console.

If I start the script with any other thing like import os and the write above it that line it works.

### Steps to reproduce
Start a new python script and type:
#!/usr/bin/env python

**Comment by blueyed** [comment]
Likely https://github.com/davidhalter/jedi/issues/878.

**Comment by Rmano** [comment]
Yes, and also https://github.com/davidhalter/jedi-vim/issues/687 ;-)
