### ISSUE TITLE
Unnecessary `=` character completion for argument variable

### ISSUE THREAD

**Issue by roxma** [davidhalter/jedi-vim#691]
### Issue

Copied from related issue: https://github.com/roxma/nvim-completion-manager/issues/43

![image](https://cloud.githubusercontent.com/assets/3063690/23587440/ee97f9d6-01e6-11e7-982b-4f6e2bba8b46.png)

Just like the image above shows,   it should be `testParam` instead of `testParam=`.

### Steps to reproduce

```
nvim test.py
:setlocal omnifunc=jedi#completions
```

```
def foo(testParam):
    arr = []
    arr.append(tes|)
```

where `|` is the cursor position.

Then press `<c-x><c-o>`, 

```
 def foo(testParam):
     arr = []
     arr.append(tes)
                testParam= param testParam 
```

Press `<c-n>`, 
```
 def foo(testParam):
     arr = []
     arr.append(testParam=)
```

**Comment by davidhalter** [comment]
There was a template you had to fill out when opening the issue. There's a reason it's there. I'll reopen when you have done that.

**Comment by davidhalter** [comment]
It's probably also a Jedi bug and not jedi-vim. In that case provide the Jedi version.
