### ISSUE TITLE
Current argument in function definition popup has text color same as background

### ISSUE THREAD

**Issue by simopal6** [davidhalter/jedi-vim#693]
### Issue

When the cursor is on a function argument, the list of formal arguments is shown above, however the current item text has the same color as the background, so it's unreadable. See image below for an example.

![snap1](https://cloud.githubusercontent.com/assets/4355487/24307285/da2fd478-10c3-11e7-8f1e-96b89ead7f3c.png)

I'm using the default vim in Slackware 14.1, I don't know the color scheme name, it has a white background.

**Comment by davidhalter** [comment]
Well, we don't really support all the different color schemes. IMO you have two options:

1. Change show_call_signatures to 2 or 0 (disabled).
2. Change `hi jediFat term=bold,underline cterm=bold,underline gui=bold,underline ctermbg=0 guibg=#555555` in your vimrc.

This feature breaks color schemes anyway and is a big hack. So don't expect anything from it if your using color schemes.

**Comment by simopal6** [comment]
I solved it with:
```
hi jediFunction term=NONE cterm=NONE ctermfg=6 guifg=Black gui=NONE ctermbg=0 guibg=Grey
hi jediFat term=bold,underline cterm=bold,underline ctermfg=6 gui=bold,underline ctermbg=0 guibg=#555555
```
i.e. by adding `ctermfg=6` in the second line.
