### ISSUE TITLE
does this support install on windows? 

### ISSUE THREAD

**Issue by moreoronce** [davidhalter/jedi-vim#700]
I'm working on Windows and use vim to make some python code.  I found that when i install jedi-vim through dein, it always warning me that the installation failure. Does jedi-vim support windows?

**Comment by blueyed** [comment]
Yes, I think it should work in general.
Maybe there is a problem with dein and Git submodules?!
Does `:JediDebugInfo` work?

**Comment by davidhalter** [comment]
Closed, because no information was given.
