### ISSUE TITLE
Some issues with unittest.main

### ISSUE THREAD

**Issue by memeplex** [davidhalter/jedi-vim#701]
`unittest.main` is implemented in a bit contorted way:

1. It's an import of `unittest.main.main` into `unittest`.
2. `unittest.main.main` is an alias for `unittest.main.TestProgram`.

Now, despite this complexities jedi-vim is doing a pretty well job except for docstrings. When `main` is the only completion available it works fine, but when there is more than one completion the docstring won't be shown and won't replace previous docstrings.  Let's see some examples:

* `from unittest import mai<C-Space>`) the preview window will show `Unittest main program`. This is not 100% accurate since it's the docstring for the `main` module and not the `TestProgram` class but it's still good enough.

* `from unittest import TestCase, mai<C-Space>` the preview window is now stuck at the `TestCase` docstring.

* After importing, `mai<C-Space>` will correctly show the `TestProgram` docstring.

* After importing, `ma<C-Space>` will show a menu containing `main`, `map` and `max`. Only the docstrings for `map` and `max` will show up in the preview window.

**Comment by davidhalter** [comment]
These are probably mostly Jedi issue. If possible can you track them down more precisely with direct calls to Jedi?

Like this: `jedi.Script('from unittest import mai').completions()[0].docstring()` returns the module docstring instead of the class.

**Comment by davidhalter** [comment]
I'm closing this, if you still want improvements, please post this stuff in the Jedi issue tracker. It's kind of hard for me to reproduce this stuff.

Happy to see you in Jedi's issue tracker ;-)
