### ISSUE TITLE
Wrong relative imports in unit tests with parallel hierarchy

### ISSUE THREAD

**Issue by memeplex** [davidhalter/jedi-vim#702]
I'm having a problem similar to https://github.com/davidhalter/jedi-vim/issues/195, here is a step by step procedure to reproduce the issue:

```
mkdir /tmp/proj
cd /tmp/proj
mkdir pkg
touch pkg/__init__.py
touch pkg/mod.py
mkdir tests
touch tests/__init__.py
mkdir tests/pkg
touch tests/pkg/__init__.py
touch tests/pkg/test_mod.py
export PYTHONPATH=/tmp/proj:$PYTHONPATH
vim tests/pkg/test_mod.py
```

Now try to autocomplete `import pkg.`, jedi will suggest only `test_mod`, which is wrong given the `PYTHONPATH`, and won't suggest `mod`, which is also wrong.

Now, if you edit `pkg/mod.py` instead, `import pkg.` will correctly suggest `mod`. It is as if the file being edited is influencing jedi's notion of the python path.

**Comment by davidhalter** [comment]
Setting PYTHONPATH is not respected in VIMs Python. We could potentially do that in jedi-vim. What do you think @blueyed ?

**Comment by blueyed** [comment]
Do you mean to massage `sys.path` for Jedi, or some other way?

**Comment by davidhalter** [comment]
Yeah, exactly. Not saying that it's a good idea at the moment, but somewhere in the future if virtualenvs are supported?!

**Comment by uvesten** [comment]
I'm having the exact same problem, is there any workaround at the moment?

**Comment by davidhalter** [comment]
Latest Jedi is way way smarter about this stuff and thanks to your reproduction case I was able to see that this has been solved.
