### ISSUE TITLE
Always disable automatic typing

### ISSUE THREAD

**Issue by Flimm** [davidhalter/jedi-vim#707]
Sometimes, jedi-vim automatically types characters for me when in insertion mode. For instance, after I type: `from logging `, jedi-vim automatically types for me `import `, to make the line:

```python
from logging import
```

I find this very annoying, I don't want to break muscle memory. I want jedi-vim to allow me to type `import ` myself, and then display a list of suggestions, from which I can select using keyboard shortcuts.

Another situation where jedi-vim automatically types for me, instead of displaying a list of options, is described in issue #706.

Is there a setting where I can universally stop jedi-vim from automatically typing for me?

**Comment by blueyed** [comment]
You can use `let g:jedi#smart_auto_mappings = 0` to disable it for now.
See also https://github.com/davidhalter/jedi-vim/issues/568.

**Comment by blueyed** [comment]
#706 seems to be something else, so closing this issue.

**Comment by Flimm** [comment]
I'm sure there are other cases where jedi-vim types things for me, I'll come back and when I have more cases, could we re-open this issue?

**Comment by blueyed** [comment]
Let's keep this about the import-magic (which #708 should address, please test it).
