### ISSUE TITLE
Handle parso as depenency for new Jedi (0.11+)

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/jedi-vim#711]
Jedi will be depending on https://github.com/davidhalter/parso, which will be a bit of a problem for jedi-vim's current architecture. Currently jedi-vim supports using Jedi as a sub-repository (while it also being installable from pip). This change might be coming in a few weeks or so. I'm mostly improving docs for parso, now.

IMO there's two ways we can go now:
- Add parso as a sub-repository, too. However this makes dependency management pretty hard, because it would be probably pretty common that people install versions of parso/jedi that differ.
- Remove jedi as a sub-repository and leave it to the user to install jedi (by pip). I would probably prefer this.

What do you think? @blueyed

**Comment by blueyed** [comment]
Yes, the 2nd option seems good.
A lot of distros have packages for jedi also, which would help here.
(the problem with using `pip` might be that you have to install it into your virtualenv also etc, but `pip install --user`, pipsi or something like that could be used).

**Comment by davidhalter** [comment]
> (the problem with using pip might be that you have to install it into your virtualenv also etc, but pip install --user, pipsi or something like that could be used).

I think we might just need to work around that. Virtualenv support is pretty much non-existant in Jedi itself. And I think speaking for VIM (I have no idea about neovim) the virtualenv paths are not applied, there's still system Python in there.

**Comment by blueyed** [comment]
@davidhalter 
With deoplete-jedi we have vendored jedi before (like jedi-vim does it), and I've added parso in https://github.com/zchee/deoplete-jedi/pull/131.

I think we should just do the same for jedi-vim: add parso as a submodule.

What do you think?

**Comment by davidhalter** [comment]
I'm fine with this. I think either this or just remove it entirely. Both would need an action.
