### ISSUE TITLE
rst highlighting for docstrings should not try to additionally highlight python in indented sections

### ISSUE THREAD

**Issue by anntzer** [davidhalter/jedi-vim#716]
### Issue

rst highlighting for docstrings should not try to additionally highlight python in indented sections

### Steps to reproduce

import numpy as np; np.array
press K with cursor on array to display the docs, which are displayed with some spurious python highlighting.

numpy (and most of the scientific python community) uses numpydoc as docstring format, which uses indented blocks to describe parameters (in plain text), but jedi-vim incorrectly tries to highlight it with python syntax:
```
    " highlight python code within rst
    unlet! b:current_syntax
    syn include @rstPythonScript syntax/python.vim
    " 4 spaces
    syn region rstPythonRegion start=/^\v {4}/ end=/\v^( {4}|\n)@!/ contains=@rstPythonScript
    " >>> python code -> (doctests)
    syn region rstPythonRegion matchgroup=pythonDoctest start=/^>>>\s*/ end=/\n/ contains=@rstPythonScript
    let b:current_syntax = 'rst'
```

Instead, this should be the job of the rst syntax file itself; for example, https://github.com/marshallward/vim-restructuredtext highlights embedded code just fine.

The suggested fix is to simply delete that section.

**Comment by blueyed** [comment]
Makes sense.
Can you provide a PR for it, please?
