### ISSUE TITLE
Install jedi-vim Error

### ISSUE THREAD

**Issue by Hello-Linux** [davidhalter/jedi-vim#719]
### Issue

When I use centos6.8 install jedi-vim,I found some error. I have run pip install jedi and vim for python3.5
but when I open a python file is show some errors,use python2.7 is ok blow is my screenshot

![error1](https://user-images.githubusercontent.com/17851645/27412723-2c7b18ae-5729-11e7-82a2-f6ae53e869eb.png)
![error2](https://user-images.githubusercontent.com/17851645/27412725-2c7eee20-5729-11e7-92e8-963c479e9bba.png)
![error3](https://user-images.githubusercontent.com/17851645/27412724-2c7bc9fc-5729-11e7-9d05-078be3b51079.png)

**Comment by davidhalter** [comment]
Pretty sure this is an error with the setup. Sometimes reinstalling VIM/Python helps.

This is 100% not a Jedi issue and also not a jedi-vim issue. You might try around and do stuff like `:python3 import os`, `:python3 import jedi`, `:python import os`, `:python import jedi`.
