### ISSUE TITLE
fuzzy matching in completions list

### ISSUE THREAD

**Issue by JazzCore** [davidhalter/jedi-vim#72]
Hello. Is it possible to implement something like [fuzzy matching in neocomplcache](https://github.com/Shougo/neocomplcache/blob/master/doc/neocomplcache.txt#L333)?

I mean, instead of writing `assertIsNone`, we can just write something like `asin` to choose this completion.

I've tried neocomplcache fuzzy matching, but sadly it only works on its own completion list.

**Comment by blueyed** [comment]
Plugins like deoplete provide this for now.
I would say that this is not in the scope of jedi-vim currently.
