### ISSUE TITLE
Missed interface or its documentation to configure jedi itself

### ISSUE THREAD

**Issue by mkwork** [davidhalter/jedi-vim#720]
Hello.

Jedi [settings](https://jedi.readthedocs.io/en/latest/docs/settings.html) changing interface should be documented.

Corresponding documentation should help to find answer "how to configure jedi.settings.cache_directory" (simple case) and "how to configure jedi.auto_import_modules setting" (option with multiple usecases: can be overridden or extended).

User story:
Need to append jedi.settings.auto_import_modules setting.

**Comment by davidhalter** [comment]
Sorry, you have to hack around this for now. IMO there's already very many things we expose and I'm not sure if Jedi will also get rid of some of those settings. I don't like the amount of settings that are possible.
