### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by zhai3516** [davidhalter/jedi-vim#732]
### Steps to reproduce
My .vimrc only set this to jedi configure  :

let g:jedi#completions_enabled = 0
let g:jedi#goto_definitions_command = "<leader>f"

**Comment by blueyed** [comment]
Needs more information (e.g. reproduce steps), and sounds like an issue with Jedi itself.

**Comment by davidhalter** [comment]
Closing until we have more information. Happy to reopen.
