### ISSUE TITLE
K documentation not found

### ISSUE THREAD

**Issue by zackhsi** [davidhalter/jedi-vim#738]
Sorry to open the issue, I have looked at the historical issues as well as the source code to no avail.

Given this minimal python file:

```python
import logging
```

When I hit `K`, the `__doc__` buffer opens with:
> `|No Docstring for <Definition module logging>|`

However, when I run `:!pydoc logging`, I get the expected response.

I disabled pyenv, python-mode, etc, and got the same issue.

Using neovim 0.2.0.

Any suggestions? Thanks.

**Comment by blueyed** [comment]
Works for me with a minimal vimrc:

> Docstring for logging:module logging
> …

What Python version are you using?

What does `:verb map K?` say?

I get:
```
n  K           *@:call jedi#show_documentation()<CR>                                        
        Last set from ~/.dotfiles/vim/plugged/jedi-vim/ftplugin/python/jedi.vim
```

**Comment by zackhsi** [comment]
It does not work for me with Python 3.6.1 (via pyenv) and 2.7.10 (macOS system python).

```
n  K           *@:call jedi#show_documentation()<CR>
        Last set from ~/.vim/plugged/jedi-vim/ftplugin/python/jedi.vim
```

I'm having trouble fully understanding the relationship between `autoload/jedi.vim` and `pythonx/jedi_vim.py`, but I suspect something is not working with [docstring](https://github.com/davidhalter/jedi-vim/blob/0c6a2b77379f994c316983ca7f59784c1c957f78/pythonx/jedi_vim.py#L324-L325) function.

**Comment by davidhalter** [comment]
Can you please add the debug information that was requested from you in the template? It's there for a reason.

**Comment by zackhsi** [comment]
### Issue

K to show documentation does not work properly.



### Steps to reproduce



```vim
" minimal.vimrc
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

" Put your config changes here.
call plug#begin('~/.vim/plugged')
Plug 'davidhalter/jedi-vim'
call plug#end()

syntax on
filetype plugin indent on
```

```python
# test.py
import logging
```

```sh
nvim -u minimal.vimrc test.py
# Move cursor to `logging`
# Hit K
```

<img width="840" alt="screen shot 2017-09-12 at 8 49 35 am" src="https://user-images.githubusercontent.com/806101/30335480-57be9a64-9797-11e7-9917-39b8f20e1cb8.png">


### Output of “:verbose JediDebugInfo”



#### Jedi-vim debug information
Using Python version: 2
 - sys.version: `2.7.13 (default, Jul 18 2017, 09:17:00), [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]`
 - site module: `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py`
Jedi path: `/Users/zhsi/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.10.2
 - sys_path:
    - `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python27.zip`
    - `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7`
    - `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin`
    - `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac`
    - `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages`
    - `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk`
    - `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old`
    - `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload`
    - `/usr/local/lib/python2.7/site-packages`
    - `/Users/zhsi/oss/salt`
    - `_vim_path_`
 - jedi-vim git version: 0c6a2b7
 - jedi git submodule status:  5427b02712828b2875d35b5ee1c8b5e58f820537 pythonx/jedi (v0.10.2)


##### Settings
```
  omnifunc=jedi#completions
	Last set from ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
  completeopt=menuone,longest,preview
	Last set from ~/.vim/plugged/jedi-vim/plugin/jedi.vim
```


#### :version
```

NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"

```


#### :messages
```
"test.py" 1L, 15C
```


<details><summary>:scriptnames</summary>


```
  1: ~/Desktop/jedi/minimal.vimrc
  2: ~/.vim/autoload/plug.vim
  3: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/filetype.vim
  4: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/ftplugin.vim
  5: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/indent.vim
  6: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/syntax/syntax.vim
  7: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/syntax/synload.vim
  8: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/syntax/syncolor.vim
  9: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/syntax/nosyntax.vim
 10: ~/.vim/plugged/jedi-vim/plugin/jedi.vim
 11: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/gui_shim.vim
 12: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/gzip.vim
 13: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/health.vim
 14: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/man.vim
 15: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/matchit.vim
 16: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/matchparen.vim
 17: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/netrwPlugin.vim
 18: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/rplugin.vim
 19: ~/.local/share/nvim/rplugin.vim
 20: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/autoload/remote/host.vim
 21: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/autoload/remote/define.vim
 22: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/rrhelper.vim
 23: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/shada.vim
 24: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/spellfile.vim
 25: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/tarPlugin.vim
 26: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/tohtml.vim
 27: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/tutor.vim
 28: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/plugin/zipPlugin.vim
 29: ~/.vim/plugged/jedi-vim/ftplugin/python/jedi.vim
 30: ~/.vim/plugged/jedi-vim/autoload/jedi.vim
 31: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/autoload/provider/python.vim
 32: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/autoload/provider/pythonx.vim
 33: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/ftplugin/python.vim
 34: ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 35: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/indent/python.vim
 36: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/syntax/python.vim
 37: ~/.vim/plugged/jedi-vim/after/syntax/python.vim
 38: /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/autoload/provider/clipboard.vim
```
</details>

**Comment by davidhalter** [comment]
Does K work somewhere else? I mean it's working for me and it looks a bit more like a Jedi issue than jedi-vim.

Also what gives you `:python import logging; print(repr(logging.__doc__))`?

**Comment by blueyed** [comment]
Also try adding prints before https://github.com/davidhalter/jedi-vim/blob/0c6a2b77379f994c316983ca7f59784c1c957f78/pythonx/jedi_vim.py#L324-L325.

**Comment by zackhsi** [comment]
It could certainly be unrelated to this repo -- I have no idea!

The output of `:python import logging...` is:
`"\nLogging package for Python. Based on PEP 282 and comments thereto in\ncomp.lang.python.\n\nCopyright (C) 2001-2014 Vinay Sajip. All Rights Reserved.\n\nTo use, simply 'import logging' and log away!\n"`, works properly AFAICT.

Print statements reveal that `definitions` is a list of `jedi.api.classes.Definition`. The single item in the list's `docstring()` function returns an empty string. So very likely a jedi issue.

**Comment by davidhalter** [comment]
Can you debug that further? I mean that docstring call doesn't do a lot. Even if you go in there. It's most probably a `jedi.evaluate.representation.ModuleContext` object that causes this. You could just add a few prints there.

The problem is that I can not reproduce your issue.

**Comment by zackhsi** [comment]
Yup, I will close the issue as it is not jedi-vim related. Thanks for the pointers.

**Comment by zackhsi** [comment]
Ok. I have tracked it down to pypi not being up to date. Works on jedi master, broken for 0.10.2.

**Comment by davidhalter** [comment]
Awesome!

**Comment by zackhsi** [comment]
@davidhalter can you publish a new version of jedi to [pypi](https://pypi.python.org/pypi/jedi/) please? Not sure what's left for the 0.11.0 release, but it seems [slated for publication today](https://github.com/davidhalter/jedi/commit/794880b8a897249527e1e0cdf80c5e31a69d2336) :)

**Comment by davidhalter** [comment]
That was just a random date I put in. I'll change that again. There's a release issue in the jedi issue tracker that you can follow. I'm currently fixing a few bugs and preparing a release. I have like 8 bugs left that I want to fix.
