### ISSUE TITLE
Way to view full class documentation

### ISSUE THREAD

**Issue by jezeniel** [davidhalter/jedi-vim#742]
I am sorry that this might not be really an issue but just a question, never really know where to reach out.. is there a way to view not just `docstring` output but full documentation like in `pydoc` command?

**Comment by blueyed** [comment]
Not AFAIK, but there could be something like a verbose mode for the current function maybe.

**Comment by jezeniel** [comment]
@blueyed trying to search about the verbose mode, it seems i cannot find in the documentation?

**Comment by davidhalter** [comment]
I'll just answer that there is no way to do that. I agree that better documentation would be really nice, but I do not see how we do that with Jedi at the moment. We should probably start improving it there, first.

**Comment by jezeniel** [comment]
@davidhalter any official github issue for jedi for this kind of feature? So we could discuss further on ways and challenges of implementing this.

**Comment by davidhalter** [comment]
@jezeniel Sorry this issue was open in one of my many tabs, but I forgot about it. There's one ticket that's kind of similar: https://github.com/davidhalter/jedi/issues/253

You may create a new ticket in jedi to track this!
