### ISSUE TITLE
Better Usages

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/jedi-vim#747]
I would like to improve the usages functionality by a lot.

I've realized that there is `:help matchaddpos` that definitely helps with marking usages. Now there's however also the tagstack. @wilywampa has already done some work with it by creating temporary files. I however don't really like that. It's incredibly complicated to work with that. How about overwriting the tagstack commands in jedi-vim (just for Python)?

Could you please tell me what you think? @wilywampa @blueyed Do you have other ideas? I'm not really a VIM pro when it comes down to the details.

**Comment by blueyed** [comment]
What is the feature you want to have?

**Comment by blueyed** [comment]
I.e. please elaborate on "Usages".

**Comment by blueyed** [comment]
Do you mean to "jump to / display usages" feature? (likely yes I think)

**Comment by davidhalter** [comment]
We have `:call jedi#usages()` now, it's mapped by default on `<leader>n`. It basically shows all names related to that name in a quickfix window. I don't like it a lot this way and therefore almost never use it.

**Comment by blueyed** [comment]
the quickfix is useful/required to jump to usages in other files, isn't it?

Your use case is highlighting the actual usages (in the current file)?

**Comment by davidhalter** [comment]
Yes. For usages in other files I agree that the quickfix would be nice. But a lot of the time it's about the current file.

**Comment by blueyed** [comment]
We/you have improved this recently.

Closing, with a reminder/pointer to https://github.com/davidhalter/jedi-vim/pull/851.
