### ISSUE TITLE
README.rst Enhancement Proposal

### ISSUE THREAD

**Issue by zwidny** [davidhalter/jedi-vim#748]
### Issue
Install Jedi by ReadMe.rst by step, but it does not work correctly.

### Steps to reproduce

I install jedi-vim by README.rst, and I use  Vundle to install jedi-vim.
The doc say nothing to how to install jedi-vim by Vundle,  but say 
```
git clone --recursive https://github.com/davidhalter/jedi-vim.git ~/.vim/bundle/jedi-vim
```
only. so I think Vundle do not need add this line"Plugin 'davidhalter/jedi-vim'"

That make my jedi does not work, and I install by README.rst, so I do not the reason.

### Suggest
Add Vundle install doc. e.g.:

For Vundle,  need add this
```
Plugin 'davidhalter/jedi-vim'
```
to ~/.vimrc

**Comment by mmequignon** [comment]
Hi @zwindy !
Yes, as you noticed, there is no install description for Vundle.
I will create a pull request.

**Comment by davidhalter** [comment]
Thanks for bringing this up. I think we can continue the discussion in #781.
