### ISSUE TITLE
Wrong indexing: info text to corresponding function shifted

### ISSUE THREAD

**Issue by IstiCusi** [davidhalter/jedi-vim#751]
### Issue

Having jedi popping up possible completions and in moving forward through possible choices
I get a +1 shift between the info text displayed describing the function and the item marked 
in the list of choices.

Used last version of the master branch.

-->

Have installed YCM, Utlisnips and Jedi-vim 

<!--

c=numpy.ar   <Ctrl-Space> (. is switched off) I get the info for array_repr when having highlighted array. 
vim version 8....

https://user-images.githubusercontent.com/1594084/31958020-b9c6a308-b8f0-11e7-8739-1108a50e0997.pn

**Comment by davidhalter** [comment]
Hmm weird. I cannot reproduce this. Does anyone else have this?

**Comment by blueyed** [comment]
Vim/Neovim version would be useful, and steps to reproduce.

**Comment by IstiCusi** [comment]
dear mate ..  it is vim 8.0.1144 compiled with all python on ubuntu 14.04 with the lastest
2 days old git master of your plugin.  cheers and greetings from zürich, stephan

Von meinem iPad gesendet

**Comment by davidhalter** [comment]
Can you try to dig a bit deeper? I think if there was something wrong with this generally we would have noticed in the last few years. (And it's also pretty hard to get this wrong in VIM)

**Comment by IstiCusi** [comment]
I give it a try -- can you check, if you can see the same behavior with numpy ?

**Comment by blueyed** [comment]
@IstiCusi 
Please provide simple steps to reproduce it.
Also make sure that it is coming from jedi-vim.. i.e. / e.g. check if you have `omnifunc=jedi#completions` (see `:set omnifunc`) and then trigger it explicitly using <kbd>Ctrl</kbd><kbd>o</kbd>.

**Comment by davidhalter** [comment]
Reproduction steps not given. Happy to reopen, if this is still  an issue. However please use a new jedi-vim version and provide `:JediDebugInfo`.
