### ISSUE TITLE
Windows Vim - Showing Expected Python Version

### ISSUE THREAD

**Issue by gusman** [davidhalter/jedi-vim#752]
### Steps to reproduce

Pre-Condition:
1. Windows 7, Python 3.6 - 32 bit
2. Vim 32 bit version 8.0.1207
3. Jedi VIM commit number : 77924398bd594e238766153cec97ace62650f082
    Installed with no changes parameter in vimrc

Procedures:
1. Open python script file using vim
2. Python initialization fails, with below error messages:
    Error detected while processing function jedi#init_python:
```
line    7:
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 2 or 3. (in function jedi#init_python[3]..<SNR>63_init_python, line 52)
```
 3. This error messages does not show expected python version, it leads confusion to interpret the root cause. Root cause is installed python is Python 3.6 - 32 bit, but expected Python is 3.5 - 32 bit.

Expectation:
1. Error message shall show expected Python version.

Error message can show 
### Output of “:version”
`:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 19 2017 22:08:59)
MS-Windows 32-bit console version
Included patches: 1-1207
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.  Features included (+) or not (-):
+acl                +cmdline_hist       -ebcdic             -hangul_input       +localmap           +packages           +ruby/dyn           +termguicolors      +visualextra
+arabic             +cmdline_info       +emacs_tags         +iconv/dyn          +lua/dyn            +path_extra         +scrollbind         +terminal           +viminfo
+autocmd            +comments           +eval               +insert_expand      +menu               +perl/dyn           +signs              -tgetent            +vreplace
-balloon_eval       +conceal            +ex_extra           +job                +mksession          +persistent_undo    +smartindent        -termresponse       +wildignore
-browse             +cryptv             +extra_search       +jumplist           +modify_fname       -postscript         +startuptime        +textobjects        +wildmenu
++builtin_terms     +cscope             +farsi              +keymap             +mouse              +printer            +statusline         +timers             +windows
+byte_offset        +cursorbind         +file_in_path       +lambda             -mouseshape         +profile            -sun_workshop       +title              +writebackup
+channel            +cursorshape        +find_in_path       +langmap            +multi_byte_ime/dyn +python/dyn         +syntax             -toolbar            -xfontset
+cindent            +dialog_con         +float              +libcall            +multi_lang         +python3/dyn        +tag_binary         +user_commands      -xim
+clientserver       +diff               +folding            +linebreak          +mzscheme/dyn       +quickfix           +tag_old_static     +vertsplit          -xpm_w32
+clipboard          +digraphs           -footer             +lispindent         -netbeans_intg      +reltime            -tag_any_white      +virtualedit        -xterm_save
+cmdline_compl      -dnd                +gettext/dyn        +listcmds           +num64              +rightleft          +tcl/dyn            +visual
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /Zl /MT -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_MBYTE -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_MZSCHEME -I "C:\Program Files (x86)\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a0solc.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a0solc.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjCULYHTRZi386/ /Zi
Linking: link  /nologo /subsystem:console,5.01 /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python35.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib /PDB:vim.pdb -debug`

**Comment by blueyed** [comment]
jedi-vim does not know about that.
We just check with Vim if it has Python 3 or Python 2.

**Comment by blueyed** [comment]
It depends on the build / installation of Vim.
See the references to "python" in the output of `:version`.
It would be a bit too much for jedi-vim to parse that somehow, and check if files exist etc.
