### ISSUE TITLE
goto_command Bug

### ISSUE THREAD

**Issue by RanchoCooper** [davidhalter/jedi-vim#754]
### Issue
the `goto_command` may works mistake in Python's decorator

### Steps to reproduce
etc.  here we define a Python function with decorator

```python
def deco(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return wrapper

@deco
def fucntion():
    pass

function()  # call goto here
```
`goto_command` will leading you to `deco` rather than function it-self

**Comment by davidhalter** [comment]
Please fill out the complete form. It's there for a reason.

**Comment by RanchoCooper** [comment]
what do you mean `fill out the complete form`?

**Comment by davidhalter** [comment]
If you open an a new issue there's a few placeholders that you should fill. You omitted half of it.

**Comment by RanchoCooper** [comment]
can you tell me,  where can I find the debug information

**Comment by davidhalter** [comment]
Click on new issue and you will see the whole template. It describes in detail what you have to do.
