### ISSUE TITLE
Don't initialize unless current buffer's filetype is python

### ISSUE THREAD

**Issue by fictionic** [davidhalter/jedi-vim#762]
### Issue

By default, the plugin changes some Vim settings. This would be fine, except that the settings are changed regardless of the filetype of the current buffer. So for example, when editing Java, the setting `completeopt` is changed from the user's original choice. I realize there is a plugin setting to disable those changes, but I shouldn't have to use that setting, because the plugin should only have any effect when editing python.

**Comment by davidhalter** [comment]
@blueyed What do you think? Can we make the setting buffer only?

**Comment by blueyed** [comment]
`completeopt` is a global-only setting it seems (see the help).

@fictionic 
Any other settings you have in mind?

**Comment by fictionic** [comment]
@blueyed I think you misunderstand me. I'm not saying `completeopt` or anything else should be buffer-only. I'm saying that `jedi-vim` should only make changes—or do anything at all—if it detects `filetype=python`. The first bit of code that runs should be to detect the filetype, and if it's not python, it should exit. I assume that's currently how things work, at least to some extent; I just want the part that changes `completeopt` to be within it!

Does that make sense? Sorry if I was unclear.

**Comment by blueyed** [comment]
@fictionic 
Understood, but it does not really help if it gets changed globally eventually.
It can probably be improved, e.g. by doing this in the ftplugin part.
So `completeopt` is the only problematic one for you?

**Comment by fictionic** [comment]
@blueyedYep! Unless `:h g:jedi#auto_vim_configuration` is misleading (it only mentions `completeopt`).

**Comment by blueyed** [comment]
IIRC @davidhalter once said that it is meant for people to configure automatically (not related to Python only): https://github.com/davidhalter/jedi-vim/blob/3be8833913bb2166cfe711e32e76e6c036058b9d/plugin/jedi.vim#L7-L46
Maybe we should remove it completely, and/or change the default for it to be off?
Moving it to `ftplugin` / only doing it for Python does not make much sense to me in this context.

**Comment by fictionic** [comment]
> ... it is meant for people to configure automatically (not related to Python only)

I don't think I understand what you mean by this.

> Maybe we should remove it completely, and/or change the default for it to be off?

I would say that's a perfectly good move. Is the particular value of `completeopt` really necessary for the plugin's function?

> Moving it to ftplugin / only doing it for Python does not make much sense to me in this context.

Why not? I mean if you're willing to ditch it entirely then I can see why it would be a waste to move just that one bit, I guess.

**Comment by davidhalter** [comment]
Decided not to change this. Feel free to use another Jedi based completion system like deocomplete YCM or all the language servers.
