### ISSUE TITLE
Can not show documentation when using import ... as ...

### ISSUE THREAD

**Issue by leoyanghw** [davidhalter/jedi-vim#766]
### Issue
When using import ... as ..., such as "import tensorflow as tf", the following code like "tf.app.run" can not show documentation using K. It shows "jedi-vim: No documentation found for that." 

### Steps to reproduce

N/A

### Output of “:verbose JediDebugInfo”
N/A

**Comment by davidhalter** [comment]
Pretty sure that Jedi has a hard time understanding what `tf.app` is.

**Comment by davidhalter** [comment]
This is working now.
