### ISSUE TITLE
DIsplay problem with autocomplete in emacs (python)

### ISSUE THREAD

**Issue by iburunat** [davidhalter/jedi-vim#773]
### Layout of autocomplete in python emacs not showing as it should

I recently installed in my Emacs (both Vanilla and Prelude) jedi, auto-complete, and yasnippet-snippets. However, when I press TAB for autocompletion, the display does not show "at point", but like this: https://snag.gy/X8cULh.jpg. I wonder how to get the more pleasing "box-at-point" display, that I see elsewhere.

**Comment by davidhalter** [comment]
@iburunat Sorry, this tracker has absolutely nothing to do with emacs. Please talk to the people responsible for your plugin.

**Comment by iburunat** [comment]
Hi David, and apologies for my sloppy use of Github. I will delete this and
post my question on the relevant place. Thanks.
