### ISSUE TITLE
change jedi cache path

### ISSUE THREAD

**Issue by anirudt** [davidhalter/jedi-vim#778]
### Issue

Is there an option to change the cache path for jedi-vim to something other than ~/.cache/jedi?
I have some issues using this as the path. If this has already been discussed/elaborated, please let me know.

**Comment by davidhalter** [comment]
There is a setting in jedi that you can overwrite (`jedi.settings.cache_directory`). However jedi-vim currently doesn't use it. If you want you can create a pull request to make that configurable. I won't implement that myself.

**Comment by anirudt** [comment]
Hi,

Could you give me some pointers to a file in which the above variable is referenced? I couldn't find it (cloned & grepped on it). It would be useful, I do intend on sending a PR.

**Comment by davidhalter** [comment]
It's not part of jedi-vim. The variable you need to change is part of jedi. This is a subrepository in jedi-vim and already imported.

I'm not sure if it's extremely easy to use this setting.

**Comment by davidhalter** [comment]
Decided not to implement this, as there is not enough interest from the community.
