### ISSUE TITLE
Open file in new tab . 

### ISSUE THREAD

**Issue by vishichoudhary** [davidhalter/jedi-vim#779]
### Issue

Currently if the defination is not in opened file vim will open the file containing the defination in same tab. Can't there we anything like if the defination is not in current file open new file in new tab.

<!--
Include if relevant.

Please provide steps to reproduce it here, preferably based on a minimal Vim
configuration.

You can use the following template (save it as `minimal.vimrc` in the directory
where jedi-vim is installed, `cd` into that directory, and run Vim with
`vim -u minimal.vimrc`):

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

" Put your config changes here.
" let g:jedi#show_call_signatures=1

syntax on
filetype plugin indent on
```

Please provide the `minimal.vimrc` you have used here, too.
-->


<!--
Please execute `:redir @+> | silent verb JediDebugInfo | redir END` in a
Python buffer to copy debug information into your clipboard.
Then paste it here.
-->

**Comment by davidhalter** [comment]
Did you see `let g:jedi#use_tabs_not_buffers`?

Please read the README next time.
