### ISSUE TITLE
this plug not worked for third-party modules

### ISSUE THREAD

**Issue by duanmuq** [davidhalter/jedi-vim#780]
### Issue

I,m a newer for vim, I want to write python3 code in vim, so I have install this plug with neovim in ubuntu systerm. The jedi already installed using pip3 tools. In most case, this tools works good for python code.

The problem is some third-party modules using many .so files, I guess these are some function realized by c or cpp code. and in this situation, the completion not worked. I have test the pygame and matplot mould, they both have the similar problem. 

I also try other autocompletion tools, such as nvim-completion-manager, YCM, jedi-vim, they all have the same problem. Other guys suggest me this is a jedi problem, so i post this problem here.

### Steps to reproduce

you can try this code:

import pygame
pygame.init()
screen = pygame.display.set_mode((640, 480), 0, 32)

The "set_mode" will not complete, and jedi-vim goto command also not work. The array fuction in numpy module have the same issue. I don't know how to solve this issue.

by the way, I also use the following code to check the jedi work or not, and not found something strange.
        import pygame
        print(pygame)

        import jedi
        list = jedi.Script('import pygame; pygame.display.').completions()
        print(list)

the output is:
       <module 'pygame' from '/usr/local/lib/python3.5/dist-packages/pygame/__init__.py'>

        [<Completion: info>, <Completion: name>, <Completion: reason>, <Completion: urgent>, <Completion: warn>, <Completion: _NOT_IMPLEMENTED_>, <Completion: __class__>, <Completion: __delattr__>, <Completion: __dir__>, <Completion: __doc__>, <Completion: __eq__>, <Completion: __format__>, <Completion: __ge__>, <Completion: __getattr__>, <Completion: __getattribute__>, <Completion: __gt__>, <Completion: __hash__>, <Completion: __init__>, <Completion: __le__>, <Completion: __lt__>, <Completion: __ne__>, <Completion: __new__>, <Completion: __nonzero__>, <Completion: __reduce__>, <Completion: __reduce_ex__>, <Completion: __repr__>, <Completion: __setattr__>, <Completion: __sizeof__>, <Completion: __str__>, <Completion: __subclasshook__>]

### Output of “:verbose JediDebugInfo”

:verbose JediDebugInfoe...
#### Jedi-vim debug information
Using Python version: 3
 - sys.version: `3.5.2 (default, Nov 23 2017, 16:37:01), [GCC 5.4.0 20160609]`
 - site module: `/usr/lib/python3.5/site.py`
Jedi path: `/home/jj/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init
__.py`
 - version: 0.11.1
 - sys_path:
    - `/usr/lib/python35.zip`
    - `/usr/lib/python3.5`
    - `/usr/lib/python3.5/plat-x86_64-linux-gnu`
    - `/usr/lib/python3.5/lib-dynload`
    - `/home/jj/.local/lib/python3.5/site-packages`
    - `/usr/local/lib/python3.5/dist-packages`
    - `/usr/lib/python3/dist-packages`
    - `_vim_path_`
 - jedi-vim git version: 37bd03c
 - jedi git submodule status:  02f238ce08f2d7f9c4af9a17cbf5754836775e2f pythonx/
jedi (v0.11.1)
 2ca629a2f6db2e905ddd5188113b1045f8a00fc2 pythonx/parso (v0.1.1)

  omnifunc=jedi#completions
        Last set from ~/.local/share/nvim/plugged/jedi-vim/autoload/jedi.vim
  completeopt=menuone,longest,preview
        Last set from ~/.local/share/nvim/plugged/jedi-vim/plugin/jedi.vim
```


#### :version
  completeopt=menuone,longest,preview
        Last set from ~/.local/share/nvim/plugged/jedi-vim/plugin/jedi.vim
```

#### :version
```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong
 -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG
-Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE
=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -peda
ntic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protecto
r-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
 -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-
0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/inc
lude -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src
/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages
```
"jiba.py" 9L, 123C
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong
 -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG
-Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE
=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -peda
ntic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protecto
r-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
 -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-
0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/inc
lude -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src
nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
```

<details><summary>:scriptnames</summary>

```
  1: ~/.config/nvim/init.vim
  2: ~/.local/share/nvim/site/autoload/plug.vim
  3: /usr/share/nvim/runtime/filetype.vim
  4: /usr/share/nvim/runtime/ftplugin.vim
  5: /usr/share/nvim/runtime/indent.vim
  6: /usr/share/nvim/runtime/syntax/syntax.vim
  7: /usr/share/nvim/runtime/syntax/synload.vim
  8: /usr/share/nvim/runtime/syntax/syncolor.vim
  9: ~/.local/share/nvim/plugged/jedi-vim/plugin/jedi.vim
 10: /usr/share/nvim/runtime/plugin/gui_shim.vim
 11: /usr/share/nvim/runtime/plugin/gzip.vim
 12: /usr/share/nvim/runtime/plugin/health.vim
 13: /usr/share/nvim/runtime/plugin/man.vim
 14: /usr/share/nvim/runtime/plugin/matchit.vim
 15: /usr/share/nvim/runtime/plugin/matchparen.vim
 16: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 17: /usr/share/nvim/runtime/plugin/rplugin.vim
 18: /usr/share/nvim/runtime/plugin/rrhelper.vim
 19: /usr/share/nvim/runtime/plugin/shada.vim
 20: /usr/share/nvim/runtime/plugin/spellfile.vim
 21: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 22: /usr/share/nvim/runtime/plugin/tohtml.vim
 23: /usr/share/nvim/runtime/plugin/tutor.vim
 24: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 25: ~/.local/share/nvim/plugged/jedi-vim/ftplugin/python/jedi.vim
 26: ~/.local/share/nvim/plugged/jedi-vim/autoload/jedi.vim
 27: /usr/share/nvim/runtime/autoload/provider/python3.vim
 28: /usr/share/nvim/runtime/autoload/provider/pythonx.vim
 29: /usr/share/nvim/runtime/autoload/remote/host.vim
 30: /usr/share/nvim/runtime/autoload/provider.vim
 31: /usr/share/nvim/runtime/ftplugin/python.vim
 32: ~/.local/share/nvim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 33: /usr/share/nvim/runtime/indent/python.vim
 34: /usr/share/nvim/runtime/syntax/python.vim
 35: ~/.local/share/nvim/plugged/jedi-vim/after/syntax/python.vim
```
</details>

**Comment by davidhalter** [comment]
This is something that appeared before.

https://github.com/davidhalter/jedi-vim/issues/146

I'm sorry, but I don't see us supporting this feature in the near future.

**Comment by enkeyz** [comment]
This is the reason I don't use vim in work. Cuz these "auto-completion" plugins can't work with complex objects. Just use PyCharm or Visual Studio.
