### ISSUE TITLE
Readme : wrong stackoverflow link

### ISSUE THREAD

**Issue by MaximeSauvage1** [davidhalter/jedi-vim#782]
Hi !

I recently discovered that the stackoverflow link in the readme redirect on the main page of the website.
I propose this link instead : https://stackoverflow.com/questions/tagged/jedi-vim
That will lead to the posts that contains the tag "jedi-vim" and should be very helpful for people looking for help.
Could I submit you a PR to resolve the problem? It will be my first contribution on GitHub and I'll be glad to do it for you.

**Comment by davidhalter** [comment]
Yeah, I'd be happy to receive a PR :) Thanks dude!

**Comment by MaximeSauvage1** [comment]
Thanks to let me contribute to this project.
Hope I did nothing wrong.

**Comment by davidhalter** [comment]
Even if you did something wrong - that's what pull requests are for.
