### ISSUE TITLE
Start jedi vim with different filetype than .py

### ISSUE THREAD

**Issue by szymonmaszke** [davidhalter/jedi-vim#784]
Title pretty much says it all. I have a custom filetype (mix of markdown and python) and I would like to turn jedi-vim on for it.
Documentation is pretty sparse on this, so any help would be appreciated, thanks.

**Comment by blueyed** [comment]
Try `:runtime! runtime ftplugin/python/jedi.vim after/ftplugin/python/jedi.vim`.

**Comment by blueyed** [comment]
Are you using `g:markdown_fenced_languages` to enable Python highlighting in the files already?
Just thought that we could ship a syntax file that would load jedi-vim when the Python syntax is used.

**Comment by vyzyv** [comment]
No, I'm using custom syntax file mixing the two (```region```, ```matchgroup```, ```containedin``` etc.).
From what I've checked I would need vim-markdown plugin for ```g:markdown_fenced_languages```, right? And I'd rather avoid this external dependency.

Unluckily your solution does not work, are there any plans for jedi supporting embedded files? Or just a loose idea?

**Comment by blueyed** [comment]
1. `g:markdown_fenced_languages` is in Vim's runtime.
2. it works for me, e.g. the smart complete after `from os import `, and completions also work - but I had to rename the file first to `.py` (and back).  Not sure if that is related to my specific setup though (e.g. I am lazy-loading jedi-vim for .py files in insert mode).
It seems like it (i.e. Jedi) might require an actual .py file though initially.

**Comment by vyzyv** [comment]
Sorry, I wasn't clear on this one. I have already enabled completion using deoplete-jedi (it seems to do better with big libraries like tensorflow), I would like to integrate other jedi functionalities like documentation/go to definition with my filetype.

Also I've been looking for some global variable telling whether jedi-vim was loaded (for example in deoplete it's g:loaded_deoplete) to no avail. Is it provided somewhere?

**Comment by blueyed** [comment]
> integrate other jedi functionalities like documentation/go to definition with my filetype

Works for me when using `:runtime ftplugin/python/jedi.vim`.
Try `:debug runtime ftplugin/python/jedi.vim` in case it really does not for you.

> global variable telling whether jedi-vim was loaded

We could have g:loaded_jedi, but it would typically be set in `plugin/jedi.vim` then (i.e. it does not mean the plugin is activate for the buffer) - not helping you much probably, or does it actually (i.e. unrelated to this issue)?

> vyzyv/vimpyter

Looks interesting!

**Comment by davidhalter** [comment]
Thanks again for your work here @blueyed. I just tested this and it seems to work very well. Please report it if something doesn't work.
