### ISSUE TITLE
AttributeError when using let g:jedi#show_call_signatures = 2

### ISSUE THREAD

**Issue by DervishD** [davidhalter/jedi-vim#785]
### Issue
```
jedi 0.11.1
vim 8.0.1553
Windows 10 x64
[I don't know how to obtain jedi-vim version]
```

When using `let g:jedi#show_call_signatures = 2` in my `.vimrc` (together with `set noshowmode`, of course), Vim produces the following error instead of showing the function signature on the command line:
    
    Traceback (most recent call last):
      File "...vim/vimfiles\pythonx\jedi_vim.py", line 128, in wrapper
        return func(*args, **kwargs)
      File "...vim/vimfiles\pythonx\jedi_vim.py", line 457, in cmdline_call_signatures
        max_msg_len -= len(signatures[0].call_name) + 2  # call name + parentheses
    AttributeError: 'CallSignature' object has no attribute 'call_name'

Curiously enough, `let g:jedi#show_call_signatures = 1` works perfectly, showing the popup with the correct function signature.

### Steps to reproduce

Create an empty Python file, edit it with Vim and include the following text:
```
import time
time.sleep(
```

After typing the opening parentheses the error is produced, silently. The error message is only visible when typing `:messages` after it has produced, in my Vim setup.

No difference between my usual `.vimrc` and a minimal one, but I'm including here the minimal one I've used for testing:

```
set nocompatible
set noshowmode

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

" Put your config changes here.
let g:jedi#show_call_signatures=2

syntax on
filetype plugin indent on

```

### Output of “:verbose JediDebugInfo”

I'm sorry, when trying to get JediDebugInfo I got the following error:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test.pyw" [unix] 2L, 17C
Error detected while processing function jedi#debug_info:
line   28:
Traceback (most recent call last):
  File "C:/Users/DervishD/Desktop/Drive/config/vim/vimfiles\pythonx\jedi_vim_debug.py", line 34, in display_debug_info
    for p in jedi_vim.jedi.Script('')._evaluator.sys_path:
AttributeError: 'Evaluator' object has no attribute 'sys_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Users/DervishD/Desktop/Drive/config/vim/vimfiles\pythonx\jedi_vim_debug.py", line 38, in display_debug_info
    "{0!r})".format(e))
  File "C:/Users/DervishD/Desktop/Drive/config/vim/vimfiles\pythonx\jedi_vim_debug.py", line 8, in echo
    vim.command('echo {0}'.format(msg))
vim.error: Vim(echo):E117: Unknown function: AttributeError
E171: Missing :endif
```

**Comment by davidhalter** [comment]
This was probably fixed in 7e6811cb4b214fce25d39eec2c4362378c50e479.

Please upgrade your jedi-vim version (the other errors were AFAIK also fixed with the newer version).

**Comment by DervishD** [comment]
Hi @davidhalter and thanks for the information!

I actually saw that commit but I thought I had a later jedi-vim version, from December if I recall correctly. Obviously, I haven't.

Any easy way of checking the jedi-vim version when `JediDebugInfo` fails? I'm probably going to `git pull` it from now on, but just in case I install it by hand again, I'm just curious.

Again, thanks a lot for the help and for replying so fast :)

**Comment by davidhalter** [comment]
You're welcome! :)

There's no "easy" way without JediDebugInfo. That command was broken for a while and it's hopefully fixed now. Please let me know if it still fails.

**Comment by DervishD** [comment]
@davidhalter I decided to install jedi-vim using `git clone` to keep it up to date easily, and in the latest version (well, latest as of yesterday, March 7th 2018), `JediDebugInfo` works perfectly, except for getting the version of `jedi-vim`, but that's not a bug, it's because my git install on my Windows, no biggie.

As for the original issue, now it throws another different error:
```
Traceback (most recent call last):
  File "XXXX\vimfiles\pack\_\start\jedi-vim\pythonx\jedi_vim.py", line 131, in wrapper
    return func(*args, **kwargs)
  File "XXXX\vimfiles\pack\_\start\jedi-vim\pythonx\jedi_vim.py", line 497, in cmdline_call_signatures
    column - len(signatures[0].name),
  File "XXXX\vimfiles\pack\_\start\jedi-vim\pythonx\jedi_vim.py", line 80, in vim_eval
    return _catch_exception(string, True)
  File "XXXX\vimfiles\pack\_\start\jedi-vim\pythonx\jedi_vim.py", line 71, in _catch_exception
    raise VimError(result['exception'], result['throwpoint'], string)
jedi_vim.VimError: Vim(let):E121: Undefined variable: g:jedi#first_col; created by: 'g:jedi#first_col +wincol() - col(".")'
```

Do you want me to open a new issue for this or is it not needed?

Thanks A LOT for `jedi-vim` and for your help :)

**Comment by davidhalter** [comment]
Do you have a `let g:jedi#auto_initialization = 0` somewhere? If so, please read the docs.

**Comment by DervishD** [comment]
Nope, David, the only setting I have regarding `jedi-vim` is `let g:jedi#smart_auto_mappings = 0`.

When I have the time I'll try to debug this issue and I'll provide more information.
