### ISSUE TITLE
Goto Overridden Method

### ISSUE THREAD

**Issue by voidus** [davidhalter/jedi-vim#786]
It would be nice if there was a way to navigate from an overriding method to the overridden one.

Example:
```python
class A:
  def foo():  # should go to here
    pass

class B(A):
  def foo(): # cursor on "foo", \d just stays in this line
    pass
```

As the goto isn't really useful by default here, maybe it could just go to the next method in the MRO when over a method definition?

**Comment by davidhalter** [comment]
This would be nice in the future. Can you please post that to the jedi tracker? Here it will not be noticed.

I'm not sure exactly if it's a great idea as a default.

**Comment by davidhalter** [comment]
Jedi issue: https://github.com/davidhalter/jedi/issues/1175
