### ISSUE TITLE
can jedi-vim complete Python function name when imported by `from A import *`

### ISSUE THREAD

**Issue by NewUserHa** [davidhalter/jedi-vim#791]
can jedi-vim complete Python function name when imported by from A import *

it's a good feature and I cost days for the answer.
can jedi-vim do this?
if jedi-vim can, can it be documented?
thanks!

**Comment by davidhalter** [comment]
Just look up the documentation for jedi. You will find a list of supported things there.

Jedi supports most Python features - including the star import.

**Comment by NewUserHa** [comment]
thank you very much
