### ISSUE TITLE
Ability to filter out usages from standard library

### ISSUE THREAD

**Issue by fenuks** [davidhalter/jedi-vim#792]
Hello, it would be useful to have option to configure jedi-vim to *not* show usages from standard library.
For instance for following code
```python
import socket
socket
# ^ :call jedi#usages() on `socket`
```
quickfix window is populated with dozens of matches, that might be not particularly interesting from the standpoint of the project I am working on.

**Comment by davidhalter** [comment]
Usages is going to get reworked very soon anyway. You probably just have to wait for at least half a year.

**Comment by fenuks** [comment]
Thank you for letting me know. Can you share some details, if that doesn't pose too much trouble?

**Comment by fenuks** [comment]
Sounds great. Can't wait!

**Comment by davidhalter** [comment]
This should be way better now. The latest changes haven't arrived in jedi-vim and the release is not public, but according to my tests everything is looking pretty good.
