### ISSUE TITLE
Is it possible to keep quickfix window open after selection?

### ISSUE THREAD

**Issue by HansPinckaers** [davidhalter/jedi-vim#793]
Hi all,

I think this line causes the quickfix window to close on \<CR\>. I would like it to stay open. Is there a way to do that?

https://github.com/davidhalter/jedi-vim/blob/48af2afd3ef06a61242d5c08a6357879ea639c36/autoload/jedi.vim#L406

edit: I commented these lines out in my local plugin and it works. Any way to do this in a nicer way? 

Thanks for your help,
Hans

**Comment by davidhalter** [comment]
For now there is no nicer way in jedi-vim. You cannot simply reconfigure it.

However you could maybe define an `autocmd BufEnter` that changes the `augroup jedi_goto_window`:

```
augroup jedi_goto_window
    au!
augroup END
```

You obviously still have to wrap that with BufEnter and I'm not even sure that works. If you have some VIM script knowledge you can probably somehow overwrite it like that.
