### ISSUE TITLE
Crash on autocomplete when using type hints for protobuf classes

### ISSUE THREAD

**Issue by pascalwhoop** [davidhalter/jedi-vim#794]
Vim crashes when using the following code the moment the `.` is placed after `request`:

```python
class PortfolioManagerService(ptac_grpc.PortfolioManagerServiceServicer):
    def handlePBCashPosition(self, request:ptac_pb2.PBCashPosition, context):
        request. #crash
        warn_about_grpc_not_implemented()
        return ptac_pb2.Empty()

```

it seems the moment the autocomplete is triggered, something is happening with the protobuf generated sources that jedi doesn't like. 

```
[libprotobuf FATAL google/protobuf/stubs/common.cc:67] This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
```

**Comment by davidhalter** [comment]
This will be fixed in a few days (maybe weeks) once jedi 0.12.0 is released.

**Comment by pascalwhoop** [comment]
@davidhalter do you mind sharing a link where I can follow up on this? Will Jedi be able to autocomplete this metaclass magic that's going on or will just the crash be avoided? Protobuf generates this really weird code from the proto files and all IDEs fail to work with this. pyCharm doesn't do anything and vim crashed so if Jedi now somehow learns to autocomplete this, that would be amazing.

**Comment by davidhalter** [comment]
You can follow the release schedule here: https://github.com/davidhalter/jedi/issues/1063.

Understanding metaclass magic will only be possible with https://github.com/davidhalter/jedi/issues/626.

So I'm sorry to disappoint you, understanding this is not that easy :)

**Comment by pascalwhoop** [comment]
Thanks! 
It may also be solved on the protobuf side by generating more info

https://github.com/google/protobuf/issues/2638

Apparently there's a mypy-protobuf project by the Dropbox crew

https://github.com/dropbox/mypy-protobuf
