### ISSUE TITLE
Change colour of completion menu

### ISSUE THREAD

**Issue by ashishtibrewal** [davidhalter/jedi-vim#797]
### Issue
Hi there, I would like to know if it is possible to change the background colour of the completion (and function definition) menus? In my current setting the colour of the function definition menu is the same as my window background which makes it difficult to differentiate the function definition text from the content already present in the current buffer. Please have a look at the following screenshot:

![screenshot](https://user-images.githubusercontent.com/8990952/38312280-fa705d9a-383e-11e8-8049-9016dde81972.png)

Please let me know if this is possible or if I need to change some settings on other completion plugins that are currently being used.

**Comment by davidhalter** [comment]
This has nothing to do with jedi-vim, but here you go:

https://vi.stackexchange.com/questions/12664/is-there-any-way-to-change-the-popup-menu-color
