### ISSUE TITLE
How I can disable the parameter recommendation list for functions

### ISSUE THREAD

**Issue by widon1104** [davidhalter/jedi-vim#799]
### Issue
How can I disable the parameter recommendation list for functions after typing the open bracket. I don't like this feature.I don't know how to disable it.Just tell me a way to do it.

### Steps to reproduce
my vimrc
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" jedi
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:jedi#popup_on_dot = 0
let g:SuperTabDefaultCompletionType = "<C-n>"
let g:jedi#popup_select_first = 0
let g:jedi#goto_command = "<leader>d"
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = "<C-]>"
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#completions_command = "<C-n>"
let g:jedi#rename_command = "<leader>r"

**Comment by davidhalter** [comment]
The README is not quite clear enough I think, but it's

```
let g:jedi#show_call_signatures = "0"
```
