### ISSUE TITLE
completion asyncio slow

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi-vim#809]
### Issue

When completion asyncio very slow.

### Steps to reproduce

```
import asyncio

asyncio.
```
jedi-vim\pythonx\jedi_vim.py, line 206:
ignore `info=PythonToVimStr(c.docstring()),` seem to be resolved.

**Comment by davidhalter** [comment]
Hmm maybe the `fast` option is not really properly working anymore. Is it faster the second time you complete? Can you measure the time maybe?

**Comment by davidhalter** [comment]
It's pretty fast now after the first time (probably since Jedi 0.15). The first time it takes a few seconds. But this is a known issue in Jedi and there's a couple of tickets in Jedi. Especially the one about the database index.

The caches just need to be loaded first.
