### ISSUE TITLE
Disable jedi's autocompletion for tensorflow

### ISSUE THREAD

**Issue by walkerlala** [davidhalter/jedi-vim#810]
Is it possible to disable autocompletion for a specific module? When auto-complete for tensorflow, jedi-vim runs too slow and block the whole editor, so I would like to disable it for tensorflow. 

ps, I am using pathegon to load module.

**Comment by davidhalter** [comment]
Currently there is no such thing at the moment. I'm hoping that it will get a lot better with a few changes in the future, stay tuned. Otherwise we might just do what you propose here. The only thing that might help (but really doesn't exactly do what you want) is adding `tensorflow` to `jedi.settings.auto_import_modules`.

**Comment by svetlov** [comment]
@davidhalter so is it possible now to preload modules with `jedi.settings.auto_import_modules`? i can't find any relative information about this option in jedi-vim docs.

**Comment by davidhalter** [comment]
It's not possible in jedi-vim and I doubt it would really help you a lot. The problem in tensorflow is that it's always slow no matter what you do.

**Comment by davidhalter** [comment]
This won't happen. The way to deal with this (if you're annoyed by it) is using another Jedi plugin that's async. You can use either `deoplete-jedi` or `YouCompleteMe`. It's very much possible to use those plugins only for completions and use jedi-vim for the rest (signatures, etc).

**Comment by caixxiong** [comment]
> This won't happen. The way to deal with this (if you're annoyed by it) is using another Jedi plugin that's async. You can use either `deoplete-jedi` or `YouCompleteMe`. It's very much possible to use those plugins only for completions and use jedi-vim for the rest (signatures, etc).

Hi, Thanks for this good job! I have a similar problem about TensorFlow. When I import tensorflow modules, the jedi plugin only completes less than 3 level of path. For example,  when I type ` tf.keras` , there is no any completion prompt for me. And the parameter list is not available for tensorflow functions. But all these things can work well for other python libraries ,e.g., numpy, panda.
My environment infos are as follows:
- mac os x 10.14.6
- vim 8.2 with option: +python3 -python +conceal (this vim is compiled by me)
-python3.7.7
-jedi 0.17.0
