### ISSUE TITLE
The little popup window when typing a ( does not show up in neovim

### ISSUE THREAD

**Issue by BrandonShega** [davidhalter/jedi-vim#811]
#### Jedi-vim debug information
Using Python version: 3
 - sys.version: `3.6.4 (default, Mar  1 2018, 18:36:42), [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
 - site module: `/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py`
Jedi path: `/Users/bshega/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.0
 - sys_path:
            Error detected while processing function jedi#debug_info[28]..provider#python3#Call:
line   18:
Traceback (most recent call last):

  File "/Users/bshega/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 37, in display_debug_info
    sys_path = script_evaluator.project.sys_path

AttributeError: 'Project' object has no attribute 'sys_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/bshega/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 39, in display_debug_info
    sys_path = script_evaluator.sys_path

AttributeError: 'Evaluator' object has no attribute 'sys_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/bshega/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 44, in display_debug_info
    "{0!r})".format(e))

  File "/Users/bshega/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 8, in echo
    vim.command('echo {0}'.format(msg))

  File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 242, in command
    return self.request('nvim_command', string, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 140, in request
    res = self._session.request(name, *args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)

neovim.api.nvim.NvimError: b'Vim(echo):E117: Unknown function: AttributeError'
syntax-error: unexpected EOF while parsing (<string>, line 7)-- INSERT ---- INSERT --
No matching autocommands-- INSERT ---- INSERT ---- INSERT --
No matching autocommands

syntax-error: unexpected EOF while parsing (<string>, line 7)

**Comment by davidhalter** [comment]
I'm pretty sure that JediDebugInfo will be better once #806 is going to be merged. So let's wait for that.

**Comment by blueyed** [comment]
Reminded me of https://github.com/neovim/neovim/issues/3757 - i.e. a bug in Neovim, where CursorHoldI might get/be broken.

**Comment by blueyed** [comment]
@BrandonShega 
Are you using deoplete also?

**Comment by BrandonShega** [comment]
@blueyed I am using deoplete, yes.

**Comment by blueyed** [comment]
@BrandonShega 
Normally `<c-x><c-o>` should work by itself (even in Neovim) - not sure when you expect it to happen though.
Anyway, #652 is the way forward IMHO anyway.

**Comment by blueyed** [comment]
@BrandonShega 
Have you tried https://github.com/davidhalter/jedi-vim/pull/652 (I've just rebased it).

**Comment by davidhalter** [comment]
Same issue as #493. We are trying to get rid of changing the buffer for this feature and are trying to use floating windows.
