### ISSUE TITLE
`attrs` created classes does not support `__init__` args tooltips

### ISSUE THREAD

**Issue by gr4viton** [davidhalter/jedi-vim#816]
### Issue

The tooltip for instantiation of `attrs`-style defined class is not showing arg variables.

### Steps to reproduce

Define class via `attrs`
```python
from attr import attrs, attrib
@attrs
class Class()
   a = attrib()
   b = attrib(default=42)
```
Tooltip for class initialization shows: 

```py
     (...)
Class(
```

It would be more usefull if the init args tooltip shown the actual generated args.

```py
     (a, b=42)
Class(
```

Though, not sure how difficult it would be to search for `@attrs` wrapper and parse the vars. 

Also the `attr.make_class` can be used, where the `__init__` args are defined in form of dict, which can possibly be even more difficult to parse.

### Output of “:verbose JediDebugInfo”

N/A

**Comment by davidhalter** [comment]
This goes into the direction of https://github.com/davidhalter/jedi/issues/626

I suppose that it will take at least a year, but it's not going to be possible without a plugin structure.
