### ISSUE TITLE
Can I start completion with the 1st char after dot?

### ISSUE THREAD

**Issue by pasiiww** [davidhalter/jedi-vim#818]
**Can I start completion with the 1st or 2nd char after dot?**
such as `ycm_min_num_of_chars_for_completion = 1` in ycm
i just don't want to see all the completion after dot because sometime it reveals to much 
and in which way maybe it would lag less?
(sorry for my poor english

**Comment by blueyed** [comment]
jedi-vim uses an abbreviation for this (https://github.com/davidhalter/jedi-vim/blob/6781eb17dad705eab1d1d932ebf3b1871a90c783/ftplugin/python/jedi.vim#L37).
It's not trivial to change this to require more chars, but the help (`:h :map-expression`) mentions that `getchar()` could be used.  It would likely cause Vim to not display what you typed though.

I suggest looking at deoplete and deoplete-jedi for completions, which provides more customization)  It can be used together with jedi-vim, if you disable completions in jedi-vim.

**Comment by davidhalter** [comment]
Like @blueyed I would argue that this is not easily possible at the moment, but if you find an easy way to make this possible, let us know.

Since this doesn't seem very realistic, I'm closing for now.
