### ISSUE TITLE
Can't use jedi-vim for python

### ISSUE THREAD

**Issue by PhungVanDuy** [davidhalter/jedi-vim#820]
I use jedi-vim when using python, but it has problems like the one pictured below. Previously I still use normally.

![screenshot from 2018-05-16 18-46-56](https://user-images.githubusercontent.com/28798474/40155241-c3571002-59bc-11e8-8742-3b80a4cf7434.png)

**Comment by blueyed** [comment]
The error from Jedi appears to be:
`ModuleNotFoundError: No module named 'distutils.spawn'`

@PhungVanDuy 
You should be able to see the traceback in `:messages` - so that you could have copied it from there.

It looks like you are using Ubuntu and that its apport hook is involved there, too.
Can you try `:verbose JediDebugInfo`? (see the issue template)

**Comment by PhungVanDuy** [comment]
@blueyed Thank you for your reply!

`Using Python version: 2                                                                                                                                                                 
 - global sys.version: `2.7.12 (default, Dec  4 2017, 14:50:18), [GCC 5.4.0 20160609]`                                                                                                  
 - global site module: `/usr/lib/python2.7/site.pyc`                                                                                                                                    
Jedi path: `/home/pvduy/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.pyc`                                                                                                           
 - version: 0.12.0                                                                                                                                                                      
 - environment: <Environment: 3.6.5 in /usr>                                                                                                                                            
There was an error accessing jedi_vim.jedi: The subprocess /usr/bin/python3.6 has crashed.                                                                                              
Traceback (most recent call last):                                                                                                                                                      
  File "/home/pvduy/.vim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 45, in display_debug_info                                                                                    
    sys_path = environment.get_sys_path()                                                                                                                                               
  File "/home/pvduy/.vim/plugged/jedi-vim/pythonx/jedi/jedi/cache.py", line 142, in wrapper                                                                                             
    result = method(self, *args, **kwargs)                                                                                                                                              
  File "/home/pvduy/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/environment.py", line 116, in get_sys_path                                                                              
    return self._get_subprocess().get_sys_path()                                                                                                                                        
  File "/home/pvduy/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 161, in get_sys_path                                                        
    return self._send(None, functions.get_sys_path, (), {})                                                                                                                             
  File "/home/pvduy/.vim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/compiled/subprocess/__init__.py", line 205, in _send                                                               
    raise InternalError("The subprocess %s has crashed." % self._executable)                                                                                                            
InternalError: The subprocess /usr/bin/python3.6 has crashed.                                                                                                                           
 - jedi-vim git version: f07ff6a                                                                                                                                                        
 - jedi git submodule status:  bd7c65d9639c2d451d44c6d135b4f6043a918950 pythonx/jedi (v0.12.0)                                                                                          
 579146b5010ae22aa0a32c6098413189baa4367d pythonx/parso (v0.2.0)`

This is the message. Maybe my system using python 2.7 but jedi-vim require python 3.6. How to config for my system ?

**Comment by blueyed** [comment]
Can you try https://github.com/davidhalter/jedi/pull/1124 to see why Jedi crashes?

It looks a bit like your Python 3 might be just broken.

Can you run `/usr/bin/python3.6` by itself?

**Comment by PhungVanDuy** [comment]
![image](https://user-images.githubusercontent.com/28798474/40173623-a3b36724-59fc-11e8-8a4c-1afd78b56959.png)
@blueyed It still working! How to fix it!

**Comment by davidhalter** [comment]
Please try davidhalter/jedi#1124.

**Comment by davidhalter** [comment]
Did it work?
