### ISSUE TITLE
goto_assigment and goto freeze NeoVim

### ISSUE THREAD

**Issue by RobinRamael** [davidhalter/jedi-vim#825]
### Issue

Calling `<leader>d` shows that the jedi#goto()` was called in the statusbar, but it freezes the entire editor (can't cancel or do anything with it) undefinitely. Even ctrl-c and ctrl-z don't work.

### Steps to reproduce

minimal vimrc:

```
let g:python_host_prog = expand('~/.pyenv/versions/neovim2/bin/python')
let g:python3_host_prog = expand('~/.pyenv/versions/neovim3/bin/python')

"" PLUGINS {{{1
" auto-install vim-plug
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
call plug#begin(expand('~/.config/nvim/plugged'))

Plug 'davidhalter/jedi-vim'

call plug#end()

let mapleader=","

let g:jedi#goto_command = "<leader>d"
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = ""
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#rename_command = "<leader>r"

```

### Output of “:verbose JediDebugInfo”

It looks like running `:verbose JediDebugInfo` also freezes neovim...

I've checked with the latest version of regular vim and the problem persists there too. Is there something I'm missing?

**Comment by davidhalter** [comment]
Does it happen regardless where you are using it? e.g. in an empty document?

**Comment by RobinRamael** [comment]
After a rework of my python/nvim environment, goto definition seems to work again, so I'm closing this issue. I'm not sure what I did to fix it, but should anyone have a similar issue: What I ended up fixing first (and which seems to have helped here) is to stop using `pyenv-virtualenv` in favor of what I was using before that, good old `virtualenvwrapper` to manage the environment used by neovim.
