### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [davidhalter/jedi-vim#827]
Hi Sir @davidhalter , I am a graphic designer and i want to contribute to your good project by proposing a logo design for jedi-vim to give it an image representation and be a more visible program. If you will give me permission or it interests you,I will begin the designs and show you here. I will be giving it to the project as my gift for free. :) 

Thanks and best regards Sir,

-Tobaloidee

**Comment by davidhalter** [comment]
Hi @Tobaloidee Yeah please do :) I will not promise yet that we'll use it, but we're excited for any help!

**Comment by davidhalter** [comment]
One thing maybe: Don't use Star Wars light sabers or Master Yoda or whatever from the star wars universe. I'm already not liking the fact that it's called jedi (for trademark reasons) so if we ever rename, it would be nice if the logo could stay kind of the same. Sorry for the inconvenience.

**Comment by Tobaloidee** [comment]
Hi Sir! I will take note of that.. do you have something in mind that i can incorporate to the idea of my design? Or color preferences?

**Comment by davidhalter** [comment]
My girlfriend drew the logo for parso: http://parso.readthedocs.io/en/latest/

I liked that one, but yours doesn't have to be the same. I liked that it wasn't some crazy colors, but really just feel free. It can also be crazy. I'll just let you do your work ;-)

**Comment by Tobaloidee** [comment]
Okay Sir .thanks! I will post my draft here as soon as i finished it..

**Comment by Tobaloidee** [comment]
Hi Sir, heres my design, I made the letters J & V incorporated in a snake that is a Phyton

color version 1
![jedi vim-01](https://user-images.githubusercontent.com/36028424/40520518-223b4506-5ff9-11e8-8c3a-e4ddbb6ccf45.png)
![jedi vim-03](https://user-images.githubusercontent.com/36028424/40520537-3aeb42cc-5ff9-11e8-9180-140ba3e853ad.png)

color version 2
![jedi vim-02](https://user-images.githubusercontent.com/36028424/40520543-4dc9a118-5ff9-11e8-8b0a-13e53ecfd979.png)
![jedi vim-04](https://user-images.githubusercontent.com/36028424/40520544-507769b8-5ff9-11e8-9602-8a69ea19e081.png)

**Comment by davidhalter** [comment]
I llike it a lot! I like the colors. The old pycharm looks a bit similar (especially in colors) that's probably my biggest issue with it :) https://seeklogo.com/vector-logo/273829/pycharm

What do you think @blueyed? Since the pycharm logo has changed and it's not official anymore, I don't really have a problem with it, but maybe we can try it with two different nice colors?

**Comment by Tobaloidee** [comment]
6 color combinations in light/dark background appearance

![all colors-07](https://user-images.githubusercontent.com/36028424/40571128-e5b129d4-60c5-11e8-9d57-cd1fbb63b96f.png)

**Comment by Tobaloidee** [comment]
same for me Sir..blue and orange stands out..ill wait for the final decision then ill make a PR..

**Comment by davidhalter** [comment]
@blueyed What do you think about adding one of these logos? IMO they are very well made and we could happily adopt one for jedi-vim.

**Comment by blueyed** [comment]
Yes, very nice!
I like the first version ("color version 1") the most, followed by blue/orange from the 2nd set, too.

**Comment by Tobaloidee** [comment]
ill just wait for your go signal for me to make a PR and upload the files of the logo..Im glad @blueyed liked it!

**Comment by davidhalter** [comment]
@Tobaloidee Can you make a PR? I think it would make sense to include the logo in the README at the top. Good stuff! Since @blueyed likes green/orange best, I think we can just use that one.

**Comment by Tobaloidee** [comment]
Sure Sir i will prepare the logo files and make a PR when i get home..I am glad that you liked it!

**Comment by Tobaloidee** [comment]
Here's the PR #837 @davidhalter  

Thanks for accepting my contribution! Best regards!

-Tobaloidee

**Comment by davidhalter** [comment]
Thank you! I'll close this one and leave the pull request open.
