### ISSUE TITLE
setup_python_imports: could not import jedi_vim

### ISSUE THREAD

**Issue by hujingguang** [davidhalter/jedi-vim#829]
"test.py" 6L, 50C
Error detected while processing function jedi#init_python:
line    7:
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: could not import jedi_vim: SyntaxError: invalid syntax (parser_utils.py, line 9). (in function jedi#init_python..<SNR>62_init_python..jedi
#setup_python_imports, line 30)
Error detected while processing function <SNR>46_BufReadPostHook..<SNR>46_UpdateErrors..<SNR>46_CacheErrors..17..16..SyntaxCheckers_python_python_GetLocList..SyntasticMake:
line   65:
E380: At bottom of quickfix stack
error list 1 of 1; 1 errors
Error detected while processing function <SNR>46_BufReadPostHook..<SNR>46_UpdateErrors..<SNR>46_CacheErrors..17..39:
line    3:
E712: Argument of filter() must be a List or Dictionary

**Comment by hujingguang** [comment]
please help me T.T

**Comment by blueyed** [comment]
What Python version do you use?
Likely refers to https://github.com/davidhalter/jedi/blob/6fbbeffaebc1c8bc4ee952dfcebcace6f9e88e83/jedi/parser_utils.py#L9.

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.

**Comment by davidhalter** [comment]
@blueyed Sorry didn't see your post. IMO we should just close these and wait for people to fill out the forms. I have a pre-formatted reply ready for people that avoid it. We just lose very much time if we always have to ask questions first. Your debug command is great and at least that is needed to debug most cases.
