### ISSUE TITLE
Metaclass completions

### ISSUE THREAD

**Issue by pattyjogal** [davidhalter/jedi-vim#830]
Hi, I've been using jedi-vim with my current Vim setup, and it's been very good so far. Having migrated over from Pycharm, I did miss the completions on `ModelName.objects`, and after reading through davidhalter/jedi#626 I understand why it's a complex issue.

I don't think I've seen anyone bring up IPython, however, since I noticed when I used its completions feature, it _does_ show suggestions for `ModelName.objects`:

![screenshot from 2018-06-12 00-21-16](https://user-images.githubusercontent.com/13685040/41271520-b8cb7de8-6dd6-11e8-9629-a3467ca5fd11.png)
I even looked through [IPython's source](https://github.com/ipython/ipython/blob/master/IPython/core/completer.py) and it uses jedi for its completions! Beyond that I am not familiar at all with how they accomplish this, but perhaps this could be of some use to anyone wanting to add this feature?

**Comment by davidhalter** [comment]
The difference is actually pretty simple, Jedi has direct access to all the live objects in IPython. If you just do static analysis, this is not possible and you have to write additional code for each meta class.

It's usually very easy to understand Python objects if you have access to them. You can just use `dir(ChatRoom.objects)` and you basically have access to its completions.

**Comment by pattyjogal** [comment]
No that makes perfect sense, thanks!
