### ISSUE TITLE
E523 on vim 8.1

### ISSUE THREAD

**Issue by rjsilvestre** [davidhalter/jedi-vim#831]
Recently Fedora 28 updated its vim package to version 8.1. After this update every time I type '.' and the auto competition popup vim exits insert mode and the popup continues displaying. If I try to enter insert mode by pressing 'i' vim shows a error message: E523: Not allowed here.
Reverting to vim 8.0 does not show the error anymore and everything works fine.
I have jedi-vim installed with vundle.

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.

**Comment by rjsilvestre** [comment]
Sorry, yesterday I was rushing a bit. Was late and felt very tired.
Here is the form, tell me if you need anything else.
Thank you!

### Issue



Recently Fedora 28 updated its vim package to version 8.1. After this update every time I type '.' and the auto competition popup vim exits insert mode and the popup continues displaying. If I try to enter insert mode by pressing 'i' vim shows a error message: E523: Not allowed here.
Reverting to vim 8.0 does not show the error anymore and everything works fine.
I have jedi-vim installed with vundle.

### Steps to reproduce



1. Created a new minimal.vimrc and saved it in ~/.vim/bundle/jedi-vim, the installation folder.
```
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

" Put your config changes here.
" let g:jedi#show_call_signatures=1

syntax on
filetype plugin indent on
```
2. Created a file test.py on the same directory.
3. Run `vim -u minimal.vimrc test.py`.
4. Type some simple code:
```
a = []
a.append(1)
```
5. As soon '.' is typed the popup shows up but vim quits insert mode.
6. Type `i` to enter insert mode, vim shows `E523: Not allowed here`

### Output of “:verbose JediDebugInfo”



This is the debug info using the minimal.vimrc.

#### Jedi-vim debug information
Using Python version: 3
 - global sys.version: `3.6.5 (default, Mar 29 2018, 18:20:46), [GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)]`
 - global site module: `/usr/lib64/python3.6/site.py`
Jedi path: `/home/rjsilvestre/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.0
 - environment: <Environment: 3.6.5 in /usr>
 - sys_path:
    - `/usr/lib64/python36.zip`
    - `/usr/lib64/python3.6`
    - `/usr/lib64/python3.6/lib-dynload`
    - `/usr/local/lib/python3.6/site-packages`
    - `/usr/lib64/python3.6/site-packages`
    - `/usr/lib/python3.6/site-packages`
 - jedi-vim git version: 0.9.0-21-g84a5299
 - jedi git submodule status:  bd7c65d9639c2d451d44c6d135b4f6043a918950 pythonx/jedi (v0.12.0)
 6f385bdba182059e0c46917a414981a6d0894527 pythonx/parso (v0.2.1)


##### Settings
```
  omnifunc=jedi#completions
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim
  completeopt=menuone,preview,noinsert
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim
```


#### :version
```

VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun  6 2018 10:52:31)
Included patches: 1-35
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     -ebcdic            -hangul_input      +lua/dyn           +mouse_xterm       +python/dyn        +tag_binary        +vertsplit         -xpm
+arabic            +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        +python3/dyn       +tag_old_static    +virtualedit       -xsmp
+autocmd           +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +quickfix          -tag_any_white     +visual            -xterm_clipboard
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +reltime           -tcl               +visualextra       -xterm_save
-balloon_eval      +conceal           +extra_search      +jumplist          +mouse             +netbeans_intg     +rightleft         +termguicolors     +viminfo           
+balloon_eval_term +cryptv            +farsi             +keymap            -mouseshape        +num64             +ruby/dyn          +terminal          +vreplace          
-browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +scrollbind        +terminfo          +wildignore        
++builtin_terms    +cursorbind        +find_in_path      +langmap           +mouse_gpm         +path_extra        +signs             +termresponse      +wildmenu          
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     +perl/dyn          +smartindent       +textobjects       +windows           
+channel           +dialog_con        +folding           +linebreak         +mouse_netterm     +persistent_undo   +startuptime       +timers            +writebackup       
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +postscript        +statusline        +title             -X11               
-clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +printer           -sun_workshop      -toolbar           -xfontset          
-clipboard         -dnd               +gettext           +localmap          +mouse_urxvt       +profile           +syntax            +user_commands     -xim

**Comment by rjsilvestre** [comment]
Thank you for the reply.
I upgraded again from 8.0 to 8.1 and suddenly all was working fine.
When I looked at the version of Vim I noticed that Fedora repos have a higher patch version: 0042.
On the [release notes](https://github.com/vim/vim/releases/tag/v8.1.0042) it states to solve exactly the problem I found.
Thank you for your help!
