### ISSUE TITLE
Autocomplete without key binding

### ISSUE THREAD

**Issue by dzervas** [davidhalter/jedi-vim#84]
hello,
can you add an option to make jedi like autocomplpop?
autocmplpop autocompletes as you type, without the need of ctrl+space or tab.
thank you.

**Comment by msm-code** [comment]
I guess that issue is dead now? That's a shame, because it's one feature that I really miss in jedi-vim.

**Comment by johntyree** [comment]
@msm-code I've been using youcompleteme+jedi to get this behavior. It's both fast and easy. I recommend going that route.

**Comment by blueyed** [comment]
You should use deoplete, YCM or something similar as a wrapper.
