### ISSUE TITLE
The completion is in incomplete when packages in different levels have the same name.

### ISSUE THREAD

**Issue by qs-cosmos** [davidhalter/jedi-vim#855]
+ The  project structure 
![2018-07-24 3 12 22](https://user-images.githubusercontent.com/33800508/43122542-084a2b5a-8f54-11e8-8e0d-d646e58c60f8.png) ![2018-07-24 3 19 35](https://user-images.githubusercontent.com/33800508/43122860-030ad760-8f55-11e8-918e-9bb1bdcd6c73.png)

+ Edit the `a/a/d/d.py`, the completion may be `a` or `b`, not be `c` or `d`, How can I fix it ?
![2018-07-24 3 13 48](https://user-images.githubusercontent.com/33800508/43122592-3327d930-8f54-11e8-9538-f460b9bf0f2b.png)

**Comment by blueyed** [comment]
Closing here.
Improvements to Jedi would be appreciated really, of course.
