### ISSUE TITLE
Very limited preview capabilities for external modules

### ISSUE THREAD

**Issue by Time0o** [davidhalter/jedi-vim#871]
### Issue

Not sure if this is an issue with jedi-vim, jedi itself or my system setup but in many cases the preview window will not pop up and display function type hints for non-standard python modules, e.g. in my case `PyQt4`.

### Steps to reproduce

For the following snippet, when typing `self.`, available methods are displayed correctly, but when I select e.g. `addAction` in the drop-down list, no preview window is displayed. However, I assume that information regarding the function parameters and return types is available to Jedi since PyCharm correctly infers `def addAction(self, action: QAction) -> None ` in the same situation.

```python
from PyQt4 import QtGui

class Foo(QtGui.QDialog):
    def __init__(self, parent=None):
        super(Foo, self).__init__(parent)
        self.addAction*
```

##### jedi-vim version

 - jedi-vim git version: 0.9.0-57-g132d850
 - jedi git submodule status:  a79a1fbef57564d031c59f47def20a6d9adf3439 pythonx/jedi (v0.12.1)
 - parso git submodule status:  e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso (v0.3.1)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.0 (default, Jul 15 2018, 10:44:58), [GCC 8.1.1 20180531]`
 - global site module: `/usr/lib/python3.7/site.py`

##### Jedi

 - path: `/home/timo/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.1

##### Jedi environment: <SameEnvironment: 3.7.0 in /usr>

 - executable: /usr/bin/python3
 - sys_path:
    - `/usr/lib/python37.zip`
    - `/usr/lib/python3.7`
    - `/usr/lib/python3.7/lib-dynload`
    - `/usr/lib/python3.7/site-packages`

##### Known environments

 - <Environment: 2.7.15 in /usr> (/usr/bin/python2.7)

##### Settings

```
g:jedi#force_py_version = 3 (default: 'auto')

  omnifunc=jedi#completions
        Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim
  completeopt=menuone,longest,preview
        Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim
```

I don't know whether Python 2 should really be listed under `Known environments`.

**Comment by davidhalter** [comment]
This is probably also an issue with Python3.7. It's not yet supported. We're working on it.

**Comment by davidhalter** [comment]
I'm pretty sure this is better now, because Python 3.9 is now supported and Python 3.7 as well. 

Feel free to open a new issue if this is still a problem for you.
