### ISSUE TITLE
how to change global python used in jedi-vim

### ISSUE THREAD

**Issue by lemWX** [davidhalter/jedi-vim#876]
### Issue

I have Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32 with jedi (0.12.1)
but JediDebugInfo show global python : 2.7.13 (v2.7.13:a06454blafal, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
how to change global python used in jedi-vim

####Jedi-vim debug information

#####jedi-vimversion

 - jedi-vim git version: 0.9.0-58-gc6f05cd
 - jedi git submodule status: a79alfbef57564d031c59f47def20a6d9adf3439 pythonx/jedi (vO.12.1)
 - parso git submodule status:e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso (vO.3.1)

#####Global Python

using Python version 2 to access Jedi.
 - global sys.version: '2.7.13 (v2.7.13:a06454blafal, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]'
 - global sitemodule: 'C:\Soft\Dev\Python27\Lib\site.pyc'

error: could not import the "jedi" Python module: importError: cannot import name _remove_dead_weakref 

my default python:
C:\Users\96357>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by aliahmed45** [comment]
lemWX I have this same error. Can you share how you fixed this error?

**Comment by bgenchel** [comment]
follow up here? what do you mean you forgot to install python 2.7?
