### ISSUE TITLE
insert mode <c-o>  did not work well

### ISSUE THREAD

**Issue by haolian9** [davidhalter/jedi-vim#877]
### Issue

after enabled jedi-vim plugin, insert mode keymap <c-o> did not work well.

### Steps to reproduce

env:

* nvim 0.3.1 (no other plugin, no config file)
* jedi-vim master c6f05c

steps:

* nvim test.py
* type in nvim: `import time; time.sleep()<c-o>`
* when typed `time.`, some popup window occured which shows jedi-vim has been loaded.
* when typed `()<c-o>`, `<c-o>` did not work, meanwhile status line will display `Back at original`

others:

* `verbose imap <c-o>` outputs: `no mapping found`

### expecting behavior

`help i_CTRL_O`

**Comment by blueyed** [comment]
jedi-vim triggers completion on dot (https://github.com/blueyed/jedi-vim/blob/50699d2d097de8ea292fed2a02f63927d0232dac/ftplugin/python/jedi.vim#L36-L38).
So use `let g:jedi#completions_enabled = 0` etc, or just use `<c-e>` to close the (non-visible) popup menu before `<c-o>`.
