### ISSUE TITLE
Error: jedi-vim failed to initialize Python

### ISSUE THREAD

**Issue by BullfroG21** [davidhalter/jedi-vim#879]
### Issue

Error by opening python file, using debian stretch with Gnome

Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 2 or 3. (in function jedi#init_python[4]..<SNR>48_init_python, line 10)

##### jedi-vim version

 - jedi-vim git version: c6f05cd
 - jedi git submodule status:  a79a1fbef57564d031c59f47def20a6d9adf3439 pythonx/jedi (v0.12.1)
 - parso git submodule status:  e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso (v0.3.1)

##### Global Python

Using Python version null to access Jedi.

Error detected while processing function <SNR>16_jedi_debug_info[12]..jedi#debug_info:
line   22:
E492: Not an editor command:     PythonJedi import vim; vim.command('let s:pythonjedi_called = 1')

**Comment by blueyed** [comment]
> jedi-vim requires Vim with support for Python 2 or 3

What does `:ver` say?
It looks like your Vim does not have Python.

**Comment by BullfroG21** [comment]
Yep you are right.
by installing  vim-nox instead of the usual vim made it work. 
apt-get install vim-nox

thx for the quick response

**Comment by joeytai** [comment]
the error occurs because vim does not have python3.
my solution:
check the vim -v check it if support python and python3
```brew install macvim```
then reopen the vim,
it works for me.
