### ISSUE TITLE
multiple autocmd in jedi_usages augroup

### ISSUE THREAD

**Issue by liushapku** [davidhalter/jedi-vim#882]
### Issue
When `doautocmd FileType` is run manually to update the filetype plugin for python files, the `jedi_usages` augroup will be installed multiple times

### Steps to reproduce
run ex command `:doautocmd FileType` in python files.

### Fix
This can be fixed by clear the `augroup jedi_usages` before setup the `autocmd`, i.e., in `ftplugin/pytyhon/jedi.vim`

      augroup jedi_usages
          autocmd!
          autocmd TextChanged <buffer> call jedi#remove_usages()
          autocmd InsertEnter <buffer> call jedi#remove_usages()
      augroup END

**Comment by blueyed** [comment]
Thanks for the report.
https://github.com/davidhalter/jedi-vim/pull/883 should fix this.
