### ISSUE TITLE
Disabling import autocomletion

### ISSUE THREAD

**Issue by lbenezriravin** [davidhalter/jedi-vim#888]
### Issue

I can't seem to disable jedi's autocomplete of import statements. I've searched the documentation to the best of my ability, but come up empty. If this is not currently configurable, could we get an option for it?

### Steps to reproduce
With the following vimrc, hitting `space` after typing `from collections` autocompletes the word `import`. I would like this not to happen.

```
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

let g:jedi#completions_enabled = 0
let g:jedi#use_splits_not_buffers = "right"
let g:jedi#show_call_signatures = "0"

syntax on
filetype plugin indent on
```

**Comment by blueyed** [comment]
Please see https://github.com/davidhalter/jedi-vim/blob/b6dfc5fd49c26d4dbe9f54c814956567a7a9b3a8/doc/jedi-vim.txt#L498-L508.
