### ISSUE TITLE
Make "fat char" in signature popups configurable

### ISSUE THREAD

**Issue by and3rson** [davidhalter/jedi-vim#890]
### Issue

I'm using a hack to "unconceal" "fat marker" inside signature popups (`*_*`) because default approach of using `conceal` for `jediFatSymbol` is rendered incorrectly due to conflict with `Yggdroot/indentLine`. I think this "fat marker" combination should be configurable to make it possible to use signature popups *without* any concealing.

### Steps to reproduce

1. Install `Yggdroot/indentLine` & `jedi-vim`.
2. Fat char is displayed transparently, thus breaking aesthetics of the popup.

Default config:

![Screenshot 1](https://dun.ai/p/nYJB1pY.jpg)

After adding `au BufRead *.py :syn match jediFatSymbol "\*_\*" contained`:

![Screenshot 2](https://dun.ai/p/9pXlW4Y.jpg)

After adding one more line - `hi jediFatSymbol ctermfg=234 ctermbg=234`:

![Screenshot 3](https://dun.ai/p/AQOwp3j.jpg)

This is not perfect, but It currently works for me. (c)

### Suggested solution

You could possibly move definition of `'*_*'` into `g:jedi#call_signatures_fat_chars` as a list (for opening & closing char) as well as make conceal configurable, for example:

    " This would make it more appropriate IMO
    let g:jedi#call_signatures_fat_chars = ['[[', ']]']
    let g:jedi#call_signatures_conceal = 0
    " Also, I guess `cchar` could be configurable as well
    " (and applied if call_signatures_conceal is 1):
    let g:jedi#call_signatures_fat_chars_cchar = '#'

Somewhat related: https://github.com/davidhalter/jedi-vim/commit/69160c329ac94f8c2f0eefaa82c1dbe0ac14cab3

Thanks in advance!

**Comment by davidhalter** [comment]
Sorry. The call signature hack is already bad enough. I'm very much against even more configuration. If you want a less hacky solution, just use `show_call_signatures = 2` (see docs for the proper assignment). That makes signatures part of the command line, which is not a hack anymore and doesn't interfere with the plugin you're mentioning.
