### ISSUE TITLE
Remove/Fade Rename Highlighting

### ISSUE THREAD

**Issue by weilbith** [davidhalter/jedi-vim#892]
### Issue

When I use the renaming function, all occurrences which have been renamed get highlighted. This is okay, but since this highlighting does not disappear again it is annoying. Moreover this applies for all other buffers displayed in the same window, what is much more annoying.

### Steps to reproduce
```vim
" Disable everything per default and use functions in custom mappings at the
" ftplugin.
let g:jedi#auto_initialization = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0

nnoremap <buffer> <silent> <leader>rr :<C-u>call jedi#rename()<CR>
```

### Output of “:verbose JediDebugInfo”

```vim
pynvim.api.nvim.NvimError: b'Vim(let):E903: Process failed to start: too many open files: "xsel"
```

**Comment by blueyed** [comment]
Please try https://github.com/davidhalter/jedi-vim/pull/851.

**Comment by weilbith** [comment]
Yes, works for me. :+1:
