### ISSUE TITLE
Typo under settings

### ISSUE THREAD

**Issue by HawaiinPizza** [davidhalter/jedi-vim#898]
"Jedi is by default automatically initialized. If you don't want that I suggest you disable the auto-initialization in your .vimrc:"

It's missing the on, after is.

**Comment by davidhalter** [comment]
I might brain lag, but can you please write the sentence in the correct form? I'm not sure what you mean. Not saying that this is a good sentence, but I don't get what you're saying :)

**Comment by blueyed** [comment]
Sounds like "Jedi is on by default automatically initialized." is requested, but that is wrong.

"Jedi is initialized by default automatically." sounds better.

But grepping for it I've found that this even controls Vim config/setup (e.g. maps), although there is `g:jedi#auto_vim_configuration` also..
