### ISSUE TITLE
jedi-vim not working properly with vim recent, dropping find_module

### ISSUE THREAD

**Issue by oivulf** [davidhalter/jedi-vim#899]
### Issue

accessing doc (shift-k) triggers exception:
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2104, in _handle_ns
    loader = importer.find_module(packageName)
AttributeError: module 'vim' has no attribute 'find_module'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/fc/.vim/pack/myplugins/start/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
  File "/home/fc/.vim/pack/myplugins/start/jedi-vim/pythonx/jedi_vim.py", line 423, in show_documentation
AttributeError: module 'jedi' has no attribute 'NotFoundError'

From a net research:
recently vim dropped find_module in its bindings because deprecated in python 3.5.2+ in favour of find_spec.

I understand that the problem may be actually primarily with setuptools/pkg_resources rather than jedi-vim, but is there a workaround?

Please find attached the complete trace.
[vim_version.txt](https://github.com/davidhalter/jedi-vim/files/2786729/vim_version.txt)
[trace.txt](https://github.com/davidhalter/jedi-vim/files/2786665/trace.txt)

**Comment by oivulf** [comment]
I also found that python-mode has been trying solving this [https://github.com/python-mode/python-mode/issues/972](problem) since at least 2018-12-15.

**Comment by davidhalter** [comment]
I removed the NotFoundError, but can you run it again? I would like to see the original error.

**Comment by oivulf** [comment]
Dear David,
it works fine with your last commit.
I did not understand your request, the original error is in trace.txt attached to my first message.
Do you need something else?

**Comment by davidhalter** [comment]
This error only happened because of another error. The other error would have been interesting. But whatever, I guess I'll just wait for your next report. Please let us know if you find something again :)

**Comment by oivulf** [comment]
Dear David,
how right you are!
I had the problem on another machine of mine.
I am attaching the relevant trace.
[vim_trace.txt](https://github.com/davidhalter/jedi-vim/files/2883778/vim_trace.txt)

**Comment by davidhalter** [comment]
Wow, this is coming from using `from numpydoc.docscrape import NumpyDocString`. It might have to do something with namespaces. And even worse it's also triggered by `from pkg_resources import iter_entry_points`. I'm not sure what's causing this, but it looks like an issue with your installation. Are you able to import those two things before and after any completions (please restart VIM in between)? `:python3 from numpydoc.docscrape import NumpyDocString`?

I'm digging down the rabbit hole. This looks like a VIM issue:
```
:python3 print(sys.path_importer_cache['_vim_path_'])
<module 'vim' (built-in)>
```
This should normally be a FileLoader or None.

```
['/home/dave/source/parso', '/home/dave/source/jedi', '/usr/lib/python3/dist-packages', '/usr/local/li
b/python3.5/dist-packages/pycodestyle-2.3.1-py3.5.egg', '/usr/lib/python35.zip', '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/home/dave/.local/lib/
python3.5/site-packages', '/usr/local/lib/python3.5/dist-packages', '_vim_path_']
```
There's this '_vim_path_' path, which makes no sense IMO, you can just work with meta_path. It looks like the VIM loading is probably just outdated. I don't have the time to fix this.

sys.path_hooks is supposed to return a Finder object and not the module itself: https://docs.python.org/3/library/sys.html#sys.path_hooks

I'm sorry it all looks pretty broken. If you're interested, the path hook in VIM is in `vim/src/if_py_both.h`. I think they should just use meta_path and all the hacks would be gone. However they still want to make Python 2 work (which at this point I would just drop), so they stick with path_hooks. It's probably a pretty big rewrite to do this correctly (in VIM).

Possible solutions for you are:
- Use NeoVIM, that loads Python in a different - better way AFAIK.
- Fix VIM for Python 3, good luck with that :)
- Uninstall numpydocs, that module loads pkg_resources

Sorry we cannot fix this here. Please consult the VIM mailing list instead.

**Comment by oivulf** [comment]
Dear David,
I uninstalled numpydoc and now all works fine. 
I don't know what numpydoc was doing, also, I did not need it and did not explicitly import it, it somehow plugged into the import system to be imported with numpy I guess.
Thank you
Fulvio
