### ISSUE TITLE
add a `jedi#show_call_signatures` mode for displaying under the function, but in the buffer

### ISSUE THREAD

**Issue by towc** [davidhalter/jedi-vim#903]
### Issue

The only mode for showing call signatures in the buffer does it before your cursor, and I hate it when the thing I'm editing moves around as I edit it.
If the signature is longer than the line (which is common when working with frameworks, or small terminals), vim will make the line I'm editing go down quite a bit, and it's really disrupting.
This can also be fixed by disabling line wrapping in vim itself, but that will affect other parts of most people's workflow

![image](https://user-images.githubusercontent.com/6382186/51792625-a998d300-21ab-11e9-979d-19b45a8b951a.png)

My suggestion is to add a mode for getting the signature to be displayed just below the cursor, or as a list, so it can be used similarly to autocompletion functionality

**Comment by towc** [comment]
as a less relevant side-note, and possibly a side-issue (that I'm personally not worried about), is that ale linting gets confused by this display method (as shown by the red arrow in the sign column)

**Comment by blueyed** [comment]
There is `g:jedi#show_call_signatures = 2` to display it in the command line.
With Neovim it could also use its virtual text feature, but that would display it at the end of the current line (which would be fine/great for editing the end of a line, of course).

**Comment by towc** [comment]
the command line is very far from the function usually :/ It's still a possibilty, but this would be very nice to have either way

**Comment by davidhalter** [comment]
IMO this is just one more case that we have to support and will likely just not properly test, I'm against this for maintenance reasons.

Sorry at @towc, but I really feel like this is such a big hack already and making it even bigger makes it just worse. If we can ever properly write to the screen I'm all yours.

**Comment by blueyed** [comment]
btw: https://github.com/davidhalter/jedi-vim/pull/652
