### ISSUE TITLE
Parsing badly formed file

### ISSUE THREAD

**Issue by therealadityashankar** [davidhalter/jedi-vim#910]
### Issue

the following code is successfully parsed
```
class Token{
    tok_eof = -1

    # commands
    tok_def = -2
    tok_extern = -3

    # primary
    tok_identifier = -4
    tok_number = -5
}
```

### Steps to reproduce
1. write the above mentioned code in a file
2. import the file in another python code using vim
3. the code is successfully taken by vim-jedi

### Output of “:verbose JediDebugInfo”

ModuleNotFoundError: No module named 'jedi_vim_debug'

I *think* the above lack of debug info might be because of installing via apt first, ughhh

**Comment by davidhalter** [comment]
What's your VIM version? I feel like it's probably very old.

**Comment by therealadityashankar** [comment]
not really
vim says its of version 8.0.1453, is that old ?

**Comment by davidhalter** [comment]
Can you print `:version`?

**Comment by therealadityashankar** [comment]
Here's what it says -
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
```
then its a whole bunch of features
ok, you're right, thanks !
