### ISSUE TITLE
Completion order is incorrect/unexpected

### ISSUE THREAD

**Issue by majuscule** [davidhalter/jedi-vim#912]
### Issue

Omni completion starts at the top of the window list, then resets (no completion selected) then wraps around (presumably), and goes to the bottom where it continues up. Expected behaviour would be to proceed downwards immediately, or start at the bottom and move upwards.

### Steps to reproduce
```
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

syntax on
filetype plugin indent on
```

type `from sys ` and followed by `<C-p><C-p>`

**Comment by davidhalter** [comment]
I have no idea what you mean.

**Comment by davidhalter** [comment]
Please provide `:JediDebugInfo` and help us understand better what your issue is. We have no idea at this point and can therefore not help.

I'm closing until we have more information.
