### ISSUE TITLE
How to change global python version?

### ISSUE THREAD

**Issue by stasik92** [davidhalter/jedi-vim#920]
### Issue
I'm using **Python 3.7.2**, when I run `:verbose JediDebugInfo`
I'm getting:
##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.5.3 (default, Sep 27 2018, 17:25:39), [GCC 6.3.0 20170516]`
 - global site module: `/usr/lib/python3.5/site.py`

How can I change it to **python3.7.2**? 

<!--
Please describe the issue here.

**Comment by davidhalter** [comment]
Search for `force_py_version` in the docs. Also please use the templates with the debug info, it would have helped here.
