### ISSUE TITLE
Another release, please?

### ISSUE THREAD

**Issue by cipherboy** [davidhalter/jedi-vim#928]
In the style of #787, another year has gone by. I'm sure `jedi-vim` is still not quite yet perfect (what code ever is?), but I'd love another tagged release if I could bother y'all for it. 

At any rate, the master branch fixes some of the lag that the `0.9.0` version has for me. Having a new release would help me suggest that Fedora should update the package. :)

**Comment by blueyed** [comment]
Likely after https://github.com/davidhalter/jedi-vim/pull/915 (and waiting a bit) I assume.

**Comment by cipherboy** [comment]
Sure, no rush :) I've really enjoyed using `vim-jedi`. Thanks for this wonderful piece of software!

**Comment by davidhalter** [comment]
Done.

@blueyed I just used 0.10.0, felt like that made the most sense. Hope you didn't mind me tagging something. Feel free to do that as well in the future :)
