### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by janepen** [davidhalter/jedi-vim#933]
### Issue

git clone https://github.com/davidhalter/jedi-vim.git jedi-vim
Initialized empty Git repository in /home/pengz/.vim/bundle/jedi-vim/.git/
error:  while accessing https://github.com/davidhalter/jedi-vim.git/info/refs

fatal: HTTP request failed

**Comment by davidhalter** [comment]
This was probably an issue with Github. Just try again after deleting the directory.
