### ISSUE TITLE
Option to show doc in pedit window

### ISSUE THREAD

**Issue by blayz3r** [davidhalter/jedi-vim#937]
### Issue
Can we have the option to view docs in preview windows and not splits

### Steps to reproduce
Press K for word under cursor

**Comment by blayz3r** [comment]
[Example](https://github.com/mhinz/vim-signify/blob/f32b69033bb7a127fba26f5afe056af6efe0cd51/autoload/sy/util.vim#L121)

**Comment by davidhalter** [comment]
I'm all for that, if somebody implements it. For me personally it's currently not important enough.

**Comment by blayz3r** [comment]
That's fair, it's certainly more of a convenience thing.

**Comment by davidhalter** [comment]
Nobody is stepping up, so I'm closing.
