### ISSUE TITLE
jedi work wrong

### ISSUE THREAD

**Issue by shanyujie** [davidhalter/jedi-vim#939]
![Jietu20190812-162049](https://user-images.githubusercontent.com/22969676/62852893-59cfc280-bd1d-11e9-9c62-882e4f517a36.jpg)
I don't konw how to solve the problem，can you help me?

**Comment by blueyed** [comment]
Please see the issue template for providing additional info.
Also please state if this started happending only recently (Jedi was just updated for example).

**Comment by davidhalter** [comment]
We are happy to reopen this issue if you add the necessary information.
