### ISSUE TITLE
jedi-vim omni completions not working sometimes

### ISSUE THREAD

**Issue by kerwinxu** [davidhalter/jedi-vim#945]
# Problems summary
for example :
import os
os.
then error： omni completion  pattern not found 

## Environment Information
 * OS: win 10 
 * Vim version: vim 8

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/neocomplete.nvim/
let g:neocomplete#enable_at_startup = 1
```

if isdirectory(expand("~/vimfiles/pugged/jedi-vim/"))
	if &filetype == 'python' 
		let g:neocomplete#enable_at_startup = 1
		let g:jedi#completions_enabled = 1
		let g:jedi#auto_vim_configuration = 1
		let g:jedi#smart_auto_mappings = 1 "加上这个，就会增加比如，from PIL 后自动输入import ，然后弹出自动补全。
		if !exists('g:neocomplete#force_omni_input_patterns')
			let g:neocomplete#force_omni_input_patterns = {}
		endif
		let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
		let g:jedi#completions_command = "<a-Space>"
		let g:jedi#documentation_command = "<leader>k"
		let g:jedi#rename_command = "<F2>"
	endif
endif

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Upload the log messages by `:redir` and `:message`
:message
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"C:\Users\kerwin\Desktop\how_many_contacts_of_outlook_for_search_stock_per_day.py" [unix] 75L, 1370C
Traceback (most recent call last):
  File "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi_vim.py", line 262, in completions
    info=PythonToVimStr(c.docstring()),  # docstr
  File "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi\jedi\api\classes.py", line 479, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi\jedi\api\classes.py", line 242, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi\jedi\api\classes.py", line 756, in docstring
    signature_text = _format_signatures(context)
  File "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi\jedi\api\classes.py", line 715, in _format_signatures
    for signature in context.get_signatures()
  File "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi\jedi\evaluate\context\klass.py", line 229, in get_signatures
    return [sig.bind(self) for sig in init_funcs.get_signatures()]
  File "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi\jedi\evaluate\context\klass.py", line 229, in <listcomp>
    return [sig.bind(self) for sig in init_funcs.get_signatures()]
  File "E:\home\kerwin\vimfiles\pugged\jedi-vim\pythonx\jedi\jedi\evaluate\signature.py", line 107, in bind
    assert not self.is_bound
AssertionError

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.

**Comment by kerwinxu** [comment]
> Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.
> 
> We are happy to reopen this issue if you add the necessary information.

you can try the following in your pc 
import os
os.

**Comment by blueyed** [comment]
The traceback/error is interesting, but completion after "os." works for me.
Therefore we need more information, and there is an extra command that you could run and paste here then (see the issue template).

**Comment by kerwinxu** [comment]
> The traceback/error is interesting, but completion after "os." works for me.
> Therefore we need more information, and there is an extra command that you could run and paste here then (see the issue template).

In my pc , only "import os" does not work , "import re" works well ,

**Comment by davidhalter** [comment]
Dude, just finally provide `:verbose JediDebugInfo`.

**Comment by bstaint** [comment]
Python 3.7.4
jedi 0.15.2
typeshed master

I have same question, i checked something，when assert failed：
```
===========
<BuiltinSignature: CompiledBoundMethod(<CompiledObject: <slot wrapper '__init__' of 'object' objects>>)>
<ClassValue: <Class: DirEntry@243-257>>
===========
```

I looked at `typeshed\stdlib\3\os\__init__.pyi` 245:
```
    class DirEntry(PathLike[AnyStr]):
        # This is what the scandir interator yields
        # The constructor is hidden
```

add:
`def __init__(self) -> None: ...`

The problem will disappear

**Comment by davidhalter** [comment]
@bstaint Are there reproduction steps for this? If there are, please post it as a new issue in Jedi, it feels like a Jedi issue.
