### ISSUE TITLE
completion with ultisnips and a path escape bug on windows

### ISSUE THREAD

**Issue by NewUserHa** [davidhalter/jedi-vim#949]
### Issue1

both jedi-vim and ultisnips can work with supertab, but jedi-vim can't list snipts from ultisnips which has an api for this.
can jedi-vim add this feature?

### Issue2

by the way, I found a issue:
```
:verbose JediDebugInfo
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: fatal: cannot change to 'C:\Program\': No such file or directory
 - jedi git submodule status: fatal: cannot change to 'C:\Program\': No such file or directory
 - parso git submodule status: fatal: cannot change to 'C:\Program\': No such file or directory

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `C:\Program Files\Vim\vim81\gvim.exe`
 - global sys.version: `3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]`
 - global site module: `C:\Program Files\Python37\Lib\site.py`

##### Jedi

 - path: `C:\Program Files\Vim\vimfiles\plugged\jedi-vim\pythonx\jedi\jedi\__init__.py`
 - version: 0.15.1
...
```
'C:\Program\' looks like a problem.

**Comment by blueyed** [comment]
> 'C:\Program' looks like a problem.

Thanks, see https://github.com/davidhalter/jedi-vim/pull/950.

> jedi-vim can't list snipts from ultisnips which has an api for this.

Out of scope.

You could create your own wrapper function, or use something like deoplete or other completion wrappers.

**Comment by NewUserHa** [comment]
why won't jedi-vim want this feature? otherwise ppl only use python who already has jedi-vim also has to install YCM?

**Comment by blueyed** [comment]
jedi-vim only provides custom omni-completion.
It is not meant to act as a completion plugin itself - there are several of them already, e.g. also deoplete - and supertab like you've mentioned: those are meant to use different completion mechanisms/providers, but that's out of scope for jedi-vim (IMHO).

I recommend just triggering snippets manually anyway - it's not something you want/need all the time in completions, is it?

**Comment by NewUserHa** [comment]
and this signutrue hint bug:
![image](https://user-images.githubusercontent.com/32261870/65477897-54d46600-deba-11e9-8f98-7800b76a829e.png)
```
a = [f'aaaaaaaaaaaaaaaa{_}' for _ in [1,2,3,4]]
a.extend([for])
```

**Comment by NewUserHa** [comment]
1.isn't jedi-vim a completion? I thought it is:
> jedi-vim - awesome Python autocompletion with VIM

2.supertab can trigger user-defined competition but don't know itself can be a completion plugin which also doesn't have popup-menu from its document I browser.

3.it is not always needed. but for newcomers who are not familiar with what snippets there're, it should be needed.

**Comment by blueyed** [comment]
@NewUserHa 
Please do not add minor issues here.. call signatures via concealing are buggy - although that should not happen.  See https://github.com/davidhalter/jedi-vim/pull/652 for WIP to get rid of the conceal hack.  For now you could also use the cmdwindow.

> awesome _Python_ autocompletion

;)

**Comment by NewUserHa** [comment]
ok. didn't know it's a minor issue. could it be documented in FAQ?

hmm... doesn't snippets for python belong to python autocompletion?

**Comment by blueyed** [comment]
> ok. didn't know it's a minor issue. could it be documented in FAQ?

It happens only for some special signatures, no?
(it does not make sense to document bugs in the FAQ I think)

> doesn't snippets for python belong to python autocompletion?

jedi-vim is a wrapper around the Jedi library mostly, which does not provide snippets.

**Comment by blueyed** [comment]
btw: there's `:UltiSnipsEdit` to see existing snippets IIRC.

**Comment by NewUserHa** [comment]
only found that one will cause this issue for now.
I googled no result so open an issue since I thought it's a new bug.

it's just for convenient.

**Comment by blueyed** [comment]
It wouldn't really help to find it in a FAQ, would it?

btw: if you've copy'n'pasted the text, and not posted a screenshot people might find it now here (but surrounded by 2-3 other issues).. ;)

It is pretty certain that the signature contains some special character combination that is also used for the concealing.
One major issue with the signatures in this form is that it actucally changes the buffer contents, which then triggers misbehavior with indenting (when this looks for opening parenthesis, which are then replaced etc).
It's not worth fixing given that https://github.com/davidhalter/jedi-vim/pull/652 should be finished soon rather instead.

**Comment by NewUserHa** [comment]
yea...
eh, I thought `Please do not add minor issues here` = `do not post that kind issues`

listing all related snippets in completion is for convenience. and it' just a suggestion.
