### ISSUE TITLE
Mouse support [Feature Request]

### ISSUE THREAD

**Issue by ekiefl** [davidhalter/jedi-vim#955]
Hello,

I was wondering whether or not any mouse support is available with jedi-vim. I used to be a keyboard purist, but I've developed debilitating RSI and now I use eye-tracking hardware and voice control to code. As a consequence, my workflow in vim is very mouse-centric, which makes selecting autocompletion options in jedi difficult.

I was wondering if either of these two options could be implemented:

1. Could line numbers be added to the omnicompletion popup window? This way I could say something like '14 down enter' to select the entry I was interested. This is what I currently do, but I have to manually count how many I should go down.

2. Add mouse support so that clicking mimics moving the cursor to that option and then pressing enter.

I understand if the amount of effort this would require surpasses the net gain for the community, but this would personally really enable me. Thanks for your time.

Cheers,
Evan

**Comment by davidhalter** [comment]
Hi Evan

Just a related question: Why don't you use something like Visual Studio Code (maybe with its VIM mode?). I'm just wondering why you would even choose to use VIM with your condition.

> I was wondering if either of these two options could be implemented: [...]

It's unfortunately not that easy. The first option could probably be implemented, but I'm not even sure. If that really helps you, we could consider helping you out to do this. This would probably then linger around as a fork (jedi-vim doesn't change like crazy, so it should be easy to maintain it).

Now the second option... Is probably not possible. If you look at jedi-vim's code, you can see that it doesn't really do a lot for completions. It basically passes them towards VIM and VIM does whatever with them.

I quickly tried to research

**Comment by ekiefl** [comment]
Hey Dave,

Thanks so much for thoughtful response. 

> Just a related question: Why don't you use something like Visual Studio Code (maybe with its VIM mode?). I'm just wondering why you would even choose to use VIM with your condition.

I've found the vim grammar to be essential in how I code, because I can pack a large sequence of events using vim grammar into just one or two spoken words. I could use vim emulators, and I'm sure visual studio has a decent one, but the customization afforded by a vimrc is just so useful and nothing emulates vim better than vim. Also I like the portability across servers. If you're curious, here is a realistic example of how I code: https://youtu.be/fBhBqlQj00Q

If it was possible to implement option 1, that would be extremely helpful to me. I don't know what kind of legwork it would involve for you, but if you at some point could find the time to decide if its possible or not, i would be greatly appreciative. 

The second option sounds like a lot, and i feel it would be much easier to manage a fork because I don't always have control of the vim version I am using.

**Comment by blueyed** [comment]
I think both the options make more sense to add to Vim (or Neovim) directly, especially since they would affect all other completion menus.
I'm actually surprised that the second option (selection of popupmenu entries by mouse) does not work: I've just tried it in both Neovim and Vim (with `set mouse=a`), but it appears to not work.

So, I recommend creating an issue for Vim (or search for existing ones), to have the features being added there in general.

(closing, but please feel free to follow up)

**Comment by davidhalter** [comment]
@blueyed What VIM version do you have? I tried in GVIM and VIM 7.4.

@ekiefl I'll try to see what I can do. We are investigating fuzzy completions anyway for Jedi, so something similar might become an Option soon, at that point I might write your feature as well. Even though this is closed, it's on my mind!

**Comment by blueyed** [comment]
@davidhalter 
Do you mean it works in Vim for you?  (I've tried Vim master, Neovim, and gvim now also to be sure)
Clicking into a popupmenu closes it, but does not select the option.
I think it would be a valid feature request for Vim/Neovim.

**Comment by ekiefl** [comment]
Thanks for this fruitful discussion @davidhalter @blueyed
