### ISSUE TITLE
pls remove winleave of 'q' for qf if an option was not made.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [davidhalter/jedi-vim#956]
### Issue

qf would auto closed once 'enter'

### Steps to reproduce
after call usage(), the qf auto closed once 'enter'

```viml
function! jedi#add_goto_window(len) abort
    set lazyredraw
    cclose
    let height = min([a:len, g:jedi#quickfix_window_height])
    execute 'belowright copen '.height
    set nolazyredraw
    if g:jedi#use_tabs_not_buffers == 1
        noremap <buffer> <CR> :call jedi#goto_window_on_enter()<CR>
    endif
    augroup jedi_goto_window
      au!
      au WinLeave <buffer> q  " automatically leave, if an option is chosen
    augroup END
    redraw!
endfunction
```

pls remove au of 'jedi_goto_window' or an option was really made ... or let me know what's option name it was ... :)

**Comment by blueyed** [comment]
Please try #851.

**Comment by Shane-XB-Qian** [comment]
looks there are several topic there at that issue#, 
to me, i just wish keep the 'qf' open (as usual) if 'enter' a item.
if no 'option' there, it should not be **hard code** there as my understanding ..
but whatever i just add a 'au!' to myself, issue workaround for my side. as for 'remove' that or not, pls keep investigating ...

**Comment by blueyed** [comment]
@Shane-XB-Qian 
It is meant to be merged soon and improves the usage handling in general.

**Comment by blueyed** [comment]
I mean that it might not be the case there anymore in the first place, and feedback from users would be appreciated.

**Comment by Shane-XB-Qian** [comment]
oh, i did not look into that issue# detail, sorry for that .. since looks there lots check-in there .. :)
anyway, that winleave q happened even `g:jedi#use_tabs_not_buffers == 0`, looks that (if == 1) registed a `normal! ZQ` on it too.
to me, i did not set (just/still was == 0), so i just wish that winleave q removed ... :)
not sure if it was helpful or not, to myself, it is not problem now, i au! it at my side.
but that will be great if did not need to do such magic thing on user side .. :)
