### ISSUE TITLE
Jedi autocompletes home folders for imports

### ISSUE THREAD

**Issue by artem0** [davidhalter/jedi-vim#959]
I have the next scenario:

`import p` Jedi, in this case, shows the home folder `Pictures` alongside with different packages that begin on `P`. Definitely, home folders have nothing common with imports and it's unexpected behavior.

**Comment by davidhalter** [comment]
Please give us some more information (OS, etc). This doesn't happen for me. Do you have a file named  `requirements.txt`, `Manifest.in` or `setup.py` in your home directory?

**Comment by artem0** [comment]
Here is an example of this behavior. I was experiencing alongside different autocomplete plugins: SuperTab and Neocomplete. 
![image](https://user-images.githubusercontent.com/9960628/67627515-23a6d700-f866-11e9-9692-f6e4ebf4c6fe.png)

**Comment by davidhalter** [comment]
WTF I can reproduce this. Definitely a bug. Thanks.

**Comment by davidhalter** [comment]
Fixed in https://github.com/davidhalter/jedi/pull/1451

It's not yet in jedi-vim, but it will be in a few months probably.
