### ISSUE TITLE
nvim 0.3.8 seems unhappy with jedi-vim

### ISSUE THREAD

**Issue by karenin-overseas** [davidhalter/jedi-vim#963]
### Issue
Jedi-vim keybindings and/or plugin installation appear to be broken with the default version of vim in the ubuntu 19.10 repositories (actually NVIM v0.3.8)

### Steps to reproduce
Using a minimal .vimrc and sourcing jedi-vim with pathogen seems to reproduce the issue.

```
execute pathogen#infect()
syntax on
filetype plugin indent on
```

### Output of “:verbose JediDebugInfo”
..oh, this happens:
![Screenshot from 2019-11-04 20-14-02](https://user-images.githubusercontent.com/17558590/68171009-f8944580-ff3f-11e9-8029-21edb4f7d082.png)

I ended up compiling regular vim (8.1), and jedi works normally there.

**Comment by davidhalter** [comment]
It looks like Jedi is not properly installed. Maybe @blueyed has a way to install it with neovim. I'm pretty sure it works fine with neovim. Maybe `:messages` also helps.
