### ISSUE TITLE
how to change signature colors

### ISSUE THREAD

**Issue by astier** [davidhalter/jedi-vim#969]
Is it possible to change the foreground and background colors of then signature when its shown in the command line `let g:jedi#show_call_signatures = 2`? Similar to how it is possible for the [echodoc](https://github.com/Shougo/echodoc.vim) plugin.

**Comment by astier** [comment]
In particular I dislike the background color of the argument list and would like to make it transparent. I am using the nord-theme.
![2019-12-10-024500_168x27_scrot](https://user-images.githubusercontent.com/36510152/70487903-1c2a4d00-1af7-11ea-8a05-0dd4ff6a9998.png)

**Comment by davidhalter** [comment]
Please have a look at https://github.com/davidhalter/jedi-vim/blob/master/pythonx/jedi_vim.py#L911-L925

You probably have to overwrite those definitions.

**Comment by astier** [comment]
Thank you. I am using now

```vim
hi Function ctermbg=none ctermfg=blue
hi jediFat ctermbg=none ctermfg=red
hi jediFunction ctermbg=none ctermfg=white
```

and it looks like

![2019-12-11-043330_161x18_scrot](https://user-images.githubusercontent.com/36510152/70589190-65e66680-1bcf-11ea-9dc9-bbf817986986.png)

Maybe this should be mentioned somewhere in the documentation. Also the names are somewhat confusing and not descriptive. Additionally I would suggest to change the default foreground and background colors but this might be just personal preference. You can close this issue if you want.

**Comment by davidhalter** [comment]
I'll let you discuss possible changes with @blueyed, because he originally wrote that part of call signatures.

**Comment by davidhalter** [comment]
Not important enough for me to document it. I will close.
