### ISSUE TITLE
How to display pop-up content in real time

### ISSUE THREAD

**Issue by Elinpf** [davidhalter/jedi-vim#970]
How to pop up content like YCM in real time?
When I use it, it only pops up after ".", And then the popup window will be closed after input.

**Comment by davidhalter** [comment]
This is currently not possible. Might be possible in the future, but it's not implemented at the moment and definitely won't be done as long as there are no async completions (like YCM). However you can easily use YCM completions (which is also powered by Jedi) and use the rest of the Jedi features with a bit configuration.

Also @blueyed might know more about other solutions (like deoplete-jedi).
