### ISSUE TITLE
cannot autocomplete the python3 style defination(fix the format)

### ISSUE THREAD

**Issue by zYeee** [davidhalter/jedi-vim#972]
### Issue

```
class Solution:
    def stoneGame(self, piles: List[int]) -> bool:
        pass

s = Solution()
s.
```

after I press '.', it would not complete the function stoneGame for me.
But if I use python2 style, it can work:

```
def stoneGame(self, piles):
        pass
```

### Steps to reproduce

just create a new python file and paste the code below:
```
class Solution:
    def stoneGame(self, piles: List[int]) -> bool:
        pass

s = Solution()
s.
```

after typing the '.', if would not show the popup.

##### jedi-vim version

 - jedi-vim git version: 0.10.0-11-gc80a08d
 - jedi git submodule status:  005f69390c4b1a3b864e7373cfcbdaf95e65411d pythonx/jedi (v0.15.1)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 2 to access Jedi.
 - global sys.executable: `/usr/bin/python`
 - global sys.version: `2.7.10 (default, Feb 22 2019, 21:17:52), [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]`
 - global site module: `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc`

##### Jedi

 - path: `/Users/zjude/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.pyc`
 - version: 0.15.1

##### Jedi environment: <SameEnvironment: 2.7.10 in /System/Library/Frameworks/Python.framework/Versions/2.7>

 - executable: /usr/bin/python
 - sys_path:
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload`
    - `/Library/Python/2.7/site-packages`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC`

##### Known environments

 - <Environment: 3.7.3 in /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7> (/usr/local/opt/python/bin/python3.7)
 - <Environment: 2.7.10 in /System/Library/Frameworks/Python.framework/Versions/2.7> (/System/Library/Frameworks/Python.framework/Versions/2.7/Resourc
es/Python.app/Contents/MacOS/Python)
Error when running display_debug_info: Vim(python):Exception TypeError: '__call__() takes exactly 1 argument (2 given)' in <jedi._compatibility.finali
ze object at 0x10c9745c0> ignored

##### Settings

```
g:jedi#completions_command = '<C-j>' (default: '<C-Space>')
g:jedi#goto_assignments_command = '<C-]>' (default: '<leader>g')

  omnifunc=jedi#completions
        Last set from ~/.vim/plugged/jedi-vim/autoload/jedi.vim line 741
  completeopt=menu,preview
```

#### :version
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 25 2019 17:43:25)
macOS version
Included patches: 1-1048
Compiled by zjude@C02YC0YFJHD4
Huge version without GUI.  Features included (+) or not (-):
+acl               +conceal           +folding           +menu              +packages          -sun_workshop      +virtualedit
+arabic            +cryptv            -footer            +mksession         +path_extra        +syntax            +visual
+autocmd           +cscope            +fork()            +modify_fname      +perl              +tag_binary        +visualextra
+autochdir         +cursorbind        -gettext           +mouse             +persistent_undo   +tag_old_static    +viminfo
-autoservername    +cursorshape       -hangul_input      -mouseshape        +postscript        -tag_any_white     +vreplace
-balloon_eval      +dialog_con        +iconv             +mouse_dec         +printer           -tcl               +wildignore
+balloon_eval_term +diff              +insert_expand     -mouse_gpm         +profile           +termguicolors     +wildmenu
-browse            +digraphs          +job               -mouse_jsbterm     +python/dyn        +terminal          +windows
++builtin_terms    -dnd               +jumplist          +mouse_netterm     +python3/dyn       +terminfo          +writebackup
+byte_offset       -ebcdic            +keymap            +mouse_sgr         +quickfix          +termresponse      -X11
+channel           +emacs_tags        +lambda            -mouse_sysmouse    +reltime           +textobjects       -xfontset
+cindent           +eval              +langmap           +mouse_urxvt       +rightleft         +textprop          -xim
-clientserver      +ex_extra          +libcall           +mouse_xterm       -ruby              +timers            -xpm
+clipboard         +extra_search      +linebreak         +multi_byte        +scrollbind        +title             -xsmp
+cmdline_compl     -farsi             +lispindent        +multi_lang        +signs             -toolbar           -xterm_clipboard
+cmdline_hist      +file_in_path      +listcmds          -mzscheme          +smartindent       +user_commands     -xterm_save
+cmdline_info      +find_in_path      +localmap          +netbeans_intg     +startuptime       +vartabs
+comments          +float             -lua               +num64             +statusline        +vertsplit
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-
multi-2level/CORE -lperl
```

**Comment by davidhalter** [comment]
You are still using a Python 2.7 environment.

Use `:let jedi#force_py_version = 3`.

**Comment by zYeee** [comment]
after I tried this, I can see the warning like this
![21576836405_ pic](https://user-images.githubusercontent.com/9430026/71248939-0fa7bf00-2357-11ea-963b-a996d641a121.jpg)

**Comment by davidhalter** [comment]
You probably need to have a working Python 3 somewhere in your system. Otherwise you cannot complete Python 3.
