### ISSUE TITLE
Incorrect docstring preview formatting with *args and **kwargs

### ISSUE THREAD

**Issue by adigitoleo** [davidhalter/jedi-vim#977]
### Issue

Docstring previews are formatted incorrectly (bold/italics, no colors) because they parse the call signature/synopsis line as reStructuredText.

Good docstring preview:

![jedi-vim-docstring-good](https://user-images.githubusercontent.com/34595875/71886392-3dcb3280-3190-11ea-8afa-6e193ffde14b.png)

Bad docstring preview:

![jedi-vim-docstring-bad](https://user-images.githubusercontent.com/34595875/71886432-4cb1e500-3190-11ea-97c7-e71644d6d9f3.png)

It's a relatively minor aesthetic issue, otherwise the plugin has been great.

```
:version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBU
G -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototype
s -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla
 -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATION
S -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim
/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovi
m/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

### Output of “:verbose JediDebugInfo”

```
#### Jedi-vim debug information


##### jedi-vim version


 - jedi-vim git version: 2572136
 - jedi git submodule status:  afbd8cad8938331ff89dac34126b4960809dc75b pythonx/jedi (v0.15.2)
 - parso git submodule status:  fb010f2b5d67a7b284962e1059e4ebadf87792d0 pythonx/parso (v0.5.2)


##### Global Python


Using Python version 3 to access Jedi.
 - global sys.executable: `/home/leon/.miniconda3/envs/NVIM/bin/python`
 - global sys.version: `3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42), [GCC 7.3.0]`
 - global site module: `/home/leon/.miniconda3/envs/NVIM/lib/python3.6/site.py`

##### Jedi

 - path: `/home/leon/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.15.2

##### Jedi environment: <Environment: 3.7.6 in /home/leon/.miniconda3/envs/SWS>


 - executable: /home/leon/.miniconda3/envs/SWS/bin/python
 - sys_path:
    - `/home/leon/.miniconda3/envs/SWS/lib/python37.zip`
    - `/home/leon/.miniconda3/envs/SWS/lib/python3.7`
    - `/home/leon/.miniconda3/envs/SWS/lib/python3.7/lib-dynload`
    - `/home/leon/.local/lib/python3.7/site-packages`
    - `/home/leon/.miniconda3/envs/SWS/lib/python3.7/site-packages`

##### Known environments


 - <Environment: 3.7.6 in /home/leon/.miniconda3/envs/SWS> (/home/leon/.miniconda3/envs/SWS/bin/python)

 - <Environment: 3.8.1 in /usr> (/usr/bin/python3.8)

 - <Environment: 3.7.6 in /home/leon/.miniconda3/envs/SWS> (/home/leon/.miniconda3/envs/SWS/bin/python3.7)

 - <Environment: 2.7.17 in /usr> (/usr/bin/python2.7)



##### Settings


```

**Comment by davidhalter** [comment]
I'm not really sure how to avoid that. I would just close this one, because it's really not worth the effort. There might be a way to search for these strings and put them into backticks, but even that is ugly. The rst part is just a minor feature that was never really intended to work well for all cases.

**Comment by adigitoleo** [comment]
I understand. Maybe an option to not print the call signature in the doc buffer at all? But if there hasn't been much noise about this then maybe it's not worth it.

**Comment by davidhalter** [comment]
> Maybe an option to not print the call signature in the doc buffer at all?

I'd rather not have that. IMO the only proper solution would be something that let's us make some part of the buffer a different "filetype". This is just an area where VIM is really lacking and where it's much easier to implement if you can work with a GUI/terminal elements instead of buffers.

I'm closing, because I don't think this will happen in the next few years.

**Comment by blueyed** [comment]
I guess we could have a special syntax file to handle `*args` and `**kwargs` in a special way.
But this then should maybe also handle `**kwds`, `**options` etc.
This could be limited to only the signature's line maybe.

**Comment by adigitoleo** [comment]
> I guess we could have a special syntax file to handle `*args` and `**kwargs` in a special way.
> But this then should maybe also handle `**kwds`, `**options` etc.
> This could be limited to only the signature's line maybe.

I'm not sure how the reST is parsed currently, but maybe even a regex substitution would do? I recently thought of this issue again after reading some [matplotlib docs](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.axes.Axes.inset_axes.html#matplotlib.axes.Axes.inset_axes) where their sphinx (I guess) seems to add `\` escapes to the `*args` and `**kwargs`.
