### ISSUE TITLE
jedi-vim turns markdown to python script by mistake

### ISSUE THREAD

**Issue by laoshaw** [davidhalter/jedi-vim#978]
if I include any code block in a markdown file with jedi-vim installed, e.g.

<pre>
```python
whatever
```
</pre>

it makes the markdown text into a python script when you run "file my.markdown"

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. The form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.

**Comment by laoshaw** [comment]
it's ubuntu 18.04 with the newest vim 8 and that's it. Anyway I disabled jedi-vim for now. I wish there is a script to collect info for github issues.

**Comment by davidhalter** [comment]
You still didn't provide the debug information, so I'm still not reopening it. You know if you provided it, I might actually try to help you ;-)
