### ISSUE TITLE
jedi-vim super distracting, I can't work anymore

### ISSUE THREAD

**Issue by GianniGi** [davidhalter/jedi-vim#984]
Hello, I'm trying to use your plugin but I'm really overwhelmed by popups, autocompletions, suggestions... I really can't type anymore. Each time I type print, everything moves and is hidden by a gigantic popup that tells me how to use print.

Can you please suggest me a vimrc configuration that disables all aspects of jedi-vim?
Then I'll gradually enable them one by one each and all jedi-vim features so I'll appreciate what your plugin is doing.
Right now I don't know what depends on your plugin and what depends on ctrl-p and similar plugins, so I can't fine tune anything...

thanks

**Comment by davidhalter** [comment]
Read the documentation, it's available with `:help jedi-vim`.

You can fine tune a lot of things. Please note that VIM lets you fine tune things as well (like `:help completeopt`. Your question is not specific enough that I can help you.

**Comment by blueyed** [comment]
> Each time I type print, everything moves and is hidden by a gigantic popup that tells me how to use print.

Try `set completeopt-=preview`.

**Comment by GianniGi** [comment]
Thanks for pointing me in the right direction.
I've uninstalled all python plugins because they do too much. By default all the developers enable all the autocompletions, error checking, popups, messages... I find yourself with a completely different "vim". I think that plugins should behave differently: you should have a list of features the you enable one by one.
For example... how do I disable autocomplete popup on functions that I use ten times a day like print? I'll try wit completeopt, but I already feel that it will do nothing, and each time I'll type print I'll see a message that insctructs me how to actually use print.
It's the equivalent of a browser without a popupblocker, soon I'll have to install mublock also on vim :-D

**Comment by blueyed** [comment]
@GianniGi 
> how do I disable autocomplete popup on functions that I use ten times a day like print?

If it's only ten times it should be ok.. ;)

There is no setting to use call signatures only/not for specific things, but it might make sense to allow for this actually - maybe something like a list of patterns to ignore could be added?
(but honestly, I would just ignore it with e.g. `print()`, and it can be useful there actually for its kwargs etc).

**Comment by blueyed** [comment]
FWIW https://github.com/numirias/semshi is awesome (but requires Neovim).

**Comment by davidhalter** [comment]
> For example... how do I disable autocomplete popup on functions that I use ten times a day like print?

Why would that be a problem?

> maybe something like a list of patterns to ignore could be added?

No chance I'll ever merge that, haha :D
